### ISSUE TITLE
Basics ./prereqs.sh  Error ./prereqs.sh: line 250: ghcup: command not found

### ISSUE THREAD

**Issue by Bossman42** [cardano-community/guild-operators#1028]
Trying to setup cardano node and following the guild guide on the basics page the following happened. 

Using Ubuntu on windows 10

After attempting  the line in basics

./prereqs.sh

 to setup the prereqs.sh  I got this error.  

Installing GHC v8.10.4 ..
./prereqs.sh: line 250: ghcup: command not found
./prereqs.sh: line 251: ghcup: command not found
./prereqs.sh: line 252: ghc: command not found
Installing Cabal v3.4.0.0..
./prereqs.sh: line 261: ghcup: command not found

Am I missing something?  or is this normal?

![Command Not Found](https://user-images.githubusercontent.com/89239478/130201223-6dcf186a-ee0b-4c73-be87-be7c0dda62ed.JPG)

**Comment by rdlrt** [comment]
> Using Ubuntu on windows 10

I think this is the issue 🙂 Most of the scripts are created purely for Linux environments. In this case, after installing `ghcup`, it seems that the profile / session has not been retained - requiring you to run `source ~/ada/.ghcup/env` manually and then potentially re-running the script.

**Comment by kivanio** [comment]
I got same on Ubuntu 20.04 (LTS) x64 VM machine at Digital Ocean
5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rdlrt** [comment]
@kivanio 
1. Could you confirm if bashrc file under your profile contains the ghcup additions?
2. Could you also try using `prereqs.sh -b alpha` and then rerun prereqs script (specifically for [this commit ](https://github.com/cardano-community/guild-operators/commit/da95c4ad04c099bca5e42f765e84238db4149e88#diff-ca2d5467ca4f040aae143f055a3a5704cb8656a0f0f03218f2b50ef9e0ac6430) additions)

**Comment by kivanio** [comment]
@rdlrt
1 -  This is what .bashrc has:
```
export CNODE_HOME=/opt/cardano/cnode

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

. "$HOME/.cargo/env"

[ -f "/home/user/.ghcup/env" ] && source "/home/user/.ghcup/env" # ghcup-env
```

2 - 
```
:~/tmp$ ./prereqs.sh -b alpha
Using apt to prepare packages for "Ubuntu" system
  Updating system packages...
[sudo] password for kadarelay: 
  Installing missing prerequisite packages, if any..
Creating Folder Structure ..
Environment Variable already set up!
IOG fork of libsodium installed to /usr/local/lib/
Downloading files...
```

Are supposed to destroy everything and start again with /prereqs.sh -b alpha?

**Comment by rdlrt** [comment]
Looks like it went fine (even from master), as ghcup was already available in your $PATH. Are you sure you received the exactly same message as OP (incl. the line numbers)?

**Comment by dehy** [comment]
Had this problem today. Ubuntu 20.04. I was installing it from root user (`SUDO=n ./prereqs.sh`, because automation, non ideal case, only testing) and the `/root/.bashrc` file contains this line:

```bash
# If not running interactively, don't do anything
[ -z "$PS1" ] && return
```

So environment is not reloaded after it got updated.

**Comment by rdlrt** [comment]
Linked PR should fix it, as it will directly source the env file instead of bashrc
