### ISSUE TITLE
after node update to 1.29.0 there is an exception AesonException "Error in $: key \"AlonzoGenesisFile\" not found"

### ISSUE THREAD

**Issue by marckkh** [cardano-community/guild-operators#1045]
after i update my node to 1.29.0 with guild operators i have an exception as below
```

AesonException "Error in $: key \"AlonzoGenesisFile\" not found"

cardano-node: Aeson exception:
Error in $: key "AlonzoGenesisFile" not found
```

but i follow this tutorial to fix it and it works perfectly

`https://forum.cardano.org/t/update-cardano-node-to-1-29-0-for-cntools-users/70526`

Download the mainnet-alonzo-genesis.json file and modify the config.json file

I saw that the prereqs.sh script was not updated for alonzo-genesis file so, we will need to download it manually;

Download the mainnet-alonzo-genesis.json file (for cntools I renamed the file to alonzo-genesis.json only and also the name should match with the filename from config.json file)

```
cd $CNODE_HOME/files or cd /opt/cardano/cnode/files
curl -sL -f -o alonzo-genesis.json https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/mainnet-alonzo-genesis.json
chmod 755 alonzo-genesis.json
ls -l
```

Modify the config.json file

`
nano config.json
`

add the 2 lines inside the file (I added on top)
```

 "AlonzoGenesisFile": "/opt/cardano/cnode/files/alonzo-genesis.json",
 "AlonzoGenesisHash": "7e94a15f55d1e82d10f09203fa1d40f8eede58fd8066542cf6566008068ed874",
```
save the file

example:

```
{
 "AlonzoGenesisFile": "/opt/cardano/cnode/files/alonzo-genesis.json",
 "AlonzoGenesisHash": "7e94a15f55d1e82d10f09203fa1d40f8eede58fd8066542cf6566008068ed874",
  "ApplicationName": "cardano-sl",
  "ApplicationVersion": 1,
  "ByronGenesisFile": "/opt/cardano/cnode/files/byron-genesis.json",
  "ByronGenesisHash": "5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb",
  "LastKnownBlockVersion-Alt": 0,
  "LastKnownBlockVersion-Major": 3,
  "LastKnownBlockVersion-Minor": 0,
  "MaxKnownMajorProtocolVersion": 2,
  "Protocol": "Cardano",
  "RequiresNetworkMagic": "RequiresNoMagic",
  "ShelleyGenesisFile": "/opt/cardano/cnode/files/genesis.json",
  "ShelleyGenesisHash": "1a3be38bcbb7911969283716ad7aa550250226b76a61fc51cc9a9a35d9276d81",
  "MaxConcurrencyDeadline": 4,
  "TraceBlockFetchClient": true,
```

**Comment by DamjanOstrelic** [comment]
Yes, 1.29.0 needs Alonzo genesis added to the config, it's documented on the node release: https://github.com/input-output-hk/cardano-node/releases/tag/1.29.0

CNTools has support for 1.29.0 but it's only on the `alpha` branch. Still waiting to make sure this release will end up as the last release (most likely) before Alonzo hardfork - after that changes will be pushed to `master` and the new CNTools version officially released.

**Comment by rdlrt** [comment]
>  i follow this tutorial to fix it and it works perfectly
> https://forum.cardano.org/t/update-cardano-node-to-1-29-0-for-cntools-users/70526

We're well aware of changes needed (and they're in place on alpha branch) , but please check the announcements channels in CNTools for any actions - as we cannot guarantee a customisation following instructions on forum/elsewhere will work - historically, we've found users often mix instructions and end up in wierd state. The action to not merge to master is intentional and is in line with the announcements on the documented (also a link within the tool) announcements channel
