### ISSUE TITLE
Installing prereqs from root to non-root user

### ISSUE THREAD

**Issue by dehy** [cardano-community/guild-operators#1053]
I'm actually testing some installation automation through Ansible and got some trouble running `prereqs.sh`

Launching the script as non-root triggers sudo prompt that cannot be answered in a script. Giving NOPASSWD:ALL sudo privileges to my user is not an option.

Would you mind if I updated the script to enable the launch from the root user and giving it a target non-root user for installation? Something like `prereqs.sh --target-user cardano` and the use of `sudo -u` inside the script.

**Comment by rdlrt** [comment]
> I'm actually testing some installation automation through Ansible and got some trouble running prereqs.sh

Do you have an option to make use of -K and continue with the script?
(PS: Docker uses SUDO environment variable)

**Comment by dehy** [comment]
> Do you have an option to make use of -K and continue with the script?

I'm currently executing my playbook using root (just after the vm is available), I cannot "become" my unprivileged user with ansible then execute sudo commands. The -K applies only during the "become" phase, not any subsequent sudo call. My user is a _dumb_ user only for executing the node(ie. no password, no sudo group).

For now, I made a workaround a little risky if something goes wrong: add NOPASSWD:ALL for my user, execute the script, then remove the NOPASSWD:ALL. Risky because if the script fails before the removal and for some reason is not seen and left that way.

Afterthoughts, updating the script itself with some more sudo command is too risky because of the human errors and cognitive complexity.

So, my only possibility left is:  execute the script with SUDO=n then manually move and chown files, just like the Docker image stages you have. May need rework each time the script is updated to follow the updates.

**Comment by rdlrt** [comment]
> Afterthoughts, updating the script itself with some more sudo command is too risky because of the human errors and cognitive complexity.

Ye - it's a constant battle between having contention for automation scripts (be it docker/ansible/kubectl/..) and users who will more likely use basic script automations 🙁 

If you think a middle ground can help you with your ops that does not disrupt normal user's operation, we'd be happy to customise.

> May need rework each time the script is updated to follow the updates

The permissions for folders should be almost the same from top folder (anything sensitive should go to <top folder>/priv) and executable scripts in scripts folder. Happy to discuss details/thoughts on https://t.me/guild_operators_official and then capture outcomes here if you'd like to

**Comment by dehy** [comment]
I ended up following the Docker stages and executing the script with root and then manually updating the rights and variables.

Afterthoughts, this is too much changes on a script that already automates many things. Using a provisioning tool for this job is not relevant. For 3 nodes, that too much work instead of doing it manually. So finally, i dumped ansible.
