### ISSUE TITLE
All files are executable after prereqs.sh

### ISSUE THREAD

**Issue by dehy** [cardano-community/guild-operators#1054]
https://github.com/cardano-community/guild-operators/blob/3ed17a1fd90768e1aa85f841cb648db5ad62800d/scripts/cnode-helper-scripts/prereqs.sh#L514

Any reason why you make all files executable at the end of script? For the first installation, it makes scripts (👍 ) and json files (? but not too harmful) executables but on subsequent reinstallations, it makes all files (logs, db files, ...) executable. Potential security issue, don't you think?

Would it be better to only target scripts with `find ${CNODE_HOME}/scripts -name '*.sh' -or -name 'env' -or -name 'cntools.libary' -exec chmod 755 \;`?

**Comment by rdlrt** [comment]
Good catch, would you like to add it as PR to alpha branch?
