### ISSUE TITLE
basics page says config goes in cnode/files but docker page says map config in cnode/priv, which is correct?

### ISSUE THREAD

**Issue by hamishcunningham** [cardano-community/guild-operators#1056]
hi,

Great repo, thanks!

https://cardano-community.github.io/guild-operators/basics/ implies that config.json etc. should be in /opt/cardano/cnode/files 

https://cardano-community.github.io/guild-operators/docker/tips/ describes mapping cnode/priv only

probably the latter should actually map both priv and files ?   

thanks!

hamish

**Comment by rdlrt** [comment]
- `priv` will contain sensitive information (keys , passwords)
- `files` would contain configuration files
will add a note to clarify in next doco PR
Thanks
