### ISSUE TITLE
Reset configs when start or restart a docker container

### ISSUE THREAD

**Issue by MichaelTMS** [cardano-community/guild-operators#1058]
Hi guys
When I restart the container, the config files are overwritten. This behavior is due to the regular run of the command in the entrypoint.sh. 
```bash
if [[ "$NETWORK" == "mainnet" ]]; then
  $CNODE_HOME/scripts/prereqs.sh -n mainnet -t cnode -s -f > /dev/null 2>&1 \
  && customise \
  && exec $CNODE_HOME/scripts/cnode.sh
```
The -f key passed to the prereqs .sh script and FORCE_OVERWRITE='Y'. 

```bash
if [[ ${NETWORK} = "guild" ]]; then
  curl -s -f -m ${CURL_TIMEOUT} -o byron-genesis.json.tmp ${URL_RAW}/files/byron-genesis-guild.json
  curl -s -f -m ${CURL_TIMEOUT} -o shelley-genesis.json.tmp ${URL_RAW}/files/genesis-guild.json
  curl -s -f -m ${CURL_TIMEOUT} -o alonzo-genesis.json.tmp ${URL_RAW}/files/alonzo-genesis-guild.json
  curl -s -f -m ${CURL_TIMEOUT} -o topology.json.tmp ${URL_RAW}/files/topology-guild.json
  curl -s -f -m ${CURL_TIMEOUT} -o config.json.tmp ${URL_RAW}/files/config-guild.json
elif [[ ${NETWORK} =~ ^(mainnet|testnet|staging)$ ]]; then
  curl -sL -f -m ${CURL_TIMEOUT} -o byron-genesis.json.tmp https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/${NETWORK}-byron-genesis.json
  curl -sL -f -m ${CURL_TIMEOUT} -o shelley-genesis.json.tmp https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/${NETWORK}-shelley-genesis.json
  curl -sL -f -m ${CURL_TIMEOUT} -o alonzo-genesis.json.tmp https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/${NETWORK}-alonzo-genesis.json
  curl -sL -f -m ${CURL_TIMEOUT} -o topology.json.tmp https://hydra.iohk.io/job/Cardano/iohk-nix/cardano-deployment/latest-finished/download/1/${NETWORK}-topology.json
  curl -s -f -m ${CURL_TIMEOUT} -o config.json.tmp ${URL_RAW}/files/config-${NETWORK}.json
else
  err_exit "ERROR!! Unknown network specified! Kindly re-check the network name, valid options are: mainnet, testnet, guild & staging"
fi
sed -e "s@/opt/cardano/cnode@${CNODE_HOME}@g" -i ./*.json.tmp
[[ ${FORCE_OVERWRITE} = 'Y' && -f topology.json ]] && cp -f topology.json "topology.json_bkp$(date +%s)"
[[ ${FORCE_OVERWRITE} = 'Y' && -f config.json ]] && cp -f config.json "config.json_bkp$(date +%s)"
[[ ${FORCE_OVERWRITE} = 'Y' && -f dbsync.json ]] && cp -f dbsync.json "dbsync.json_bkp$(date +%s)"
if [[ ${FORCE_OVERWRITE} = 'Y' || ! -f byron-genesis.json ]]; then mv -f byron-genesis.json.tmp byron-genesis.json; else rm -f byron-genesis.json.tmp; fi
if [[ ${FORCE_OVERWRITE} = 'Y' || ! -f shelley-genesis.json ]]; then mv -f shelley-genesis.json.tmp shelley-genesis.json; else rm -f shelley-genesis.json.tmp; fi
if [[ ${FORCE_OVERWRITE} = 'Y' || ! -f alonzo-genesis.json ]]; then mv -f alonzo-genesis.json.tmp alonzo-genesis.json; else rm -f alonzo-genesis.json.tmp; fi
if [[ ${FORCE_OVERWRITE} = 'Y' || ! -f topology.json ]]; then mv -f topology.json.tmp topology.json; else rm -f topology.json.tmp; fi
if [[ ${FORCE_OVERWRITE} = 'Y' || ! -f config.json ]]; then mv -f config.json.tmp config.json; else rm -f config.json.tmp; fi
if [[ ${FORCE_OVERWRITE} = 'Y' || ! -f dbsync.json ]]; then mv -f dbsync.json.tmp dbsync.json; else rm -f dbsync.json.tmp; fi

```

**Comment by shibug** [comment]
Not sure what OP wants. Do you want to reset at every container run or not? When a container starts, the previous state is not maintained unless it the config folder is mapped to host.  

If mapped to host, I believe you need to manage it.

**Comment by MichaelTMS** [comment]
The folder with the configuration files is moved to the host and is mounted every time the container is started

**Comment by MichaelTMS** [comment]
Due to this process, it normally does not start for us, since the configuration files are overwritten with the default. On the producer node, you need to run topologyUpdate.sh every time.

**Comment by MichaelTMS** [comment]
From the documentation, this script must be run in relay nodes

**Comment by shibug** [comment]
> From the documentation, this script must be run in relay nodes

Right. topologyUpdater script is to be run at the relays, Update the mainnet-topology daily and restart the relay. I only mount this file from the host and leave the rest of the config to be used inside the container.

**Comment by shibug** [comment]
> Due to this process, it normally does not start for us, since the configuration files are overwritten with the default. On the producer node, you need to run topologyUpdate.sh every time.

Try to use all the config from the container itself. Just mount the topology file from the host.

**Comment by MichaelTMS** [comment]
I have set a variables "TOPOLOGY" and "CONFIG"  in docker-compose .yml, but config file regular update after restart  container.

**Comment by MichaelTMS** [comment]
Do I need to set these variables: TraceTxInbound, TraceTxOutbound and TraceTxSubmissionProtocol on true?
These variable have default value is false.

**Comment by shibug** [comment]
> Do I need to set these variables: TraceTxInbound, TraceTxOutbound and TraceTxSubmissionProtocol on true?
> These variable have default value is false.

I don’t mess with them simply because I don’t look at the logs that often.

**Comment by shibug** [comment]
Please close the issue. This is not a defect anymore. Use other channels to ask questions
