### ISSUE TITLE
Docker. It is not possible to enable 'TraceMempool = true' in config.json

### ISSUE THREAD

**Issue by MichaelTMS** [cardano-community/guild-operators#1062]
The script **entrypoint.sh** contains a function **customise()** that always sets '**TraceMempool = false**' when starting the container

```bash
customise () {
find /opt/cardano/cnode -name "*config*.json" -print0 | xargs -0 sed -i 's/127.0.0.1/0.0.0.0/g' > /dev/null 2>&1 \
&& find /opt/cardano/cnode -name "*config*.json" -print0 | xargs -0 sed -i 's/\"TraceMempool\": false/\"TraceMempool\": true/g' > /dev/null 2>&1 \
&& find /opt/cardano/cnode -name "cntools.config" -print0 | xargs -0 sed -i 's/ENABLE_CHATTR=true/ENABLE_CHATTR=false/g' > /dev/null 2>&1 \
&& find $CNODE_HOME/scripts/env -print0 | xargs -0 sed -i 's/node0.socket/node.socket/g' > /dev/null 2>&1 \
&& find /opt/cardano/cnode -name "*config*.json" -print0 | xargs -0 sed -i 's/\"hasEKG\": 12788,/\"hasEKG\": [\n    \"0.0.0.0\",\n    12788\n],/g' > /dev/null 2>&1
}
```

It is necessary to implement the ability to change the value through a variable. If the variable is not set, then TraceMempool = false

**Comment by rdlrt** [comment]
> that always sets 'TraceMempool = false' when starting the container

This is done to avoid memory leaks and potential DDoS on servers that are on edge wrt system resources (should only be enabled for troubleshooting). Is there a reason you'd want to keep it enabled?

**Comment by MichaelTMS** [comment]
The parameter is needed to check the work. By default, the parameter should be disabled, but with the ability to change the flag using a variable. If you use a container, then each time you start / restart, this parameter is overwritten in config.json.

**Comment by shibug** [comment]
So this is not really a bug. OP is requesting the ability to change the value when the container starts by passing docker run arguments. Is that right? @MichaelTMS

**Comment by MichaelTMS** [comment]
I would like to be able to pass an environment variable to the container to enable this functionality or fix:
https://github.com/cardano-community/guild-operators/issues/1058.

**Comment by shibug** [comment]
And you can do that without any change to the code. Pass env in docker run using the -e option

**Comment by MichaelTMS** [comment]
Which variable should I pass?

**Comment by redoracle** [comment]
I removed the TraceMempool forcing to false. Besides you can always use your own configuration by mapping the files with the "-v" option in the run command.

**Comment by redoracle** [comment]
using the -e option is something doable if requested.

are you interested? or having the ../priv mapping for custom cfg is not enough?
