### ISSUE TITLE
Cnode Systemd file throws up a YAML exception

### ISSUE THREAD

**Issue by AndrewGoodson** [cardano-community/guild-operators#1067]
**Describe the bug**
When prereqs.sh udpates and ./prereqs.sh -f is run systemd cnode throws up a YAML Exception "Yaml file not found: /files/config.json"

Troubleshooting:
1. When cnode.sh is run independently, the node runs without any errors. 
2. When the Cardano-node command is run manually, it runs without any errors with the same config.json file
3. Based on the above, the issue is with the cnode systemd service and not the config.json file as states in the journalctl logs
4. Have updated the cnode systemd service through the deploy-systemd script and re-ran prereqs.sh, and the results are still the same

**To Reproduce**
Could not reproduce this error

**Expected behavior**
Once ./prereqs.sh -f is run and files are edited accordingly, *sudo systemctl start cnode* should start the node but does not

**Screenshots**
<img width="839" alt="cnode sh config error" src="https://user-images.githubusercontent.com/62703301/132104572-df7951c6-a302-481f-983a-b6e50f22420e.png">

**Version:**
 - OS: Ubuntu 18 Bonic
 - Product version: - v8.6.3
 - Cardano Node version: 1.29.0
 - Network you're connecting to: Mainnet
 - $CNODE_HOME/files/genesis.json`]

**Additional context**
As I updated my other nodes, I could not reproduce the issue.

**Comment by rdlrt** [comment]
Make sure your systemd is running as correct user (same as you run on shell9.
Also, provide your systemd file and your OS details
