### ISSUE TITLE
archiveLog() function should also delete old node0.json logs from {LOG_DIR}/archive

### ISSUE THREAD

**Issue by t0m3kf** [cardano-community/guild-operators#1081]
**Describe the bug**
There's a function in cnode.sh that copy old logs from {LOG_DIR} to {LOG_DIR}/archive. This is true for all the logs (cntools logs and cardano node logs node0.json). This can lead to disk issues on systems with low disk space 

archiveLog()  funciton from cntools.library does take care of old cntools logs but node0.logs stays there forever and need to be deleted manually

**To Reproduce**
1. Leave the node running for some time
2. Check the {LOG_DIR}/archive folder periodically
3. cntools-history.log_* files  are correctly removed but all the node0-<date>.json files stay there forever

**Expected behavior**
archiveLog() routine should also delete old node0-<date>.json files

**Version:**
 CNTools v8.6.3 mainnet

**Comment by rdlrt** [comment]
If you're not restarting node, then the archival is not required as the config file retains only a certain number of log files (as defined in rotation rules). The only reason to move it to archive is upon a crash, this allows you to investigate the issue. You can set up the removal from archive folder if you need externally, but that's not a use case that we can generalise to all.

CNTools archiveLog function is completely seperate and unrelated to node.
