### ISSUE TITLE
cardano-db-sync requires genesis hashes: Error parsing node config: AesonException \"Error in $: key \\\"ByronGenesisHash\\\" not found

### ISSUE THREAD

**Issue by rssfed23** [cardano-community/guild-operators#1083]
**Describe the bug**
A clean install/build of cntools (master branch), node started and successfully synced and cardano-db-sync built. No custom changes.
When running 
```cardano-db-sync-extended --config $CNODE_HOME/files/dbsync.json --socket-path $CNODE_HOME/sockets/node0.socket --state-dir $CNODE_HOME/guild-db/ledger-state --schema-dir schema/```

I get the following error:
```cardano-db-sync-extended: FatalError {fatalErrorMessage = "Error parsing node config: AesonException \"Error in $: key \\\"ByronGenesisHash\\\" not found\""}```

**Expected behavior**
DB Sync starts

**Version:**
 - OS: Ubuntu 21.04
 - Product version: v8.6.3
 - Cardano Node version: 1.29.0 4c594429
 - Network you're connecting to: mainnet

**Additional context**
I was able to resolve this by adding in the hashes for Byron, Shelly and Alonzo and sync started successfuly. It seems cardano-db-sync requires the 3 hashes in config.json, but these are not present in the default install of cntools?

**Comment by Scitz0** [comment]
You need to add the genesis hashes to the config file, Byron is the only one needed but you can add the other as well. Hopefully, this dependency can soon be removed from dbsync as it is for cardano-node. 
called:
`ByronGenesisHash` `ShelleyGenesisHash` `AlonzoGenesisHash`
Byron:
`cardano-cli byron genesis print-genesis-hash --genesis-json FILEPATH`
Shelley/Alonzo:
`cardano-cli genesis hash --genesis FILEPATH`
