### ISSUE TITLE
LD_LIBRARY_PATH=/usr/local/lib:"${LD_LIBRARY_PATH}" fails to load

### ISSUE THREAD

**Issue by Bmtxs** [cardano-community/guild-operators#1085]
**Describe the bug**
Updating the node using prereqs.sh and cabal-build-all.sh scripts in the default mode, the libsodium path is not being taken by the service running the node. The node reports Symbol lookup error. Undefined symbol:crypto_vrf_publickeybytes

**To Reproduce**
1.run prereqs.sh and cabal-build-all.sh scripts without arguments

**Expected behavior**
While updating the node compiling the latest binaries using the scripts in the default mod the path LD_LIBRARY_PATH=/usr/local/lib:"${LD_LIBRARY_PATH}" should be loaded automatically.

**Version:**
 - OS: Ubuntu 20.04 LTS
 - Product version: Latest cnode-helper-scripts
 - Cardano Node version: Upgrade from cardano-node 1.27.0 to 1.29.0

**Comment by rdlrt** [comment]
LD_LIBRARY_PATH is added to ~/.bashrc by prereqs, and the systemd definition executes bash command to execute the script.
Thus, it sounds like in your case, you do not have ~/.bashrc being used by your bash

> Cardano Node version: Upgrade from cardano-node 1.27.0 to 1.29.0

The behaviour has not changed between the two versions
