### ISSUE TITLE
Add missed slots to displayed statistics

### ISSUE THREAD

**Issue by orpheus-antpool** [cardano-community/guild-operators#1101]
Missed slots are an important performance metric for SPOs. 
This should be captured and displayed by gLIveView.sh from Prometheus, e.g.:
``curl -s localhost:12798/metrics | grep cardano_node_metrics_slotsMissedNum_int | cut -f 2 -d ' '``

**Comment by rdlrt** [comment]
Could you please clarify what is your understanding of metric missed slot and how it maps as important metric (versus leader:forged:adopted counts)?

**Comment by Scitz0** [comment]
Thanks for your contribution, PR now merged into alpha with some minor changes.
