### ISSUE TITLE
Docker: POOL IN/OUT RTT NOT WORKED

### ISSUE THREAD

**Issue by MichaelTMS** [cardano-community/guild-operators#1113]
Hi,

We run docker cardano node 1.29: but RTT not showing any statistics

Any one can assist me what is wrong in our configuration?

![image](https://user-images.githubusercontent.com/90009297/134414485-3e6a9e0e-8a2c-4cd4-9525-c83786677563.png)

![image](https://user-images.githubusercontent.com/90009297/134414540-6545e14a-09a4-4428-981d-9b62783c425e.png)

If I run command: cardano-ping -h relay-eu.adaimpulse.club -p 6000 -q -j -c 2 | jq
all ok.

from outside container I can ping our relay nodes success:
![image](https://user-images.githubusercontent.com/90009297/134414675-808f7f9d-b8ba-4ea4-a2d8-b4cfa11edd90.png)

**Comment by shibug** [comment]
I am aware of this issue but didn't get time to work on it yet. Hopefully sometime next week.  If anyone else wants to pick it up, you are more than welcome.

**Comment by redoracle** [comment]
You need to install tcptraceroute

I have made a PR about it, I guess in 24 hours the new image will be available on docker-hub

**Comment by MichaelTMS** [comment]
I rebuilt the docker image, but the problem was not fixed.

**Comment by redoracle** [comment]
What dockerfile are you using to build the image? Alpha or Master?

On the master repo the dockerfile still the older version, but the image on
dockerhub is properly built.
https://hub.docker.com/repository/docker/cardanocommunity/cardano-node/general

**Comment by MichaelTMS** [comment]
I used the Alpha branch and I saw what changed
