### ISSUE TITLE
Cardano-Node docker image is missing dialog package

### ISSUE THREAD

**Issue by kantic** [cardano-community/guild-operators#1119]
**Describe the bug**
After setting up a fresh cardano node using the provided [docker image](https://hub.docker.com/r/cardanocommunity/cardano-node), I've tried to use the backup function of CNTools. When I get the prompt to select a target file path for the backup file, I get the following error message: **cntools.library: line 265: dialog: command not found**.
It seems that the dialog package has not been installed in the _prereqs.sh_ script. When I try to execute `$ dialog` in the bash, I get the error message `bash: dialog: command not found'`
Furthermore, when I try to install the dialog package with apt-get in the running container with the command
`$ sudo apt-get install dialog` I get the following results:
```bash
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package dialog is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'dialog' has no installation candidate
```
This is resolved by first issuing `$ sudo apt-get update` and then `$ sudo apt-get install dialog`, which installs the dialog package correctly.
After that, the backup function of CNTools works properly.

**To Reproduce**
1. Run a new docker container with the cardano-node image
2. Wait until synced.
3. Open a bash terminal in the container, start the CNTools script and try to make a backup

**Expected behavior**
I would expect that the dialog package is already installed properly in the docker image and that I can execute the backup function of the CNTools script without any errors.

**Screenshots**
n/a

**Version:**
 - Host OS: Manjaro Linux (latest)
 - Product version: latest cardano-node docker image, CNTools version v8.6.5
 - Cardano Node version: cardano-node 1.29.0 - linux-x86_64 - ghc-8.10, git rev 4c59442958072657812c6c0bb8e0b4ab85ce1ba2
 - Network you're connecting to: testnet

**Additional context**
n/a

**Comment by kantic** [comment]
Thank you for your commit and changes.
Unfortunately the problem with the same error message still exists because the environment variables **ENABLE_CHATTR** and **ENABLE_DIALOG** are still set to true in the file _cntools.config_. Maybe they should be also by default set to false in the _entrypoint.sh_ script file?

**Comment by rdlrt** [comment]
> Unfortunately the problem with the same error message still exists because the environment variables **ENABLE_CHATTR** and **ENABLE_DIALOG** are still set to true in the file _cntools.config_. Maybe they should be also by default set to false in the _entrypoint.sh_ script file?


Check the linked PR, the change was to sed those values to FALSE in cntools.config files
