### ISSUE TITLE
cncli not working in Docker container

### ISSUE THREAD

**Issue by rcourtman** [cardano-community/guild-operators#1158]
**Describe the bug**
cncli does not work in the docker container. It's in the path and shows with just 'cncli', but when you actually try and use a function like cncli sync you get:

> Checking for script updates...
ERROR: failed to locate cncli executable, please install with 'prereqs.sh'

**To Reproduce**
1. Run docker image (I had to build from stage 3 and add sqlite3 otherwise it complained it was missing)
2. try and use cncli sync

**Screenshots**
![image](https://user-images.githubusercontent.com/8825017/138971272-8b9827ba-1d30-49d5-aa9d-709512006560.png)
![image](https://user-images.githubusercontent.com/8825017/138971335-7d55e93b-0f3b-4ddf-a9c1-ddca35282321.png)
![image](https://user-images.githubusercontent.com/8825017/138971364-1b9ae8a1-d059-4e8b-a221-38f48950d8a9.png)
![image](https://user-images.githubusercontent.com/8825017/138971700-e4c920bd-bd7d-4964-9a6b-7aaa0928b16c.png)
![image](https://user-images.githubusercontent.com/8825017/138971817-9ca12626-658d-4f0b-9f07-6303dd1c86e2.png)
![image](https://user-images.githubusercontent.com/8825017/138971846-f56e095a-81dd-4ecf-ba79-6a62d7dacec4.png)
![image](https://user-images.githubusercontent.com/8825017/138971870-51e462ab-9634-4139-a22f-776c15c9e72c.png)

**Version:**
 - OS: Ubuntu
 - Cardano Node version: cardano-node 1.30.1 - linux-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

**Comment by TrevorBenson** [comment]
@rcourtman PR #1171 should resolve your issue. Leaving the ticket open until I or someone else confirms.

**Comment by rcourtman** [comment]
Not working for me

`ERROR: sqlite3 not found, please install before activating blocklog function
`

**Comment by redoracle** [comment]
![image](https://user-images.githubusercontent.com/1196958/140323796-2deef135-c2bc-4e6d-91ff-85113ef267bf.png)
