### ISSUE TITLE
udev is not installed but expected by prereqs.sh

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#1170]
**Describe the bug**
The prereqs.sh script expects and calls udev, but has only reqeusted the installation of libudev-dev development packages, which do not contain udevadm. Observed when building from `files/docker/node/dockerfile_stage1` which is specific to debian slim.

**To Reproduce**
1. Run prereqs.sh (manually or via `docker build`)
2. See errors about line 2, 19, 20, 373 and 374

**Expected behavior**
The udev paths exist and udevadm is installed and functional when required.

**Screenshots**
```
Creating Folder Structure ..
Setting up Environment Variable
IOG fork of libsodium installed to /usr/local/lib/
Installing CNCLI
  downloading CNCLI...
  latest version: v4.0.1
  installing RUST...
  building CNCLI v4.0.1 ...
  cncli 4.0.1 installed!
Installing Vacuumlabs cardano-hw-cli
  downloading Vacuumlabs cardano-hw-cli...
  latest version: 1.6.2
  adding cardano-hw-cli to PATH and setting Ledger udev rules, reload shell to take effect!
bash: line 2: /etc/udev/rules.d/20-hw1.rules: No such file or directory
bash: line 19: udevadm: command not found
bash: line 20: udevadm: command not found
sed: can't read /etc/udev/rules.d/20-hw1.rules: No such file or directory
sed: can't read /etc/udev/rules.d/51-trezor.rules: No such file or directory
./prereqs.sh: line 373: udevadm: command not found
./prereqs.sh: line 374: udevadm: command not found
  cardano-hw-cli v1.6.2 installed!
Downloading files...
COMMIT cardanocommunity/cardano-node:stage1
```

**Version:**
 - OS: Debian Slim (Bullseye)
 - Product version: prereqs.sh commit 8f7b3ae
 - Cardano Node version: 1.30.1
 - Network you're connecting to: Mainnet

**Comment by TrevorBenson** [comment]
I'm not finding that debian stretch has `udevadm`. It does contain the libudev1 package, but this does not provide udevadm so that `udevadm trigger` can be called. Even though debian slim has libudev1 this does not appear to provide the `/etc/udev/rules.d/` directory required to deploy `20-hw1.rules` & `51-trezor.rules` files.

- Debian Buster appears to have udevadm within its packages.

@redoracle This makes it appear as if debian slim (stretch) is not viable for cardano-hw-cli. I may drop this from the `cncli-in-container` branch to not introduce additional errors and keep the PR focused solely on CNCLI functionality.

**Comment by redoracle** [comment]
updated
