### ISSUE TITLE
Problematic local port range recommendations for sysctl.conf

### ISSUE THREAD

**Issue by pyromaniac3010** [cardano-community/guild-operators#1200]
**Describe the bug**
In guild-operators/docs/Build/grest.md it is suggested to change sysctl.conf to allow more source ports for haproxy:
net.ipv4.ip_local_port_range="1024 65534"
In the same file it is recommended to bind haproxy to port 8053 and 8453. As these ports are within the range "1024 65534" it could happen that you force a source port collision. Also the cardano-node port (3001) and postgresql-ports (5432) are within the recommended range "1024 65534".
There are two solutions possible:
1. Increase net.ipv4.ip_local_port_range to a range not colliding with default ports like probably "10000 65534"
2. add all problematic ports to "net.ipv4.ip_local_reserved_ports".
Ports in comma separated list net.ipv4.ip_local_reserved_ports are excluded from automatic port assignments.
More information: https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

-

**Expected behavior**
Avoid possible source port collisions with known ports.

**Screenshots**

**Version:**
 - OS: Linux
 - Product version: documentation

**Additional context**

**Comment by rdlrt** [comment]
> As these ports are within the range "1024 65534" it could happen that you force a source port collision.

That is not a reservation for ports to listen on, they're used for ad-hoc connections by load balancers to connect to node or other components. The short-lived connection requests will only start polling static services listening on ports, it cannot cause a conflict when the mentioned port is already used by node or haproxy (and absence of node being up automatically removes your service from cluster), unless you're using this on a shared system with components running that's not within the guide - which would then need a seperate assessment
