### ISSUE TITLE
Trouble with gLiveView 1.24.0

### ISSUE THREAD

**Issue by icculp** [cardano-community/guild-operators#1212]
**Describe the bug**
gLiveView failing to connect. 
Will cycle through three times:
`Connection to node lost, retrying (1/3)!`
until finally
`COULD NOT CONNECT TO A RUNNING INSTANCE, 3 FAILED ATTEMPTS IN A ROW!`

**To Reproduce**
Install node via the following steps on fresh VPS after creating separate cardano sudoer user and `sudo apt-get update -y && sudo apt-get upgrade -y`:
![image](https://user-images.githubusercontent.com/57159226/144356538-020cbe84-3443-4d39-99d4-3e8497ab3530.png)
env defaults explicit
![image](https://user-images.githubusercontent.com/57159226/144356639-565f642d-42ee-43c8-b86b-1b260bf7cc68.png)

**Expected behavior**
gLiveView to work as expected

**Version:**
 - Same issue on Debian 10 as well as Ubuntu 20.04 LTS
 - gLiveView 1.24.0
 - Cardano Node version: 1.31.0
 - Network you're connecting to: testnet 1097911063 

**Additional context**
No issues in `journalctl -e -f -u cnode`, can query the blockchain fine in `cardano-cli query tip --testnet-magic 1097911063`, confirm running params when viewing from `ps auxf | grep cardano`. Tried initially on Debian 10 to no avail, even waited all day for it to fully sync. echo'd the obvious vars in env around lines 618-622 of gLiveView before error to make sure they are as expected. nodeStartTime was always 0, but haven't traced back further to determine why. After rebuilding the node from scratch again but this time using Ubuntu 20.04 I ran into the exact same issue. This time by accident I discovered that if I press a random key (like space or c or whatever) when it’s going through the 3 tries (Connection to node lost, retrying (1/3)!
), the gliveview screen will actually display for a few seconds, then sometimes it goes back to retrying, or sometimes just stay showing gLive. If I don't press any keys it just retries until failure.

![image](https://user-images.githubusercontent.com/57159226/144357166-56444a3b-dab1-435d-823d-0b08591b3f18.png)

**Comment by rdlrt** [comment]
1. Your screenshot suggests that node sync status as queried by EKG, is 2.6% (and you're in epoch 53 on testnet). cli tip not returning error does not necessarily mean your node is in sync. _If your status at CLI is different_ to what you see on that screenshot (example a different epoch), then you likely have a mismatch of ports for some reason.
2. The error message you see is because EKG is not responsive yet, and if the curl request to EKG times out, you'd see the `Connection to node lost` message.
3. While the node is synching up, depending on the task, it is normal for it to not respond for a bit to EKG requests, does not necessarily mean an issue.

**Comment by icculp** [comment]
Hey Priyank, thanks for the response. 1. As I indicated in the issue, I had a fully synced node and still had the issue. The SS is from last night after starting from scratch again. It's been overnight, now I'm back at 100%, and it's still doing the same thing. 2. On the initial attempt I had curled at localhost:12788 and gotten a response.
![image](https://user-images.githubusercontent.com/57159226/144429331-09e0cd6e-3053-4e24-99b5-a070ee9b3b5e.png)
3. Still an issue.
![image](https://user-images.githubusercontent.com/57159226/144429403-7f188a8f-f4a7-41bb-892b-2dbc9c840933.png)

**Comment by Scitz0** [comment]
Thats not ekg output you posted, thats html code, should be json code. 
What is the port in files/config.json for ekg?
Also, what does this command give you:
`curl -s -H 'Accept: application/json' http://localhost:12788 | jq .cardano.node.metrics.nodeStartTime.int.val`
It needs this metric from ekg, else it will not start.

**Comment by icculp** [comment]
In files/config.json "hasEKG": 12788
That command results in null. Without the pipe to jq, this is the full output:


{"iohk-monitoring version":{"val":"0.1.10.1","type":"l"},"cardano":{"node":{"metrics":{"blockNum":{"int":{"val":3121699,"type":"g"}},"blockfetchclient":{"blockdelay":{"s":{"val":"0.41943237","type":"l"},"cdfFive":{"val":"0.9990740740740741","type":"l"},"cdfThree":{"val":"0.9990740740740741","type":"l"},"cdfOne":{"val":"0.9722222222222222","type":"l"}},"lateblocks":{"val":2,"type":"c"},"blocksize":{"val":1590,"type":"g"}},"epoch":{"int":{"val":172,"type":"g"}},"connectedPeers":{"int":{"val":2,"type":"g"}},"forks":{"int":{"val":21,"type":"g"}},"density":{"real":{"val":"3.11616365629869e-2","type":"l"}},"Mem":{"resident":{"int":{"val":1486282752,"type":"g"}}},"RTS":{"gcMajorNum":{"int":{"val":824,"type":"g"}},"gcLiveBytes":{"int":{"val":803614288,"type":"g"}},"gcHeapBytes":{"int":{"val":1409286144,"type":"g"}},"gcMinorNum":{"int":{"val":537908,"type":"g"}},"mutticks":{"int":{"val":2647677,"type":"g"}},"gcticks":{"int":{"val":405479,"type":"g"}}},"slotInEpoch":{"int":{"val":190583,"type":"g"}},"slotNum":{"int":{"val":44124983,"type":"g"}},"Stat":{"cputicks":{"int":{"val":3053156,"type":"g"}},"threads":{"int":{"val":16,"type":"g"}}}}}},"ekg":{"server_timestamp_ms":{"val":1638494242151,"type":"c"}},"rts":{"gc":{"bytes_allocated":{"val":16283090665472,"type":"c"},"gc_wall_ms":{"val":2187466,"type":"c"},"mutator_cpu_ms":{"val":26476780,"type":"c"},"peak_megabytes_allocated":{"val":1344,"type":"g"},"par_tot_bytes_copied":{"val":710460974320,"type":"g"},"cumulative_bytes_used":{"val":239788959848,"type":"c"},"par_max_bytes_copied":{"val":505133546280,"type":"g"},"init_wall_ms":{"val":2,"type":"c"},"max_bytes_used":{"val":475313992,"type":"g"},"bytes_copied":{"val":710460974320,"type":"c"},"current_bytes_used":{"val":803614288,"type":"g"},"wall_ms":{"val":76831217,"type":"c"},"cpu_ms":{"val":30531576,"type":"c"},"mutator_wall_ms":{"val":74643751,"type":"c"},"gc_cpu_ms":{"val":4054796,"type":"c"},"par_avg_bytes_copied":{"val":710460974320,"type":"g"},"num_gcs":{"val":538732,"type":"c"},"current_bytes_slop":{"val":19546544,"type":"g"},"num_bytes_usage_samples":{"val":824,"type":"c"},"max_bytes_slop":{"val":25309416,"type":"g"},"init_cpu_ms":{"val":2,"type":"c"}}}}

**Comment by rdlrt** [comment]
> That command results in null.

As mentioned on first reply, that is the cause of the error below:

> The error message you see is because EKG is not responsive yet (eg: uptime metric is not available), and if the curl request to EKG times out or does not give expected response, you'd see the `Connection to node lost` message.

Your EKG output is missing `nodeStartTime`, resulting in the issue.

**Comment by icculp** [comment]
I'm running into this issue on brand new fresh builds after running prereqs and then compiling cardano-node and cardano-cli binaries from source, the exact commands I used are posted in the screen shot in the original post. I even indicated in my troubleshooting in the op that nodeStartTime was 0. So your response that the problem is that nodeStartTime is null seems a bit redundant. It's like you're just repeating the problem I posted in my op back to me. What is the root of this problem and how do I solve it?

**Comment by DamjanOstrelic** [comment]
Just for info, I recently did a completely fresh install and have not run into this issue (on MAINNET):
```
curl -s -H 'Accept: application/json' http://localhost:12788 | jq .cardano.node.metrics.nodeStartTime.int.val

1638028752
```

**Comment by Scitz0** [comment]
> I'm running into this issue on brand new fresh builds after running prereqs and then compiling cardano-node and cardano-cli binaries from source, the exact commands I used are posted in the screen shot in the original post. I even indicated in my troubleshooting in the op that nodeStartTime was 0. So your response that the problem is that nodeStartTime is null seems a bit redundant. It's like you're just repeating the problem I posted in my op back to me. What is the root of this problem and how do I solve it?

Have you disabled some metrics in config.json from default downloaded by prereqs?

**Comment by icculp** [comment]
Nope, I haven't disabled anything, or done anything during setup beyond what I posted above. After deploying as systemd service, I verify the status of the service, check journalctl for errors, then try to query the tip, then run gLiveView.

**Comment by icculp** [comment]
The only part of my setup that's not above, is on a brand new fresh node I logged in as root, then performed the following:

sudo adduser cardano
sudo adduser cardano sudo
sudo apt-get update -y && apt-get upgrade -y

Once that's done, I exit the session and log back in as cardano and run the setup script in the ss above

**Comment by Scitz0** [comment]
> {"iohk-monitoring version":{"val":"0.1.10.1","type":"l"},"cardano":{"node":{"metrics":{"blockNum":{"int":{"val":3121699,"type":"g"}},"blockfetchclient":{"blockdelay":{"s":{"val":"0.41943237","type":"l"},"cdfFive":{"val":"0.9990740740740741","type":"l"},"cdfThree":{"val":"0.9990740740740741","type":"l"},"cdfOne":{"val":"0.9722222222222222","type":"l"}},"lateblocks":{"val":2,"type":"c"},"blocksize":{"val":1590,"type":"g"}},"epoch":{"int":{"val":172,"type":"g"}},"connectedPeers":{"int":{"val":2,"type":"g"}},"forks":{"int":{"val":21,"type":"g"}},"density":{"real":{"val":"3.11616365629869e-2","type":"l"}},"Mem":{"resident":{"int":{"val":1486282752,"type":"g"}}},"RTS":{"gcMajorNum":{"int":{"val":824,"type":"g"}},"gcLiveBytes":{"int":{"val":803614288,"type":"g"}},"gcHeapBytes":{"int":{"val":1409286144,"type":"g"}},"gcMinorNum":{"int":{"val":537908,"type":"g"}},"mutticks":{"int":{"val":2647677,"type":"g"}},"gcticks":{"int":{"val":405479,"type":"g"}}},"slotInEpoch":{"int":{"val":190583,"type":"g"}},"slotNum":{"int":{"val":44124983,"type":"g"}},"Stat":{"cputicks":{"int":{"val":3053156,"type":"g"}},"threads":{"int":{"val":16,"type":"g"}}}}}},"ekg":{"server_timestamp_ms":{"val":1638494242151,"type":"c"}},"rts":{"gc":{"bytes_allocated":{"val":16283090665472,"type":"c"},"gc_wall_ms":{"val":2187466,"type":"c"},"mutator_cpu_ms":{"val":26476780,"type":"c"},"peak_megabytes_allocated":{"val":1344,"type":"g"},"par_tot_bytes_copied":{"val":710460974320,"type":"g"},"cumulative_bytes_used":{"val":239788959848,"type":"c"},"par_max_bytes_copied":{"val":505133546280,"type":"g"},"init_wall_ms":{"val":2,"type":"c"},"max_bytes_used":{"val":475313992,"type":"g"},"bytes_copied":{"val":710460974320,"type":"c"},"current_bytes_used":{"val":803614288,"type":"g"},"wall_ms":{"val":76831217,"type":"c"},"cpu_ms":{"val":30531576,"type":"c"},"mutator_wall_ms":{"val":74643751,"type":"c"},"gc_cpu_ms":{"val":4054796,"type":"c"},"par_avg_bytes_copied":{"val":710460974320,"type":"g"},"num_gcs":{"val":538732,"type":"c"},"current_bytes_slop":{"val":19546544,"type":"g"},"num_bytes_usage_samples":{"val":824,"type":"c"},"max_bytes_slop":{"val":25309416,"type":"g"},"init_cpu_ms":{"val":2,"type":"c"}}}}

Could you post your config.json file?

**Comment by icculp** [comment]
{
  "AlonzoGenesisFile": "/opt/cardano/cnode/files/alonzo-genesis.json",
  "ApplicationName": "cardano-sl",
  "ApplicationVersion": 1,
  "ByronGenesisFile": "/opt/cardano/cnode/files/byron-genesis.json",
  "LastKnownBlockVersion-Alt": 0,
  "LastKnownBlockVersion-Major": 3,
  "LastKnownBlockVersion-Minor": 0,
  "MaxKnownMajorProtocolVersion": 2,
  "Protocol": "Cardano",
  "RequiresNetworkMagic": "RequiresMagic",
  "ShelleyGenesisFile": "/opt/cardano/cnode/files/shelley-genesis.json",
  "TraceBlockFetchClient": true,
  "TraceBlockFetchDecisions": true,
  "TraceBlockFetchProtocol": false,
  "TraceBlockFetchProtocolSerialised": true,
  "TraceBlockFetchServer": false,
  "TraceChainDb": true,
  "TraceChainSyncBlockServer": true,
  "TraceChainSyncClient": false,
  "TraceChainSyncHeaderServer": false,
  "TraceChainSyncProtocol": false,
  "TraceConnectionManager": true,
  "TraceDNSResolver": true,
  "TraceDNSSubscription": false,
  "TraceDiffusionInitialization": false,
  "TraceErrorPolicy": true,
  "TraceForge": true,
  "TraceHandshake": false,
  "TraceInboundGovernor": false,
  "TraceIpSubscription": false,
  "TraceLedgerPeers": false,
  "TraceLocalChainSyncProtocol": false,
  "TraceLocalErrorPolicy": true,
  "TraceLocalHandshake": false,
  "TraceLocalRootPeers": false,
  "TraceLocalTxSubmissionProtocol": false,
  "TraceLocalTxSubmissionServer": false,
  "TraceMempool": false,
  "TraceMux": false,
  "TracePeerSelection": false,
  "TracePeerSelectionActions": false,
  "TracePublicRootPeers": false,
  "TraceServer": false,
  "TraceTxInbound": false,
  "TraceTxOutbound": false,
  "TraceTxSubmissionProtocol": false,
  "TracingVerbosity": "NormalVerbosity",
  "TurnOnLogMetrics": true,
  "TurnOnLogging": true,
  "MaxConcurrencyDeadline": 2,
  "defaultBackends": [
    "KatipBK"
  ],
  "defaultScribes": [
    [
      "FileSK",
      "/opt/cardano/cnode/logs/node0.json"
    ]
  ],
  "hasEKG": 12788,
  "hasPrometheus": [
    "127.0.0.1",
    12798
  ],
  "minSeverity": "Info",
  "options": {
    "mapBackends": {
      "cardano.node.metrics": [
        "EKGViewBK"
      ],
      "cardano.node.resources": [
        "EKGViewBK"
      ]
    },
    "mapSubtrace": {
      "cardano.node.metrics": {
        "subtrace": "Neutral"
      }
    }
  },
  "rotation": {
    "rpKeepFilesNum": 10,
    "rpLogLimitBytes": 50000000,
    "rpMaxAgeHours": 24
  },
  "setupBackends": [
    "KatipBK",
    "EKGViewBK"
  ],
  "setupScribes": [
    {
      "scKind": "FileSK",
      "scName": "/opt/cardano/cnode/logs/node0.json",
      "scFormat": "ScJson",
      "scRotation": null
    }
  ]
}

**Comment by Scitz0** [comment]
Nothing obvious sticks out as wrong. 
what about output in logs/node0.json, any error that sticks out?
What's output as reported by systemd?
`systemctl status cnode`

**Comment by icculp** [comment]
sudo systemctl status cnode
![image](https://user-images.githubusercontent.com/57159226/144623140-241f1164-41b3-4113-8a4e-08d713111d9c.png)
journalctl -e -f -u cnode
![image](https://user-images.githubusercontent.com/57159226/144623283-9e2f13ac-c554-40ab-af70-8c284b442e35.png)

logs/node0.json is huge, so I cat | tail -50, didn't see anything. cat | grep error, grep 12788, grep retry, grep fail... nothing stuck out

**Comment by rdlrt** [comment]
I think your issue is instead of using a release, you're building your node against master

The release commit you should be using :
![IMG_20211204_103823](https://user-images.githubusercontent.com/3169068/144686329-4b26dc07-03f5-46b8-9705-9f45edeeec0d.jpg)

The one you're using:
![IMG_20211204_103855](https://user-images.githubusercontent.com/3169068/144686393-6eeef4e0-6605-4f9a-b6f3-56f5ab683e04.jpg)

**Comment by icculp** [comment]
Well, that was the only difference between the first run through and the second, is the second time I commented out the checkout and pull from latest. Maybe something got corrupted the first time around. I will rebuild from scratch again and verify that it's coming from the release commit above and let you know how it goes. Thanks to everyone who made suggestions here.

**Comment by rdlrt** [comment]
The specific metric was removed **after** 1.31.0 [against a WIP](https://github.com/input-output-hk/cardano-node/pull/3337) as they're changing tracing infra. , but from tools point of view - we'd only keep support for current production release on master branch. While on alpha branch, we try to take a balanced view of realistic changes (atm - we're not even sure what the new tracing infra changes will be, we might have to rely on OS for basic stats instead ..but that's a decision in future when there's a realistic release finalized.

**Comment by icculp** [comment]
Can confirm it's now working fine. Thanks again for all your help and for the info, I've enjoyed learning more about how it all works in the process.
