### ISSUE TITLE
Weird error messages when starting cntools in offline mode

### ISSUE THREAD

**Issue by amani1104** [cardano-community/guild-operators#1213]
**Describe the bug**
When starting cntools in offline mode after a fresh install with prereqs.sh, the tool does not start and quits with an error: 

`ERROR: Failed to create wallet directory: ` 

I checked the permissions in the cnode folder and they are all set to my user. When I uncomment wallet, pool and asset folders in the env file, the error message goes away. However, new errors appear: 

```
find: ‘//archive’: Permission denied
./cntools.sh: line 131: cmdAvailable: command not found

Missing one or more of the required command line tools, press any key to exit
```

I have no idea to what folder the first message relates (`find: ‘//archive’: Permission denied`). I have checked line 131 in cntools.sh and I had installed all tools stated there. 

To test if those errors are somehow related to the particular server, I installed cntools on another local machine, but I get the exact same error there. 

**Expected behavior**
CNTools should start and not quit with an error. 

**Version:**
 - OS: Ubuntu 20.04 LTS
 - Product version: CNTools v8.7.3
 - Cardano Node version: n/a (offline mode)
 - Network you're connecting to: n/a (offline mode)

**Comment by Scitz0** [comment]
Its clear that env file is not correctly sourced by cntools and quits before it loads it fully. 
Can you run this manually and let me know of output:
`. ./env`

**Comment by amani1104** [comment]
When running the env file manually I get the following error message: 

`You do not have a cardano-node binary available in $PATH.`

However, I'm running CNTools on an airgapped computer in offline mode. So while this message is true, it shouldn't be checked in offline mode.

**Comment by rdlrt** [comment]
> So while this message is true, it shouldn't be checked in offline mode.

That message is fine, for offline mode - the sourcing of env should be `. ./env offline` .
