### ISSUE TITLE
Failed to start after today's upgrading from v1.22.4 to v1.24.0

### ISSUE THREAD

**Issue by monkey-jsun** [cardano-community/guild-operators#1215]
**Describe the bug**
Today I ran gLiveView on producer node, it prompted me for upgrading.  I chose "no" first time and it ran fine.  See screen below.

==============
Checking for script updates...

The static content from env does not match with guild-operators repository, do you want to download the updated file? (yes/no): no

A new version of Guild LiveView is available
Installed Version : v1.22.4
Available Version : v1.24.0

Do you want to upgrade to the latest version of Guild LiveView? (yes/no): no
...
===============

Then I ran the second time and I chose "yes" to both upgrade suggestions.  After that I fail to start up.  See errors below.

===============
Checking for script updates...

Guild scripts has now been upgraded to support cardano-node 1.31.0 or higher (1.30.1 found).
Please update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.

ERROR: gLiveView failed to load common env file
Please verify set values in 'User Variables' section in env file or log an issue on GitHub
=================

**To Reproduce**

See above description.

**Expected behavior**
gLiveView should start after upgrading

**Screenshots**

**Version:**
 - OS: Ubuntu 20.04
 - Product version: My own setup with pulling gLiveView directly
 - Cardano Node version: 

cardano-cli 1.30.1 - linux-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]

ubuntu@producer:~/cardano$ jq -r .systemStart mainnet-shelley-genesis.json 
2017-09-23T21:44:51Z

**Additional context**

**Comment by monkey-jsun** [comment]
since I have another copy of env file on the relay node.  I copied it over to producer.  Now it works again if I just say "no" to both upgrade suggestions.

**Comment by rdlrt** [comment]
Please ensure you're in announcements channels to be notified of any changes post upgrade. The latest release required you to use node-1.31.0 (and was announced before the merge)

**Comment by monkey-jsun** [comment]
What is the announcement channel?  is it on telegram?

**Comment by rdlrt** [comment]
Yes
![image](https://user-images.githubusercontent.com/3169068/144726936-e52b39bd-5445-4026-b539-729ffe1e1007.png)
