### ISSUE TITLE
Improved reliability during package installation.

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#1226]
**Describe the bug**
Some items inside the `pkg_list` variable are not actually packages, but the binary itself. If during installation multiple repositories exist and differing packages contain the same named binary the user may end up with unexpected packages.

**Expected behavior**
The installer should explicitly request the packages it wants from each version, so the expected RPM is installed regardless of which repositories or other RPM's have the same or similar named binaries (or tools, libraries, etc.).

**Additional context**
A branch named `refine_list_of_packages` was created to address this. A draft PR #1225 has been submitted, if the fix is of interest I will transition it to a full PR for review and discussion.

**Comment by rdlrt** [comment]
I think those changes would definitely be welcome.
We just need to ensure that all the components do continue to work fine and specific flavours do not get impacted with the change:
- We cannot strip ncurses-lib, as required by node and dbsync
- pkgconfig is still required by many components (predominantly those that require use of `make`, but also node - for dependency by cabal)
- In certain cases (historically), names had to be elected depending on differences between flavours (even for example considering within EL line, unfortunately the repos may not be aligned across RHEL, Fedora, AL2), so needs to be tested accordingly.

**Comment by TrevorBenson** [comment]
> We cannot strip ncurses-lib, as required by node and dbsync

- Not stripped but rather "corrected", but your comment does bring up the fact that I moved `ncurses-libs` into the three versioned additions, where it could just be in the original list. I'll relocate that back to the original list.
- ncurses-compat-libs was "removed" from the primary list because it does not exist in el7 distributions.
  - ncurses-libs in el7 provides v5
  - ncurses-libs in el8/Fedora provides v6
    - ncurses-compat-libs provides ABI version 5 of the ncurses libraries (what I presume we are trying to obtain by including compat)

>pkgconfig is still required by many components (predominantly those that require use of make, but also node - for dependency by cabal)

It's still included.

I believe the el8 & Fedora based changes came later from from contributors, maybe myself included, and el7 was the original "source of truth" for what packages to use. I used this logic to isolate what was being asked for during installation. Checking el7 it showed that pkgconfig RPM was of tools maintained by freedesktop.

The el8 and Fedora distributions do not have a `pkgconfig` RPM. They do have 2 alternative RPM's named `pkgconf` and a less ambiguous `pkgconf-pkg-config`. I chose the latter because it uses the naming convention I believe I saw when investigating the tool from freedesktop and other sources. 

We still request `pkgconfig` RPM for el7, but for el8 or Fedora this PR would now request the explicit `pkgconf-pkg-config` RPM, eliminating the potential for a different RPM to be installed when asking for `pkgconfig` binary (since no RPM exists).

>In certain cases (historically), names had to be elected depending on differences between flavours (even for example considering within EL line, unfortunately the repos may not be aligned across RHEL, Fedora, AL2), so needs to be tested accordingly.

I've already reviewed el7, el8 via RHEL, CentOS and RockyLinux, as well as Fedora 35. The package names honor the upstream enterprise linux distribution names. The downstream distributions honoring package names (as most generally do) defined in the SRPM's should be identical to the list for appending to the pkg_list once the distribution is identified.

**Comment by rdlrt** [comment]
> I've already reviewed el7, el8 via RHEL, CentOS and RockyLinux, as well as Fedora 35. 
Right, I'd say that's already > than what I have tested 👍🏻 

> If we have a list of supported distro's I can investigate further and see if any package names conflict or differ. 
That's a good point, we have [ so far ] not maintained a list of OS, except trying to support common Debian/Fedora lines. I think other than RHEL and CentOS/Rocky the only one likely to be used more is AL2 indeed, wherein few bug reports directed changes to prereqs.sh. As long as the above 3 (under EL line) are checked, I'm comfortable with changes - especially since we're anyways not touching Debian line. I will wait for @Scitz0 to confirm as well.

**Comment by TrevorBenson** [comment]
Draft converted to PR and reviews requested from Scitzo and yourself.

**Comment by Scitz0** [comment]
Answered in PR, https://github.com/cardano-community/guild-operators/pull/1225#pullrequestreview-831608154
