### ISSUE TITLE
Hybrid pool registration error message

### ISSUE THREAD

**Issue by Aperico-com** [cardano-community/guild-operators#1233]
When trying to register a pool created in offline mode via the Pool-->Resiter->Hybrid I get this message:
```
Pool operational certificate not generated in hybrid mode, please use 'Pool >> Rotate' in offline mode to generate new hot keys, op cert and KES start period and transfer to online node!
Files generated when running 'Pool >> Rotate' to be transferred:
/opt/cardano/cnode/priv/pool/Sigma_Stake/hot.vkey
/opt/cardano/cnode/priv/pool/Sigma_Stake/hot.skey
/opt/cardano/cnode/priv/pool/Sigma_Stake/op.cert
/opt/cardano/cnode/priv/pool/Sigma_Stake/kes.start
```
Even though those files are present in the correct location with the correct rights/owner

**To Reproduce**
On offline: 
Pool->New
Pool->Rotate
move files to online
Pool->Register->Hybrid
After stake and reward wallet options are set the above message pops

**Expected behavior**
To not see "Pool operational certificate not generated in hybrid mode" since they should be generated in offline mode? There is no hybrid mode option for that command.
To maybe not see it at all, because looking at the source:
```
if [[ ${SUBCOMMAND} = "register" ]]; then
                if [[ ${op_mode} = "online" ]]; then
                  current_kes_period=$(getCurrentKESperiod)
                  echo "${current_kes_period}" > ${pool_saved_kes_start}
                  println ACTION "${CCLI} node issue-op-cert --kes-verification-key-file ${pool_hotkey_vk_file} --cold-signing-key-file ${pool_coldkey_sk_file} --operational-certificate-issue-counter-file ${pool_opcert_counter_file} --kes-period ${current_kes_period} --out-file ${pool_opcert_file}"
                  ${CCLI} node issue-op-cert --kes-verification-key-file "${pool_hotkey_vk_file}" --cold-signing-key-file "${pool_coldkey_sk_file}" --operational-certificate-issue-counter-file "${pool_opcert_counter_file}" --kes-period "${current_kes_period}" --out-file "${pool_opcert_file}"
                else
                  println DEBUG "\n${FG_YELLOW}Pool operational certificate not generated in hybrid mode,"
                  println DEBUG "please use 'Pool >> Rotate' in offline mode to generate new hot keys, op cert and KES start period and transfer to online node!${NC}"
                  println DEBUG "Files generated when running 'Pool >> Rotate' to be transferred:"
                  println DEBUG "${FG_LGRAY}${pool_hotkey_vk_file}${NC}"
                  println DEBUG "${FG_LGRAY}${pool_hotkey_sk_file}${NC}"
                  println DEBUG "${FG_LGRAY}${pool_opcert_file}${NC}"
                  println DEBUG "${FG_LGRAY}${pool_saved_kes_start}${NC}"
                  waitForInput "press any key to continue"
                fi
              fi
```
This message will always pop since you are in hybrid mode.

**Version:**
Ubuntu 20.04
latest CNTools
1.31 cardano
Mainnet

**Additional context**
I am not sure how to interpret the error/warning have I done something wrong or can I just continue with the execution?
It looks like I can because right after this message it asks for TTL

**Comment by rdlrt** [comment]
It seems you're not following the workflow as per guideline here (refer to the diagram [here](https://cardano-community.github.io/guild-operators/Scripts/cntools/#offline-workflow)

**Comment by Aperico-com** [comment]
Thank you for the quick answer. I followed the instructions on github cntools.md but they look exactly the same. I see now that I did not to it exactly: The step "Create a backup w/o private keys" I only did that for the wallet, the pool keys I moved manually later. And now I am stuck on "Register pool in hybrid mode"

Can I really not as well move the files manually instead of backup/restore. I even tried to move all pool files except cold.skey.

**Comment by rdlrt** [comment]
> Can I really not as well move the files manually instead of backup/restore.

You absolutely can, as long as you understand and accomodate for keys accurately, which can take a bit to get understand fully - hence, the backup/restore functionality.

**Comment by Aperico-com** [comment]
I will try the backup/restore see if there is any difference. Looking at the code it looks like this message will pop no matter what since it checks if you are in online mode and if you are not it will pop this message. If you register the pool in online mode and not hybrid it will create the op.cert file. 

If you are in hybrid mode however the message will pop no matter if you have the files or not?

**Comment by Scitz0** [comment]
Thats not an error message, just information that rotation has to be done on offline machine and copy files to online.

**Comment by Aperico-com** [comment]
I did not continue since the message says that my op.cert was generated in the wrong way some how.  And that I should rotate keys in offline mode. 

When I looked at your code I started suspecting that this was shown no matter if I had already done what was written in the message. I started this issue so I could know for sure, and also let you know that the message can be confusing to at least some people.

**Comment by Scitz0** [comment]
I guess we could check if files already exist and skip information in that case.

**Comment by Aperico-com** [comment]
Yeah I don't know it was confusing enough for me to halt the registration. I just want to say that I really like CNTools, I have been using it for a few days on testnet and it makes everything go so much faster and smoother. Not having to calculate fees and query tips every time is just great QoL.

One thing I could not figure out is when I use the built in file browser (to select for example a tx file) is how I can select the file that is currently marked? I tried enter and a few other but that did not work.

**Comment by Scitz0** [comment]
Use space for all things you normally use enter for :)
only use enter as a final command to accept whats written in path.

**Comment by Scitz0** [comment]
#1235 removes the info if files required are already present.
