### ISSUE TITLE
Error: Invalid raw transaction CBOR using Ledger

### ISSUE THREAD

**Issue by reqlez** [cardano-community/guild-operators#1234]
**Describe the bug**
Attempted using Ledger X ( FW v2, Cardano App version 3.0.0 ) to withdraw rewards operation.

Getting Error: Invalid raw transaction CBOR

**To Reproduce**
Attempt any operation with above Ledger firmware / Cardano app combo. 
I have tried the alpha CNTools as well, same result. 

i'm running hw-cli version v1.9.1

**Version:**
 - OS: Ubuntu Server 20.4
 - Product version: CNTools 8.7.3
 - Cardano Node version: 1.32.1
 - Network you're connecting to: mainnet

**Comment by Scitz0** [comment]
Can you please check the cntools-history.log and post ACTIONs for tx building and errors.

**Comment by arussell29** [comment]
Just an observation that I believe the Vacuumlabs hw-cli has not yet been updated for Alonzo-era support and so with the recent node update to default to Alonzo-era in transactions, the functionality may be broken unless you revert to Mary-era or Vacuumlabs pushes the Alonzo-compatible update.

**Comment by reqlez** [comment]
> Just an observation that I believe the Vacuumlabs hw-cli has not yet been updated for Alonzo-era support and so with the recent node update to default to Alonzo-era in transactions, the functionality may be broken unless you revert to Mary-era or Vacuumlabs pushes the Alonzo-compatible update.

You know what, that does make sense. They do say that there in their release notes. I was wondering what that meant...  In any case ill post the logs

**Comment by reqlez** [comment]
> Can you please check the cntools-history.log and post ACTIONs for tx building and errors.

Is this the string you want?
![image](https://user-images.githubusercontent.com/6512602/146578646-27c3b2ac-ea0d-4f52-b5bf-3a288e77157c.png)

**Comment by Scitz0** [comment]
yeah, but please send it all as text, the screenshot only shows it partially. But might be a plausible cause whats mentioned about era in tx.

**Comment by reqlez** [comment]
> yeah, but please send it all as text, the screenshot only shows it partially. But might be a plausible cause whats mentioned about era in tx.

cardano-cli transaction build-raw --tx-in 12d67ecb29115188c23ea926e7e6053a8db92044f95eaaed11abfab7b9a033fc#0 --tx-in 12d67ecb29115188c23ea926e7e6053a8db92044f95eaaed11abfab7b9a033fc#1 --tx-out addr1qytjf8f9csyluu3dvck8g4nrgjfaryvzggdnnpna55xfxu4jnkhthhfhduv0p5m4l93pdadpgxsuf3xl89rk2tnknx4qamufyf+0 --invalid-hereafter 48160284 --fee 0 --out-file /tmp/cnode/cntools/tx0.tmp

**Comment by Scitz0** [comment]
Just pushed #1235 to alpha, could you test to see if this solves it.

**Comment by reqlez** [comment]
> Just pushed #1235 to alpha, could you test to see if this solves it.

Works with the latest alpha ! Thanks for the quick fix!

![image](https://user-images.githubusercontent.com/6512602/146650328-91ba3617-920a-415d-bef5-1989b87b399d.png)

**Comment by reqlez** [comment]
Also tested updating pool parameters, that also works!

**Comment by reqlez** [comment]
I wonder if this fix is going to work with 1.33.0 and also, I read somewhere, that after version 7 you cannot use the old non-alonzo cli ? Is that correct?  Maybe we could be stuck until Vaccum Labs releases new code?

**Comment by lgbtqpool** [comment]
I am using cntools 8.8.1. 
I tried to change the pool parameters and I received the following error:

The transaction contains following fixable errors: - CBOR is not canonical (transaction) Error: Transaction CBOR contains fixable errors, please run "transform" or "transform-raw" command first

**Comment by Scitz0** [comment]
> I am using cntools 8.8.1. I tried to change the pool parameters and I received the following error:
> 
> The transaction contains following fixable errors: - CBOR is not canonical (transaction) Error: Transaction CBOR contains fixable errors, please run "transform" or "transform-raw" command first
> 
> UPDATE: Fixed locally by adding "cardano-hw-cli transaction transform-raw" command in cntools.library

CNTools 8.8.2 should fix this issue, please test and report back if you can.

**Comment by lgbtqpool** [comment]
> > I am using cntools 8.8.1. I tried to change the pool parameters and I received the following error:
> > The transaction contains following fixable errors: - CBOR is not canonical (transaction) Error: Transaction CBOR contains fixable errors, please run "transform" or "transform-raw" command first
> > UPDATE: Fixed locally by adding "cardano-hw-cli transaction transform-raw" command in cntools.library
> 
> CNTools 8.8.2 should fix this issue, please test and report back if you can.

So far seems to be working without any issues. Many thanks!
