### ISSUE TITLE
cardano-cli and cardano-node don't get produced

### ISSUE THREAD

**Issue by rob-grokism** [cardano-community/guild-operators#1250]
After running the prereqs.sh script and sourcing my .bashrc file, while following the directions explicitly with git pull and checkout

Running the following should produce a cardano-cli and cardano-node
$CNODE_HOME/scripts/cabal-build-all.sh

this actually fails with these errors after running for a good 45 minutes

wstyle/build/x86_64-linux/ghc-8.10.4/cardano-cli-1.32.1/build/Cardano/CLI/Parsers.dyn_o )
cabal: Failed to build exe:chain-sync-client-with-ledger-state from
cardano-client-demo-0.1.0.0.
Failed to build exe:ledger-state from cardano-client-demo-0.1.0.0.
Failed to build exe:scan-blocks from cardano-client-demo-0.1.0.0.

Tried running this 2 times...same thing

the files are supposed to be produced into the .cabal/bin directory but  there is nothing

[robert@relay1 bin]$ pwd
/home/robert/.cabal/bin
[robert@relay1 bin]$ ls
bech32  cardano-address  cardano-topology  locli  trace-dispatcher-examples  unit
[robert@relay1 bin]$

[robert@relay1 bin]$ cardano-cli
-bash: cardano-cli: command not found

[robert@relay1 bin]$ cardano-node
-bash: cardano-node: command not found

Is there perhaps another directory where the cardano-cli gets put.  I have looked all over and there doesn't seem to be anything.  

As a side note the prereqs.sh file will fail because the install of the epel repo fails with a 404 error.  I can work around this issue by installing  the epel repository before the prereqs.sh script is run.

**Comment by rdlrt** [comment]
Please post the complete log output for your cabal build command, the node tag you're using and also if it is a fresh machine or if it had another cabal/ghc install/attempt from before

**Comment by rob-grokism** [comment]
These are fresh builds on Google Cloud Platform.
  
HEAD is now at 4f65fb9a2 Bump to version 1.32.1 #I think this is what you mean with the node tag...

I removed everything from the directory structure include  the .cabal and .ghcup directories.  I also turned off selinux...

I just don't see where there were any logs produced.  I am going to try the build again and will update the case with this information.  

I have been able to get a node pool running in testnet with the more traditional way but ran across the guild operators setup which would seem to be much better  for prod use.

**Comment by rdlrt** [comment]
> I just don't see where there were any logs produced.

By the complete build log , I meant the stdout generated when running `cabal-build-all.sh`.

> I removed everything from the directory structure include the .cabal and .ghcup directories

You shouldn't have to manually remove those, the project specific cache is in dist-newstyle in the root of cardano-node github folder

**Comment by rob-grokism** [comment]
Thanks for the clarification.  I should redirect to a file and post that here, but I didn't think to do it that  way...I am running again and will send that when it is done.  
Rob

**Comment by rob-grokism** [comment]
no dice...same thing...here is the build log.  There was some sort of linker issue because of some failure with gcc.  

[stdout-install.txt](https://github.com/cardano-community/guild-operators/files/7783518/stdout-install.txt)

**Comment by rob-grokism** [comment]
[robert@block1 bin]$ gcc --version
gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
Copyright (C) 2018 Free Software Foundation, Inc

**Comment by rob-grokism** [comment]
for the sake of completeness ...these are Rocky Linux systems
Operating System: Rocky Linux 8.5 (Green Obsidian)
       CPE OS Name: cpe:/o:rocky:rocky:8:GA
            Kernel: Linux 4.18.0-348.7.1.el8_5.x86_64
      Architecture: x86-64

**Comment by rdlrt** [comment]
Could you confirm the below:
1. cabal --version
2. ghc --version
Also, could you run `cabal update` before build?

**Comment by rob-grokism** [comment]
[robert@block1 bin]$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
[robert@block1 bin]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.4
[robert@block1 bin]$ cabal update
Downloading the latest package list from hackage.haskell.org

I used ghcup to update cabal and ghc

[robert@block1 bin]$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library
[robert@block1 bin]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7

**Comment by rob-grokism** [comment]
I have 3 nodes all installed to the same cabal and ghc version...ghcup worked very well.

**Comment by rob-grokism** [comment]
same issue...the linker problem looks exactly the same...with the exception that it is using ghc-8.10.7

/home/robert/.cabal/store/ghc-8.10.7/cardano-crypto-praos-2.0.0-4dd0a11f8480c169c170b76fc19ba87d355cca5c8bbc6491525947b1971c1c7c/lib/libHScardano-crypto-praos-2.0.0-4dd0a11f8480c169c170b76fc19ba87d355cca5c8bbc6491525947b1971c1c7c.a(Praos.o):ghc_3.c:function cardanozmcryptozmpraoszm2zi0zi0zm4dd0a11f8480c169c170b76fc19ba87d355cca5c8bbc6491525947b1971c1c7c_CardanoziCryptoziVRFziPraos_zdwskFromBytes_info: error: undefined reference to 'crypto_vrf_secretkeybytes'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)


1.32.1/build/Cardano/Node/Run.o, /home/robert/git/cardano-node/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-node-1.32.1/build/Cardano/Node/Run.dyn_o )
cabal: Failed to build exe:scan-blocks from cardano-client-demo-0.1.0.0.
Failed to build exe:scan-blocks-pipelined from cardano-client-demo-0.1.0.0.
Failed to build exe:stake-credential-history from cardano-client-demo-0.1.0.0.

**Comment by rob-grokism** [comment]
I have a couple of Dell servers with vmware on them that I had intended on using for mainnet.  I will start setting that up with this method.  I don't know what is wrong here, but it seems to have something to do with libsodium.  We can close this case and I will reopen if the same thing happens with my production mainnet setup.
