### ISSUE TITLE
Cardano-db-sync build using Nix Failed

### ISSUE THREAD

**Issue by shad1872T** [cardano-community/guild-operators#1254]
Hi Was installing cardano-db-sync [for dev works related]  using nix, command below ran

nix-build -A cardano-db-sync -o db-sync-node

but failed to create the bin

Installed Cardano Node 1.32.1
Installed Latest CNTools Latest

Any guidance would be most appriciated

**Comment by rdlrt** [comment]
Sorry but we do not support or use nix in guild documentations, it would be best to use cardano-db-sync repo instead for nix (also make sure to include more details and logs on dbsync repo as it will be difficult for them to assist you otherwise 👍🏻 )

**Comment by shad1872T** [comment]
ok noted, thanks for quick reply.
Kind Regards and Happy 2022 to all
Shad
