### ISSUE TITLE
Would be nice if gliveview would retry forever

### ISSUE THREAD

**Issue by jacky4566** [cardano-community/guild-operators#1272]
**Describe the bug**
I would like gLiveView to run forever and not give up after X tries.

**To Reproduce**
run gLiveView without a live node service.

**Expected behavior**
With a setting of "RETRIES=0"  gLiveView should try forever.

**Additional context**
Setting a variable to 0  in a console script usually implies "try forever". Would be nice to see that behavior here. 
Additionally, I could just wrap the script in my own script.

**Comment by Scitz0** [comment]
Hi, Shouldn't be a problem adding so that setting a value of 0 sets it in continuous retry. Will try to remember this for next update 👍

**Comment by jacky4566** [comment]
Dope. That would be appreciated.

Jackson Wiebe
________________________________
