### ISSUE TITLE
Create New KeyVault Fails

### ISSUE THREAD

**Issue by oldcryptogeek** [cardano-community/guild-operators#128]
After running `./cnKeyVault.sh create` and entering a password the output is:

```text
Creating key vault directory to encrypt:

mkdir: cannot create directory ‘’: No such file or directory

Error: failed to create encrypted vault for key storage


```

**Comment by Scitz0** [comment]
cnKeyVault.sh is not part of guild repo any more... it's from a previous PR that was never merged with master. Key encryption now handled and built into cntools.
