### ISSUE TITLE
ogmios install section in prereqs.sh not working

### ISSUE THREAD

**Issue by pyromaniac3010** [cardano-community/guild-operators#1281]
**Describe the bug**
in prereqs.sh the ogmios_asset_url is not pointing to the json url, but to the human readable version:

```ogmios_asset_url=$(curl -s https://github.com/CardanoSolutions/ogmios/releases/latest | jq -r '.assets[].browser_download_url')```
this leads to a `parse error: Invalid numeric literal at line 1, column 16` which breaks the installation.
the line should be corrected to:

```ogmios_asset_url=$(curl -s https://api.github.com/repos/CardanoSolutions/ogmios/releases/latest | jq -r '.assets[].browser_download_url')```

**To Reproduce**
execute prereqs.sh with -o flag

**Expected behavior**
correct installation of all tools

**Screenshots**
-

**Version:**
current master https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh

**Additional context**

**Comment by pyromaniac3010** [comment]
More things to fix:
```
ogmios_git_version="$(ogmios --version)"
```
should be:
```
ogmios_git_version=$(curl -s https://api.github.com/repos/CardanoSolutions/ogmios/releases/latest | jq -r '.tag_name')
```

and ogmios must be executable:
```
mv -f /tmp/ogmios/bin/ogmios "${HOME}"/.cabal/bin/
```
should be:
```
chmod +x /tmp/ogmios/bin/ogmios
mv -f /tmp/ogmios/bin/ogmios "${HOME}"/.cabal/bin/
```

**Comment by Scitz0** [comment]
Thanks 👍

**Comment by pyromaniac3010** [comment]
pull request: https://github.com/cardano-community/guild-operators/pull/1282
