### ISSUE TITLE
Cannot run submitapi.sh

### ISSUE THREAD

**Issue by lead-pool** [cardano-community/guild-operators#1308]
**Describe the bug**
submitapi.sh failed with error -  cardano-submit-api: FatalError {fatalErrorMessage = "readTxSubmitNodeConfig: Error parsing config: AesonException \"Error in $: key \\\"EnableLogging\\\" not found\""}

**To Reproduce**
1. Download latest prereqs.sh with no additional flags
2. Try running submitapi.sh

**Expected behavior**
API starts without issue

**Version:**
 - OS: Ubuntu 20.04.3
 - Product version: 
 - Cardano Node version: 1.33.0

**Additional context**
Appears that the correct config file is missing and a testnet-magic parameter is being used in the run step?
After downloading the config file seperately from here: https://raw.githubusercontent.com/input-output-hk/cardano-node/master/cardano-submit-api/config/tx-submit-mainnet-config.yaml and updating the code along with --testnet-magic param to --mainnet it appears to work ok

**Comment by Scitz0** [comment]
You are missing EnableLogging entry in your config.json file. Latest version of configs on guild repo include these metrics. So please update this file either through prereqs script or by manual download.

**Comment by Scitz0** [comment]
testnet-magic thing I will look into.

**Comment by lead-pool** [comment]
Thanks Ola

**Comment by DamjanOstrelic** [comment]
The error message is fairly obvious, and the config files are updated for those required fields in order to run `submit-api`. But I don't think NW magic has anything to do with this issue.

My understanding is the NW magic is simply taken from the genesis files your node is running and passed to the `submit-api` start command.

**Comment by lead-pool** [comment]
Thanks Damjan - Yes Ola has already mentioned the issue with the config file

However I am not so sure how obvious it is that the guild config needs updating, given there is a separate config file which can be downloaded like i stated - perhaps an improvement could be to add a check in the pre_statup_sanity function?


Regarding the NM it is my understanding that --testnet-magic should never be referred to for mainnet in the first place? And it should simply be --mainnet as no magic is required. Or are you saying that --testnet-magic can be used providing a "mainnet magic" it referred to in the variable ${NWMAGIC}

For reference this is the line of code i am referring to
# Run Submit API
"${SUBMITAPIBIN}" --config "${CONFIG}" --testnet-magic ${NWMAGIC} --socket-path "${CARDANO_NODE_SOCKET_PATH}" --listen-address ${HOSTADDR} --port ${HOSTPORT}

**Comment by lead-pool** [comment]
Apologies - I just did some more looking around and see what you mean - it appears you can the the argument --testnet-magic with a mainnet magic (learn something new everyday!). Sorry for wasting everyones time. I will close the issue. Thank you for responding

**Comment by DamjanOstrelic** [comment]
Yep, I think mainnet network magic can be passed under the `--testnet-magic` flag as well. 👍 
Fair point on not being aware of when node config needs updating, I remember I ran into this same problem for submit-api.

**Comment by Scitz0** [comment]
Even if --testnet-magic is valid for mainnet we might look into replacing it with existing variables for it from env file. To keep consistency.

**Comment by lead-pool** [comment]
Thanks Damian, Thanks Ola

Just a quick FYI (Im sure you already know this though) It definitely is valid - I tested it out with a quick query tip command however it certainly is a bit confusing to use an argument called "testnet-magic" with a mainnet parameter

Cheers for noting the point about the config update too
