### ISSUE TITLE
Ogmios not installing via install prereqs

### ISSUE THREAD

**Issue by huths0lo** [cardano-community/guild-operators#1310]
**Describe the bug**
Prereq install bombs if you use it to install ogmios.  It looks like ogmios 5.1.0 was recently released, and that is the likely cause of the failure.

**To Reproduce**
1. Run ./prereqs.sh -o

The below is the output from Ubuntu 20 cli

john@DB-Sync-Alonzo:~/tmp$ ./prereqs.sh -o
Using apt to prepare packages for "Ubuntu" system
  Updating system packages...
  Installing missing prerequisite packages, if any..
Creating Folder Structure ..
Environment Variable already set up!
IOG fork of libsodium installed to /usr/local/lib/
Installing Ogmios
parse error: Invalid numeric literal at line 1, column 16
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
ERROR: Download of latest release of ogmios archive from GitHub failed! Please retry or manually install it.

**Comment by rdlrt** [comment]
Which branch are you using? master or alpha?

**Comment by huths0lo** [comment]
I've tried with both branches.  Outcome was identical for both.

**Comment by chadle-git** [comment]
I have the same error on Ubuntu 18.  Only tried master.  Thank you.

**Comment by rdlrt** [comment]
Thanks @chadle-git for providing outcome of tests offline on telegram, the issue he when using alpha branch was due to missing `unzip` package. should be sorted by linked commit
