### ISSUE TITLE
gLiveView Error failed to load common env file

### ISSUE THREAD

**Issue by MaxWS** [cardano-community/guild-operators#1313]
Hi there, just looking for some help with this issue. Thanks in advance. This is the message I get when I run the command
**./gLiveView.sh**

Could not parse /home/ADMIN/cardano-my-node/mainnet-config.json file in JSON format, please double-check the syntax of your config, or simply download it from guild-operators repository!

ERROR: gLiveView failed to load common env file
Please verify set values in 'User Variables' section in env file or log an issue on GitHub

I'm running a Testnet and I have substituted the part where is says mainnet-config.json for testnet-config.json
Everything is working smooth. 
sudo systemctl status cardano-node shows the node is active. I have restarted the node and the server.

System info:
OS:Ubuntu
Version: 20.04
Node version: 1.33.0

**Comment by rdlrt** [comment]
I think I am a bit confused, you mentioned you `substituted the part where is says mainnet-config.json for testnet-config.json` , but your error message presented still includes `/home/ADMIN/cardano-my-node/mainnet-config.json`. Could you confirm if you also uncommented the line containing CONFIG variable definition in env file where you're running the script as documented [here](https://cardano-community.github.io/guild-operators/Scripts/env/)?

In case you were not following the documentation on this site (you certainly do not have to download and change config files manually if you used instructions from this site), that might explain your issue (and potentially incoming once you get past this step).

**Comment by MaxWS** [comment]
Hi @rdlrt , thanks for your answer. Sorry for not being very clear about my issue. I fixed it finally! The problem was the env file for sure. 
I changed this part of the file **CONFIG="${NODE_HOME}/testnet-config.json"** and problem solved. Thanks again.
