### ISSUE TITLE
SELECT GREST.STAKE_DISTRIBUTION_CACHE_UPDATE_CHECK(); taking hours on testnet instances

### ISSUE THREAD

**Issue by pyromaniac3010** [cardano-community/guild-operators#1332]
**Describe the bug**
We are monitoring the haproxys from our grest-instances via zabbix and getting constantly errors for the grest local backend on our testnet instances.
I get a lot of "Stake Distribution cache too far from tip !!" timeouts in haproxy for the local grest backend on my **testnet** instances. 
After checking postgresql I see that there is a running query "SELECT GREST.STAKE_DISTRIBUTION_CACHE_UPDATE_CHECK();
" which is running for a very long time:
```
SELECT pid, age(clock_timestamp(), query_start), usename, query
FROM pg_stat_activity
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%'
ORDER BY query_start desc;
  pid  |       age       | usename  |                                        query
-------+-----------------+----------+-------------------------------------------------------------------------------------
 27662 | 02:18:49.286034 | cardano  | SELECT GREST.STAKE_DISTRIBUTION_CACHE_UPDATE_CHECK();
  1490 | 02:41:39.990768 | cardano  | LISTEN "pgrst"
```
All instances were setup and optimized according to the docs (including postgres optimizations) and I used alpha branch, becaus master branch does not work for grest.
I was using AWS r5a.xlarge for testnet and r5a.2xlarge for mainnet.
I did not experience these problems with mainnet yet. Only my testnet instances report the local haproxy backends going down.
I switched to t3a.2xlarge for one testnet instance but still get these long running querys and the local haproxy backend goes down.

**To Reproduce**
1. setup grest with testnet

**Expected behavior**
It should not take many hours on testnet.

**Screenshots**

**Version:**
 - OS: Ubuntu 
 - Product version: 
 - Cardano Node version: cardano-node 1.33.0 - linux-x86_64 - ghc-8.10
 - Network you're connecting to: testnet

**Additional context**

**Comment by DamjanOstrelic** [comment]
One more thing to check for useful info here are logs under `CNODE_HOME/logs/stake-distribution-update.log`

**Comment by pyromaniac3010** [comment]
@DamjanOstrelic
Here the stake-distribution-update.log from one testnet grest setup:
[stake-distribution-update.log](https://github.com/cardano-community/guild-operators/files/8087469/stake-distribution-update.log)

**Comment by DamjanOstrelic** [comment]
Looks like it's taking ~5 hours to complete the query. I can confirm same happening on my testnet instance. The `grest-poll.sh` that haproxy runs has a check for [1000 blocks up to tip for stake distribution cache](https://github.com/cardano-community/guild-operators/blob/7bcf7f88f79fcdcc453ef55c8d8384c596b2caa8/scripts/grest-helper-scripts/grest-poll.sh#L123) on alpha.
So I think you were only getting `Stake Distribution cache too far from tip !!` message at the start of the logs, as from the logs I see around 600 blocks lag on each new run (after previous has finished), e.g. `NOTICE:  Last stake distribution update was 552 blocks ago...`

But it doesn't make sense for this to take 5 hours on testnet. @rdlrt @Scitz0 @hodlonaut Can you check your instances related to this cache query?

**Comment by hodlonaut** [comment]
Everything looking okay on my testnet instance, the ' Last stake distribution update was ' message gets up to about 250 blocks max before the catch-up is done. As far as initial population of the stake cache table, my testnet instance did it in about 30 seconds:

2022-01-02_12:30:01 Running stake distribution update...
NOTICE:  Last stake distribution update was 3203832 blocks ago...
NOTICE:  Re-running...
NOTICE:  table "accounts_with_delegated_pools" does not exist, skipping
NOTICE:  table "pool_ids" does not exist, skipping
NOTICE:  table "account_total_utxo" does not exist, skipping
NOTICE:  table "account_total_rewards" does not exist, skipping
NOTICE:  table "account_total_withdrawals" does not exist, skipping
NOTICE:  table "account_last_withdrawal" does not exist, skipping
NOTICE:  table "account_total_reserves" does not exist, skipping
NOTICE:  table "account_total_treasury" does not exist, skipping
NOTICE:  relation "idx_stake_address_id" already exists, skipping
NOTICE:  relation "idx_stake_address_id" already exists, skipping
NOTICE:  relation "idx_stake_address_id" already exists, skipping
NOTICE:  relation "idx_stake_address_id" already exists, skipping
NOTICE:  relation "idx_stake_address_id" already exists, skipping
NOTICE:  relation "idx_stake_address_id" already exists, skipping
NOTICE:  relation "idx_stake_address_id" already exists, skipping
2022-01-02_12:30:32 Job done!

Worth noting the multiple 'NOTICE:  relation "idx_stake_address_id" already exists, skipping' messages in my log, and just one of those in the pyromaniac3010's logs, maybe that's a clue of some kind.

**Comment by Scitz0** [comment]
Same here, nothing strange in logs. Takes ~9s to complete on testnet. The notices are expected due to temp table and index usage.

**Comment by DamjanOstrelic** [comment]
I ran `setup-grest.sh -r -q` to reset everything. It is still taking the same time, around 5 hours.

I am on Postgres 14.

**Comment by DamjanOstrelic** [comment]
@pyromaniac3010 can you run the following and post the output file please?

`psql cexplorer -c "explain analyze CREATE TEMP TABLE account_total_utxo AS (
  SELECT accounts_with_delegated_pools.stake_address_id,
    COALESCE(SUM(TX_OUT.VALUE), 0) AS UTXO
  FROM tx_out
    INNER JOIN accounts_with_delegated_pools on tx_out.stake_address_id = accounts_with_delegated_pools.stake_address_id
    INNER JOIN TX ON TX.ID = TX_OUT.TX_ID
    LEFT JOIN TX_IN ON TX_OUT.TX_ID = TX_IN.TX_OUT_ID
    AND TX_OUT.INDEX::smallint = TX_IN.TX_OUT_INDEX::smallint
  WHERE TX.BLOCK_ID <= 3329407
    AND TX_IN.TX_IN_ID IS NULL
  GROUP BY accounts_with_delegated_pools.stake_address_id,
    accounts_with_delegated_pools.stake_address
)" > out.log`

It's the part of the query that is the pain point on my instance, manual run of this took 10 hours for some reason.

**Comment by pyromaniac3010** [comment]
@DamjanOstrelic 
Here the requested output:
`
$ psql cexplorer -c "explain analyze CREATE TEMP TABLE account_total_utxo AS ( SELECT accounts_with_delegated_pools.stake_address_id, COALESCE(SUM(TX_OUT.VALUE), 0) AS UTXO FROM tx_out INNER JOIN accounts_with_delegated_pools on tx_out.stake_address_id = accounts_with_delegated_pools.stake_address_id INNER JOIN TX ON TX.ID = TX_OUT.TX_ID LEFT JOIN TX_IN ON TX_OUT.TX_ID = TX_IN.TX_OUT_ID AND TX_OUT.INDEX::smallint = TX_IN.TX_OUT_INDEX::smallint WHERE TX.BLOCK_ID <= 3329407 AND TX_IN.TX_IN_ID IS NULL GROUP BY accounts_with_delegated_pools.stake_address_id, accounts_with_delegated_pools.stake_address )" > out.log
ERROR:  relation "accounts_with_delegated_pools" does not exist
LINE 1: ...(TX_OUT.VALUE), 0) AS UTXO FROM tx_out INNER JOIN accounts_w...

`
Looks like a missing table name to me.

**Comment by DamjanOstrelic** [comment]
Thx, my bad - you will need to create this TEMP table in the same session for this to work, so:

```
CREATE TEMP TABLE accounts_with_delegated_pools AS (
  SELECT DISTINCT ON (STAKE_ADDRESS.ID) stake_address.id as stake_address_id,
    stake_address.view as stake_address,
    pool_hash_id
  FROM STAKE_ADDRESS
    INNER JOIN DELEGATION ON DELEGATION.ADDR_ID = STAKE_ADDRESS.ID
  WHERE NOT EXISTS (
      SELECT TRUE
      FROM DELEGATION D
      WHERE D.ADDR_ID = DELEGATION.ADDR_ID
        AND D.ID > DELEGATION.ID
    )
    AND NOT EXISTS (
      SELECT TRUE
      FROM STAKE_DEREGISTRATION
      WHERE STAKE_DEREGISTRATION.ADDR_ID = DELEGATION.ADDR_ID
        AND STAKE_DEREGISTRATION.TX_ID > DELEGATION.TX_ID
    )
);

CREATE INDEX IF NOT EXISTS idx_stake_address_id ON accounts_with_delegated_pools (stake_address_id);
CREATE INDEX IF NOT EXISTS idx_pool_hash_id ON accounts_with_delegated_pools (pool_hash_id);
```

And then:

```
EXPLAIN ANALYZE CREATE TEMP TABLE account_total_utxo AS (
  SELECT accounts_with_delegated_pools.stake_address_id,
    COALESCE(SUM(TX_OUT.VALUE), 0) AS UTXO
  FROM tx_out
    INNER JOIN accounts_with_delegated_pools on tx_out.stake_address_id = accounts_with_delegated_pools.stake_address_id
    INNER JOIN TX ON TX.ID = TX_OUT.TX_ID
    LEFT JOIN TX_IN ON TX_OUT.TX_ID = TX_IN.TX_OUT_ID
    AND TX_OUT.INDEX::smallint = TX_IN.TX_OUT_INDEX::smallint
  WHERE TX.BLOCK_ID <= _last_accounted_block_id
    AND TX_IN.TX_IN_ID IS NULL
  GROUP BY accounts_with_delegated_pools.stake_address_id,
    accounts_with_delegated_pools.stake_address
);
```

Might be best to do in the `psql` shell.

**Comment by pyromaniac3010** [comment]
Here the new output:
```
$ psql cexplorer
psql (14.2 (Ubuntu 14.2-1.pgdg20.04+1))
Type "help" for help.

cexplorer=# CREATE TEMP TABLE accounts_with_delegated_pools AS (
cexplorer(#   SELECT DISTINCT ON (STAKE_ADDRESS.ID) stake_address.id as stake_address_id,
cexplorer(#     stake_address.view as stake_address,
cexplorer(#     pool_hash_id
cexplorer(#   FROM STAKE_ADDRESS
cexplorer(#     INNER JOIN DELEGATION ON DELEGATION.ADDR_ID = STAKE_ADDRESS.ID
cexplorer(#   WHERE NOT EXISTS (
cexplorer(#       SELECT TRUE
cexplorer(#       FROM DELEGATION D
cexplorer(#       WHERE D.ADDR_ID = DELEGATION.ADDR_ID
cexplorer(#         AND D.ID > DELEGATION.ID
cexplorer(#     )
cexplorer(#     AND NOT EXISTS (
cexplorer(#       SELECT TRUE
cexplorer(#       FROM STAKE_DEREGISTRATION
cexplorer(#       WHERE STAKE_DEREGISTRATION.ADDR_ID = DELEGATION.ADDR_ID
cexplorer(#         AND STAKE_DEREGISTRATION.TX_ID > DELEGATION.TX_ID
cexplorer(#     )
cexplorer(# );
SELECT 84868
cexplorer=#
cexplorer=# CREATE INDEX IF NOT EXISTS idx_stake_address_id ON accounts_with_delegated_pools (stake_address_id);
CREATE INDEX
cexplorer=# CREATE INDEX IF NOT EXISTS idx_pool_hash_id ON accounts_with_delegated_pools (pool_hash_id);
CREATE INDEX
cexplorer=# EXPLAIN ANALYZE CREATE TEMP TABLE account_total_utxo AS (
cexplorer(#   SELECT accounts_with_delegated_pools.stake_address_id,
cexplorer(#     COALESCE(SUM(TX_OUT.VALUE), 0) AS UTXO
cexplorer(#   FROM tx_out
cexplorer(#     INNER JOIN accounts_with_delegated_pools on tx_out.stake_address_id = accounts_with_delegated_pools.stake_address_id
cexplorer(#     INNER JOIN TX ON TX.ID = TX_OUT.TX_ID
cexplorer(#     LEFT JOIN TX_IN ON TX_OUT.TX_ID = TX_IN.TX_OUT_ID
cexplorer(#     AND TX_OUT.INDEX::smallint = TX_IN.TX_OUT_INDEX::smallint
cexplorer(#   WHERE TX.BLOCK_ID <= _last_accounted_block_id
cexplorer(#     AND TX_IN.TX_IN_ID IS NULL
cexplorer(#   GROUP BY accounts_with_delegated_pools.stake_address_id,
cexplorer(#     accounts_with_delegated_pools.stake_address
cexplorer(# );
ERROR:  column "_last_accounted_block_id" does not exist
LINE 9:   WHERE TX.BLOCK_ID <= _last_accounted_block_id
```

**Comment by DamjanOstrelic** [comment]
My bad again, limit the block_id:

```
EXPLAIN ANALYZE CREATE TEMP TABLE account_total_utxo AS (
  SELECT accounts_with_delegated_pools.stake_address_id,
    COALESCE(SUM(TX_OUT.VALUE), 0) AS UTXO
  FROM tx_out
    INNER JOIN accounts_with_delegated_pools on tx_out.stake_address_id = accounts_with_delegated_pools.stake_address_id
    INNER JOIN TX ON TX.ID = TX_OUT.TX_ID
    LEFT JOIN TX_IN ON TX_OUT.TX_ID = TX_IN.TX_OUT_ID
    AND TX_OUT.INDEX::smallint = TX_IN.TX_OUT_INDEX::smallint
  WHERE TX.BLOCK_ID <= 3342661
    AND TX_IN.TX_IN_ID IS NULL
  GROUP BY accounts_with_delegated_pools.stake_address_id,
    accounts_with_delegated_pools.stake_address
);
```

**Comment by DamjanOstrelic** [comment]
Thanks, a similar result to mine, which was ~10 hours. Now we have to analyse the these explains to see if we can spot any obvious issues 😄
