### ISSUE TITLE
[CNTOOLS] Ability to delegate to a pool that is not your own

### ISSUE THREAD

**Issue by papacarp** [cardano-community/guild-operators#135]
Just noting a few things here that need cleaning up.  I'll add to this as I find more
- [x] Ctrl-C does not get you out of `waitNewBlockCreated`
- [x] Payment from or to staking wallet should allow selection of payment address or staking address
- [ ] Need ability to delegate to a pool that is not your own (by pool id) 
- [x] New pool creation needs to set KES period correctly rather than always 0

**Comment by Scitz0** [comment]
We have three addresses created, or will have. Payment, reward(staking) and base (combination of the two). What of these three should be valid as from and/or to?

**Comment by Scitz0** [comment]
I think payment and base should be valid as the destination address and all three as the source so you can also send ADA out from reward address.

**Comment by hodlonaut** [comment]
Currently blocked by the lack of relevant CLI command - delegating to another person's pool at the moment requires you to ask them for their Node operator vkey

**Comment by Scitz0** [comment]
Partly implemented in 933e1bf78e90adf975e69b6dde95b4d1189aca6f
Still require you to get hold of pools cold vkey cbor-hex.
Leaving issue open until fully resolved.

**Comment by Scitz0** [comment]
Closing issue as it's handled by #235
