### ISSUE TITLE
Make postgrest & haproxy service deployments(name) unique to allow multiple instances/networks on the same deployment. e.g. for example cnode-postgrest.service

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#1350]

**Comment by Scitz0** [comment]
Isn't this basically done? At least when it comes to service deployments. 
Ports etc still have to be changed manually but I think this would be expected of user.

**Comment by rdlrt** [comment]
yes - just artifact moved from trello (was in to-do) to github, OK to close
