### ISSUE TITLE
Koios address_info transaction order wrong

### ISSUE THREAD

**Issue by pyromaniac3010** [cardano-community/guild-operators#1356]
**Describe the bug**
Hello,
we use the koios api on local servers mainly for the route "/api/v0/address_info". We found out, that the transaction order from the local koios server is different than the one from blockfrost.io. After some checking, we also found out, that the "official" servers "https://api.koios.rest/api/v0/address_info" are returning the results sometimes in the right order (aka blockfrost-order) and sometimes in the wrong order (aka like our local koios nodes).

**To Reproduce**
1. call https://api.koios.rest/api/v0/address_info?_address=addr1q9axt8587qdgn2vy3urcf3vk3nrmvr8dk5z5aqur7qs5558txcjplj8ksunxnxugfypzu0y2arjkf99x50n9htgr2cysa5y960 
2. The first transaction should be "a610a4357a9f647687fe00c749f1b7f2423b160d051df82b7906fbe636f5d8fb" 
3. reload the page several times and you will see, that the first transaction is not always "a610a4357a9f647687fe00c749f1b7f2423b160d051df82b7906fbe636f5d8fb"

Example 1st call:
```
[{"balance":"132983123896","stake_address":"stake1u84nvfqlermgwfnfnwyyjq3w8j9w3etyjjn28ejm45p4vzgzf2nh9","utxo_set":
[{"tx_hash" : "1b6909281007809b78794f31035ec277760b2be54cbe0530394e1562d2a27164", "tx_index" : 1, "value" : "55787639", "asset_list" : []}, 
{"tx_hash" : "8ba87725659720f44f6ecb2aafef96b2523d71d9345ac9299f3019cab57205dd", "tx_index" : 1, "value" : "55787595", "asset_list" : []}, 
{"tx_hash" : "66f0bc64035ef678d7d97d309d4eddc072e73ba610443a483c6b1864d944d6ed", "tx_index" : 1, "value" : "111771183", "asset_list" : []}, 
{"tx_hash" : "e736916d0c0502e4bdb4d945f1349af63fc6f1f5c22ef98150247f0bbdd90038", "tx_index" : 1, "value" : "55787639", "asset_list" : []}, 
{"tx_hash" : "9befe335f205917863fe7039651584094b83eb5596f9fc9f0427d153249e02c4", "tx_index" : 1, "value" : "111771491", "asset_list" : []}, 
{"tx_hash" : "41869873d760d2e340e0a9e2a09c31efe5705ffb92c372dd8e5ab870b96e73c3", "tx_index" : 1, "value" : "55787375", "asset_list" : []}, 
aso...
```
Example 2nd call:
```
[{"balance":"132983123896","stake_address":"stake1u84nvfqlermgwfnfnwyyjq3w8j9w3etyjjn28ejm45p4vzgzf2nh9","utxo_set":
[{"tx_hash" : "a610a4357a9f647687fe00c749f1b7f2423b160d051df82b7906fbe636f5d8fb", "tx_index" : 1, "value" : "103777563", "asset_list" : []}, 
{"tx_hash" : "d311c3c2708ebddac566b87b8a331ea85da00a4218a1b69f1a1c539e12b11069", "tx_index" : 1, "value" : "103777827", "asset_list" : []}, 
{"tx_hash" : "dd47f39675f4f7a0de5947f30739622ff0281a129ed8bf067bf0c45757fd16e0", "tx_index" : 1, "value" : "103777651", "asset_list" : []}, 
{"tx_hash" : "0be4ef3815c2e5ece49ca727db74dce29848e75ea0c12f7ba776959914df51db", "tx_index" : 1, "value" : "103777255", "asset_list" : []}, 
{"tx_hash" : "708bfa2d7095f291915d83f87e9bd10ab5d4c47f96ef61fd8b52c7aa3b5eb9d7", "tx_index" : 1, "value" : "103777827", "asset_list" : []}, {"tx_hash" : 
aso...
```

Output our local koios nodes:
```
[{"balance":"132983123896","stake_address":"stake1u84nvfqlermgwfnfnwyyjq3w8j9w3etyjjn28ejm45p4vzgzf2nh9","utxo_set":
[{"tx_hash" : "6755ccba89d206bc318fefebcc1b28585c4ca121a696778d0a98c30a03c33b50", "tx_index" : 1, "value" : "101771491", "asset_list" : []}, 
{"tx_hash" : "0f31f83c757001c3a2ee586c7a5c142068a7f549c7e07e13b10dd685b35f6e82", "tx_index" : 1, "value" : "101771491", "asset_list" : []}, 
{"tx_hash" : "3d38c64957627c0a974881ee1719e8b7fd4ee31edc2d5fe708af0244716aba9a", "tx_index" : 1, "value" : "101771227", "asset_list" : []}, 
{"tx_hash" : "359742dd8408472b001798ae5142f9102be416e26b4342ec488b6d8836e6f1f8", "tx_index" : 1, "value" : "50787639", "asset_list" : []},
aso...
```

Here the complete result sets (renamed to txt, as otherwise not permitted by github): 
[api.koios.rest.1.json.txt](https://github.com/cardano-community/guild-operators/files/8151825/api.koios.rest.1.json.txt)
[api.koios.rest.2.json.txt](https://github.com/cardano-community/guild-operators/files/8151826/api.koios.rest.2.json.txt)
[local-koios-node.json.txt](https://github.com/cardano-community/guild-operators/files/8151827/local-koios-node.json.txt)
each file has the exact same count of utxo:
```
$ jq '.[].utxo_set | length' api.koios.rest.1.json
1568
$ jq '.[].utxo_set | length' api.koios.rest.2.json
1568
$ jq '.[].utxo_set | length' local-koios-node.json
1568
```

If I sort the three resultsets by "tx_hash with `jq` and then diff the sorted files, I get exactly the same result from all sources. So there is no difference in the database being not up to date:
```
jq '.[].utxo_set | sort' api.koios.rest.1.json > api.koios.rest.1.sorted.json
jq '.[].utxo_set | sort' api.koios.rest.1.json > api.koios.rest.1.sorted.json
jq '.[].utxo_set | sort' local-koios-node.json > local-koios-node.sorted.json
$ diff api.koios.rest.1.sorted.json api.koios.rest.2.sorted.json --report-identical-files
Files api.koios.rest.1.sorted.json and api.koios.rest.2.sorted.json are identical
$ diff api.koios.rest.1.sorted.json local-koios-node.sorted.json --report-identical-files
Files api.koios.rest.1.sorted.json and local-koios-node.sorted.json are identical
```

**Expected behavior**
https://api.koios.rest/api/v0/address_info?_address=addr1q9axt8587qdgn2vy3urcf3vk3nrmvr8dk5z5aqur7qs5558txcjplj8ksunxnxugfypzu0y2arjkf99x50n9htgr2cysa5y960 should always return the same order of the transactions starting with the first transaction a610a4357a9f647687fe00c749f1b7f2423b160d051df82b7906fbe636f5d8fb.
Our local koios nodes always return the "wrong" order and never the "blockfrost.io"-order

**Screenshots**

**Version:**
 - OS: NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
 - Product version: 
 - Cardano Node version: cardano-node 1.33.0 - linux-x86_64 - ghc-8.10
 - Network you're connecting to: mainnet
 - 
**Additional context**
It would probably be a good idea to add an additional "x-served-by" http response header to identify the source server used for the return of the official api.koios.rest server. CDN providers use this to identify nodes. Amazon for example uses "X-Amz-Cf-Pop" header.

**Comment by Scitz0** [comment]
See #1355

After its implemented, you can sort the result your self on block height or time using postgrest functions described on [api page](https://api.koios.rest/#overview--ordering).

**Comment by rdlrt** [comment]
Also, regarding:
> It would probably be a good idea to add an additional "x-served-by" http response header to identify the source server used for the return of the official api.koios.rest server. 

Individual nodes are free to do so if they would like to by adding custom headers (or not deleting default ones provided via haproxy), but it may not be fair to publish all server host information from primary URL itself to end users as some instance providers have already wished against it.

**Comment by tobler** [comment]
> See #1355
> 
> After its implemented, you can sort the result your self on block height or time using postgrest functions described on [api page](https://api.koios.rest/#overview--ordering).

The problem is, that it does not work currently with the Cardanoshark Koios SDK - because it does not support order. 
And the second problem with this sort order is, that it is at the moment not in the result set - i think in the sql there must be an additional inner join for the tx table where timestamp is stored.

**Comment by rdlrt** [comment]
>  I think we need an additional inner join to the tx table where these informations are stored.

If you read the PR Ola linked , the change is *adding* block height/timestamp that you can then use for sorting on client side, it's not present before PR on alpha

> but why does the official Koios Server provide one time the informations in the correct order and when you reload, in a different order

It is a [complicated query](https://github.com/cardano-community/guild-operators/blob/alpha/files/grest/rpc/transactions/tx_info.sql) requiring a join against many tables to cater for different types of transaction. The data returned will depend on each dbsync instance behind the scenes, sorting it will add to ms of the response - which is not ideal on server end serving millions of transaction (while cost on client is minimal). Once you have the PR mentioned above added, you can easily sort the results as desired.

**Comment by rdlrt** [comment]
#1355 is now live, which allows the ability for client-side sorting as per comments above
