### ISSUE TITLE
[gLiveView] No longer connects to node v1.34.0

### ISSUE THREAD

**Issue by olliejm** [cardano-community/guild-operators#1357]
**Describe the bug**
After re-compiling cardano-node to use the 1.34.0 release, gLiveView seems to fail to connect to cardano-node. The same issue occurs on both my BP and relay servers.

**To Reproduce**
1. Update the running cardano-node instance to v1.34.0
2. Run `gLiveView.sh`
3. See the error `Connection to node lost, retrying (2/3)!`

**Expected behavior**
gLiveView continues to connect to the cardano-node instance as normal

**Version:**
 - OS: Ubuntu Server 20.04 LTS
 - Product version: gLiveView 1.26.0
 - Cardano Node version: 1.34.0
 - Network you're connecting to: mainnet

**Additional context**
Attaching to the node service via journalctl shows that both my BP and relay nodes seem to be running as expected. Additionally if I press the up arrow key while gLiveView is trying to connect, I see gLiveView as it should appear, showing current node status as of the time I started gLiveView, but frozen.

So from what I'm able to gather so far this is not a node issue but a gLiveView problem

**Comment by btbf** [comment]
`cardano_node_metrics_nodeStartTime_int`
This metric seems to have been removed in 1.34.0.

**Comment by rdlrt** [comment]
Thank you for reporting, we have not yet passed node 1.34.0 yet for tooling.

**Comment by rdlrt** [comment]
For those who are not in announcements channel and reaching this post, please ensure to read [this](https://t.me/guild_operators_official/42) message
