### ISSUE TITLE
Installation ghcup with Error: syntax error near unexpected token `(' 

### ISSUE THREAD

**Issue by MichaelTMS** [cardano-community/guild-operators#1375]
**Describe the bug**
I got an error while build docker stage1 image. 

```
Install ghcup (The Haskell Toolchain installer) ..
bash: line 393: syntax error near unexpected token `('
bash: line 393: `			warn "[P] Yes, prepend  [A] Yes, append  [N] No  [?] Help (default is \"P\")."'
Upgrading ghcup ..
Installing GHC v8.10.7 ..
./prereqs.sh: line 267: ghcup: command not found
./prereqs.sh: line 268: ghcup: command not found
./prereqs.sh: line 269: ghc: command not found
Installing Cabal v3.6.2.0..
./prereqs.sh: line 278: ghcup: command not found
```

**Screenshots**
![image](https://user-images.githubusercontent.com/90009297/159186573-07239c88-acd8-4e29-9eab-4172654407e2.png)

**Version:**
 - OS: Ubuntu 20.04.4 LTS 
 - Cardano Node version: 1.34.1

**Comment by rdlrt** [comment]
Thanks for reporting , looks like ghc setup had an update in last few days...the mentioned line 293 is coming from ghcup bootstrap script that's downloaded from haskell site...the corresponding change they added seems to be relevant for windows, but has kinda caused a broken build for interactive session on bash.

We might have to patch it for now removing interactive support (as I doubt anyone really uses ghcup interactive anymore).
