### ISSUE TITLE
gLiveView Peers listed multiple times after switching back to home and then back peers

### ISSUE THREAD

**Issue by brouwerQ** [cardano-community/guild-operators#1383]
If you press 'p' for peers, then 'h' for home and then 'p' again, each connection is listed twice.
If you do it again, it's listed three times.
Another time: four times.
And so on...

Version 1.26.4.

**Comment by rdlrt** [comment]
Nice catch, [peersFiltered](https://github.com/cardano-community/guild-operators/blob/33ceec05ef615212307efbbfe26690bfa1498f07/scripts/cnode-helper-scripts/gLiveView.sh#L474) isn't initialised to `()` in checkPeers function, will patch it later in the day - unless you'd like to add it to L442, and bump patch version at L60.

Thanks
