### ISSUE TITLE
./prereqs -w does not add cardano-hw-cli to PATH

### ISSUE THREAD

**Issue by gmoratorio** [cardano-community/guild-operators#1406]
**Describe the bug**
I recently installed CNTools on a new Ubuntu laptop (22.04 LTS), first running `./prereqs` then installing  cardano-hw-cli with `./prereqs -w` (I also tried `./prereqs -f` followed by `./prereqs -w` to be sure), and after the scripts completed, the cardano-hw-cli executable was not in my PATH.

I looked at the `./prereqs.sh` script and saw this on line `379`
```
echo "  PATH=\"$HOME/bin/cardano-hw-cli:\$PATH\"" >> "${HOME}"/.bashrc
```

and when I ran this command manually in my terminal it updated the PATH correctly in `.bashrc`, but it seems like the `prereqs.sh` might have a bug that keeps it from running this line as part of the install.

**To Reproduce**
Install cntools via steps in https://cardano-community.github.io/guild-operators/basics/#pre-requisites
1. `mkdir "$HOME/tmp";cd "$HOME/tmp"`
2. `curl -sS -o prereqs.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh`
3. `chmod 755 prereqs.sh`
4. `./prereqs.sh`
5. `. "${HOME}/.bashrc"`
6. `./prereqs.sh -w`
7. `. "${HOME}/.bashrc"`
8. Check contents of `.bashrc`
9. CNTools PATH variables such as `CNODE_HOME` are correctly added, but `cardano-hw-cli` is not

**Expected behavior**
`cardano-hw-cli` should be added to `.bashrc` automatically as part of running the script

**Version:**
 - OS: Ubuntu 22.04 LTS
 - Product version: latest version, installed yesterday
 - Cardano Node version: none - defect is part of prereqs install
 - Network you're connecting to: none - defect is part of prereqs install

**Comment by Scitz0** [comment]
Closing issue and handling it in #1407 instead as its basically the same issue.
