### ISSUE TITLE
Uptime is unavailable

### ISSUE THREAD

**Issue by minzak** [cardano-community/guild-operators#1427]
I'm used not script-provided setup, and I found, that uptime is always set to zero. 
<img width="438" alt="image" src="https://user-images.githubusercontent.com/12154217/171463656-2db14dc3-205d-4b29-88a0-a66d4d7856e1.png">

But if see in htop, i see how long this service is here:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/12154217/171465179-a63f084b-d3c8-4bdd-9d0e-1fd3539ef06f.png">

It can be related to https://github.com/cardano-community/guild-operators/issues/1418

**Comment by rdlrt** [comment]
You'd want to update your cardano-node startup command (see example [here](https://github.com/cardano-community/guild-operators/blob/alpha/scripts/cnode-helper-scripts/cnode.sh#L123-L142) ), port=3000 -> port 3000

**Comment by minzak** [comment]
Yes, it helps.
