### ISSUE TITLE
[CNTOOLS] Pool registration waiting forever for the correct balance

### ISSUE THREAD

**Issue by MarcelKlammer** [cardano-community/guild-operators#143]
First: Thanks for this great repo.

Just registered a pool via an addr that had two utxo.

17c2b93c6e541c5f475779e2a2db5ea4caa26f09999285b0dfe1cc4f80dbb362     0      399499244314
cfeba634d0528b6a5c141ff03ab7dc4ddcf483e950bd6fe2cfb942e4de21708f     1           4832035

Total balance in 2 UTxO is 399504076349 Lovelaces or 399504.076349 ADA

WARN: Balance mismatch, transaction not included in latest block (399504076349 != 399499244314)

It didn't finish, because the amounts didn't match with each new block.
Calculating the mismatch it turns out that the amount missing is the second utxo.

399504076349 - 399499244314 = 4832035

So the second utxo wasn't taken in consideration for the final balance.

**Comment by papacarp** [comment]
I assume this is related to CNTOOLS?

**Comment by MarcelKlammer** [comment]
Sorry, yes.

**Comment by papacarp** [comment]
Ok, I just pushed a bunch of changes around this.  feel free to try again with the PR

https://github.com/cardano-community/guild-operators/pull/144

**Comment by MarcelKlammer** [comment]
So I had two utxo again on the addr. 400k and 5 ADA.
I deleted the old Staking keys and rewards addr to be able to upgrade the addr again via cntools.

Same behavior. The Transaction that creates the new Base.addr leaves the small amout on the old addr.

The Waiting script waits forever.

**Comment by MarcelKlammer** [comment]
Pool registration: Same behavior.

Base.addr: 

400k ADA
5 ADA

The 5 ADA throw the waiting script off.

**Comment by papacarp** [comment]
ok.  Makes sense.  I misunderstood the issue when I read it the first time.

**Comment by Scitz0** [comment]
A fix has been pushed for wallet staking upgrade.
This should now send balance from all utxo to the new base address.
2a5d5782a46d8fbce9bb5d10808af4e4f78bd869

Was this issue opened for this or Pool Registration as title suggest?
Waiting to close issue until this is verified.

**Comment by papacarp** [comment]
He was referring to staking wallet upgrade.  So I think your changes fixed this.  I think we close it and can re-open if it comes up again.

**Comment by Scitz0** [comment]
Closing issue as we suspect this has been resolved in 2a5d578
