### ISSUE TITLE
Using CNCLI v5.0.1, the wrong readership schedule is obtained.

### ISSUE THREAD

**Issue by btbf** [cardano-community/guild-operators#1438]
**Describe the bug**
When installing CNCLI v5.0.1 on a server and retrieving the leader schedule via cncli.sh leaderlog, the wrong schedule is retrieved.
(Public testnet Alonzo-era)

**Version:**
 - OS: Ubuntu20.01
 - Product version: [node-1.35-alpha]
 - Cardano Node version: 1.35.0-rc4
 - Network you're connecting to: --testnet-magic 1097911063

**Additional context**
The "--consensus" option has been added to the "cncli leaderlog" command in CNCLI v5.

**Comment by rdlrt** [comment]
Thanks for raising the issue, guild tools dont yet support 1.35, for context - see [here](https://t.me/guild_operators_official/44) , tho this is one of the known changes that will go into open draft PRs

**Comment by AndrewWestberg** [comment]
For context, if no `--consensus tpraos` option is set, cncli will assume we are already in the babbage era by default. This fix can be made on the guild tools side once we have a final 1.35 release.

**Comment by rdlrt** [comment]
Closed by #1440
