### ISSUE TITLE
The `cncli.sh leaderlog` will work with `tpraos` even if the network goes into Babbage-era.

### ISSUE THREAD

**Issue by btbf** [cardano-community/guild-operators#1458]
https://github.com/cardano-community/guild-operators/blob/9cf5e37062fdb5c1b8cb9f8f12be6b2b2ed8c231/scripts/cnode-helper-scripts/env#L703

I think it is due to the fact that double quotes are taken into the variable together.
It worked correctly by specifying the `jq -r` option and removing the double quotes.

Version:
OS: Ubunto 20.04 LTS
Cardano Node version:
cardano-node 1.35.1 - linux-x86_64 - ghc-8.10
git rev c75451f0ffd7a60b5ad6c4263891e6c8acac105a
Network : Testnet

**Comment by Scitz0** [comment]
You are correct, -r to show value in raw format is needed indeed.
I will patch alpha 👍

**Comment by btbf** [comment]
@Scitz0 Thank you for your prompt reply.
