### ISSUE TITLE
Guild scripts has now been upgraded to support cardano-node 1.32.1 or higher / no old cardano-node versions

### ISSUE THREAD

**Issue by HT-Moh** [cardano-community/guild-operators#1463]
On my backup server I have the following issue:

`tail -f -n 100 /var/log/syslog`
```
Jul 17 15:35:04 moh systemd[1]: cnode-submit-api.service: Service hold-off time over, scheduling restart.
Jul 17 15:35:04 moh systemd[1]: cnode-submit-api.service: Scheduled restart job, restart counter is at 194.
Jul 17 15:35:04 moh systemd[1]: Stopped Cardano Node Submit API.
Jul 17 15:35:04 moh systemd[1]: Started Cardano Node Submit API.
Jul 17 15:35:04 moh cnode-submit-api[584]: Guild scripts has now been upgraded to support cardano-node 1.32.1 or higher (1.29.0 found).
Jul 17 15:35:04 moh cnode-submit-api[584]: Please update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.
Jul 17 15:35:04 moh cnode-submit-api[584]: Guild scripts has now been upgraded to support cardano-node 1.32.1 or higher (1.29.0 found).
Jul 17 15:35:04 moh cnode-submit-api[584]: Please update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.
Jul 17 15:35:04 moh cnode-submit-api[584]: ERROR: Failed to load common env file
Jul 17 15:35:04 moh cnode-submit-api[584]: Please verify set values in 'User Variables' section in env file or log an issue on GitHub
Jul 17 15:35:04 moh systemd[1]: cnode-submit-api.service: Main process exited, code=exited, status=1/FAILURE
Jul 17 15:35:04 moh systemd[1]: cnode-submit-api.service: Failed with result 'exit-code'.
```

 This issue/bug I had before, and I fixed by searching for old `cardano-node` and deleting it, but this time I am not sure what is the issue?

![image](https://user-images.githubusercontent.com/34759569/179400477-e0e1c940-464d-4088-bacd-8ee6bbe5fe41.png)

```
ubuntu@moh:~$ /home/ubuntu/.cabal/bin/cardano-node --version
cardano-node 1.34.1 - linux-x86_64 - ghc-8.10
git rev 73f9a746362695dc2cb63ba757fbcabb81733d23
```

The version is the correct one 

I updated ubuntu and restarted problem still there:

```
sudo apt-get update
sudo apt-get upgrade
sudo reboot 
``` 

I switched to root and search all the system for another version 
```
find / -type f -executable  -name "cardano-node"
```
and guess what ? I have only one version 
![image](https://user-images.githubusercontent.com/34759569/179400606-f8e330b8-4244-406e-894f-efc576ba6240.png)

I removed `cnode` services from the system, deleted all folders except the DB, and reinstalled the guild, but unfortunately the same problem 

```
cd "$HOME/tmp"
curl -sS -o prereqs.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh
chmod 755 prereqs.sh
./prereqs.sh -f
. "${HOME}/.bashrc
```
I checked the bashrc file, it's correct

```
[ -f "/home/ubuntu/.ghcup/env" ] && source "/home/ubuntu/.ghcup/env" # ghcup-env
export CNODE_HOME=/opt/cardano/cnode
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export PATH=$PATH:/opt/cardano/cnode/scripts
export CNODE_PORT=6000
export CARDANO_NODE_SOCKET_PATH=${CNODE_HOME}/sockets/node0.socket
``` 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

Hopefully can somebody help with annoying problem.

**Comment by rdlrt** [comment]
You have another binary in your `$PATH` when starting up as systemd, you can `echo $PATH` from script and remove stale binary.
`bashrc` may not always be sourced when running as systemd, but you can forcefully tell your setup to use specific binary by specifying `CCLI` and `CNODEBIN` variables in your env file.

**Comment by HT-Moh** [comment]
Thanks, however The exact issue is I had `cardano-cli` on `/usr/local/bin` which the same version as `/home/ubuntu/.cabal/bin/cardano-cli`, this is what causing the issue. I deleted and it works. the error mesage `Guild scripts has now been upgraded to support cardano-node...` is misleading .

**Comment by dostrelith678** [comment]
Your syslog shows the other version (now presumably deleted) to be 1.29.0, and if so, the error message does make sense.

**Comment by rdlrt** [comment]
>  is misleading , and IMHO if the version is correct the script should proceed and run the node.

If you mean incorrect `cardano-cli` vs `cardano-node`, sorry but the functionality assumes you're following documentations, we shouldn't be starting to support malpractices wherein a node or CLI binary are on a different version. If following documentations you should never end up having binaries in `/usr/bin`, and if you do for specific reasons - you should be using those via variables in `env` pointed out earlier
