### ISSUE TITLE
504 Gateway Time-out for Tx Metalabels Request

### ISSUE THREAD

**Issue by edridudi** [cardano-community/guild-operators#1470]
**Describe the bug**
Tx Metalabels Requests are timing out (infrequently)

**To Reproduce**
GET https://api.koios.rest/api/v0/tx_metalabels?limit=10

**Expected behavior**
No Timeout

**Screenshots**
```
Aug 02, 2022 11:59:12 AM okhttp3.internal.platform.Platform log
INFO: --> GET https://api.koios.rest/api/v0/tx_metalabels?limit=10
Aug 02, 2022 11:59:12 AM okhttp3.internal.platform.Platform log
INFO: --> END GET
Aug 02, 2022 11:59:45 AM okhttp3.internal.platform.Platform log
INFO: <-- 504 Gateway Time-out https://api.koios.rest/api/v0/tx_metalabels?limit=10 (33376ms)
Aug 02, 2022 11:59:45 AM okhttp3.internal.platform.Platform log
INFO: content-length: 92
Aug 02, 2022 11:59:45 AM okhttp3.internal.platform.Platform log
INFO: cache-control: no-cache
Aug 02, 2022 11:59:45 AM okhttp3.internal.platform.Platform log
INFO: content-type: text/html
Aug 02, 2022 11:59:45 AM okhttp3.internal.platform.Platform log
INFO: 
Aug 02, 2022 11:59:45 AM okhttp3.internal.platform.Platform log
INFO: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

Aug 02, 2022 11:59:45 AM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (92-byte body)
```

**Comment by rdlrt** [comment]
The current query code (view for select distinct) is not really optimal, we'd want to perhaps improve the `tx_metalabels` endpoint by moving into a cache table instead - the result set being as small as it currently is. The keys returned are not really changing often, so it might be alright for this table to get refreshed every 10/15 minutes

@dostrelith678 @Scitz0 - thoughts?

**Comment by Scitz0** [comment]
Agree, that the current view is not great as it is. I suggest turning the current view into a materialized view (or a cache table)  that is updated on a schedule. If a materialized view is used, we should refresh it using `CONCURRENTLY` option to allow select on it while updating.

**Comment by Scitz0** [comment]
Actually, let me investigate loost index scan first before creating a cache table.
ref: https://wiki.postgresql.org/wiki/Loose_indexscan

**Comment by Scitz0** [comment]
Yip, this is the way to go, current view takes ~15s on a fast dedicated server. While loose index scan approach takes ~10ms.

```
WITH RECURSIVE t AS (
  (SELECT key FROM tx_metadata ORDER BY key LIMIT 1)  -- parentheses required
  UNION ALL
  SELECT (SELECT key FROM tx_metadata WHERE key > t.key ORDER BY key LIMIT 1)
  FROM t
  WHERE t.key IS NOT NULL
)
SELECT key FROM t WHERE key IS NOT NULL; 
```

**Comment by rdlrt** [comment]
Nice, wasn't aware of skip scan bit, seems straightforward indeed

**Comment by rdlrt** [comment]
Should be fixed by linked issue, now just need to create a release soon (alongwith open PRs) - and version bump to have it available on instances
