### ISSUE TITLE
Inconsistent Token Registry Metadata value in Asset Information Response

### ISSUE THREAD

**Issue by edridudi** [cardano-community/guild-operators#1471]
**Describe the bug**
GET Request - https://api.koios.rest/api/v0/asset_info?_asset_policy=14696a4676909f4e3cb1f2e60e2e08e5abed70caf5c02699be971139&_asset_name=43554259

respond with a null value for the token_registry_metadata field (infrequently)

**Comment by rdlrt** [comment]
Thanks for raising. Should be resolved now - one of the instances had missed a `-r` which resulted in having an invalid meta for some tokens (due to wrong commit in control_table). Should no longer be replicable, but do yell out if you see anything unexpected
