### ISSUE TITLE
Koios-BF Address Info Endpoint Gap

### ISSUE THREAD

**Issue by edridudi** [cardano-community/guild-operators#1481]
![image](https://user-images.githubusercontent.com/3818746/183419903-285a1843-efe6-47dd-a78f-8a4bb8994215.png)

There are two new fields in Address Info Endpoint in BF which are missing in Koios.
I understood that I can take them from TX Info Endpoint (I don't know how do they called exactly) but it would be best to have them also in Address Info Endpoint in order to decrease the number of requests involved using Cardano Java Client Library used by Java developers (Bloxbean).

Linked Issue in cardano-client-lib Repo: https://github.com/bloxbean/cardano-client-lib/issues/148

**Comment by rdlrt** [comment]
to be triaged via cardano-community/koios-artifacts#72
