### ISSUE TITLE
problem on cncli.sh , don't run leaderlog with --consensus praos in testnet that is Babbage era

### ISSUE THREAD

**Issue by stefanosu-code** [cardano-community/guild-operators#1493]
The if to choose consensus is not verified because var $NETWORK_ERA contains value Babbage with quotes "Babbage"
so modifying the if by adding single quotes
FROM:
if [[ ${NETWORK_ERA} = "Babbage" ]];
TO:
if [[ ${NETWORK_ERA} = '"Babbage"' ]];

is verified and consensus set to praos.
The if is present twice,  lines 248 and 302 .

1. run command:  ./cncli.sh leaderlog
2. From another terminal run command:   ps -efa | grep leaderlog
2. Check consensus parameter value is: --consensus tpraos that is wrong

**Expected behavior**
is: --consensus praos

**Version:**
 - OS: [Oracle linux 8]
 - Product version: [CNTools 9.1.0]
 - Cardano Node version: 1.35.3
 - Network you're connecting to: testnet

**Comment by btbf** [comment]
#1458
This issue has been fixed in this issue.
I believe the next update will reflect this in the main branch as well.

**Comment by rdlrt** [comment]
1.35.3 is only cleared on `alpha` branch for guild tools, networks other than mainnet should use `alpha` - while mainnet (currently cleared only for 1.34.1) for `master` branch
