### ISSUE TITLE
gLiveview does not detect the node and shows the relay information

### ISSUE THREAD

**Issue by orelvis15** [cardano-community/guild-operators#1507]
**Describe the bug**
I just set up the pool from scratch, it already appears in the [adapool](https://cexplorer.io/pool/pool1wwqqcyr7nu045pnjsaajrxuw3aq45cqxz0jj349w8ttxjh7n5n9) dashboard but when I run the gLiveview in it it shows me as if it were running in the relay.

<img width="514" alt="Captura de Pantalla 2022-08-25 a la(s) 09 28 39" src="https://user-images.githubusercontent.com/19788313/186692382-f03bc765-a48f-480c-b065-5cd7335a8a29.png">

I have a somewhat custom configuration of folders, I use [CVM](https://github.com/orelvis15/cvm) to create the pool, this has worked well for me so far or the only strange thing that happens is that the cnode folder is deleted from the tree, that is, my cardano path is /opt/cardano . And on the other hand, when I use cntools to manage the pool, it creates a cardano folder inside the existing one with its priv folder and the keys inside. I leave a screenshot of my current folder tree.

<img width="415" alt="Captura de Pantalla 2022-08-25 a la(s) 09 33 28" src="https://user-images.githubusercontent.com/19788313/186694152-c26b99f2-89bc-4bde-9861-033e1358394a.png">

The folder marked "cardano" is the one created by cntool.

**Comment by rdlrt** [comment]
> it already appears in the adapool dashboard but when I run the gLiveview in it it shows me as if it were running in the relay.

What you see on chain is your pool registration information, what you see on gLiveView is your node status .


> I have a somewhat custom configuration of folders, I use CVM to create the pool, this has worked well for me so far or the only strange thing that happens is that the cnode folder is deleted from the tree, that is, my cardano path is /opt/cardano 

This might be unrelated to your issue statement. When using custom folders, you'd need to uncomment and set variables to point the script to individual folders. The common folder tree assumption from tools is documented [here](https://cardano-community.github.io/guild-operators/basics/#pre-requisites) - when customising, you'd need to read the script and replace all variables available (ensure you disable auto update in that case by editing env file).
