### ISSUE TITLE
blockPerf Systemd Service Fails on Reboot and Cnode Restart

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#1508]
**Describe the bug**
The blockPerf systemd service fails to start on reboot or cnode restart. Error provided indicates that service thinks prior instance is still running due to existence of PID file.

**To Reproduce**
1. cnode service and cnode-tu-blockperf service are running 
2. sudo systemctl restart cnode
3. sudo systemctl status cnode-tu-blockperf.service

**Expected behavior**
The service should handle node restarts and machine reboots without error.

**Version:**
 - OS: Ubuntu 20.04
 - Product version: BP_Version=v1.2.0
 - Cardano Node version: cardano-node 1.35.3 - linux-x86_64 - ghc-8.10
   git rev 950c4e222086fed5ca53564e642434ce9307b0b9
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]  2017-09-23T21:44:51Z

**Additional context**
Simply deleting the existing blockPerf-Mainnet.pid file and restarting cnode-tu-blockperf service fixes the error.

**Comment by samcgill29** [comment]
One additional note: I found that blockPerf wants both tracechainsyncclient and traceblockfetchclient to be true in node configuration JSON file. Current guild mainnet-config JSON has tracechainsyncclient set to false.

**Comment by gufmar** [comment]
> service thinks prior instance is still running due to existence of PID file.

v1.2.1 added a first fix to solve this issue.  please 
1) update with prereqs.sh 
2) manually delete the existing blockPerf-running.pid file once
3) execute scripts/blockperf.sh -d once to apply the fix in the existing systemd service file

There will be a further update to improve this setup/update mechanism.

**Comment by gufmar** [comment]
> One additional note: I found that blockPerf wants both tracechainsyncclient and traceblockfetchclient to be true in node configuration JSON file. Current guild mainnet-config JSON has tracechainsyncclient set to false.

yes I know. the guild config files generally try to be as efficient and light as possible. setting tracechainsyncclient to true will add a noticeable amount of logfiles. Not really a problem for the node instance, but shouldn't become a default setting for any cntools managed node, as long as it is not actively contributing to the blockPerf reporting and wisdom sharing. 

Here to we will look into some options to automate/improve the setup mechanism.
