### ISSUE TITLE
Cnode-submit-api Systemd Service Fails to Start

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#1509]
**Describe the bug**

**To Reproduce**
1. sudo systemctl start cnode
2. sudo systemctl status cnode-submit-api
3. See error

Error: cardano-submit-api: FatalError {fatalErrorMessage = "readTxSubmitNodeConfig: Error parsing config: AesonException \"Error in $: key \\\"EnableLogging\\\" not found\""}

**Expected behavior**
Service should launch without error

**Version:**
 - OS: Ubuntu 20.04
 - Product version: CNTools 10.0.3 release
 - Cardano Node version: [e.g. output of `cardano-node version`] cardano-node 1.35.3 - linux-x86_64 - ghc-8.10
    git rev 950c4e222086fed5ca53564e642434ce9307b0b9
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`] 2017-09-23T21:44:51Z

**Additional context**
The problem seems to stem from the line in submitapi.sh:

# Run Submit API
"${SUBMITAPIBIN}" --config "${CONFIG}" --testnet-magic ${NWMAGIC} --socket-path "${CARDANO_NODE_SOCKET_PATH}" --listen-address ${HOSTADDR} --port ${HOSTPORT}

${CONFIG} should point to separate submit-api-config.json, but currently env only registers cardano-node CONFIG files.

**Comment by rdlrt** [comment]
You're perhaos mixing guides, the guide from this repo downloads files that contain the mentioned missing keys as part of node config, you dont need a seperate config for submit api if those keys are present in config
