### ISSUE TITLE
[CNTools] Pool registration on with already registered pool display error message of missing files

### ISSUE THREAD

**Issue by 0rtis** [cardano-community/guild-operators#1522]
**Describe the bug**
With a single already registered pool, trying register show a misleading error msg:
```
WARN: No pools available that can be selected! Required files:
cold.vkey
cold.skey
vrf.vkey
```
even though all files are accessible

**To Reproduce**
1. Have an laready registered pool
2. Select `Pool`->`Register`->`Online`

**Expected behavior**
The message should mention that no unregsitered pool were found

**Cause of the bug**
The `REGISTER` operation calls `selectPool` with `mode` set to `non-reg`. In the case of an already registered pool `isPoolRegistered` is returning 2 and the pool entry is skept (https://github.com/cardano-community/guild-operators/blob/alpha/scripts/cnode-helper-scripts/cntools.library#L537). Since there is no other non registered pool, the variable `pool_dirs` is empty and the misleading error message is printed.

Additionally, the labels `Regsiter` and `Modify` should be changed to something more explicit like `Register new pool` and `Modify existing registration`

**Version:**
 - OS: Ubuntu
 - Product version: 10.0.3
 - Cardano Node version: 1.35.3

**Comment by rdlrt** [comment]
The behaviour is as-expected. At best, we can probably change the description at the top to spell it out that register is for new pool.

Will add that as part of 10.0.4 PR open
