### ISSUE TITLE
[CNTOOLS] Create pool list feature with KES expiry

### ISSUE THREAD

**Issue by papacarp** [cardano-community/guild-operators#156]
When you create pools or rotate the KES it will save the most recent kes start.   We should calculate the expiry and include it in a list of pools (maybe highlight it green, yellow, red if its close to expiring)

**Comment by Scitz0** [comment]
Very good suggestion.

**Comment by gitmachtl** [comment]
Just a suggestion, the KES / OpCert generation should be done on a offline machine. So better using the genesis.json and calculate the KES period from the startTime and not from the current slot.
