### ISSUE TITLE
Asset Transaction History endpoint wrong data

### ISSUE THREAD

**Issue by HT-Moh** [cardano-community/guild-operators#1569]
Calling the endpoint `GET /asset_txs` with the following parameters 
{
    "_asset_policy": "3789bb09f7ac281e049455f9b4ca4a92687aab7ca13eb46df947099d",
    "_asset_name": "496b6967616933343636"
}
respond with 
```
[
  {
    "tx_hash": "fdc9d44d1ae526370fbe146b8cec6ab329e17f8eda7af4e8bdae036a57e1f4ab",
    "epoch_no": 372,
    "block_height": 7957368,
    "block_time": 1667284367
  },
  {
    "tx_hash": "037d15a47963f81a23e3d474ec1faea688c1d4dcaea3c5760ca4e303e2db2402",
    "epoch_no": 372,
    "block_height": 7956462,
    "block_time": 1667265309
  },
  {
    "tx_hash": "79eea55ff4ad1e4ec3ed20a79562ffc13f52cfc9fdde54818ae7ad290da358ad",
    "epoch_no": 372,
    "block_height": 7955478,
    "block_time": 1667245097
  },
  {
    "tx_hash": "3ba260f21b6951dcebb253fd7273083776fdc40d5838cca81701af5e1aaaca33",
    "epoch_no": 372,
    "block_height": 7955457,
    "block_time": 1667244606
  },
  {
    "tx_hash": "4ed14c936e587db93ac2ef9a6ba4f83f89e5e9bbe04856fe9665a901630a1f6a",
    "epoch_no": 372,
    "block_height": 7955442,
    "block_time": 1667244295
  },
  {
    "tx_hash": "3779d630919a9c5fc1124b2a2e5daa743edecb6485d2786999987f0f420c47f3",
    "epoch_no": 372,
    "block_height": 7955436,
    "block_time": 1667244185
  },
  {
    "tx_hash": "5b923e9f90e1e9fbd6f797d3ca89b240c23ca6ae927bf50094fae27728fadcc7",
    "epoch_no": 372,
    "block_height": 7955388,
    "block_time": 1667243250
  },
  {
    "tx_hash": "d25c19d2aad25c5840db0acd0665c9fe5e0bfbd7ce3d1a118f92206d11793b2d",
    "epoch_no": 372,
    "block_height": 7955356,
    "block_time": 1667242401
  },
  {
    "tx_hash": "a5b223167020c5620203a7ebff828ea2654fec8c505072d62d6cce47d5ae25c8",
    "epoch_no": 372,
    "block_height": 7955340,
    "block_time": 1667242033
  }
]
```
The 2, 3,4  tx hashes  are not for the asset  `496b6967616933343636` and don't even belong to the same policy id 

```
037d15a47963f81a23e3d474ec1faea688c1d4dcaea3c5760ca4e303e2db2402
79eea55ff4ad1e4ec3ed20a79562ffc13f52cfc9fdde54818ae7ad290da358ad
3ba260f21b6951dcebb253fd7273083776fdc40d5838cca81701af5e1aaaca33
```

**Comment by HT-Moh** [comment]
As well the policy has around [47 tx](https://cardanoscan.io/tokenPolicy/3789bb09f7ac281e049455f9b4ca4a92687aab7ca13eb46df947099d), when a call is made only with the parameter policy id to `GET /asset_txs` it returns []

![image](https://user-images.githubusercontent.com/34759569/199220343-675b9666-dee0-4448-88c1-8fa7c4e5af71.png)

**Comment by rdlrt** [comment]
> when a call is made only with the parameter policy id to GET /asset_txs it returns []

Empty asset name is valid asset token (it represents royalty token) - see [CIP 27](https://cips.cardano.org/cips/cip27/)

**Comment by HT-Moh** [comment]
@rdlrt thanks, what about the first issue?  is there a way to display all tx for the same policy ID, maybe something like using the wildcard *?

**Comment by rdlrt** [comment]
> @rdlrt thanks, what about the first issue? is there a way to display all tx for the same policy ID, maybe something like using the wildcard *?

The mentioned asset is part of transaction UTxO for each of the mentioned transactions (check querying them via tx_info):
```
037d15a47963f81a23e3d474ec1faea688c1d4dcaea3c5760ca4e303e2db2402
79eea55ff4ad1e4ec3ed20a79562ffc13f52cfc9fdde54818ae7ad290da358ad
3ba260f21b6951dcebb253fd7273083776fdc40d5838cca81701af5e1aaaca33
```

As regards your query about policy, unfortunately it's not sustainable on a free tier system the way DeFi ecosystem is progressing, see comment [here](https://github.com/cardano-community/koios-artifacts/issues/90#issuecomment-1235060884)
