### ISSUE TITLE
CNTools v10.0.5 - Wallet intermittently shows zero balance

### ISSUE THREAD

**Issue by lbcrypt** [cardano-community/guild-operators#1574]
This is running Preview with release 1.35.4.

Intermittently, when I list the wallet, it will show funds of 0 but it will show the correct rewards amount. If I list the wallet a 2nd time it usually shows the correct balance. I've seen where each time I list it will toggle between 0 and the correct balance, and I've seen it show the correct balance 10 times in a row, so I can put any rhyme or reason into what causes the funds to show 0.

This started after I updated the cnode version to 1.35.4. I have not seen this behavior on PreProd, only on my Preview system.

**Comment by Scitz0** [comment]
We have been aware of this since yesterday and are investigating the issue. It seems one of the instances does not serve valid data.

**Comment by Scitz0** [comment]
Should be solved now.
