### ISSUE TITLE
gLiveView fail to exec on debian docker based img

### ISSUE THREAD

**Issue by mberrueta** [cardano-community/guild-operators#1582]
**Describe the bug**

Given this [Dockerfile](https://gist.github.com/mberrueta/e10a47d6147998541720798193bf643f) the gLiveView failed to run by lack of `pgrep` command

**To Reproduce**
1. Download/create a the dockerfile
2. Run the container
3. Run the node
4. Run the gLiveView

**Expected behavior**

It works without the throwing the error `COULD NOT CONNECT TO A RUNNING INSTANCE, 3 FAILED ATTEMPTS IN A ROW!`

**Screenshots**

**Version:**
 - OS: Debian 11
 - Product version: 1.27.3 b:master
 - Cardano Node version: 1.35.3
 - Network you're connecting to: testnet-magic 764824073

**Comment by redoracle** [comment]
Hi,

thanks for reporting it. A fix has been released in alpha, soon it will be merged to the master branch.
