### ISSUE TITLE
Cannot register stake pool with cntools script, getting 

### ISSUE THREAD

**Issue by brittocj** [cardano-community/guild-operators#1589]
**Describe the bug**
While trying to register stake pool getting following error.
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (ValueNotConservedUTxO (Value [9497624778](tel:9497624778) (fromList [])) (Value [8997624778](tel:8997624778) (fromList [])))))])

**To Reproduce**
1. Run cntools and select pool, then register with details, it will throw the UTxO error after submitting final step.

**Expected behavior**
We should able to register the pool.

**Screenshots**
![image](https://user-images.githubusercontent.com/1892301/209561499-490f607f-bcc7-4bfd-9a89-f1a8ef59de2f.png)

**Version:**
 - OS: Docker image cardanocommunity/cardano-node:1.35.3
 - Product version: CNTools v10.0.5
 - Cardano Node version: cardano-node 1.35.3 - linux-x86_64 - ghc-8.10
git rev 950c4e222086fed5ca53564e642434ce9307b0b9
 - Network you're connecting to: Preprod

**Additional context**

**Comment by rdlrt** [comment]
Could you create a **new** CNTools session, replicate the error by going to `Pool` > `Register` (if registering a new pool) OR `Modify` (if modifying/re-registering an already registered pool) , and then provide the complete cntools-history.log file for this session , it is important that the log isnt cropped - the one that was shared on support group simply contained output from `Pool` > `Show` and referred to TEST1 pool, while screenshots were for BRITS1 on preprod network.

**Comment by brittocj** [comment]
[cntools-history.log](https://github.com/cardano-community/guild-operators/files/10328732/cntools-history.log)
Just reproduced the issue and attached the log file.

**Comment by rdlrt** [comment]
Did you create *.addr files elsewhere and import it to cntools (instead of creating keys/addresses via CNTools itself)?
In the logs, I see the address used for stake-address-info to be the base address instead of reward/stake address

**Comment by brittocj** [comment]
Used cntools and got error, so tried manual commands and registered the stake pool. Last as you suggested created new pool Test123 and got same error.

**Comment by rdlrt** [comment]
Sorry, that's not clear to me. As said above, it seems address files in your wallet contains wrong  information, if it was created manually. You have a  value of `addr_test1qzhr4qzuy3lvzyycl6ccmvc2r90n9x0d6xglhkyxer6wfusgv7v269cg3lly3gaxlef0vuuwqdx8yx8fsyy0nw45kdjqmzffsk` for reward address instead of `stake_test1uqyx0x9dzuyglljg5wn0u5hkww8qxnrjrr5czz8eh26txeqsr0sra` . If so, that would not be something done from within CNTools but perhaps manually?

Also, that's not the error that you originally reported (likely coz you've now registered the pool manually).

**Comment by brittocj** [comment]
Instruct me the steps to follow in cntools so that I could share the correct log history file.

**Comment by rdlrt** [comment]
If you've created a new pool , you shouldn't have to copy anything to pool directory - as it should already exist at right destination.

Again, this might be a different instance of error than before - but seems in this case, you've got an error due to cold/hot/opcert key mismatch as error says:

``` bash
/usr/local/bin/cardano-cli node issue-op-cert --kes-verification-key-file /opt/cardano/cnode/priv/pool/git_test_pool/hot.vkey --cold-signing-key-file /opt/cardano/cnode/priv/pool/git_test_pool/cold.skey --operational-certificate-issue-counter-file /opt/cardano/cnode/priv/pool/git_test_pool/cold.counter --kes-period 130 --out-file /opt/cardano/cnode/priv/pool/git_test_pool/keys/op.cert

[ERROR]  Command failed: node issue-op-cert  Error: Key mismatch: the signing key does not match the one that goes with the counter
```

**Comment by rdlrt** [comment]
This being 3rd _different_ issue being used to report on this issue (alongwith traces that show manual tampering of key files in the folder), am gonna go ahead and close this one for now - as the issue description as well as steps taken are chaotic with different issue on different attempts.
