### ISSUE TITLE
Docker image won't start - ERROR: Failed to load common env file

### ISSUE THREAD

**Issue by GunnarHelliesen** [cardano-community/guild-operators#1599]
Hi,

As of today, when I try to pull and run the `cardanocommunity/cardano-node` Docker image, it refuses to run. I get the following error message:

```
cardano-node 1.35.4 - linux-x86_64 - ghc-8.10
git rev ebc7be471b30e5931b35f9bbc236d21c375b91bb

Guild scripts has now been upgraded to support cardano-node 1.35.5 or higher (1.35.4 found).
Please update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.



Guild scripts has now been upgraded to support cardano-node 1.35.5 or higher (1.35.4 found).
Please update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.


ERROR: Failed to load common env file
Please verify set values in 'User Variables' section in env file or log an issue on GitHub

```

I set all environment variables in a script when I run the Docker image:

```
docker run [...] \
[...]
    -e PROMETHEUS_HOST=0.0.0.0 \
    -e NETWORK=mainnet \
    -e CNODE_PORT=NNNN \
    -e POOL_NAME=XXXX \
    -e HOSTNAME=relay.example.com \
    -e CONFIG=/opt/cardano/cnode/priv/files/mainnet-config.json \
    -e TOPOLOGY=/opt/cardano/cnode/priv/files/mainnet-topology.json \
    -e CUSTOM_PEERS=“core.local,3001,1|relays-new.cardano-mainnet.iohk.io,3001,2" \

```

It looks to me like the Docker image automatically pulls the updated scripts, without asking, and then fails to run due to some incompatibility.

To reproduce, simply try to run the Docker image with the default entrypoint, which will start the cardano-node.

This is on CentOS 9, with the latest cardano-node 1.35.4 Docker image. I'm connecting to the mainnet.

Is there a way I can tell the Docker image to use the legacy-scripts?

**Comment by redoracle** [comment]
Hi , many thanks for raising this issue.
The problem are not the downloading scripts but the docker building pipeline that pushes the image to docker hub.
Now the problem should be fixed. Can you download the latest image and try again please?

**Comment by GunnarHelliesen** [comment]
Hi,

Thanks! I just did, but now it dies without giving any error messages:


```
  _____     _ __   __  ____                    __             
 / ___/_ __(_) /__/ / / __ \___  ___ _______ _/ /____  _______
/ (_ / // / / / _  / / /_/ / _ \/ -_) __/ _ `/ __/ _ \/ __(_-<
\___/\_,_/_/_/\_,_/  \____/ .__/\__/_/  \_,_/\__/\___/_/ /___/
                         /_/ 
                         

NETWORK: mainnet PDT1 /opt/cardano/cnode/priv/files/mainnet-topology.json
NODE: uw2p01r01.pdtpools.io - Port:3001 - PDT1
cardano-node 1.35.5 - linux-x86_64 - ghc-8.10
git rev 8762a10efe3f9f97939e3cb05edaf04250456702
```

There's nothing after that. docker logs -f just returns to the command prompt.

```
$ docker ps
CONTAINER ID   IMAGE                                  COMMAND             CREATED         STATUS                         PORTS     NAMES
e45ee5b27436   cardanocommunity/cardano-node:latest   "./entrypoint.sh"   3 minutes ago   Restarting (1) 7 seconds ago             relay
```

**Comment by GunnarHelliesen** [comment]
I did not restart it. Here's the command:

```
docker run --detach \
    --log-opt max-size=10m \
    --log-opt max-file=5 \
    --restart always \
    --security-opt=no-new-privileges \
    --name=relay \
    -p 3001:3001 \
    -p 12798:12798 \
    -e PROMETHEUS_HOST=0.0.0.0 \
    -e NETWORK=mainnet \
    -e CNODE_PORT=3001 \
    -e POOL_NAME=XXXX \
    -e HOSTNAME=relay.example.com \
    -e CONFIG=/opt/cardano/cnode/priv/files/mainnet-config.json \
    -e TOPOLOGY=/opt/cardano/cnode/priv/files/mainnet-topology.json \
    -e CUSTOM_PEERS="pdt1-core.local,3001,1|relays-new.cardano-mainnet.iohk.io,3001,2" \
    -v /cardano/data/config:/opt/cardano/cnode/priv/files:Z \
    -v /cardano/data/db:/opt/cardano/cnode/db:Z \
    cardanocommunity/cardano-node:latest

```
This run command hasn't changed and was working fine until the latest update.

**Comment by redoracle** [comment]
I guess we found the issue, a fix will be released within 24 hours.

The temporary workaround is to download manually the file: https://github.com/cardano-community/guild-operators/blob/master/scripts/cnode-helper-scripts/guild-deploy.sh

and comment the lines from #231 to #243.

then mount the local custom guild-deploy.sh script with the docker run command option: 
-v  /PATHTO/guild-deploy.sh:/opt/cardano/cnode/scripts/guild-deploy.sh

I am sorry for the inconvenience, but because I was not able to replicate the issue (on my system works great) I needed some help from an other user experiencing it.

**Comment by GunnarHelliesen** [comment]
That's awesome, thanks! I'll give it a try again in 24 hours and report back.

**Comment by GunnarHelliesen** [comment]
Success! Thanks for all your help!
