### ISSUE TITLE
[Feature request] LiveView check for invalid certificate counter

### ISSUE THREAD

**Issue by sunapi386** [cardano-community/guild-operators#1605]
**Describe**
LiveView should check the certificate counter.

If the OnDisk counter differs from the OnChain counter by more than 1, the certificate will be invalid.

https://developers.cardano.org/docs/stake-pool-course/assignments/kes_period/#how-do-i-know-if-i-have-issued-an-invalid-operational-certificate

The purpose is to guard against this scenario https://github.com/input-output-hk/cardano-node/issues/4114

**Comment by Scitz0** [comment]
We will take the suggested change into consideration for an upcoming release.

**Comment by rdlrt** [comment]
Just a note - we would not want to rely on CLI or storage - but look at runtime (in line with all metrics gLV shows), we already had an item to use Koios query layer to check for latest OpCert metrics for given pool which would be refreshed at:
- KES time interval change;
- Startup of gLiveView;
- PID change of node
- KOIOS_MODE being set to N will disable this check.
This is in line with Catalyst proposal from Koios to further integrate between query layer and SPO tools

**Comment by rdlrt** [comment]
Closed in #1705
