### ISSUE TITLE
Hardware Wallet Registration Failure

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#1618]
**Describe the bug**
When registering a Trezor hardware wallet via cntools an error occurs and two warnings and two errors are printed.

**To Reproduce**
1. Install **trezor-bridge v2.0.27** from [github.com/trezor/data repo](https://github.com/trezor/data/tree/master/bridge/)
2. Run `trezord -l /var/log/trezord.log &` (or inside screen/tmux etc.)
3. Run cntools.sh
4. Choose **wallet** -> **register**, select an already imported Trezor Hardware Wallet.
5. Follow the instructions to connect wallet, unlock device and sign transactions.
6. Observe two Warning messages about superfluous HW signing file and superfluous output file.
   * `Warning! A superfluous HW signing file specified (1 of 1), the witness was not created.`
   * `Warning! A superfluous output file specified (1 of 1), the file was not written to.`
8. Press space after being told to press any key after following directions on device.
9. Observe two errors:
   * `Error: Missing signing file for certificate`
   * `ERROR: during hardware wallet signing !!`

**Expected behavior**
Successful wallet registration.

**Screenshots**

**Version:**
 - OS: Docker Slim (Container)
 - Product version: CNTools 10.20 / Branch alpha
 - Cardano Node version: 1.35.5
 - Network you're connecting to: 2022-06-01T00:00:00Z

**Additional context**

Running inside the Docker slim container. When I tested with `./cntools.sh -b cntools-10.2.0` on the preview network the error about trying to use the `sign` instead of `witness` command was resolved and no errors were observed. As that branch was merged and removed I used `./cntools.sh -b alpha` and updated to 10.2.0 today for Preprod network and the above bug was observed.

**Comment by Scitz0** [comment]
I have not forgotten about this one. Need to think of a good way to solve it. Possibly by a special case for HW devices when witnessing. It seems like cardano-hw-cli enforce signing of registration cert with both payment and stake key. Even though technically stake key isn't neccessary. The bigger problem is that it enforce you to sign tx with both at the same time. This is a problem with current implementation in cntools.
