### ISSUE TITLE
ENABLE_CHATTR for containers

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#1621]
There is a discussion in #936 on this topic, but I don't want to taint a clean thread with what is potentially a bug report, if it isn't a bug then maybe the discussion can be updated with more details. I'm unsure what the intended logic is, but I have assumptions, I'll provide a list below of items which may or may not lead to this transforming into a bug report.

1. The link in the original answer points to a commit with the deprecated `cntools.config` being referenced and does not show the `customize()` function which now handles this. 
   - Could potentially be updated to: [here](https://github.com/cardano-community/guild-operators/blob/master/files/docker/node/addons/entrypoint.sh#L33) if using the master branch is acceptable.
2. In `cntools.sh` the line the grep returns true for is `#ENABLE_CHATTR=true`, however the sed being applied does not take the comment into account resulting a commented out `#ENABLE_CHATTR=false` and `ENABLE_CHATTR=true` from `cntools.library` taking precedence.

Due to the above a container executing cntools results in:
```
Testing chattr access permission, enter user password if requested...
```

**Comment by TrevorBenson** [comment]
Removed number 3, I must have had an old branch or commit open on one of the tabs while reviewing, looking back at master I can see it was not correct and removed it from the list.

**Comment by rdlrt** [comment]
Agreed - docker setup would need to be updated to use cntools.library instead of cntools.config

**Comment by TrevorBenson** [comment]
@rdlrt 

I believe it does, since the container simply builds the master branch. My point above on #1 was that discussion #936 answer points to older commits which do use `cntools.config` even though the container does not.

The second point I believe is where the problem arises as the grep is not expected `#ENABLE_CHATTR=false` so the sed does not do anything, resulting in the default behavior of `cntools.library` inside the container. I'll open a branch and submit a change as I suspect its a bug but did not want to assume.

Thanks
