### ISSUE TITLE
topologyUpdater.sh - What is it doing ??

### ISSUE THREAD

**Issue by HuguesD** [cardano-community/guild-operators#1630]
Hi,

Trying to use the topologyUpdater.sh script. I assume, maybe wrongly, that it should create a new topology.json file.

I followed these steps from the documentation: 

cd $CNODE_HOME/scripts
curl -s -o topologyUpdater.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/topologyUpdater.sh
curl -s -o env https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/env
chmod 750 topologyUpdater.sh
./topologyUpdater.sh

The script ran but no output at all : no files created, no error message. The original topology.json remains the same.

What is that script doing ? where are the results ? where are the logs ? Shouldn't the script update/produce a new topology.json file ? 

It would be nice to have at least an example and explanations how to use the script in this github documentation : where are the results produced ?

**Comment by rdlrt** [comment]
Have you read the [documentation](https://cardano-community.github.io/guild-operators/Scripts/topologyupdater/)? What it does, results, logs , explanations, etc can be found above.

**Comment by HuguesD** [comment]
Hi,

Yes I have read the documentation. But it does not explain:
-how to use the script : there is no step by step example on how to use it (from the intiial parameters setting in the script itself , until the result)
-There is no clarity what the result is from the script : is it a modified topology.json file ? if so, where is modified topology.json ? In which folder ? Does it modify the existing one ? if so, how does the script knows where the topology.json file is ? Does it make a backup copy of the original one before modifying it ?

and my most important remark : it does not work. I launched it trying to follow what I could get from the documentation. What happened is nothing : not an error message, not an output message, my topology.json file is not even touched nor modified.

So I must do soemthing wrong and clearly the documentation is not sufficient to find out what goes wrong. Or the script is bugged which I doubt but still can be possible.

**Comment by rdlrt** [comment]
The script does not expect you to run interactively. The documentation asks to deploy it as systemd and also the logging.

Also, as indicated on the homepage, guild-operators does not intend to provide step by step instructions, nor does it want users to blindly trust running script without reading. These are only utility scripts for experienced sysops.
