### ISSUE TITLE
[CNTools] - Ledger withdrawal error

### ISSUE THREAD

**Issue by dmitrystas** [cardano-community/guild-operators#1634]
**Describe the bug**

When we try to withdraw rewards from the Ledger wallet, we get an error

```
INFO: follow directions on hardware device to witness the transaction
Error: The requested operation failed. Check that your Ledger device is connected, unlocked and with Cardano app running.
Details: Error: Missing signing file for certificate

ERROR: during hardware wallet signing !!
```

**To Reproduce**
1. On the online environment run cntools.sh, go to Funds -> Withdraw Rewards -> Hybrid
2. Select Ledger wallet to withdraw funds
3. Copy offline transaction file to the local environment
4. On the offline environment run cntools.sh, go to Transaction -> Sign, and try to sign the tx
5. See error

**Additional context**

This is happening because with cntools we make a witness for each payment and stake key separately. For some unknown reason this doesn't work properly with the rewards withdrawal transaction. For such transactions we must use the following syntax:

```
cardano-hw-cli transaction witness \
--tx-file tx.transformed \
--hw-signing-file payment.hwsfile \
--hw-signing-file stake.hwsfile \
--mainnet \
--out-file payment.witness \
--out-file stake.witness
```

i.e. use both payment and stake keys at the same time.

P.S. since it's possible this is cardano-hw-cli bug-not-feature, just in case I also opened the issue in the cardano-hw-cli repo https://github.com/vacuumlabs/cardano-hw-cli/issues/162

**Comment by Scitz0** [comment]
Could you please try alpha version of cntools. I added a change in last patch version to create all witnesses in a single call for HW.

**Comment by dmitrystas** [comment]
thanks Ola! unfortunately I can't test it at the moment because I've already withdrawn the rewards manually, but since you've added the change to the latest version we can close the issue I guess
