### ISSUE TITLE
Error during registration and failure during delegation with Trezor HW Wallet and CNTools 10.2.2

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#1635]
**Describe the bug**
1. Warning when registering with a Trezor hardware wallet 
   * This warning does not appear to cause registration failure as the stake address can be found in a `cardano-cli query`.
2. Error when delegating to a pool with a Trezor hardware wallet 
   * This error appears to prevent the delegation process from suceeding.

**To Reproduce**
Steps to reproduce the behavior for registration:

1. Run `trezord` (aka Trezor Bridge)
2. Run CNTools version 10.2.2
3. Choose Wallet -> Register
4. Follow instructions
5. See warning message, then see message for successful registration submission after.

Steps to reproduce the behavior for delegation:

1. Run `trezord` (aka Trezor Bridge)
2. Run CNTools version 10.2.2
3. Choose Funds -> Delegate
4. Follow instructions
5. See error about hardware wallet signing and delegation failure

**Expected behavior**
1. No warning messages regarding a superfluous HW signing file when registration appears to succeed.
2. No errors/failures observed during fund delegation to a pool, delegation certificate successfully submitted to node and recorded transaction on the blockchain.

**Screenshots**
* **REGISTRATION:**
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 >> WALLET >> REGISTER
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Online mode  -  The default mode to use if all keys are available

Hybrid mode  -  1) Go through steps to build a transaction file
                2) Copy built tx file to offline computer
                3) Sign it using 'Sign Tx' with keys on offline computer
                   (CNTools started in offline mode '-o' without node connection)
                4) Copy the signed tx file back to online computer and submit using 'Submit Tx'

Selected value: [o] Online

# Select wallet to register (only non-registered wallets shown)
Selected wallet: TrezorWallet (Funds: 100,000.000000 Ada)


INFO: follow directions on hardware device to witness the transaction
Warning! A superfluous HW signing file specified (1 of 2), the witness was not created.
Writing to file '/tmp/cnode/cntools/tx.witness_7BqPEe4aMd'.
Transaction successfully submitted.

Waiting for new block to be created (timeout = 600 slots, 600s)
INFO: press any key to cancel and return (won't stop transaction)


TrezorWallet successfully registered on chain!

press any key to proceed ..
```

While it did produce an error, querying the stake-address-info shows the stake address registered without delegation:
```
# cardano-cli query stake-address-info  --testnet-magic $NWMAGIC --address stake_test1uz5ah77y8xvnxs6cyp979hg7fhxezjw39jfrpardqymnz7sg7ea8y
[
    {
        "address": "stake_test1uz5ah77y8xvnxs6cyp979hg7fhxezjw39jfrpardqymnz7sg7ea8y",
        "delegation": null,
        "rewardAccountBalance": 0
    }
]
```

* **DELEGATION:**
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 >> FUNDS >> DELEGATE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Online mode  -  The default mode to use if all keys are available

Hybrid mode  -  1) Go through steps to build a transaction file
                2) Copy built tx file to offline computer
                3) Sign it using 'Sign Tx' with keys on offline computer
                   (CNTools started in offline mode '-o' without node connection)
                4) Copy the signed tx file back to online computer and submit using 'Submit Tx'

Selected value: [o] Online

# Select wallet to delegate
Selected wallet: TrezorWallet (99,997.998462 Ada)

Do you want to delegate to a local CNTools pool or specify the pool ID?
Selected value: [i] Pool ID
Pool ID (blank to cancel): pool19st4a2vvu78tjtyywjte2eml3kx6ynersgd2nyw0y4jvyhlfu0u


INFO: follow directions on hardware device to witness the transaction
Error: Not enough output files specified

ERROR: during hardware wallet signing !!

ERROR: failure during delegation, removing newly created delegation certificate file

press any key to proceed ..
```

**Version:**
 - OS: RockyLinux 8
 - Product version: CNTools 10.2.2
 - Cardano Node version: 1.35.7
 - Network you're connecting to: GUILD / 2021-12-09T22:55:22Z

**Additional context**

**Comment by Scitz0** [comment]
This is a bit strange. 

1. You are correct that it gives a warning about superfluous HW signing file. In theory, stake key is not needed to witness a stake key registration. Only the payment key for input utxo to put certificate on chain.
Omitting the stake key in witness command however throws:
`Error: Missing signing file for certificate`
If you have an idea for correct formatting for witnessing a stake key registration let me know.

2. Fixed in cntools-10.2.3 hopefully. Please give it a try.

**Comment by TrevorBenson** [comment]
Signing a registration cert is one of the items missing from VacuumLabs doc examples from what I can tell.  

Maybe I misinterpret what they mean in this release note:

> - Ledger no longer creates a staking witness for staking key registration certificate (consistently with Trezor)

I suppose this really means it DOES NOT create a witness signature, but it DOES require the stake key listed as a hwsfile for the transaction. It feels like they incorrectly reference the stake key as "superfluous" because it is clearly "necessary" to sign the transaction as using only a payment hwsfile results in `Error: Missing signing file for certificate` has an RC of 1 and does not produce ANY output file.

I was thinking of opening a ticket upstream this weekend asking vacuumlabs to produce example registration signing steps.

**Comment by TrevorBenson** [comment]
> Signing a registration cert is one of the items missing from VacuumLabs doc examples from what I can tell.

The docs were not missing but does not have its own page, it is part of the stake delegation page.
