### ISSUE TITLE
[docker] - Incorrect node stop in the container

### ISSUE THREAD

**Issue by MichaelLLC** [cardano-community/guild-operators#1648]
**Describe the bug**
After stopping the container with the command: docker stop cardano-node, launching the node takes a long time more 1 hour

**To Reproduce**
1. Run command "docker stop cardano-node"
2. Run command "docker start cardano-node"

**Expected behavior**
After executing  command "docker start cardano-node",  cardano node must start quickly and synchronize

**Version:**
 - OS: Ubuntu 22.04 LTS
 - Cardano Node version: 1.35.5

**Additional context**
When executing the command "docker stop" , a SIGTERM signal is sent, but the primary process does not terminate at the right time.
Then the SIGKILL signal is sent.  If you manually run the command "kill -2 PID" inside the container and stop the child process: /usr/local/bin/cardano-node run --topology ......., then the next time the node is started, it will take ~ 5 minutes.

**Comment by redoracle** [comment]
thank you Michael, SIGINT added to the container trap code. In the next release should be fixed.
