### ISSUE TITLE
Error when submitting a CNTOOLS transaction on Cardano Node 8.0

### ISSUE THREAD

**Issue by mcvetyty** [cardano-community/guild-operators#1652]
**Describe the bug**
When I attempt to submit a transaction (either sending funds or withdrawing rewards) within CNTOOLS, cardano-cli fails with the following error:

Invalid option `–cddl-format’

**To Reproduce**
1. Go to Funds
2. Select Withdraw Rewards
3. Select wallet

**Expected behavior**
The transaction should submit.

**Version:**
 - OS: Ubuntu 20.0.4
 - Product version: CNTools v10.3.1 
 - Cardano Node version: 8.0

**Comment by rdlrt** [comment]
CNTools does not support 8.0.0 as per announcement [here](https://t.me/guild_operators_official/63) - it might potentially get skipped for next version. If you need to, you can switch to `cnode-8.0.0` branch - many folks who are using node 8.0.0 fo use this branch of CNTools.
