### ISSUE TITLE
How to connect to the node socket from outside Docker container?

### ISSUE THREAD

**Issue by jeremybarnes2342** [cardano-community/guild-operators#1656]
Given the following command:
```
docker run -dit --name cardano --memory 24G --cpus 16 --security-opt=no-new-privileges -e NETWORK=mainnet -v ~/db:/opt/cardano/cnode/db cardanocommunity/cardano-node:1.35.5
```

How do I connect to the socket (`/opt/cardano/cnode/sockets/node0.socket`) from outside the Docker container? I have some scripts, etc that i'd like to connect to the Cardano node.

I tried adding `-v ~/sockets:/opt/cardano/cnode/sockets` but the docker container always crashes with the error `cardano-node: Network.Socket.bind: permission denied (Permission denied)`

Any guidance would be appreciated!

**Comment by rdlrt** [comment]
> I tried adding -v ~/sockets:/opt/cardano/cnode/sockets but the docker container always crashes with the error cardano-node: Network.Socket.bind: permission denied (Permission denied)

Did you try to align permissions to be same as existing cnode/socket folder?

**Comment by iliketowritecode** [comment]
> > I tried adding -v ~/sockets:/opt/cardano/cnode/sockets but the docker container always crashes with the error cardano-node: Network.Socket.bind: permission denied (Permission denied)
> 
> Did you try to align permissions to be same as existing cnode/socket folder?

Not sure how I would go about that unfortunately :( 

I outputted the permissions on the `/opt/cardano/cnode/sockets` folder and got this:
```
guild@f6051ecd2320:/opt/cardano/cnode$ ls -ld /opt/cardano/cnode/sockets
drwxr-xr-x 1 guild guild 4096 Jun 18 00:32 /opt/cardano/cnode/sockets
```

**Comment by jeremybarnes2342** [comment]
> > I tried adding -v ~/sockets:/opt/cardano/cnode/sockets but the docker container always crashes with the error cardano-node: Network.Socket.bind: permission denied (Permission denied)
> 
> Did you try to align permissions to be same as existing cnode/socket folder?

Not sure how I would go about that unfortunately.

But I was able to get the permissions via `ls -ld` for the `/opt/cardano/cnode/sockets` folder:
```
guild@f6051ecd2320:/opt/cardano/cnode$ ls -ld /opt/cardano/cnode/sockets
drwxr-xr-x 1 guild guild 4096 Jun 18 00:32 /opt/cardano/cnode/sockets
```

**Comment by rdlrt** [comment]
> Not sure how I would go about that unfortunately.

To changing ownership of a folder, you can use `sudo chown <uid>:<gid> <folder>` , and for permissions (if setting to guild as owner, sudo chmod 755 <folder> ). This folder on host can than be mounted as sockets folder using -v parameter on your docker container run command.

**Comment by jeremybarnes2342** [comment]
> > Not sure how I would go about that unfortunately.
> 
> To changing ownership of a folder, you can use `sudo chown <uid>:<gid> <folder>` , and for permissions (if setting to guild as owner, sudo chmod 755 ). This folder on host can than be mounted as sockets folder using -v parameter on your docker container run command.

Yeah tried that and still getting errors. Figured this would be more straight forward of a process. I'll just stick with a manual install for now until the team provides official instructions :) Thanks for your help!

**Comment by TrevorBenson** [comment]
> > > Not sure how I would go about that unfortunately.
> > 
> > 
> > To changing ownership of a folder, you can use `sudo chown <uid>:<gid> <folder>` , and for permissions (if setting to guild as owner, sudo chmod 755 ). This folder on host can than be mounted as sockets folder using -v parameter on your docker container run command.
> 
> Yeah tried that and still getting errors. Figured this would be more straight forward of a process. I'll just stick with a manual install for now until the team provides official instructions :) Thanks for your help!

I suspect your running SELinux (or maybe AppArmour?) enabled. If you are you probably have AVC denial messages in your `audit.log` which are related to this issue. There are two things you can try:

1. When mounting pass the option `Z` to your mount which will modify the SELinux label of the passed in folder or file.
   * The `Z` option indicates that the bind mount content is shared among multiple containers. This is how I run the same mount point in 2 containers. The first container being the node, and the second being any container which sends commands to the node via the socket.
   * The `z` option indicates that the bind mount content is private and unshared. This is what I use when I just want it to be local to my container host, but not allowed to be mounted into any other container.
```
-v ~/sockets:/opt/cardano/cnode/sockets:Z
```
2. Use the `--privileged` option
```
--privileged -v ~/sockets:/opt/cardano/cnode/sockets
```

I suspect you maybe experiencing SELinux AVC denial messages. You might be able to observe this in `/var/log/audit/audit.log`, or wherever your distro stores its AVC denials. Even if you inspect and do not see denials, try both options and see what happens. 

FWIW In some rare cases a few years ago I noticed a lack of AVC denials for docker when this occurred. Using privileged and/or the z/Z options allowed the container to start anyway though, so I believe was just a bug related to logging AVC's from the container runtime engine.
