### ISSUE TITLE
ERROR: failure during pool modify

### ISSUE THREAD

**Issue by sleepingnatives** [cardano-community/guild-operators#1657]
**Describe the bug**
Receiving an error when trying to modify my relay configuration. I've modified it several times before without any issue, but this time it's failing with "ERROR: failure during pool modify!"

**To Reproduce**
1. Launch ./cntools.sh from script folder on core server.
2. Decrypt pool and wallet files.
3. Select 'pool' -> 'modify' 
4. Select not to re-use previous relay configuration, enter new server address/port details, and submit.

**Expected behavior**
Relay configuration is updated accordingly.

**Screenshots**

**Version:**
 - OS: Ubuntu 22.04
 - Product version: CNTools v10.3.1
 - Cardano Node version: 8.0.0
 - Network you're connecting to: cardano@SVRN:/opt/cardano/cnode/scripts$ jq -r .systemStart $CNODE_HOME/files/shelley-genesis.json
2017-09-23T21:44:51Z

**Additional context**
What follows is the copy/paste of the respective modify request:

"
# Pool Relay Registration

Previous relay configuration:

TYPE  ADDRESS         PORT
IPv4  202.61.246.89   6001
IPv4  159.89.245.111  6001

Reuse previous relay configuration?
Selected value: [n] No
Selected value: [i] IPv4/v6 address
Enter relays's IPv4/v6 address: 173.212.234.18
Enter relays's port: 6001
Add more relay entries?
Selected value: [y] Yes
Selected value: [i] IPv4/v6 address
Enter relays's IPv4/v6 address: 144.126.129.40
Enter relays's port: 6001
Add more relay entries?
Selected value: [n] No

# Previous Owner(s)/Reward wallets
Owner wallet #1 : SVRN
Reward wallet   : SVRN_Rewards

Reuse previous Owner(s)/Reward wallets?
Selected value: [y] Yes

# Pool Update Transaction
Invalid option `--cddl-format'

Usage: cardano-cli transaction build-raw
            [ --byron-era
            | --shelley-era
            | --allegra-era
            | --mary-era
            | --alonzo-era
            | --babbage-era
            ]
            [--script-valid | --script-invalid]
            (--tx-in TX-IN
              [ --spending-tx-in-reference TX-IN
                --spending-plutus-script-v2
                ( --spending-reference-tx-in-datum-cbor-file CBOR FILE
                | --spending-reference-tx-in-datum-file JSON FILE
                | --spending-reference-tx-in-datum-value JSON VALUE
                | --spending-reference-tx-in-inline-datum-present
                )
                ( --spending-reference-tx-in-redeemer-cbor-file CBOR FILE
                | --spending-reference-tx-in-redeemer-file JSON FILE
                | --spending-reference-tx-in-redeemer-value JSON VALUE
                )
                --spending-reference-tx-in-execution-units (INT, INT)
              | --simple-script-tx-in-reference TX-IN
              | --tx-in-script-file FILE
                [
                  ( --tx-in-datum-cbor-file CBOR FILE
                  | --tx-in-datum-file JSON FILE
                  | --tx-in-datum-value JSON VALUE
                  | --tx-in-inline-datum-present
                  )
                  ( --tx-in-redeemer-cbor-file CBOR FILE
                  | --tx-in-redeemer-file JSON FILE
                  | --tx-in-redeemer-value JSON VALUE
                  )
                  --tx-in-execution-units (INT, INT)]
              ])
            [--read-only-tx-in-reference TX-IN]
            [--tx-in-collateral TX-IN]
            [--tx-out-return-collateral ADDRESS VALUE]
            [--tx-total-collateral INTEGER]
            [--required-signer FILE | --required-signer-hash HASH]
            [--tx-out ADDRESS VALUE
              [ --tx-out-datum-hash HASH
              | --tx-out-datum-hash-cbor-file CBOR FILE
              | --tx-out-datum-hash-file JSON FILE
              | --tx-out-datum-hash-value JSON VALUE
              | --tx-out-datum-embed-cbor-file CBOR FILE
              | --tx-out-datum-embed-file JSON FILE
              | --tx-out-datum-embed-value JSON VALUE
              | --tx-out-inline-datum-cbor-file CBOR FILE
              | --tx-out-inline-datum-file JSON FILE
              | --tx-out-inline-datum-value JSON VALUE
              ]
              [--tx-out-reference-script-file FILE]]
            [--mint VALUE
              ( --mint-script-file FILE
                [
                  ( --mint-redeemer-cbor-file CBOR FILE
                  | --mint-redeemer-file JSON FILE
                  | --mint-redeemer-value JSON VALUE
                  )
                  --mint-execution-units (INT, INT)]
              | --simple-minting-script-tx-in-reference TX-IN --policy-id HASH
              | --mint-tx-in-reference TX-IN
                --mint-plutus-script-v2
                ( --mint-reference-tx-in-redeemer-cbor-file CBOR FILE
                | --mint-reference-tx-in-redeemer-file JSON FILE
                | --mint-reference-tx-in-redeemer-value JSON VALUE
                )
                --mint-reference-tx-in-execution-units (INT, INT)
                --policy-id HASH
              )]
            [--invalid-before SLOT]
            [--invalid-hereafter SLOT]
            [--fee LOVELACE]
            [--certificate-file CERTIFICATEFILE
              [ --certificate-script-file FILE
                [
                  ( --certificate-redeemer-cbor-file CBOR FILE
                  | --certificate-redeemer-file JSON FILE
                  | --certificate-redeemer-value JSON VALUE
                  )
                  --certificate-execution-units (INT, INT)]
              | --certificate-tx-in-reference TX-IN
                --certificate-plutus-script-v2
                ( --certificate-reference-tx-in-redeemer-cbor-file CBOR FILE
                | --certificate-reference-tx-in-redeemer-file JSON FILE
                | --certificate-reference-tx-in-redeemer-value JSON VALUE
                )
                --certificate-reference-tx-in-execution-units (INT, INT)
              ]]
            [--withdrawal WITHDRAWAL
              [ --withdrawal-script-file FILE
                [
                  ( --withdrawal-redeemer-cbor-file CBOR FILE
                  | --withdrawal-redeemer-file JSON FILE
                  | --withdrawal-redeemer-value JSON VALUE
                  )
                  --withdrawal-execution-units (INT, INT)]
              | --withdrawal-tx-in-reference TX-IN
                --withdrawal-plutus-script-v2
                ( --withdrawal-reference-tx-in-redeemer-cbor-file CBOR FILE
                | --withdrawal-reference-tx-in-redeemer-file JSON FILE
                | --withdrawal-reference-tx-in-redeemer-value JSON VALUE
                )
                --withdrawal-reference-tx-in-execution-units (INT, INT)
              ]]
            [--json-metadata-no-schema | --json-metadata-detailed-schema]
            [--auxiliary-script-file FILE]
            [--metadata-json-file FILE | --metadata-cbor-file FILE]
            [--protocol-params-file FILE]
            [--update-proposal-file FILE]
            --out-file FILE

  Build a transaction (low-level, inconvenient)

  Please note the order of some cmd options is crucial. If used incorrectly may produce undesired tx body. See nested [] notation above for details.

ERROR: failure during pool modify!

press any key to proceed ..
"

Many thanks for your help! =)

Best regards,
Philip
SPO for SVRN

**Comment by rdlrt** [comment]
https://t.me/guild_operators_official/63
