### ISSUE TITLE
libsodium version preventing 8.1.1 compiling

### ISSUE THREAD

**Issue by adavault** [cardano-community/guild-operators#1660]
**Describe the bug**
Using the latest scripts it was not possible to get the node to compile without separately building a new version of libsodium.
The version provided by the scripts does not work.

To correct the issue

```
cd git
git clone https://github.com/input-output-hk/libsodium
cd libsodium
git fetch --tags --all
git checkout dbb48cc
./autogen.sh
./configure
make
sudo make install
```

Then follow build instructions

**To Reproduce**
1. Follow guild instructions and attempt to compile node
2. Fails when building cardano node
3. Install correct libsodium version
4. Build successfully
5. See error from step 2
```
home/cardano/.cabal/store/ghc-8.10.7/cardano-crypto-praos-2.1.2.0-3665a2444452565d86335fe527ffb30a40b8f0c82ad16f51f7ad140e0105c385/lib/libHScardano-crypto-praos-2.1.2.0-3665a2444452565d86335fe527ffb30a40b8f0c82ad16f51f7ad140e0105c385.a(PraosBatchCompat.o):ghc_18.c:function cardanozmcryptozmpraoszm2zi1zi2zi0zm3665a2444452565d86335fe527ffb30a40b8f0c82ad16f51f7ad140e0105c385_CardanoziCryptoziVRFziPraosBatchCompat_zdwskFromBytes_info: error: undefined reference to 'crypto_vrf_ietfdraft13_secretkeybytes'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build exe:cardano-cli from cardano-cli-8.1.1.
Failed to build exe:cardano-node from cardano-node-8.1.1.
Failed to build exe:cardano-submit-api from cardano-submit-api-3.1.2.
```

**Expected behavior**
Successful build

**Screenshots**

**Version:**
 - OS: Ubuntu 20.04LTS
 - Product version: n/a (latest from repo)
 - Cardano Node version: 8.1.1
 - Network you're connecting to: n/a

**Additional context**
Attempted to download correct libsodium in advance of build using:
./guild-deploy.sh -n preprod -s pbl

**Comment by rdlrt** [comment]
This would typically occur when you did not source your bashrc after running guild-deploy, as mentioned in the [instructions](https://cardano-community.github.io/guild-operators/basics/#os-prereqs) , as you would then not have LD_LIBRARY_PATH referred to libsodium install location (i.e. /usr/local/lib) :
![image](https://github.com/cardano-community/guild-operators/assets/3169068/9acc504b-4d20-4719-96db-6cabd882fa91)

**Comment by adavault** [comment]
Appreciate the quick response. Just tested again- on a node that was also last built using 1.35.7, didn't specify that I sourced bashrc, but that was done before as well. Same issue when compiling. But thanks to your feedback have worked out the issue. For some reason the script (at some point?) was incorrectly setting LD_LIBRARY_PATH in bashrc to:
`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`
Which of course didn't work. Once corrected to
`export LD_LIBRARY_PATH=/usr/local/lib`
then it was possible to ls $LD_LIBRARY_PATH but it still doesn't compile and the sizes of the files in from your versions are different to the version that works.

Working
```
ll $LD_LIBRARY_PATH
total 13380
drwxr-xr-x  4 root root     4096 Jun 21 17:22 ./
drwxr-xr-x 10 root root     4096 Apr 23  2020 ../
-rw-r--r--  1 root root  1779872 Jun 21 16:26 libsecp256k1.a
-rwxr-xr-x  1 root root      961 Jun 21 16:26 libsecp256k1.la*
lrwxrwxrwx  1 root root       21 Jun 21 16:26 libsecp256k1.so -> libsecp256k1.so.0.0.0*
lrwxrwxrwx  1 root root       21 Jun 21 16:26 libsecp256k1.so.0 -> libsecp256k1.so.0.0.0*
-rwxr-xr-x  1 root root  1594936 Jun 21 16:26 libsecp256k1.so.0.0.0*
-rw-r--r--  1 root root  6525222 Jun 21 17:22 libsodium.a
-rwxr-xr-x  1 root root      959 Jun 21 17:22 libsodium.la*
lrwxrwxrwx  1 root root       19 Jun 21 17:22 libsodium.so -> libsodium.so.23.3.0*
lrwxrwxrwx  1 root root       19 Jun 21 17:22 libsodium.so.23 -> libsodium.so.23.3.0*
-rwxr-xr-x  1 root root  3765096 Jun 21 17:22 libsodium.so.23.3.0*
```

Non working from guild...
```
ll $LD_LIBRARY_PATH
total 13284
drwxr-xr-x  4 root root     4096 Jun 22 10:28 ./
drwxr-xr-x 10 root root     4096 Apr 23  2020 ../
-rw-r--r--  1 root root  1779872 Jun 22 10:28 libsecp256k1.a
-rwxr-xr-x  1 root root      961 Jun 22 10:28 libsecp256k1.la*
lrwxrwxrwx  1 root root       21 Jun 22 10:28 libsecp256k1.so -> libsecp256k1.so.0.0.0*
lrwxrwxrwx  1 root root       21 Jun 22 10:28 libsecp256k1.so.0 -> libsecp256k1.so.0.0.0*
-rwxr-xr-x  1 root root  1594936 Jun 22 10:28 libsecp256k1.so.0.0.0*
-rw-r--r--  1 root root  6475308 Jun 22 10:28 libsodium.a
-rwxr-xr-x  1 root root      959 Jun 22 10:28 libsodium.la*
lrwxrwxrwx  1 root root       19 Jun 22 10:28 libsodium.so -> libsodium.so.23.3.0*
lrwxrwxrwx  1 root root       19 Jun 22 10:28 libsodium.so.23 -> libsodium.so.23.3.0*
-rwxr-xr-x  1 root root  3723112 Jun 22 10:28 libsodium.so.23.3.0*
```

Puzzled now...any thoughts? Am I missing something obvious?

**Comment by adavault** [comment]
Ok, so just went into ~/git and deleted the libsodium directory. Ran `./guild-deploy.sh -n preprod -s pbl` again, and this time the versions in $LD_LIBRARY_PATH matched. And of course it now compiles.

So I don't understand why that worked. Was it not overwriting the previous version that would have been present?

I will check on another node and see if can figure out, perms perhaps?

**Comment by rdlrt** [comment]
Hmm - that's a good point, we could potentially add a git fetch to that line to ensure the commit is not unknown if folder already exists
