### ISSUE TITLE
using using the guild-deploy.sh script fails on RHEL 8.8 with no such repo

### ISSUE THREAD

**Issue by rob-grokism** [cardano-community/guild-operators#1668]
**Describe the bug**
When running guild-deploy.sh the install fails with no such repo...[robert@cablprev1 tmp]$ ./guild-deploy.sh -n preview -s lfd

failing with the latest guild-deploy.sh file

Preparing OS dependency packages for "Red Hat Enterprise Linux" system

  Updating system packages...

  Enabling epel repository...

  Symlink updates not required for ncurse libs, skipping..

  Installing missing prerequisite packages, if any..
Error: Unknown repo: 'devel'

An error occurred while installing the prerequisite packages, please investigate by using the command below:

  sudo yum -y --allowerasing install python3 coreutils ncurses-devel ncurses-libs openssl-devel systemd systemd-devel libsodium-devel tmux git jq gnupg2 libtool iproute bc traceroute sqlite util-linux xz wget unzip procps-ng llvm clang numactl-devel libffi-devel gmp-devel zlib-devel make gcc-c++ autoconf udev lmdb-devel --enablerepo=devel,crb libusbx ncurses-compat-libs pkgconf-pkg-config

It would be best if you could submit an issue at https://github.com/cardano-community/guild-operators with the details to tackle in future, as some errors may be due to external/already present dependencies
ERROR:

The error can be reproduced every time.

**Expected behavior**
Everything works as expected with the other associated OS's  Fedora server, Rocky Linux but with RHEL 8.8 it always fails with the above error.

v211       #RHEL/CentOS/RockyLinux8
212       pkg_opts="${pkg_opts} --allowerasing"
213       pkg_list="${pkg_list} --enablerepo=devel,crb libusbx ncurses-compat-libs pkgconf-pkg-config"
214     elif [[ "${DISTRO}" =~ Fedora ]]; then

The problem can be overcome by editing the guild-deploy.sh line 213 in the below way

212       pkg_opts="${pkg_opts} --allowerasing"
213       pkg_list="${pkg_list} --enablerepo=codeready-builder-for-rhel-8-x86_64-rpms libusbx ncurses-compat-libs pkgconf-pkg-config"
214     elif [[ "${DISTRO}" =~ Fedora ]]; then

Ultimately there is no such repos as crb and devel in RHEL  

sudo dnf config-manager --set-enabled crb
Updating Subscription Management repositories.
Error: No matching repo to modify: crb.

devel does not exist in RHEL 8.8 either.  Same problem...The solution is to make sure that the epel repository is enabled and then to enable codeready-builder-for-rhel-8-x86_64-rpms This will allow all of the system prereqs that are required.

I am trying to install an an enterprise level node pool with RHEL 8.8, jumpcloud and would like to use RHEL for the nodes.  It I edit the guild-deploy.sh script in the above manner and use the skip the updating of the script with the -u option everything works.
[robert@cablprev1 tmp]$ ./guild-deploy.sh -n preview -u -s pblfd

Regards,
Rob Phillips
robert@grokism.com
St. Paul MN

**Comment by rob-grokism** [comment]
sudo yum -y --allowerasing install python3 coreutils ncurses-devel ncurses-libs openssl-devel systemd systemd-devel libsodium-devel tmux git jq gnupg2 libtool iproute bc traceroute sqlite util-linux xz wget unzip procps-ng llvm clang numactl-devel libffi-devel gmp-devel zlib-devel make gcc-c++ autoconf udev lmdb-devel libusbx ncurses-compat-libs pkgconf-pkg-config
Updating Subscription Management repositories.
Last metadata expiration check: 0:22:39 ago on Sat 29 Jul 2023 03:03:48 PM CDT.
Package python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64 is already installed.
Package coreutils-8.30-15.el8.x86_64 is already installed.
Package ncurses-devel-6.1-9.20180224.el8.x86_64 is already installed.
Package ncurses-libs-6.1-9.20180224.el8.x86_64 is already installed.
Package openssl-devel-1:1.1.1k-9.el8_7.x86_64 is already installed.
Package systemd-239-74.el8_8.2.x86_64 is already installed.
Package systemd-devel-239-74.el8_8.2.x86_64 is already installed.
Package libsodium-devel-1.0.18-2.el8.x86_64 is already installed.
Package tmux-2.7-1.el8.x86_64 is already installed.
Package git-2.39.3-1.el8_8.x86_64 is already installed.
Package jq-1.6-6.el8.x86_64 is already installed.
Package gnupg2-2.2.20-3.el8_6.x86_64 is already installed.
Package libtool-2.4.6-25.el8.x86_64 is already installed.
Package iproute-5.18.0-1.1.el8_8.x86_64 is already installed.
Package bc-1.07.1-5.el8.x86_64 is already installed.
Package traceroute-3:2.1.0-6.el8.x86_64 is already installed.
Package sqlite-3.26.0-18.el8_8.x86_64 is already installed.
Package util-linux-2.32.1-42.el8_8.x86_64 is already installed.
Package xz-5.2.4-4.el8_6.x86_64 is already installed.
Package wget-1.19.5-11.el8.x86_64 is already installed.
Package unzip-6.0-46.el8.x86_64 is already installed.
Package procps-ng-3.3.15-13.el8.x86_64 is already installed.
Package llvm-15.0.7-1.module+el8.8.0+17939+b58878af.x86_64 is already installed.
Package clang-15.0.7-1.module+el8.8.0+17939+b58878af.x86_64 is already installed.
Package numactl-devel-2.0.12-13.el8.x86_64 is already installed.
Package libffi-devel-3.1-24.el8.x86_64 is already installed.
Package gmp-devel-1:6.1.2-10.el8.x86_64 is already installed.
Package zlib-devel-1.2.11-21.el8_7.x86_64 is already installed.
Package make-1:4.2.1-11.el8.x86_64 is already installed.
Package gcc-c++-8.5.0-18.el8.x86_64 is already installed.
Package autoconf-2.69-29.el8.noarch is already installed.
Package systemd-udev-239-74.el8_8.2.x86_64 is already installed.
Package lmdb-devel-0.9.24-2.el8.x86_64 is already installed.
Package libusbx-1.0.23-4.el8.x86_64 is already installed.
Package ncurses-compat-libs-6.1-9.20180224.el8.x86_64 is already installed.
Package pkgconf-pkg-config-1.4.2-1.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by TrevorBenson** [comment]
I've opened a branch `crb-vs-code-ready-builder` which addresses this. Rocky 8/9 get devel,crb, rhel 8 gets codeready-builder for 8, and rhel 9 gets codeready-builder for 9.

I have not opened a PR until I get around to testing it. However @rob-grokism if you would like to test and confirm by adding`-b crb-vs-code-ready-builder` to your `./guild-deploy.sh` flags and report back it resolves this issue, I'll open the PR to have it merged into alpha. Otherwise I'll test it out in the coming week and open a PR.

**Comment by rob-grokism** [comment]
Beautiful...I will test today...thanks so much.

Regards,
Rob Phillips

**Comment by rob-grokism** [comment]
This worked beautifully with the exception that line 210 needed to have the
or "||"  added.

***@***.*** tmp]$ ./guild-deploy.sh -n preview -b
crb-vs-code-ready-builder -s plfd
./guild-deploy.sh: line 210: syntax error in conditional expression
./guild-deploy.sh: line 210: syntax error near `]][['
./guild-deploy.sh: line 210: `    elif [[ "${VERSION_ID}" =~ "8" ]][[
"${VERSION_ID}" =~ "9" ]]; then'

Once the or was added
210     elif [[ "${VERSION_ID}" =~ "8" ]] || [[ "${VERSION_ID}" =~ "9" ]];
then

***@***.*** tmp]$ ./guild-deploy.sh -n preview -u -s plfd
Preparing OS dependency packages for "Red Hat Enterprise Linux" system
  Updating system packages...
  Enabling epel repository...
  Symlink updates not required for ncurse libs, skipping..
  Installing missing prerequisite packages, if any..
Installing Haskell build/compiler dependencies (if missing)...
 Uninstalling Cabal v3.6.2.0 ..
 Installing Cabal v3.10.1.0..
[Re]-Install libsecp256k1 ...
libsecp256k1 installed to /usr/local/lib/
Building libsodium ...
IOG fork of libsodium installed to /usr/local/lib/
Downloading files...
Forced full upgrade! Please edit scripts/env, scripts/cnode.sh,
scripts/dbsync.sh, scripts/submitapi.sh, scripts/ogmios.sh,
scripts/gLiveView.sh and scripts/topologyUpdater.sh (alongwith
files/topology.json, files/config.json, files/dbsync.json) as required!
Downloading binaries..
  Downloading Cardano Node archive created from IO CI builds..
  Downloading Github release package for Cardano Wallet
  Downloading Cardano DB Sync archive created from IO CI Builds..

Regards,
Rob Phillips

**Comment by rob-grokism** [comment]
So...add the "||" on line 210.  Otherwise everything works as expected with
the -b  crb-vs-code-ready-builder options

Regards,
Rob Phillips
