### ISSUE TITLE
Please do not allow automatic upgrade if the detected node version wouldn't be supported

### ISSUE THREAD

**Issue by Quantumplation** [cardano-community/guild-operators#1669]
The guild operators scripts are great, and make operating my pool much easier.

However, the following has happened to me multiple times now:
- I'm holding off on upgrading my node for one reason or another
- The cnode scripts prompt me to auto-update
- I accidentally approve the auto-update
- They are now broken until I upgrade my node, potentially with awkward timing.

Please don't prompt to auto-upgrade if doing so will upgrade to scripts that don't support the installed node version.

**Comment by rdlrt** [comment]
When going through an update with higher node version, there is usually an announcement warning. But considerations below:
1. Older tag that can be used for those who havent upgraded (for instance, you have `node-1.35.7`), you can use `./gLiveView.sh -b node-1.35.7` and the update will be reverted back.
2. There is `UPDATE_CHECK` variable in env file that can be set to N to prevent auto updates.
3. The default mode is to check for updates based on poll results (with >90℅ SPOs voting for yes) in guild announcements channel.

Happy to hear further opinions from you with above considered

**Comment by Quantumplation** [comment]
Oo, those are both really good to know and mostly solve my problem;

Could we include the downgrade command in the "we don't support this node version" error message to make it clearer?

For example, I was on node 1.35.5 and wasn't quite ready to upgrade, but the gLiveView and cnode.sh scripts upgraded on accident; I wasn't sure how to reliably and safely downgrade, so it seemed like the safest option was to panic upgrade to 8.1.2 before my next block was produced; only got everything working with 3 minutes to spare.

If the error message that said "we only support 8.1.2" included "If you'd like to downgrade this script temporarily, run XYZ", that would have saved me a lot of anxiety and headache 😅

**Comment by rdlrt** [comment]
We do make that clarification in announcements channel, but indeed - easy to change message itself , will do 👍🏻
