### ISSUE TITLE
[CNTOOLS] all pools get deleted if you enter a blank pool name

### ISSUE THREAD

**Issue by papacarp** [cardano-community/guild-operators#168]
I  just had all my pool folders get deleted when I went to create a new pool and then abandoned.  I was unable to exit the command.  I think we should detect a blank pool name and just exit rather than continuing to create the pool and asking for a password.

I suspect this area is deleting all pool entries:

https://github.com/cardano-community/guild-operators/blob/5ed849e2e8fb703ae430407fd9518e719bbe5b67/scripts/cnode-helper-scripts/cntools.sh#L1148

https://github.com/cardano-community/guild-operators/blob/5ed849e2e8fb703ae430407fd9518e719bbe5b67/scripts/cnode-helper-scripts/cntools.sh#L1153

Wallets might have a similar issue

**Comment by Scitz0** [comment]
Good catch, should definitely not allow empty pool or wallet names.
