### ISSUE TITLE
Getting error while installing dependencies for cardano node setup and install and configure LLVM:

### ISSUE THREAD

**Issue by SamirBitzees** [cardano-community/guild-operators#1686]
**Describe the bug**
When I was installing "sudo apt install llvm-9" I was getting error 
E: Package 'clang-9' has no installation candidate
ln: failed to create symbolic link '/usr/bin/llvm-config': File exists
ln: failed to create symbolic link '/usr/bin/opt': File exists
ln: failed to create symbolic link '/usr/bin/llc': File exists
ln: failed to create symbolic link '/usr/bin/clang': File exists
E: Unable to locate package llvm-9

So i checked with which llvm installation candidate is available using this command (apt list 'llvm-*' 'clang-*') so I found out that 
 multiple versions of LLVM and Clang installed on my system, including versions 11, 12, 13, 14, and 15. So i tried with LLVM 11
version.

ubuntu@ip-172-31-18-203:~/cardano-src/cardano-node$ sudo apt install llvm-11
sudo apt install clang-11 libnuma-dev
sudo ln -s /usr/bin/llvm-config-11 /usr/bin/llvm-config
sudo ln -s /usr/bin/opt-11 /usr/bin/opt
sudo ln -s /usr/bin/llc-11 /usr/bin/llc
sudo ln -s /usr/bin/clang-11 /usr/bin/clang
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
llvm-11 is already the newest version (1:11.1.0-6).
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libnuma-dev is already the newest version (2.0.14-3ubuntu2).
The following additional packages will be installed:
  libclang-common-11-dev libclang1-11
Suggested packages:
  clang-11-doc
The following NEW packages will be installed:
  clang-11 libclang-common-11-dev libclang1-11
0 upgraded, 3 newly installed, 0 to remove and 5 not upgraded.
Need to get 9143 kB of archives.
After this operation, 70.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ap-south-2c.clouds.ports.ubuntu.com/ubuntu-ports jammy/universe arm64 libclang-common-11-dev arm64 1:11.1.0-6 [3743 kB]
Get:2 http://ap-south-2c.clouds.ports.ubuntu.com/ubuntu-ports jammy/universe arm64 libclang1-11 arm64 1:11.1.0-6 [5328 kB]
Get:3 http://ap-south-2c.clouds.ports.ubuntu.com/ubuntu-ports jammy/universe arm64 clang-11 arm64 1:11.1.0-6 [71.3 kB]
Fetched 9143 kB in 2s (4003 kB/s)   
Selecting previously unselected package libclang-common-11-dev.
(Reading database ... 80198 files and directories currently installed.)
Preparing to unpack .../libclang-common-11-dev_1%3a11.1.0-6_arm64.deb ...
Unpacking libclang-common-11-dev (1:11.1.0-6) ...
Selecting previously unselected package libclang1-11.
Preparing to unpack .../libclang1-11_1%3a11.1.0-6_arm64.deb ...
Unpacking libclang1-11 (1:11.1.0-6) ...
Selecting previously unselected package clang-11.
Preparing to unpack .../clang-11_1%3a11.1.0-6_arm64.deb ...
Unpacking clang-11 (1:11.1.0-6) ...
Setting up libclang1-11 (1:11.1.0-6) ...
Setting up libclang-common-11-dev (1:11.1.0-6) ...
Setting up clang-11 (1:11.1.0-6) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.3) ...
Scanning processes...                                                                                                
Scanning candidates...                                                                                               
Scanning linux images...                                                                                             

Running kernel seems to be up-to-date.

Restarting services...
Service restarts being deferred:
 /etc/needrestart/restart.d/dbus.service
 systemctl restart getty@tty1.service
 systemctl restart networkd-dispatcher.service
 systemctl restart systemd-logind.service
 systemctl restart unattended-upgrades.service
 systemctl restart user@1000.service

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
ln: failed to create symbolic link '/usr/bin/llvm-config': File exists
ln: failed to create symbolic link '/usr/bin/opt': File exists
ln: failed to create symbolic link '/usr/bin/llc': File exists
ln: failed to create symbolic link '/usr/bin/clang': File exists

**I thought I did installation of llvm successfully but not u can see exact above this line it fail.**
And because of my unawareness I tried with 
"cabal update 
cabal build all"

But I got error after doing this and log is as  follows
Starting     SHA-1.6.4.4 (lib)
Building     SHA-1.6.4.4 (lib)

Failed to build Diff-0.4.1.
Build log (
/home/ubuntu/.cabal/logs/ghc-8.10.7/Diff-0.4.1-db2716129a4704530300596c44f8a6b9667b33e9573853e516679db2c45e87f3.log
):
Configuring library for Diff-0.4.1..
Preprocessing library for Diff-0.4.1..
Building library for Diff-0.4.1..
[1 of 3] Compiling Data.Algorithm.Diff ( src/Data/Algorithm/Diff.hs, dist/build/Data/Algorithm/Diff.o, dist/build/Data/Algorithm/Diff.dyn_o )

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
ghc: could not execute: opt

Failed to build FailT-0.1.2.0.
Build log (
/home/ubuntu/.cabal/logs/ghc-8.10.7/FailT-0.1.2.0-88f9d260bb378bcafc3becc32db88001798ebb683db5798a85e3e9d431375056.log
):
Configuring library for FailT-0.1.2.0..
Preprocessing library for FailT-0.1.2.0..
Building library for FailT-0.1.2.0..

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
[1 of 3] Compiling Control.Monad.Trans.Fail ( src/Control/Monad/Trans/Fail.hs, dist/build/Control/Monad/Trans/Fail.o, dist/build/Control/Monad/Trans/Fail.dyn_o )

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
ghc: could not execute: opt

Failed to build Only-0.1.
Build log (
/home/ubuntu/.cabal/logs/ghc-8.10.7/Only-0.1-b6d402f4cc46acbe5b22140727a706a23a0958ba12732d35035cd1666085f683.log
):
Configuring library for Only-0.1..
Preprocessing library for Only-0.1..
Building library for Only-0.1..
[1 of 1] Compiling Data.Tuple.Only  ( src/Data/Tuple/Only.hs, dist/build/Data/Tuple/Only.o, dist/build/Data/Tuple/Only.dyn_o )

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
ghc: could not execute: opt

Failed to build PyF-0.11.1.1.
Build log (
/home/ubuntu/.cabal/logs/ghc-8.10.7/PyF-0.11.1.1-6490b46f533d1714bb916c327f6a469a82e5699358ba205a10f7cc352dd25b93.log):
Configuring library for PyF-0.11.1.1..
Preprocessing library for PyF-0.11.1.1..
Building library for PyF-0.11.1.1..

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
[1 of 8] Compiling PyF.Formatters   ( src/PyF/Formatters.hs, dist/build/PyF/Formatters.o, dist/build/PyF/Formatters.dyn_o )

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
ghc: could not execute: opt

Failed to build SHA-1.6.4.4.
Build log (
/home/ubuntu/.cabal/logs/ghc-8.10.7/SHA-1.6.4.4-4e68f0e534d497a93ece86c0f8b5fd73abfb356a120cf37d40f3f3e50bfde19c.log
):
Configuring library for SHA-1.6.4.4..
Preprocessing library for SHA-1.6.4.4..
Building library for SHA-1.6.4.4..

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
[1 of 1] Compiling Data.Digest.Pure.SHA ( src/Data/Digest/Pure/SHA.hs, dist/build/Data/Digest/Pure/SHA.o, dist/build/Data/Digest/Pure/SHA.dyn_o )

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)
ghc: could not execute: opt
cabal: Failed to build Diff-0.4.1 (which is required by test:test-locli from
locli-1.29, test:cardano-testnet-test from cardano-testnet-8.1.0 and others).
See the build log above for details.
Failed to build FailT-0.1.2.0 (which is required by test:tx-generator-test
from tx-generator-2.5, test:tx-generator-apitest from tx-generator-2.5 and
others). See the build log above for details.
Failed to build Only-0.1 (which is required by test:test-locli from
locli-1.29, exe:locli from locli-1.29 and others). See the build log above for
details.
Failed to build PyF-0.11.1.1 (which is required by test:cardano-testnet-test
from cardano-testnet-8.1.0, test:cardano-cli-test from cardano-cli-8.1.2 and
others). See the build log above for details.
Failed to build SHA-1.6.4.4 (which is required by exe:demo-forwarder from
cardano-tracer-0.1.0, exe:demo-acceptor from cardano-tracer-0.1.0 and others).
See the build log above for details.

So suggest me how can i install all dependencies for cardano node setup and how to resolve above error.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - OS: [e.g. CentOS 8]
 - Product version: [e.g. CNTools 5.0.1]
 - Cardano Node version: [e.g. output of `cardano-node version`]
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]

**Additional context**

**Comment by rdlrt** [comment]
I dont see this the error you reached was while following documentation on [guild-operators](https://cardano-community.github.io/guild-operators/) , I does see doco asking for specific llvm (nor is it referred inguild-deploy script, we use `llvm
