### ISSUE TITLE
Pre-merge check failure for ogmios deployments

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#1704]
**Describe the bug**
Ogmios deployment fails with the following errors during premerge (and local testing from master branch):
```
> Pre-merge check failure appears to be ogmios based:
> 
> ```
> 280.8 Installing Ogmios
> 115
> 281.3 curl: no URL specified!
> 116
> 281.3 curl: try 'curl --help' for more information
> 117
> 281.3 ERROR: Download of latest release of ogmios archive from GitHub failed! Please retry or manually install it.
> ```
> 
```
> I can see the ogmios_asset_url curl returns. However the json from api.github.com does not appear to have the **assets key**, but does have an **assets_url**. I suspect the API implemented a change to the data structure, breaking ogmios setup.

**To Reproduce**
1. Follow Guild docs Basics section
2. Include ogmios deployment with `-s o` 
3. Observe error

**Expected behavior**
Ogmios deploys without errors.

**Screenshots**

**Version:**
 - OS: RHEL 9
 - Product version: ./guild-deploy.sh from master branch as of commit 0f0b938
 - Cardano Node version: N/A
 - Network you're connecting to: N/A (mainnet)

**Additional context**

Took a closer look during lunch and it seems that **browser_download_url** exists, however, it is no longer in the response's first indice of the first list.

```
$ curl -s https://api.github.com/repos/CardanoSolutions/ogmios/releases | jq '.[0].assets[].browser_download_url'
[guild@rhel92 tmp]$ 
```

It is now part of the second (1) indice of the first list `.[1].assets.browser_download_url`:

```
curl -s https://api.github.com/repos/CardanoSolutions/ogmios/releases | jq '.[1].assets[].browser_download_url'
"https://github.com/CardanoSolutions/ogmios/releases/download/v6.0.0-rc4/ogmios-v6.0.0-rc4-x86_64-linux.zip"
[guild@rhel92 tmp]$ 
```

**Comment by TrevorBenson** [comment]
> > it is now part of the second (1) indice of the first list `.[1].assets.browser_download_url`:
> 
> That is simply because the pre-compiled artefacts for ogmios have not yet been uploaded, outside of current PR's scope

@rdlrt Not sure I understand. Do you mean between each release there are moments where the ogmios_assets_url will fail to obtain a url and breaks the `guild-deploy.sh` script's deployment?

**Comment by rdlrt** [comment]
> Do you mean between each release there are moments where the ogmios_assets_url will fail to obtain a url and breaks the guild-deploy.sh script's deployment?

yip  - we should ideally loop through asset URL list for ogmios

**Comment by rdlrt** [comment]
Closed in commit [7f8ca9b](https://github.com/cardano-community/guild-operators/commit/7f8ca9bb3166b74b838e1c70f27535a0b4dc7f4f)

**Comment by TrevorBenson** [comment]
> Closed in commit [7f8ca9b](https://github.com/cardano-community/guild-operators/commit/7f8ca9bb3166b74b838e1c70f27535a0b4dc7f4f)

Commit 7f8ca9bb3166b74b838e1c70f27535a0b4dc7f4f did not address the Ogmios issue from what I can tell. For example, PR #1707 fails to build unless the `o` option is removed from `dockerfile_bin`. I had intended to submit a workaround with fallback logic in case there are extended periods (like now) where artifacts are not published and are break deployments.

@rdlrt Is the preference to keep the Ogmios logic as it is, letting it cause deployment failures? If not I will reopen this issue and submit a PR for review.

**Comment by rdlrt** [comment]
PR #1707  did not have the commit for ogmios fix, it was amended to that commit later

**Comment by TrevorBenson** [comment]
> PR #1707  did not have the commit for ogmios fix, it was amended to that commit later

Sorry, my mistake meant #1703 not #1707 (the current PR). 

I see the added commit with `| grep linux.zip | head -1`, I hadn't realized that was still in alpha while tests were against master branch.
