### ISSUE TITLE
OPCert of gliveView1.28.0 is not displayed

### ISSUE THREAD

**Issue by btbf** [cardano-community/guild-operators#1706]
If i build a pool without using CNTOOL, the directory hierarchy will be different.
However, the paths of pool_id_file and pool_coldkey_vk_file to obtain the OPCert value are hard-coded in the CNTool-specific hierarchy.

For Example
In this case, you need to change the file name for bech32.
[${POOL_FOLDER}/${1}/${POOL_ID_FILENAME}-bech32]
https://github.com/cardano-community/guild-operators/blob/886d1a0ca1b8af81a367845a8963d24262dc5233/scripts/cnode-helper-scripts/env#L720-L721

The pool name is included in the argument, but if the directory structure does not look like this, you will need to change it.
https://github.com/cardano-community/guild-operators/blob/886d1a0ca1b8af81a367845a8963d24262dc5233/scripts/cnode-helper-scripts/env#L725

I want POOL_DIR to be in the user variable at the top
https://github.com/cardano-community/guild-operators/blob/886d1a0ca1b8af81a367845a8963d24262dc5233/scripts/cnode-helper-scripts/gLiveView.sh#L517
https://github.com/cardano-community/guild-operators/blob/886d1a0ca1b8af81a367845a8963d24262dc5233/scripts/cnode-helper-scripts/env#L808

Please let me know if I'm wrong about this content.

i am verifying it on the prepro testnet, and the koios api specifies the preprod endpoint.

**Comment by Scitz0** [comment]
Hi, I will think of a way to make gLiveView independent from normal guild folder structure. But we cant use POOL_DIR for this function as its common between gLiveView and CNTools, and for CNTools its not only used for active pool, but you can manage multiple pools through CNTools, hence it needs to take pool name as input and construct the pool dir path this way. One option would be to add a new user variable in gLiveView to override the default path constructed.

**Comment by btbf** [comment]
Thank you for your comment.
What I wanted to tell you is that if you can set the POOL_DIR variable arbitrarily in the env user variable, you can display op cert without breaking the dependency with CNTool.

env file User Variables area
```
~~~
#POOL_NAME=""
#POOL_DIR="${POOL_FOLDER}/${POOL_NAME}"
~~~
```

However, I need the pool ID to display the on-chain data and would like to get this with an arbitrary PoolID file path.
Would it be difficult?

**Comment by rdlrt** [comment]
@btbf - please test the latest commit (gLV version bumped to 1.28.1)

**Comment by btbf** [comment]
@rdlrt Thank you for your response.
I tested the latest commit and it worked fine.

![image](https://github.com/cardano-community/guild-operators/assets/37224549/6d80920b-881b-4c0f-bfb8-935d8e1c679e)
