### ISSUE TITLE
cntools leaderlogs wrong for epoch 470

### ISSUE THREAD

**Issue by chrispalaskas** [cardano-community/guild-operators#1737]
**Describe the bug**
CNTools leaderlogs produce wrong results starting from epoch 470

**To Reproduce**
1. Run cntools.sh
2. Go to blocks
3. Choose epoch
4. Enter 470

**Expected behavior**
CNTools leadlog calculations were so far accurate.

**Screenshots**
![epoch470](https://github.com/cardano-community/guild-operators/assets/16150124/5c198f6a-86d8-486d-acef-d2cf190aa7e6)
But reality:
cardano-cli query leadership-schedule     --mainnet     --genesis /opt/cardano/cnode/files/shelley-genesis.json     --stake-pool-id $(cat /home/chruskal/keys/pool.id)     --vrf-signing-key-file /home/chruskal/keys/vrf.skey     --current
     SlotNo                          UTC Time
-------------------------------------------------------------
     117827197                   2024-03-02 15:31:28 UTC
     117879873                   2024-03-03 06:09:24 UTC

**Version:**
 - OS: Ubuntu 22.04
 - Product version: CNTools v12.0.2 (branch: master)
 - Cardano Node version: cardano-node 8.7.3
 - Network you're connecting to: mainnet

**Additional context**

**Comment by chrispalaskas** [comment]
This is concerning ASKP pool, with:
ID (hex)              : a4b576a73fd6342c0ce8e44a040686b0e0ad54932df6724efd2364b3
ID (bech32)           : pool15j6hdfel6c6zcr8gu39qgp5xkrs264yn9hm8ynhaydjtxvmznxq

**Comment by rdlrt** [comment]
Please contribute your cncli.db to issue [here](https://github.com/cardano-community/cncli/issues/44) to help with troubleshooting. I see that a few folks have mentioned deleting CNCLI DB and using CNCLI 6.0.3 to sync sorted the issue for them

**Comment by chrispalaskas** [comment]
@rdlrt I see latest release is 6.0.1. https://github.com/cardano-community/cncli/releases
Is there another repository for CNCLI?

**Comment by rdlrt** [comment]
Yes - but specifically I linked raised issue on that repo in my reply above
