### ISSUE TITLE
8.9.1 docker image release contains 8.7.3 bins

### ISSUE THREAD

**Issue by Fuma419** [cardano-community/guild-operators#1748]
**Describe the bug**
The image released here may be mis labeled: https://hub.docker.com/layers/cardanocommunity/cardano-node/8.9.1/images/sha256-77899414b0f8935cd49359355a9aab43921255519c54e2dd76d1c8d1b2a47371?context=explore

in my testing this is a 8.7.3 release. 

**To Reproduce**
1. run 'docker pull cardanocommunity/cardano-node:8.9.1'
2. deploy containerized node on any network
4. docker exec -it cnode /bin/bash
5. cardano-node --version
```
$ docker inspect --format='{{.Config.Image}}' cnode
cardanocommunity/cardano-node:8.9.1
$ docker exec -it m_relay_1a /bin/bash

  _____     _ __   __  ____                    __             
 / ___/_ __(_) /__/ / / __ \___  ___ _______ _/ /____  _______
/ (_ / // / / / _  / / /_/ / _ \/ -_) __/ _ `/ __/ _ \/ __(_-<
\___/\_,_/_/_/\_,_/  \____/ .__/\__/_/  \_,_/\__/\___/_/ /___/
                         /_/ 
                         

Availbles tools:
- cntools
- gLiveView
- cncli and cncli.sh
  
   
guild@98a58aeb246c:~$ cardano-node --version
cardano-node 8.7.3 - linux-x86_64 - ghc-8.10
git rev a4a8119b59b1fbb9a69c79e1e6900e91292161e7
```
**Expected behavior**
see above

**Screenshots**
see above

**Version:**
 - OS: Ubuntu 22
 - Product version: [[e.g. CNTools 5.0.1]](https://hub.docker.com/layers/cardanocommunity/cardano-node/8.9.1/images/sha256-77899414b0f8935cd49359355a9aab43921255519c54e2dd76d1c8d1b2a47371?context=explore)
 - Cardano Node version: 8.7.3/8.9.1
 - Network you're connecting to: all

**Additional context**
Thank for all your tooling and efforts.

**Comment by Fuma419** [comment]
Ah I see. Reviewing the alpha commit timestamped just prior to this dockerhub deployment may offer some clues.

**Comment by Fuma419** [comment]
can this hub.docker release be pulled back or deleted? Other users will be waisting efforts trying to update to 8.9.1.

**Comment by Fuma419** [comment]
> Ah I see. Reviewing the alpha commit timestamped just prior to this dockerhub deployment may offer some clues.

wait, you said manual run. disregard

**Comment by TrevorBenson** [comment]
> can this hub.docker release be pulled back or deleted? Other users will be waisting time/efforts using it to update to 8.9.1.

Right after my response I requested the contributors with login access to delete the tag for 8.9.1 and latest. I'll recreate latest after that pointing back to the image w/ 8.7.3 as the tag.
