### ISSUE TITLE
Update documentation for forked repository building

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#1762]
For reference in case this thread gets reviewed in the future **G_BRANCH** logic is handled already. 

* The execution of `guild-deploy.sh` does a `echo "${BRANCH}" > "${CNODE_HOME}"/scripts/.env_branch`. 
  * Later execution will reuse `.env_branch`, unless the branch does not exist in which case it resets to use **master**

Setting of **G_ACCOUNT**:
* Exported in the shell
* Uncomment/set in `env`
* Uncomment/set in `guild-deploy.sh`

Ensures that **cardano-community** is not used. A forked repository simply sets **G_ACCOUNT** after building from a test/feature branch to persist the fork. As long as `UPDATE_CHECK=Y` configurations from the branch originally used will be where updates come from, unless:
* The branch is overridden manually using `guild-deploy.sh -b <BRANCH>`
* The branch is deleted
* The branch never existed in the fork set with G_ACCOUNT

In each case it will revert to **master**, but still use **G_ACCOUNT** if defined.

**Comment by TrevorBenson** [comment]
This might be nice to have in the docs for SPOs who do testing work in their forked repository. If nobody else adds this first I'll do it as time permits.

**Comment by rdlrt** [comment]
IMO - it feels slightly overkill to cater for such documentation page. You'd expect SPOs working off forks should atleast have enough knowledge to know how to examine the environment variables or URLs in env or guild-deploy.sh. To me , that is part of assumptions on the [home page](https://cardano-community.github.io/guild-operators/)

**Comment by TrevorBenson** [comment]
> IMO - it feels slightly overkill to cater for such documentation page. You'd expect SPOs working off forks should atleast have enough knowledge to know how to examine the environment variables or URLs in env or guild-deploy.sh. To me , that is part of assumptions on the [home page](https://cardano-community.github.io/guild-operators/)

That was actually my original thought when adding fork support in the Docker Image workflow and why no docs were added. I'll close this request as uneeded.
