### ISSUE TITLE
cntools transactions errors

### ISSUE THREAD

**Issue by yoann54** [cardano-community/guild-operators#1763]
**Describe the bug**
When using cntools i got transdactions errors.

**To Reproduce**
1. Using cntools on alpha branch 8.9.2

"transaction read error RawCborDecodeError [DecoderErrorDeserialiseFailure \"Byron Tx\" (DeserialiseFailure 0 \"end of input\"),DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\"),DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\"),DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\"),DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\"),DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\")]"

**Comment by rdlrt** [comment]
Closed in `cntools-light` branch
