### ISSUE TITLE
Cardano node 9.1.0 Slow shutdown

### ISSUE THREAD

**Issue by adavault** [cardano-community/guild-operators#1794]
**Describe the bug**
Cardano node 8.9.4 took approx 3 mins to start. After upgrade to 9.1.0 it now takes around 60 mins on equivalent setup. This is because the systemd definition created (or possibly in combination with exit logic in cnode.sh?) causes the node not to exit cleanly. Most likely it's because the exit timeouts (TimeoutStopSec=60) are now too short...

**To Reproduce**

1. Upgrade to 9.1.0
2. Allow node to convert existing ledger (approx 5 hours)
3. Allow to operate normally for 24 hours in case node needs to checkpoint ledger
4. Restart node using systemctl stop cnode...
5. Confirm /opt/cardano/cnode/db/clean is not present
6. Node takes approx 60 mins to start

**Expected behavior**
Node starts in <3 mins

**Screenshots**

**Version:**

- OS Name: Ubuntu
- OS Version 20.04
- Node version cardano-node 9.1.0 - linux-x86_64 - ghc-8.10
git rev https://github.com/IntersectMBO/cardano-node/commit/176f99e51155cb3eaa0711db1c3c969d67438958
CLI version cardano-cli 9.2.1.0 - linux-x86_64 - ghc-8.10
git rev https://github.com/IntersectMBO/cardano-node/commit/176f99e51155cb3eaa0711db1c3c969d67438958

**Additional context**
Replacing /etc/systemd/system/cnode.service with the following fixes the problem:
```
[Unit]
Description=Cardano Node
Wants=network-online.target
After=network-online.target
StartLimitIntervalSec=600
StartLimitBurst=5

[Service]
Type=simple
Restart=on-failure
RestartSec=60
User=cardano
LimitNOFILE=1048576
WorkingDirectory=/opt/cardano/cnode/scripts
ExecStart=/usr/bin/bash -c "/opt/cardano/cnode/scripts/cnode.sh"
KillSignal=SIGINT
SuccessExitStatus=143
SyslogIdentifier=cnode
TimeoutStopSec=300

[Install]
WantedBy=multi-user.target

```

**Comment by rdlrt** [comment]
> Most likely it's because the exit timeouts (TimeoutStopSec=60) are now too short...

Why is 60s too short? Have you confirmed if that is the case for you (by sending SIGINT manually to node proces and monitor)? If so, you might want to investigate where it's stuck - you cant keep waiting indefinitely for a shutdown :)

Also, I see ExecStop is missing in your case. It is important to use that process to ensure the correct pid (and not wrapper script) is the one receiving SIGINT.

**Comment by rdlrt** [comment]
@hodlonaut did a test on two of his machines, and the shutdown timings on each of them was 6-7 seconds.
Thus, taking > 60 seconds is not an expected shutdown state from node, and if it is (for instance if you have too many node connections up that it needs to free up or if it didnt have enough to save 2.5GB ledger to disk) - then you'd want to tune your system/node - closing this as invalid here

**Comment by adavault** [comment]
Thanks for checking. We get a very large number of inbound connections (due to network speed or just the fact that SPOs hard code). The node referenced has approx 400. That’s probably why it’s slow. No big deal if you don’t want to change, we just use the config we have that works.
