### ISSUE TITLE
gLiveWiew 1.30.2 - when i hit P the error token appears

### ISSUE THREAD

**Issue by Testernode** [cardano-community/guild-operators#1823]
**Describe the bug**
In gLiveWiew 1.30.2 - when i hit P the error token appears

**To Reproduce**
1. Go to gLiveWiew
2. Click on P
3. See error
hmetic operator (error token is ".129.28.179")
 TG Announcement/Support channel: t.me/CardanoKoios/9759or: invalid arithmetic operator (error token is ".129.28.179")
./gLiveView.sh: line 1034: [[: 57.129.28.179: syntax error: invalid arithmetic operator (error token is ".129.28.179")
 [esc/q] Quit | [h] Home | [i] Info | Left/Right : Navigate List
│   2                    :      ---   Unknown location                 │

**Expected behavior**
All peers need to show

**Screenshots**
![image](https://github.com/user-attachments/assets/e1c31387-3c06-4d1a-a34e-31cdfdf79014)

**Version:**
 - OS: Ubuntu 22.04.4 LTS
 - Product version: gLiveWiew 1.30.2
 - Cardano Node version: 9.1.1.
 - bash version : 5.1.16(1)-release

**Comment by Scitz0** [comment]
I can confirm the issue and pushed a fix in #1824
