### ISSUE TITLE
Preview Pool Registration Error

### ISSUE THREAD

**Issue by mcvetyty** [cardano-community/guild-operators#1827]
**Describe the bug**
I am attempting to register a pool through cntools on preview network, and once I supply all of the prompted information, it attempts to submit the registration transaction but this error displays:
```
# Pool Registration Transaction
./cntools.library: line 2405: ${tx.signed}: bad substitution
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   601    0   601    0     0    856      0 --:--:-- --:--:-- --:--:--   856
{"contents":{"contents":["DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\")","DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\")","DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\")","DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\")","DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\")","DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 \"end of input\")"],"tag":"TxCmdTxReadError"},"tag":"TxSubmitFail"}
Waiting for new block to be created (timeout = 600 slots, 600s)
INFO: press any key to cancel and return (won't stop transaction)
WARN: Balance mismatch, transaction not included in latest block... waiting for next block!
WARN: Balance mismatch, transaction not included in latest block... waiting for next block!
WARN: Balance mismatch, transaction not included in latest block... waiting for next block!
WARN: Balance mismatch, transaction not included in latest block... waiting for next block!
WARN: Balance mismatch, transaction not included in latest block... waiting for next block!
WARN: Balance mismatch, transaction not included in latest block... waiting for next block!

```
And it never completes.

**Version:**
 - OS: Ubuntu 20.04
 - Product version: CNTools v12.1.0 - Preview
 - Cardano Node version: cardano-node 9.1.1 - linux-x86_64 - ghc-8.10
git rev efd560070aaf042d1eb4680ae37fc607c7742319
 - Network you're connecting to: preview

**Comment by Scitz0** [comment]
You are running an old version of CNTools. Please make sure to run the latest version and then try again.

**Comment by mcvetyty** [comment]
Thank you, @Scitz0. I updated to version cntools 13.2.2 and now during the registration transaction it comes back with:
```

Pool Registration Transaction

ERROR: Transaction transform failed !!
The transaction contains following unfixable errors:
- If a transaction contains a pool registration certificate, then it must not contain any other certificate (transaction_body.certificates)
Error: Transaction CBOR contains unfixable errors

ERROR: failure during pool register!
```

**Comment by Scitz0** [comment]
Sounds strange, we dont create multi-certificate transactions to my knowledge. Do you use a hardware wallet? If not, please remove the cardano-hw-cli binary in $HOME/.local/bin and it wont try to transform the transaction to make it HW compatible. 

If however you are trying to create a pool registration that includes a HW wallet, then it must be passed through the transform. Please then press ctrl-c when you get the error. Then copy the transaction file (`tx.raw`) from /tmp/cnode/cntools/ and provide it here so I can check. It would also be helpful if you could provide the cntools-history.log file from /opt/cardano/cnode/logs folder. This will let me know of the commands executed.

**Comment by mcvetyty** [comment]
That solution worked! Appreciate it, @Scitz0.
