### ISSUE TITLE
GLview Bug

### ISSUE THREAD

**Issue by SyntaxStealth** [cardano-community/guild-operators#1836]
**Describe the bug**
Glive view faileds to load after CNCLI system services are enabled. 

**Steps to reproduce the behavior:**
1. Run through per-requesites, install and run node.
2. Upon loading Gliveview the top screen of gliveview will show  a node socket error.
3. The node socket error is part 1 of the problem, but the node will still run.
4. Setup ptsendtip and ptsendslot and appropriate settings in env
5. Enable system services using deploy-as-systemd and enable all services for a block producer, basically everything but topology.
6. Shutdown the node and start it again.
7. You will notice an env error when attempting to launch glview.
8. It will list the socket error as the driver.

**Solution 1:**
Shutdown, Restarts and first time boots need to follow a sequence when these services are enabled. 
1. when Shutdown, Restarts and first time boots all cncli services need to be disabled and stopped.
2. submitapi and node start services can begin (sometimes requires pc reboot)
3. once the node is loaded, we need to be prompted to enable previously enabled CNCLI services

**Solution 2:**
1. Upon enabling CNCLI services a copy of the latest env file and other supported files need to be copied to a CNCLI folder. I believe all of these services tapping into the same files is driving a conflict (locking the file from access).
2. CNCLI should reference these copies and not the primaries, to separate dependencies on these files to a single source.
3. This also creates some redundancy when operating independent.

**Expected behavior**
ENV Error and Node.Socket error

**Version:**
 - OS: Ubuntu 24.04.1 LTS
 - Product version: Latest Release
 - Cardano Node version: 9.2.1
 - Network you're connecting to: 
 -[alonzo-genesis.json](https://github.com/user-attachments/files/17519957/alonzo-genesis.json)
[byron-genesis.json](https://github.com/user-attachments/files/17519958/byron-genesis.json)
[conway-genesis.json](https://github.com/user-attachments/files/17519959/conway-genesis.json)
[shelley-genesis.json](https://github.com/user-
[topology.json](https://github.com/user-attachments/files/17519972/topology.json)
attachments/files/17519960/shelley-genesis.json)
[config.json](https://github.com/user-attachments/files/17519976/config.json)

**Additional context**
I run pool SSX, please let know if anything stands out while you're evaluating this.
![Screenshot from 2024-10-12 10-46-49](https://github.com/user-attachments/assets/c721d44a-e63e-4be5-bad4-7485fd155c94)

**Comment by rdlrt** [comment]
> Upon loading Gliveview the top screen of gliveview will show a node socket error.
The node socket error is part 1 of the problem, but the node will still run.

Before getting into solution (which made no sense to me, but maybe I misunderstood the description) - would be good to check the source of your issue...upon reboot of system, assuming node shutdown was clean - it should be up in about 5 minutes.

Until node is up, it is expected for scripts to show you the error about missing socket

Since the issue title talks about gLiveView, let's make sure you're aligned on this before touching cncli. Could you confirm once node has actually started (i.e. you can query tip using CLI), you're able to connect to gLiveView?

**Comment by rdlrt** [comment]
Also, I notice you do not use guild-deploy.sh (which is fine if you complete the config setup as per your environment), neither have you customised config.json. I am not sure how you're running node, but if running node.sh to deploy cnode and cncli, this may interfere with operations in current state of config file. This looks like very much of an initial pool-ops issue.

**Comment by SyntaxStealth** [comment]
The node has started, the config files came from IOHK's release as the bundle downloaded using guild-deploy were having port issues with the configuration. These are all new nodes on fresh installs, in all cases i had to use the IOHK files supplied in github for the nodes to activate. To answer your question, i did use guild deploy for the implementation. Secondly, I'm attaching a series of screenshots as i had a power outage earlier and it forced the condition to resurface after 14-days of up time.

To explain in more detail:
If i run the implementation steps using guild deploy, and the IOHK config files, everything works fine. However, the moment i activate all of the system services part of CNCLI (appropriate for BP) after the node is up and running, I cannot restart the node without having to shutdown/disable those services first, the restart the machine as if i never added those extra services, and then restart the node and reconfigure CNCLI. In other words, there's a conflict somewhere or the sequencing (or shutdown and restart procedure) should encompass these steps or configuration or at minimum a warning regarding using the additional system services. 

This is not a complaint, but from a UAT and overall experience perspective, it's something an SPO needs to troubleshoot or retain via tribal knowledge. I'm sure as we work towards more sophistication and a best in class cardano network, these issues may self cure in the future, but in the short-term i am politely raising awareness to the issue. 

Have you attempted to replicate this issue?


![Screenshot from 2024-10-25 17-01-15](https://github.com/user-attachments/assets/16f25ac7-a933-44ac-9ac9-9bf191c58282)
![Screenshot from 2024-10-25 17-00-49](https://github.com/user-attachments/assets/b4e52b94-6e43-46a6-b781-18ef565a250f)
![Screenshot from 2024-10-25 17-00-20](https://github.com/user-attachments/assets/021dce26-f4df-4e78-a525-dc594fb985d7)
![Screenshot from 2024-10-25 16-59-36](https://github.com/user-attachments/assets/9a9f84ce-c5d3-4471-b4f6-c7b51b0fd539)

**Comment by SyntaxStealth** [comment]
@rdlrt as you can tell by the initial error, it indicates a gliveview issue as the error. Hence, the header of my ticket. Followed by the node.socket issue. It also includes the steps i took in order to disable CNCLI services and get back to a running state as shown in the image below. Which leads to the discussion of proposes solutions. If not, I'll continue the duct tape and Spackle work to continue to have it operate. :-)


![Screenshot from 2024-10-25 21-41-36](https://github.com/user-attachments/assets/9a464fb3-6e85-48f8-8100-5f756719f8a1)

**Comment by rdlrt** [comment]
> The node has started, the config files came from IOHK's release as the bundle downloaded using guild-deploy were having port issues with the configuration.

The port conflict indicates that there was already a process running on port 12788, that did not match the PID of node. There is no reason a config file itself should cause trouble with port conflict. Please stick to original configs and if there are any conflicts resolve those instead of replacing config that dont have full path
