### ISSUE TITLE
[CNTOOLS] Backup and Restore wallet and pool (keys + certs)

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#188]
If we need to add a breaking change to the script, or need to move the VMs across.

**Comment by gufmar** [comment]
Transfer should be easy, by moving the Priv folder.

Might Interesting would be a `priv/backup/back_[last-start-date-time].zip` automatically generated on each startup, if enabled (default yes) in the config

There could be a CMD line option `cntools.sh backup` for a Cron job

**Comment by rdlrt** [comment]
Sorry I should've added a suggestion in original issue description.
I'd say a prompt for path: since backups would usually be essential when resetting folders (eg: change in folder structure) or moving to another image (changing cloud provider).Yep - should be easy to add - hopefully someone new than usual 6 picks his hand up :)

**Comment by Scitz0** [comment]
Implemented in #372
