### ISSUE TITLE
[CNTOOLS] Registering a pool with no leading zero in margin fails

### ISSUE THREAD

**Issue by papacarp** [cardano-community/guild-operators#193]
if you enter margin like .07 instead of 0.07 it will fail.  we should probably mention this in the prompt or test for it and fix.

**Comment by Scitz0** [comment]
I think we have a regex check in send ADA function we could reuse to check for valid fraction number. 
Maybe also that it's a value 0-1

**Comment by rdlrt** [comment]
Might also be good to specify field as
`Margin (in %):` and accept number as percentage

**Comment by Scitz0** [comment]
specifying number as a percentage does sound like the better choice.
This together with some number validation for all entered pool parameters.

**Comment by Scitz0** [comment]
Fixed in 971d3282156cbf6f491342ff4a5b2e965ab7078a
