### ISSUE TITLE
Prereq.sh Fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#200]
I am attempting a new cardano-node installation using ubuntu 18.04 LTS

execution of prereqs.sh script fails with following output:

Using apt to prepare packages for "Ubuntu" system
  Updating system packages...
Warning: apt-key output should not be parsed (stdout is not a terminal)
  Installing missing prerequisite packages, if any..
E: Unable to correct problems, you have held broken packages.
An error occurred while installing the prerequisite packages, please investigate by using the command below:
sudo apt-get -y install python3 build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev systemd libsystemd-dev zlib1g-dev npm yarn make g++ tmux git jq wget libncursesw5 gnupg
It would be best if you could submit an issue at https://github.com/cardano-community/guild-operators with the details to tackle in future, as some errors may be due to external/already present dependencies

So, I ran the suggested command:

sudo apt-get -y install python3 build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev systemd libsystemd-dev zlib1g-dev npm yarn make g++ tmux git jq wget libncursesw5 gnupg

Here is the output from this command:

Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
make is already the newest version (4.1-9.1ubuntu1).
make set to manually installed.
pkg-config is already the newest version (0.29.1-0ubuntu2).
jq is already the newest version (1.5+dfsg-2).
npm is already the newest version (3.5.2-0ubuntu4).
g++ is already the newest version (4:7.4.0-1ubuntu2.3).
g++ set to manually installed.
git is already the newest version (1:2.17.1-1ubuntu0.7).
git set to manually installed.
gnupg is already the newest version (2.2.4-1ubuntu1.2).
gnupg set to manually installed.
libncursesw5 is already the newest version (6.1-1ubuntu1.18.04).
libncursesw5 set to manually installed.
python3 is already the newest version (3.6.7-1~18.04).
python3 set to manually installed.
systemd is already the newest version (237-3ubuntu10.41).
systemd set to manually installed.
tmux is already the newest version (2.6-3ubuntu0.2).
tmux set to manually installed.
wget is already the newest version (1.19.4-1ubuntu2.2).
wget set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Can you please advise on how to proceed with installation?

**Comment by Scitz0** [comment]
Change to libssl1.0-dev 
A commit was added previously for this change but was reverted as it then breaks on Ubuntu 20.04
Either upgrade to latest Ubuntu LTS or change to use 1.0 of libssl-dev package.

Not sure if prereqs script should handle all variants of the different distributions or only support the latest.

**Comment by samcgill29** [comment]
OK. It would be good to at least mention minimum supported Ubuntu release as 18.04 LTS end of life is not until 2023.
