### ISSUE TITLE
prereqs.sh needs to handle npm dependency and updates better

### ISSUE THREAD

**Issue by bergr01** [cardano-community/guild-operators#201]
While trying to set up guild operators cnode setup for Haskell node on a new ubuntu box ran into the following error:

sudo apt-get -y install python3 build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev systemd libsystemd-dev zlib1g-dev npm yarn make g++ tmux git jq wget libncursesw5 gnupg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
make is already the newest version (4.1-9.1ubuntu1).
make set to manually installed.
pkg-config is already the newest version (0.29.1-0ubuntu2).
jq is already the newest version (1.5+dfsg-2).
g++ is already the newest version (4:7.4.0-1ubuntu2.3).
g++ set to manually installed.
git is already the newest version (1:2.17.1-1ubuntu0.7).
gnupg is already the newest version (2.2.4-1ubuntu1.2).
libncursesw5 is already the newest version (6.1-1ubuntu1.18.04).
python3 is already the newest version (3.6.7-1~18.04).
tmux is already the newest version (2.6-3ubuntu0.2).
wget is already the newest version (1.19.4-1ubuntu2.2).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

npm is apparently required by graphql

For the time being commented out npm from the list of dependencies and progress further. Raising a github issue as requested by Priyank

**Comment by samcgill29** [comment]
I experienced this problem as well.

**Comment by papacarp** [comment]
since the script doesn't make it easy to understand what went wrong, perhaps we just remove it from the prereqs for now, and put a note in that they should install npm manually

**Comment by rdlrt** [comment]
@samcgill29 could you check if the changes in #223 solve the issue for you?

**Comment by samcgill29** [comment]
Issue resolved, I used Ubuntu 18.04 LTS, no problems with prereq.sh script.

**Comment by mondonet** [comment]
> While trying to set up guild operators cnode setup for Haskell node on a new ubuntu box ran into the following error:
> 
> sudo apt-get -y install python3 build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev systemd libsystemd-dev zlib1g-dev npm yarn make g++ tmux git jq wget libncursesw5 gnupg
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> build-essential is already the newest version (12.4ubuntu1).
> make is already the newest version (4.1-9.1ubuntu1).
> make set to manually installed.
> pkg-config is already the newest version (0.29.1-0ubuntu2).
> jq is already the newest version (1.5+dfsg-2).
> g++ is already the newest version (4:7.4.0-1ubuntu2.3).
> g++ set to manually installed.
> git is already the newest version (1:2.17.1-1ubuntu0.7).
> gnupg is already the newest version (2.2.4-1ubuntu1.2).
> libncursesw5 is already the newest version (6.1-1ubuntu1.18.04).
> python3 is already the newest version (3.6.7-1~18.04).
> tmux is already the newest version (2.6-3ubuntu0.2).
> wget is already the newest version (1.19.4-1ubuntu2.2).
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
> npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> 
> npm is apparently required by graphql
> 
> For the time being commented out npm from the list of dependencies and progress further. Raising a github issue as requested by Priyank

I resolved this issue with aptitude:
1. sudo apt-get install aptitude -y
2. sudo aptitude install python3 build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev             systemd libsystemd-dev zlib1g-dev npm yarn make g++ tmux git jq wget libncursesw5 gnupg
For the 1st option choose n
Accept this sollution [Y/n/q/?]  n

For the 2nd option choose y
Accept this sollution [Y/n/q/?]  y
This will install and resolve all dependencies.
