### ISSUE TITLE
[CNTOOLS] Listing undelegated wallet causes non-fatal error

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#217]
If I try to use cntools script to list wallets and one of them is not delegated to a pool, I get the following error: 

./cntools.sh: line 409: [: 7c31dfd057(truncated): unary operator expected

The undelegated wallet does have a base address with funds in it.

**Comment by rdlrt** [comment]
Hey @samcgill29 - could you replicate the issue after synching script from master?

**Comment by samcgill29** [comment]
yes, you are right, there have been changes since I last sync'd.  My apologies to you - you are moving quickly!  The error I described above no longer occurs but I do receive the following message in the output:

Wallet   delegate1

The attempted local state query does not support non-stake addresses: fromList [AddressShelley (Addr Testnet (KeyHashObj (KeyHash 97798fbb1...)) (StakeRefBase (KeyHashObj (KeyHash e8fef28c66...))))]
Base UTxOs
                           TxHash                                 TxIx        Lovelace
--------------------------------------------------------------------------
etc.

**Comment by samcgill29** [comment]
I tried this query again later two times and did not see this error again, so I am going to close this issue as the latest updates seem to have fixed it.
