### ISSUE TITLE
Update to Env file Requested

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#225]
Could you please add an entry for the logfile that is used by the Block Collector script in the env template?  I have created the json log in the config file but the Block Collecting script is looking for the location in the environment file and I don't see an entry that contains the syntax that the script is looking for to locate the json log.

**Comment by Scitz0** [comment]
The block collector script gets the location of your node configuration file from env.
It then parses this configuration file to get the location of the son log file. 
So make sure env file points to the correct configuration file and that file extension of configured json logfile ends with .json

**Comment by samcgill29** [comment]
I have the correct configuration file set in env and the logfile ends with .json.  The script still did not find the logfile.

**Comment by Scitz0** [comment]
DM me on telegram @olaahlman so we can find the cause for this issue

**Comment by Scitz0** [comment]
I just realized node configuration file could be formatted as json instead of yaml making the parsing for the log file a little more complicated but not undoable. I assume this is the case?

**Comment by Scitz0** [comment]
Hopefully solved in 51fce36b86b5925b6ad186c0e16b82461ca06550 as this adds logfile parsing of json files in addition to yaml. If not please open a new ticket.
Please note the breaking changes added, ie config change

**Comment by samcgill29** [comment]
Yes, my config file is in json format. I do not use yaml for config, topo, or genesis.
