### ISSUE TITLE
Still having trouble with BlockCollector Script

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#232]
Yes, my config file is in json.  So, prior fix should have worked.  However, I still get error:

/opt/cardano/cnode/scripts  : ./cntoolsBlockCollector.sh
/opt/cardano/cnode/logs/node0.json  (this is the correct log location)
Error: Failed to locate json logfile in node configuration file
a setupScribe of format ScJson with extension .json expected 
/opt/cardano/cnode/scripts  :

Perhaps I have error in my config file, but node is working fine and log file contains log information.

Here is my setupScribes section in config file:

  "setupScribes": [
    {
      "scFormat": "ScText",
      "scKind": "StdoutSK",
      "scName": "stdout",
      "scRotation": null
    },
    {
      "scKind": "FileSK",
      "scName": "/opt/cardano/cnode/logs/node0.json",
      "scFormat": "ScJson",
      "scRotation": null
    }
  ]

Here is my defaultScribes section in config file:

  "defaultScribes": [
    [
      "StdoutSK",
      "stdout"
    ],
    [
      "FileSK",
      "/opt/cardano/cnode/logs/node0.json"
    ]
  ],

**Comment by Scitz0** [comment]
lol, just realized that the json parser for json formatted config parse just fine but never saves the data, just spits it out to STDOUT. A PR to fix this will be released very soon.

**Comment by Scitz0** [comment]
Should be fixed in 47b6224
But I'll leave the issue open until you can confirm.

**Comment by samcgill29** [comment]
Yep, all fixed now.  Thanks!
