### ISSUE TITLE
[CNTOOLS] Save vkey delegation with name

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#235]
If pool cold vkey cbor-hex is used in `funds >> delegate` save it to be able to delegate using just a name and for display in wallet listing.

A json file with 'vkey cbor'/'pool name' array stored in POOL_FOLDER could be a solution.

**Comment by Scitz0** [comment]
Will most likely not implement solution proposed but wait until tickers are available or use some third party API to query pool by name. Leaving issue open until a better solution presents it self.

**Comment by rdlrt** [comment]
Closing this - as seems stale (also, the idea regarding ticker couldnt be implemented due to the off-chain design where multiple pools can share ticker)
