### ISSUE TITLE
prereqs.sh on CentOS server

### ISSUE THREAD

**Issue by matthijs-aeon** [cardano-community/guild-operators#240]
Experienced the following error when re-running on a CentOS 8 server.
Resolved by removing 'coreutils-single' package from line 118.

[matthijs@build tmp]$ ./prereqs.sh
Using yum to prepare packages for "CentOS Linux" system
  Updating system packages...
  Installing missing prerequisite packages, if any..
Error:
 Problem: problem with installed package coreutils-8.30-7.el8_2.1.x86_64
  - package coreutils-8.30-7.el8_2.1.x86_64 conflicts with coreutils-single provided by coreutils-single-8.30-7.el8_2.1.x86_64
  - conflicting requests
An error occurred while installing the prerequisite packages, please investigate by using the command below:
sudo yum -y install coreutils-single python3 pkgconfig libffi-devel gmp-devel openssl-devel ncurses-libs ncurses-compat-libs systemd systemd-devel zlib-devel npm yarn make gcc-c++ tmux git wget epel-release jq gnupg
It would be best if you could submit an issue at https://github.com/cardano-community/guild-operators with the details to tackle in future, as some errors may be due to external/already present dependencies
[matthijs@build tmp]$

**Comment by rdlrt** [comment]
This was added as per request from @redoracle .
Will await for his inputs, as using coreutils instead impacts docker builds
