### ISSUE TITLE
Switch Setup scripts and doco to public testnet

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#241]
Currently, the scripts and documentations set up to connect to guild network, and then we have an optional [step](https://cardano-community.github.io/guild-operators/Common.html#connect-to-public-haskell-testnet-network-htn) to change to public Haskell testnet.

We would want to switch this to other way around in future.

This is **intentionally not done yet**, as intention of guild network is to test things against master branch, which may include breaking changes (eg: CLI formats), which would make script incompatible with public testnet.

Once CLI changes are reduced (can be monitored via projects in cardano-node), we would want to swap network to default to public testnet instead.

**Comment by Scitz0** [comment]
Done when combinator branch was merged.
