### ISSUE TITLE
[CNTOOLS] reports pool not registered (pooltool shows pool registered)

### ISSUE THREAD

**Issue by coconutpool** [cardano-community/guild-operators#248]
in the cntools.sh:

1) select pool (p)
2) select show (s)
3) select your pool
4) results: `Registered: NO`

if you look up the pool ID on pooltool, it shows up just fine.

**Comment by Scitz0** [comment]
Currently rely upon ledger-state dump  to get different pool metrics like registration status as this is not available through some other cli command. 
ledger-state dump is broken in FF network but fixed in latest master so when FF network reset next time this should work again.

**Comment by Scitz0** [comment]
Closing issue as its not a cntools issue but cardano-cli.
Cntools is developed against latest master and will continue to be so.

**Comment by Scitz0** [comment]
Decided to reopen issue as I feel more issues will be created for it otherwise. Keeping it open until next FF reset.

**Comment by rdlrt** [comment]
This should now be solved if using cardano node 1.14.1  and latest version of script.
(PS: wallets and pools created in 1.13 need to be recreated due to breaking change in cardano-node)
