### ISSUE TITLE
[CNTOOLS] Register pool metadata

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#251]
1. Accept inputs to create a JSON file `$CNODE_HOME/priv/pool/${pool_name}/poolmetafile.json`:
> {
  "ticker": "BLAH",
  "name": "FOO",
  "description": "FOO",
  "homepage": "https://blabla.com"
}
2. Update `registration-certificate` command in cntools.sh to include metadata hash and the URL:
> --metadata-url https://blabla/foo/poolmetafile.json --metadata-hash $(${CCLI} shelley stake-pool metadata-hash --pool-metadata-file ${POOL_FOLDER}/${pool_name}/poolmetafile.json)

**Comment by gufmar** [comment]
Also, do input verification based on the specifications (mainly min and max length) at

https://github.com/input-output-hk/smash/blob/master/README.md
