### ISSUE TITLE
[CNTOOLS] - Should registerStakeWallet be a seperate menu?

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#277]
As the topic says, just to have a discussion about whether we should have registerStakeWallet calls as a seperate call.

**Preface assumptions:**
- Network was changed
- Keys remain compatible (valid) , address hashing remains same too

_For Pools keys:_
If a pool was previously registered on old network , and not on new network... pool will be registered again by recreating/registering new keys
So that part is good

_For Stake key used by Pool:_
Currently cntools checks if there's a staking wallet address, before you can register pool...But we do not (might be difficult) check if staking address is registered..

_Proposal:_
1. Wallet -> New creates both payment and stake keys, a new task to register wallet is added. This aligns with Pool creation, and as long as inputs are valid keys , Key/Pool Registration can be executed multiple times.
2. Wallet -> New creates both payment and stake keys, then the registration task can be called in corresponding target (eg: Register Pool)
3. When doing Wallet -> New -> Stake, we just create keys, not register them. When Registering pool/delegating, we register the existing stake keys
4. Counter argument being we should encourage people to create new wallets every time network changes.

**Comment by gufmar** [comment]
I run into this multiple times, solving it by completely swiping Priv folder with every new genesis.

Imo it would make sense as an additional menu entry. Leave the existing process for new base wallets as is, but have a new option to reuse(register) old wallets

**Comment by Scitz0** [comment]
My take on it is this:

Moving registration of wallet to pool registration seems a bit weird to me. I do however recognize the issue presented.

As suggested in proposal 2 I think joining `New » Payment` and `New » Stake` into a single action is a good solution.
When doing this the wallet registration part should be split into its own action. This aligns better with how pool creation and registration work. The creation part just creates the keys needed and the registration part is its own thing and can be reused on network restart given that the keys are compatible. 
I'm not sure how to handle this last part though

**Comment by papacarp** [comment]
I would vote for new wallets every time network changes.  I like the idea of keeping CNTOOLS as simple as possible to avoid bugs and support issues.  We have enough to do to just stay abreast of the cli changes and feature additions to cardano-node.  Just my 0.02ADA...

**Comment by Scitz0** [comment]
I see your point papacarp and I agree, best practice to avoid as many issues as possible is to wipe both wallets and pools every time network resets to avoid any issues related to key changes etc. 

I however don't think this makes the proposal any less valid. It still makes a lot of sense to me to make wallet and pool creation steps similar, ie creation creates the keys and registration puts it on-chain. So for me, proposal 1 still gets my vote. 

A docs update could add the best practice to wipe /priv/wallet and /priv/pool on network reset.

**Comment by Scitz0** [comment]
Here is another controversial idea. Could we ignore the payment address altogether and just use the base address for the wallet and just have wallet address(ie base) and reward address? In `Wallet >> New` we would create the payment and stake keys but not register. Then user can fund the base address. After this, they can register the wallet using the potential future menu option `Wallet >> Register`.
It would be good to have a way to query if stake keys have been registered on-chain though. I haven't looked into this. Goes for the current setup as well.

You can use the base address without registration just as the payment/enterprise to send and receive ADA.

This could eliminate some confusion regarding the difference between a payment address and a base address and make the overall experience a little cleaner. 

Are there any potential drawbacks of this I can't think of right now?

**Comment by rdlrt** [comment]
Yea - removing payment address (just creating it behind the scenes) is good idea indeed.

> It would be good to have a way to query if stake keys have been registered on-chain though. I haven't looked into this. Goes for the current setup as well.
@bergr01 pointed out that this can be checked via `query stake-address-info` , so this shouldnt be an issue. Thus:
Wallet > New .. Create Wallet keys (vkey, skey)
Wallet > List .. Extract address using vkey, to avoid issues regarding change of address hash
Pool > New .. Create Pool keys
Pool > Register  & Funds > Delegate ..
  - Check if stake key for wallet is Registered. If not, register the key before proceeding

**Comment by Scitz0** [comment]
> Check if stake key for wallet is Registered. If not, register the key before proceeding
So instead of as I suggested we add `Wallet >> Register` we just do it when delegating/pledge if needed. I'm ok with this.

> Wallet > List .. Extract address using vkey, to avoid issues regarding change of address hash
This is ok, but I still think its a good idea to save/update to disk in case you want to cat address of wallet outside of CNTools without having to use cli to extract it from vkey. For advanced users that is. In CNTools we only expose the base address and call it wallet address?

**Comment by gufmar** [comment]
I like this idea. 
It's required crypto tech but shouldn't worry cntools users.

**Comment by Scitz0** [comment]
I have started the work of redoing the wallet structure to just use the base address and the other stuff mentioned here.
When I have something that is presentable I will push it for you to look over. Requires more changes than first thought as base and payment structure are used throughout the entire code. But I think in the end it will provide a much cleaner user experience as well as code structure.

**Comment by rdlrt** [comment]
>its a good idea to save/update to disk in case you want to cat address of wallet outside of CNTools without having to use cli to extract it from vkey

Yip - available, but will be overwritten each time we do an action that queries a wallet address (eg: list/show wallet)

>  in the end it will provide a much cleaner user experience

agreed. Thanks @Scitz0

**Comment by Scitz0** [comment]
Fixed by #286
