### ISSUE TITLE
[CNTOOLS] Error during attempt to re-register pool

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#282]
Ubuntu 20.04 LTS
cardano-cli 1.14.2 - linux-x86_64 - ghc-8.6
git rev 924a6f7d8c2bdb1bf525be8b0d5626e440697b01

Using latest version of CNTools downloaded 10 minutes ago.

I attempted to re-register a stake pool and received the following errors:

........................
-- creating registration cert --
Error reading stake verification key at: "/opt/cardano/cnode/priv/wallet/POOL/stake.vkey" Error: Deserialisation failure while decoding StakingVerificationKey.
CBOR failed with error: DeserialiseFailure 0 "expected word8"
-- Sending transaction to chain --
...........
-- Calculate fee, new amount and remaining balance --

cardano-cli: src/Cardano/CLI/Shelley/Run/Transaction.hs:215:19-43: Non-exhaustive patterns in lambda
..........................

Expected behavior would be to successfully re-register and post certificate to blockchain.

**Comment by rdlrt** [comment]
This error occurs when you have mismatch of versions between what was used to create stake pool v/s what was used to modify.
Cardano Node + CLI has changed key formats within `1.13`, `release/1.14.x`, `1.14.0` and `1.14.2`

Best to stick to same version that you created your keys with. The workgroup is advising everyone to stay on 1.14.x
