### ISSUE TITLE
[CNTOOLS] Error during attempt to rotate pool keys

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#283]
Ubuntu 20.04 LTS
cardano-cli 1.14.2 - linux-x86_64 - ghc-8.6
git rev 924a6f7d8c2bdb1bf525be8b0d5626e440697b01

Using latest version of CNTools downloaded in last 30 minutes.

I attempted to rotate the keys for a stake pool and received the following error:

.........................................................
/opt/cardano/cnode/priv/pool/POOL/cold.counter: TextView decode error: DecoderErrorDeserialiseFailure "OperationalCertificateIssueCounter" (DeserialiseFailure 0 "expected integer")
........................................................

Nonetheless, script completed key rotation and pool restarted with new keys without issue. Expected behavior is successful rotation without the error message.

**Comment by rdlrt** [comment]
This error occurs when you have mismatch of versions between what was used to create stake pool v/s what was used to modify.
Cardano Node + CLI has changed key formats within 1.13, release/1.14.x, 1.14.0 and 1.14.2

Best to stick to same version that you created your keys with. The workgroup is advising everyone to stay on 1.14.x
