### ISSUE TITLE
`numfmt --grouping` breaks with decimal numbers and locales that don't use a dot for monetary decimal separator

### ISSUE THREAD

**Issue by SmaugPool** [cardano-community/guild-operators#292]
For example, with a french locale that uses `,` for decimal numbers:
```
$ env | grep LC_NUMERIC
LC_NUMERIC=fr_FR.UTF-8

$ numfmt --grouping 3000.14
numfmt: invalid suffix in input: ‘3000.14’

$ numfmt --grouping 3000,14
3 000,14
```
Consequently, all values that use `lovelaceToADA` then `numfmt --grouping` are broken on systems using this kind of numeric format. For example, for `Pool -> Show`, I get:
```
POOL 
ID                    : 7607d58f4ff02f4de24cb45984efab063e64cb1d6d6ce00807d69962
Pledge                : 50 000 ADA
numfmt: invalid suffix in input: ‘7.5’
Margin                :  %
Cost                  : 256 ADA
```
I'm not sure how to fix this properly, one solution is to let `numfmt` do the conversion from Lovelaces to ADA, for example:
```
$ numfmt --format "%'.6f" --to-unit=M 1000000000000
1 000 000,000000
```
The difference with current method is that numbers would always have 6 decimals (the exact number of lovelaces).

**Comment by redoracle** [comment]
May I suggest to not to use numfmt for the following reasons:
1) increase the number of required (dependences) software
2) Format incompatibility between the various software used increasing the complexity of the script
3) use instead builtin bash function (printf) or already used tools (bc) to achieve the same results.

It will make it easier to read and use. An other example can be curl and wget... they do the same thing, and using one of them will reduce the required software and related script complexity.

Thats my thought. :)

**Comment by SmaugPool** [comment]
> use instead builtin bash function (printf) or already used tools (bc) to achieve the same results.

It's not me to decide if `numfmt` should be used or not, but as far as I know, `printf` or `bc` do not allow to achieve the same resuls, ie: display monetary values according to LC_MONETARY locale.

**Comment by SmaugPool** [comment]
@redoracle Note that the issue here comes from using locales, the same problem occurs with `printf`, for example:
With a locale that uses `,` for decimal separator:
```
$ printf "%'f\n" 3.14
bash: printf: 3.14: invalid number
0,000000

$ printf "%'f\n" 3,14
3,140000
```

**Comment by redoracle** [comment]
I have tried to replicate the behavior but with no success: 

LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
root@HTN:/home/guild# printf "%'.3f\n" 30000.14001
30000.140

can you try to do:
sudo update-locale LC_NUMERIC="en_GB.UTF-8" or LC_NUMERIC="C"

**Comment by SmaugPool** [comment]
> can you try to do:
> sudo update-locale LC_NUMERIC="en_GB.UTF-8" or LC_NUMERIC="C"

I don't want to change my locale, but yeah it works with a locale that use a `.` for the decimal separator, for example:
```
$ LC_ALL=en_US.UTF-8 printf "%'f\n" 3.14
3.140000
```

This is due to:
```
$ locale -k LC_NUMERIC
decimal_point=","
```

**Comment by redoracle** [comment]
to be honest I run the node in a clean docker container environment (empty locales), as much vanilla as possible.
I guess that the is not possible to have a cross compatible version of the script (over multiple LANG), unless heavy casting of the values..

**Comment by mark-stopka** [comment]
I would just set LOCALES variables at the start of the script... it's nuts to attempt to support all different LOCALES in tool like this, the effort is not worth...  `LC_ALL=C`  seems like the right locales to me for an app like this...

**Comment by redoracle** [comment]
> I would just set LOCALES variables at the start of the script... it's nuts to attempt to support all different LOCALES in tool like this, the effort is not worth... `LC_ALL=C` seems like the right locales to me for an app like this...

I agree on this approach...but not sure if then there are other issues coming from it...

**Comment by mark-stopka** [comment]
> but not sure if then there are other issues coming from it from people using a custom one...

The sea of issues that may arise if you try to support all different LOCALES is just endless... I would stick to either `C` or `en_US.UTF-8`...
