### ISSUE TITLE
[CNTOOLS] Add undelegate option

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#296]
It's not that common to want to undelegate but the option to do so should be there.
ie `cardano-cli shelley stake-address de-register ...`

**Comment by SmaugPool** [comment]
I'm not sure that the `de-register` command is already implemented, I get:
```
bin/cardano-cli shelley stake-address de-register --signing-key-file priv/wallet/Delegator/stake.skey 
runStakeAddressCmd: StakeKeyDeRegister (PrivKeyFile "priv/wallet/Delegator/stake.skey") (NodeAddress {naHostAddress = Nothing, naPort = 0})
```
and nothing happens.

I think it can be done by building the transaction manually, but maybe it's simpler to wait for the command to be available.

**Comment by Scitz0** [comment]
I see, yeah let's wait in that case and keep the issue open for now.

**Comment by rdlrt** [comment]
Was this issue about key deregister or pool retirement? If its the latter, command should be `cardano-cli shelley stake-pool deregistration-certificate`...

**Comment by Scitz0** [comment]
This functionality is available and open for implementation. Basically, duplicate the wallet registration code. But after CNTools offline PR has been merged and matured.

```
Usage: cardano-cli shelley stake-address deregistration-certificate --stake-verification-key-file FILE
                                                                    --out-file FILE
```

**Comment by Scitz0** [comment]
Added in #553, to be closed when merged into master.
