### ISSUE TITLE
Question about CNTOOLS env parameters

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#337]
I am running cardano-cli 1.15.1 - linux-x86_64 - ghc-8.6
git rev 712a287602797e8fd889fbf73e56a08c3d8b004a
on Ubuntu 20.04

I am getting an error when I run cntools.sh.  The error occurs with the line:

${CCLI} shelley query protocol-parameters ${PROTOCOL_IDENTIFIER} ${NETWORK_IDENTIFIER} --out-file "${TMP_FOLDER}"/protparams.json 

The env file returns --cardano-mode for $Protocol_Identifier and --mainnet for $Network_Identifier.

The problem appears to be with using --mainnet for query protocol-parameters.   The error reported is:

cardano-cli: HandshakeError (Refused NodeToClientV_3 "version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 42}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}}")

When I use --testnet-magic 42 then I don't get the error.  However, the env file is correctly reading networkID in the shelley genesis.json as mainnet. 

However, the env file logic has: 
NETWORKID=$(jq -r .networkId $GENESIS_JSON)
BYRON_GENESIS_JSON=$CNODE_HOME/files/mainnet_candidate-byron-genesis.json
NODE_SOCKET_PATH=$CNODE_HOME/sockets/node0.socket
export CARDANO_NODE_SOCKET_PATH=$CNODE_HOME/sockets/node0.socket
MAGIC=$(jq -r .protocolMagicId < $GENESIS_JSON)
NWMAGIC=$(jq -r .networkMagic < $GENESIS_JSON)
if [[ "${NETWORKID}" = "Mainnet" ]]; then
  NETWORK_IDENTIFIER="--mainnet"
else
  NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}"
fi

So, it seems that env is returning --mainnet for $Network_Identifier when the cli seems to want --testnet-magic 42

**Comment by samcgill29** [comment]
Also, I use the line:

PROTOCOL=$(jq -r .Protocol "$CONFIG")

in the env files since my config file is in json format.  This is the format used when downloading the config file from hydra.

**Comment by rdlrt** [comment]
CNTools is only supposed to be used with shelley testnet (not combinator networks, as per [this ](https://cardano-community.github.io/guild-operators/Scripts/cntools-changelog.html#changed-1) message. Combinator networks will be added soon - but not with the current version.

Previous version supported it because of hardcoded values, there are few changes in the codebase that we're waiting for

**Comment by samcgill29** [comment]
OK, thank you for clarification.  Closing the question.
