### ISSUE TITLE
[CNTOOLS] Pool show delegations optional

### ISSUE THREAD

**Issue by gufmar** [cardano-community/guild-operators#345]
for mainnet we should change the `pool > show` report, to show everything except delegations. 
then ask if a list of delegators  should be shown on screen (or exported to a json file)

**Comment by SmaugPool** [comment]
We could also have another menu entry specific for that, maybe "Stake".
One benefit is that we could allow to show the delegators and stake of other pools as well if wanted.

**Comment by Scitz0** [comment]
Implemented in 5.1.0
