### ISSUE TITLE
[CNTOOLS] 4.3.0 Send Funds error

### ISSUE THREAD

**Issue by willcbanks** [cardano-community/guild-operators#347]
Using cardano 1.15.1
and CNtools 4.3.0

When I attempt to send funds from the pool owner's pledge wallet to an external address I get this error:

Address: addr1qr9e6j9tsr28pqk5latvtwq3kauy8xvt4ag0vmuvdz6zpqt44kvrlgp9hcshejlhwqws2qcsrffwaa2ns5fzltgpmp3qsvufqu
option --tx-out: Failed reading: invalid address

  Build a transaction (low-level, inconvenient)
Error while reading unsigned shelley tx: /tmp/cntools/tx0.tmp: /tmp/cntools/tx0.tmp: openBinaryFile: does not exist (No such file or directory)
option --tx-out: Failed reading: invalid address

and also:

  Build a transaction (low-level, inconvenient)
Error while reading unsigned shelley tx: /tmp/cntools/tx.raw: /tmp/cntools/tx.raw: openBinaryFile: does not exist (No such file or directory)
/tmp/cntools/tx.signed: /tmp/cntools/tx.signed: openBinaryFile: does not exist (No such file or directory)

[update - sending to another local Wallet works fine ]

**Comment by rdlrt** [comment]
1.15.1 is not a network. Address distinguishing goes against network you connect to.
If you're sending wallets from a `node` to wallet, note that node will use the prefix for address hash (addr1 v/s addr_test) based on network type. The node cannot send testnet funds to mainnet address, thus - its a limitation of what wallet provides.
