### ISSUE TITLE
Provide CLI required to start node and relays

### ISSUE THREAD

**Issue by cloudstake** [cardano-community/guild-operators#353]
With the different networks requiring --testnet-magic or --mainnet, it can sometimes be confusing to new operators what command to start the relay and node. The pool|show option does a great job of showing the Run arguments, but not the full, prepended cardano-node command. I see questions about this frequently in the Best Practices Telegram channel and have had them myself.

Would be great if one could use CNTools to create the wallet and pool, and then get the full command to start up a node and relay. Or perhaps even generate the .sh file, like it does the poolmeta.json.

Output would be something like this for the relays:
cardano-node run --config $CNODE_HOME/files/shelley_testnet-config.json --database-path $CNODE_HOME/db --host-addr 0.0.0.0 --port 5001 --socket-path $CNODE_HOME/sockets/node0.socket --topology $CNODE_HOME/files/shelley_testnet-topology.json

Output would be the relay output, plus pool run arguments added for the nodes.

Thanks!

**Comment by rdlrt** [comment]
Hi @cloudstake ,

The lifecycle for using CNTools is such that will be used *after* you have - atleast - a passive node up.

The [prerequisties](https://cardano-community.github.io/guild-operators/Common.html#dependencies-and-folder-structure-setup) script already downloads a cnode.sh that will set up the required to start the script. What you see in CNTools is correct in that respect, as those are only additions you need to make to your node.

If for some reason you do not use that script, there is documentation available on how to start node [here](https://cardano-community.github.io/guild-operators/Setup-Node.html).
