### ISSUE TITLE
[CNTools] ERROR: current KES period must be an integer number [-39]

### ISSUE THREAD

**Issue by alopezt16** [cardano-community/guild-operators#357]
**Describe the bug**
After registering a new pool, next time you open CNTOOLs display an error related to **KES**.

**To Reproduce**
1. Register a Pool
2. Close CNTOOLs
3. Reopen CNTOOLs

**Expected behavior**
CNTOOLs open successfully without reporting issues with **KES**

**Screenshots**
![image](https://user-images.githubusercontent.com/17558434/88349926-76db8680-cd1f-11ea-93c2-e00699812d07.png)

**Version:**
 - OS: **Debian 10**
 - Product version: **CNTools 5.0.1**
 - Cardano Node version: **1.17.0**
 - Network you're connecting to: **MC3**

**Comment by rdlrt** [comment]
Yes - this is known for a while, we were able to use hard coded references up until now since cardano ledger did not provide the transition details. We've got couple of ways to not depend on hardcode entries now, will test it a bit before merging to 5.0.2 release

**Comment by rdlrt** [comment]
Solved via #356
