### ISSUE TITLE
Can't Run Latest CNTools.sh Version

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#362]
**Describe the bug**
I start cntools.sh and immediately get the following error:

WARN: The logs indicate that cardano-node has not yet synched to network or the network has not reached the hard fork from Byron to shelley , please wait to use CNTools until your node is in shelley era.

I am using node 1.17.0 on mainnet_candidate_3 network.  There is no log file in the log folder.

**To Reproduce**
1. configure env after running prereq.sh for a clean install.
2. run cntools.sh
3. error

**Expected behavior**
MC 3 network has moved to shelley era , so this error should not occur.

**Screenshots**
I reproduced the exact warning text in the description.

**Version:**
 - OS: Ubuntu 20.04 LTS
 - Product version: CNTools 5.0.3
 - Cardano Node version: cardano-node 1.17.0 - linux-x86_64 - ghc-8.6
git rev 0191ff56d194b6ac074af0d51e67493c14e08ffa
 - Network you're connecting to: 2020-07-23T01:00:00Z

**Additional context**
None.

**Comment by samcgill29** [comment]
My node is fully synced with the network.

**Comment by rdlrt** [comment]
Check the changelog for 5.0.2 and 5.0.3.
You need to do the below once (together) to keep things in sync:
1. Execute prereqs.sh
2. Clear $CNODE_HOME/db folder (while node isn't running)
3. Do NOT add any curl commands (config genesis and topology all match MC3 after running prereqs)
4. Start node and wait for node to sync to epoch 3 or above
5. Start CNTools

**Comment by rdlrt** [comment]
@samcgill29 - did you get sorted?

**Comment by rdlrt** [comment]
Closing as version has changed and entire folder structure has been updated
