### ISSUE TITLE
updating cntools

### ISSUE THREAD

**Issue by Horhel** [cardano-community/guild-operators#384]
Trying to update Cntools 5.06 to 5.2 i've run into the following. 
Please excuse my naive nonsense, if any, but I'm a beginner.
I have done this steps:
 
Stop node
 
curl -sS -o prereqs.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh
 
chmod 755 ./prereqs.sh
 
./prereqs.sh
 
sudo chown -Rv cardano:cardano /home/cardano (noticed that prereqs.sh builds everything in root user)
 
Delete db, logs, and socket: rm -rf $CNODE_HOME/db
                                             rm -rf $CNODE_HOME/logs
                                             rm -rf $CNODE_HOME/sockets
and redo the empty folders

configure cnode.sh and topology.json
 
Start cnode.sh -wait to sync

Start cntools.sh 

so when i start cntools.sh i get:
WARN: failed to query protocol parameters, ensure your node is running with correct genesis (the node needs to be in sync to 1 epoch after the hardfork)

Press c to continue or any other key to quit
only offline functions will be available if you continue
and i press c and i got this
 Epoch 13 - 03h:27m:08s until next
 What would you like to do?                                        Node Sync: -12 :)
so when i try to see my wallets i get this:
 >> WALLET >> SHOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

ERROR: Missing folder: /opt/cardano/cnode/priv/wallet

so i think it is a bug because i have the line in cnode.sh: [[ -z "$CNODE_HOME" ]] && CNODE_HOME=/home/cardano/cnode
and in .bashrc : CNODE_HOME=/home/cardano/cnode
and i have corrected the paths into config.json, and prereqs.sh.


Can someone explain how to correct this path and how can someone build everything in /opt/cardano/ when the .bashrc file is in /home/cardano/  ?? 

Maybe this is completely normal but i just wanted to clarify. Looking forward to understand. Thank you!

**Comment by Horhel** [comment]
also i have noticed this while runing prereqs.sh
Config file /root/.cabal/config not found
not sure if this has anything to do with but..

**Comment by rdlrt** [comment]
> WARN: failed to query protocol parameters, ensure your node is running with correct genesis (the node needs to be in sync to 1 epoch after the hardfork)

This may have to do with NODE_SOCKET not matching your current file. Try to replicate this via 5.2.1 patch that was deployed few mins ago.

> so i think it is a bug because i have the line in cnode.sh: [[ -z "$CNODE_HOME" ]] && CNODE_HOME=/home/cardano/cnode

So in your case, you're using /home/cardano for starting node, but your $CNODE_HOME/scripts/env file is (I assume) untouched, causing trouble?

> Config file /root/.cabal/config not found

@Horhel  If you're running the prereqs script as root, you'd want to run it as a normal user who has sudo access instead.
