### ISSUE TITLE
Error when running prereq.sh in Digital Ocean CentOS 8.2 droplet

### ISSUE THREAD

**Issue by carlworks** [cardano-community/guild-operators#391]
Hi,

I followed the instructions in the Pre-Requisites page but I'm encountering the error below.

./prereqs.sh

Using yum to prepare packages for "CentOS Linux" system
  Updating system packages...
  Installing missing prerequisite packages, if any..
Error: Unable to find a match: libsodium-devel
An error occurred while installing the prerequisite packages, please investigate by using the command below:
sudo yum -y install coreutils python3 pkgconfig libffi-devel gmp-devel openssl-devel ncurses-libs ncurses-compat-libs systemd systemd-devel libsodium-devel zlib-devel npm yarn make gcc-c++ tmux git wget epel-release jq gnupg libtool autoconf util-linux
It would be best if you could submit an issue at https://github.com/cardano-community/guild-operators with the details to tackle in future, as some errors may be due to external/already present dependencies

**Version:**
 - OS: CentOS 8.2
 - Product version: prereqs.sh

Script will run if I removed libsodium-devel in prepreqs.sh and tried to reinstall it later using command yum install libsodium-devel -y

**Comment by rdlrt** [comment]
You would need the EPEL of CentOS included for prereqs, and as a general recommendation anyways
