### ISSUE TITLE
[Pool Registration] Suggestion for metadata.json

### ISSUE THREAD

**Issue by kardall** [cardano-community/guild-operators#405]
Because file formatting can be an issue if working/saving mac/windows/linux etc, perhaps a simpler approach to the metadata can be achieved by the following:

- User enters the URL of the MetaData.json location
- Script checks if it exists (like it does now).
- If it exists ask to use (like it does now and continue on with current script functions)
- If it does not exist:
-- Get User to fill out pool meta fields as normal
-- Output json and instruct user to rename file to the one specified above (or maybe ask for the file name / parse it from the url)
-- pause for confirmation it's done.
-- When user continues it will download the json file, generate the hash from the uploaded file to use for registration
-- Script continues like normal

This may assist with encoding issues if copy/pasting or similar actions between OS/languages

**Comment by rdlrt** [comment]
@kardall you will not have encoding issues if you're simply copying the JSON file and hosting on servers

The file is already created and its highlighted in Yellow to copy the file AS-IS and make it available to the server, the part from your input that already exists.

We havnt had any reports of encoding issues by users who followed the steps.

**Comment by rdlrt** [comment]
Sample screenshot of the message (asking to copy file as-is):
![image](https://user-images.githubusercontent.com/3169068/89247144-0baf7f80-d650-11ea-9fe8-1aae45a21166.png)
