### ISSUE TITLE
Warn: No pools available that can be modified

### ISSUE THREAD

**Issue by michaeljohngoff** [cardano-community/guild-operators#408]
![E45F291E-789E-4C7E-B16E-E5B547C5E0D3](https://user-images.githubusercontent.com/69106762/89392467-78368700-d701-11ea-87af-f5b508a25599.jpeg)

Hi, i have this problem modifying pool and nothing  fixes it for me? Ive tried prereqs.sh, older version of cn tools, 5.21, 5.30, 5.3.1 but it doent work. 
I registed pool with 5.2.1 and could modify it until I updated CNtools from interface and now it never works. I can show / list pool etc but modify command doesn’t work. 

Hope someone can help

**Comment by rdlrt** [comment]
1. Does Pool > Show return your pool as "Registered"?
2. Did you encrypt / move your keys at any time?

**Comment by michaeljohngoff** [comment]
1. Show - returns pool registered yes
2. I've never encrypted the pool

**Comment by michaeljohngoff** [comment]
rdlrt - I should say, thanks for your reply - its greatly appreciated. Any help you can provide to get over this hurdle would be a blessing.

**Comment by Scitz0** [comment]
For a pool to be listed in the selection menu these files must be present in the pool folder:
POOL_COLDKEY_VK_FILENAME (default: cold.vkey)
POOL_COLDKEY_SK_FILENAME (default: cold.skey)
POOL_VRF_VK_FILENAME (default: vrf.vkey)
POOL_REGCERT_FILENAME (default: pool.cert)

Check cntools.config for the filename.

**Comment by michaeljohngoff** [comment]
POOL_COLDKEY_VK_FILENAME (default: cold.vkey)
POOL_COLDKEY_SK_FILENAME (default: cold.skey)

these two arent there!

**Comment by michaeljohngoff** [comment]
Mint - I searched the files from terminal and had backups. restored the files and were golden.

Brilliant - you're an absolute diamond!

take a bow x
