### ISSUE TITLE
[CNTOOLS] Support hardware wallets for pledge and rewards

### ISSUE THREAD

**Issue by Straightpool** [cardano-community/guild-operators#409]
**Enhancement**

Love the convenience of cntools and will try to help implement the following when hardware wallets like Ledger support Shelley:

*Proposal:*
* New: At pool registration allow split into 3 wallets: owner, rewards and operator (currently with 5.3.1 we have 2: owner and rewards)
* Regarding security requirements the ranking is like this: owner > rewards > operator
* The operator wallet can reside encrypted on the server longterm as it will only carry minimal ADA to pay for pool registration / modification fees like change of registered wallets and such
* New: All pool related fees should be payed by the operator wallet by default with the lowest security requirements  
* New: The owner and rewards wallets should reside on hardware wallets long term for security reasons, to support this from my understanding the script would need to offer to specify a hardware wallet base address instead of a cntools type wallet with a short explanation on how to figure out base addresses in hardware wallets which should be used for this ideally (have not yet looked into this in detail, I assume there is a way without extracting root key and such, like first address in the GUI wallet list) and a link to a guide on how to stake the pledge from the hardware wallet to meet the pledge requirements

**Comment by rdlrt** [comment]
> At pool registration allow split into 3 wallets: owner, rewards and operator (currently with 5.3.1 we have 2: owner and rewards)

Taking a step back, CNTools is really only to be used by operators, not really for others. Operator and Reward address would be linked in 99% of the cases. The owner wallets/keys should not be present in CNTools anyways - in fact, we would really want to forbit such a bad practice being allowed/supported.

> The operator wallet can reside encrypted on the server longterm as it will only carry minimal ADA to pay for pool registration / modification fees like change of registered wallets and such

I'd say operator wallet should be moved offline too - and there should be no other wallet on the server longterm. Just having stake key of pool can be dangerous enough, having wallets allows for signing tx that can be quite painful.

> All pool related fees should be payed by the operator wallet by default with the lowest security requirements

Yes, currently the case (as per reply to point # 1 above)

> The owner and rewards wallets should reside on hardware wallets long term for security reasons, to support this from my understanding the script would need to offer to specify a hardware wallet base address instead of a cntools type wallet with a short explanation on how to figure out base addresses in hardware wallets which should be used for this ideally (have not yet looked into this in detail, I assume there is a way without extracting root key and such, like first address in the GUI wallet list) and a link to a guide on how to stake the pledge from the hardware wallet to meet the pledge requirements

This requires integration with a hardware wallet + changing cntools to a level of complication that's supposed to be done at `cardano-wallet` level, not at base level. In general, we would not want to be mixing the bridge of HD Wallets, Hardware wallets, etc with the core functionality of operator wallet tool. There are already appropriate tools for those - in my view.

I will let others comment to see their views

**Comment by Straightpool** [comment]
Thanks for your first assessment. We are mostly aligned, let me try to clarify: 

1. I believe a few changes to the script could promote better security practice:

- Currently the script is based on the assumption owner = operator. The problem with this is the script only asks for the "owner" wallet which is expected to pay for pool registration AND provide the pledge. This promotes bad practice in my point of view 
- I propose the script should ask for the operator wallet instead and make it clear that this wallet should be rather new and used to pay for the pool registration fee only and thus use the "extra multi-owner" process as the regular process to add pledge with one or multiple staking keys. 

2. Regarding hardware wallet support, this would be the ideal process from an UX and security point of view:
- When asking for "multi-owner" the script also allows for entry of base addresses (the very first receive address in a hardware wallet)
- The script then provides a prompt to wait on manual delegation of the hardware wallet via another GUI like Daedalus or Yoroi when delegation via hardware wallet is officially supported (like the metadata upload process)
- The official wallet maybe offers some stake verification string to copy to the script
- After verification of pledge delegation via pasted string and or in the blockchain the script continues to register the pool with the added hardware wallet owner

Of course in this scenario the script won't gain access to the hardware wallet stake.skey, so this process will not be possible with current CLI at least. From my understanding the only way to provide pledge from a hardware wallet, is to use e.g. Pals process to extract the stake keys from the hardware wallet: https://gist.github.com/ilap/5af151351dcf30a2954685b6edc0039b
I still wonder if another process not exposing the hardware wallet seed phrase to a computer is feasible at a later time to promote good hardware wallet hygiene.

**Comment by rdlrt** [comment]
Thanks for the reply.

> From my understanding the only way to provide pledge from a hardware wallet, is to use e.g. Pals process to extract the stake keys from the hardware wallet

Not sure if this additional step adds value yet. Also, retrieving stake keys involves entering mnemonics of a ledger device on a machine - and we would want to be very careful what we push to community, as in-spite of disclaimers the sysops are skipped and pools are being run using cntools without background. Similarly, encouraging them accessing hardware wallets using scripts - while good for advanced users - will be a bit concerning as others may simply skip the basic security.

What we do instead is:
- When prompted for owner keys, we simply ask for the path to stake vkey/skey file -> We dont try to suggest which type of wallet it comes from , or where they get to it.
- This is pretty much all needed to registered, as the funds from the HD Wallet is then available to pledge

This way we do not differentiate the type of wallet, or ask user to pick an address. Also, we're not dependent on CNTools users running a `cardano-wallet` layer on their machines, as they dont need to. So currently you can still continue to use the workaround from iilap on an offline device, but all you need to really supply to cntools is the stake.skey/vkey files - which do not have funds on them.


The ideal case for multi-owner currently implemented on master - but waiting for release tags as we're now on mainnet - is that we can provide offline / online mode in cntools.config. The offline mode will allow to perform all the tasks, except submitting the staging transaction (in your case - to be signed by pool owners). The online mode will allow accepting a tx as input to submit.

**Comment by Straightpool** [comment]
Great reply as always. I am happy with this so I will now close this issue. Looking forward to the offline-mode. :)
