### ISSUE TITLE
CNODE_NAME not considered in cntools.config

### ISSUE THREAD

**Issue by gufmar** [cardano-community/guild-operators#412]
when setting up a cnode environment in prereqs.sh interactive mode and specifying a different than default CNODE_NAME 

https://github.com/cardano-community/guild-operators/blob/master/scripts/cnode-helper-scripts/prereqs.sh#L89

this is not considered and adapted in cntools.config 

https://github.com/cardano-community/guild-operators/blob/master/scripts/cnode-helper-scripts/cntools.config#L17

**Comment by rdlrt** [comment]
I think cntools.config is correct in this case (since $CNODE_HOME = $CNODE_PATH/$CNODE_NAME) , there are a few sed commented out which we should enable back once tested a bit thoroughly - which will help us set the appropriate updates to env files. Need to find some time to test it out

**Comment by Scitz0** [comment]
Fixed by @rdlrt in #451.
