### ISSUE TITLE
[CNTOOLS ] Re-stake reward wallet feature broken

### ISSUE THREAD

**Issue by Straightpool** [cardano-community/guild-operators#415]
**Describe the bug**
Line 1635: "say "\nRe-stake reward wallet to pool?\n" 
with the steps that follow is never called. I did not see the cause for this bug on first look.

**To Reproduce**
1. Register a seperate reward wallet next to the owner wallet
2. Proceed with pool registration
4. See question "Re-stake reward wallet to pool?" never pops up

**Expected behavior**
Question "Re-stake reward wallet to pool?" shows up and allows to re-stake reward wallet to pool after confirmation.

**Version:**
 - OS: Ubunto 20.4 LTS
 - Product version: CNTools 5.3.1
 - Cardano Node version: cardano-node 1.18.0 - linux-x86_64 - ghc-8.6
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Comment by Scitz0** [comment]
I cant see any issue with the code.
`if [[ ! "${owner_wallet}" = "${reward_wallet}" ]]; then`
If a separate reward wallet is chosen this should be true.
Keep in mind that this is only valid for new pool registration, pool modify will not prompt for automatic delegation of wallet as mentioned before owner wallet is selected.
`say "${ORANGE}If a new wallet is chosen for owner/reward, a manual delegation to the pool with new wallet is needed${NC}"`

**Comment by Straightpool** [comment]
Thank you. I missed the little detail that this code is called in the new pool registration section only.
I assume this is on purpose, so I will close this minor issue.
