### ISSUE TITLE
Issue while installing prerequisites in CentOS

### ISSUE THREAD

**Issue by Akkii4** [cardano-community/guild-operators#420]
While following the [docs](https://cardano-community.github.io/guild-operators/#/basics?id=pre-requisites) ,and installing prerequisites (./prereqs.sh) got the following error .

OS Version - CentOS 

<img width="654" alt="image" src="https://user-images.githubusercontent.com/47569427/90012040-3fc61880-dcc0-11ea-88e1-5ef515371caf.png">

**Comment by matthijs-aeon** [comment]
Confirmed that Akshit installed the epel-release repo

This resolved the 'libsodium-devel' package, however 'secure-delete' still returns an error.

No further troubleshooting taken.

![IMG_20200812_195817_311](https://user-images.githubusercontent.com/55691309/90012611-495a7b00-dcd6-11ea-8474-ec6e05a1cb23.jpg)

**Comment by rdlrt** [comment]
Thanks for reporting, secure-delete was added recently - name for secure-delete in Ubuntu package is srm in epel.
The linked PR should fix and close the issue.
