### ISSUE TITLE
Unable to modify pool in cntools

### ISSUE THREAD

**Issue by bxcimu** [cardano-community/guild-operators#424]
Hello,
Initially, after registration I had some issues with cntools recognizing my pool as being registered, but my pool showed up in daedalus and pooltool/adapools.org, (at that time I was getting this error: parse error: Unfinished JSON term at EOF at line 1705531, column 7) however, after 5.3.2 update it began showing up as registered in cntools however I am still unable to make any modifications as cntools shows this error: 
"WARN: No pools available that can be modified! first register a pool or decrypt existing if encrypted"
My pool ID: 07b960bfb24f21d474043f47034ed62f89f8ac1d3f7bf8c170
I updated cntools to the most recent version 5.3.3 but the issue still prevails, what can I do to mitigate this?
Thank you!

**Comment by rdlrt** [comment]
Querying a Pool - depends on presence of `pool.id`
Modifying a pool - depends on presence of cold keys (skey + vkey), VRF keys and pool registration certificate.

Absence of any of those files, or insufficient permissions / encryption to any of those files leads to message you refer to.

You can validate the list by doing cat against each of the mentioned files outside of cntools

**Comment by bxcimu** [comment]
I completely forgot that I moved my cold keys elsewhere. That was the issue, thank you so much for prompt response!
