### ISSUE TITLE
inRewards.sh script, if the owner.pk or owner.sk file has invalid content, it still creates a wallet

### ISSUE THREAD

**Issue by ashisherc** [cardano-community/guild-operators#426]
**Describe the bug**
While trying to create a wallet from the itn keys, if the keys are not valid, the script does throw an error about it but continues to create a wallet. The wallet is created even if the owner.pk is invalid.

**To Reproduce**
1. replace pk key with sk key and vise versa for the simple example
2. run itnRewards script
3. watch out for the errors
4. a wallet is created

**Expected behavior**
It should not continue to create a wallet

**Version:**
 - OS: Ubuntu 18.04
 - Product version: CNTools 5.0.3
 - Cardano Node version: 1.18.1
 - Network you're connecting to: mainnet

**Comment by DamjanOstrelic** [comment]
The error

`Error deserialising verification key: "(/\240]\206J\STXx\ETB!\STXI\240\NUL\245\203\DC2\161,\246\151<\194^\RS\133o\180\159\216`Eq\138\175\ENQ\n\230u:i0\EM\210A\DEL\186\145\232\169.\DLEc\138Br#\EOT\230\169\DC2H\196\202"
`
comes from cardano-cli, not CNTools. I might be able to fix this

**Comment by Scitz0** [comment]
> The error
> 
> `Error deserialising verification key: (/\240]\206J\STXx\ETB!\STXI\240\NUL\245\203\DC2\161,\246\151<\194^\RS\133o\180\159\216`Eq\138\175\ENQ\n\230u:i0\EM\210A\DEL\186\145\232\169.\DLEc\138Br#\EOT\230\169\DC2H\196\202`
> comes from cardano-cli, not CNTools. I might be able to fix this:
> 
> PR:
> #434

Great, merged your PR with a minor change to also check that the files exist and pattern match to check for normal and extended key format at the same time.
