### ISSUE TITLE
[BUG] - stake pool registration issue

### ISSUE THREAD

**Issue by tanzeelrana** [cardano-community/guild-operators#429]
I registered a staking `poolpool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3yI` and got the message that it was successfully registered. But now when I check pooltool.io I can find my pool there. But when I check the from cntools to show my pool info it says it is not registered. I also lost the 500 ADA registration fee :(

Can someone please help me with this issue.

**Registration was successful as you can see below** 

<img width="791" alt="Screen Shot 2020-08-18 at 9 41 22 PM" src="https://user-images.githubusercontent.com/2520028/90631404-b26b5280-e1f0-11ea-821f-5c42001e81d2.png">

**>> POOL >> SHOW says that my pool is not registered :( as you can see from the image below**

<img width="890" alt="Screen Shot 2020-08-18 at 9 58 41 PM" src="https://user-images.githubusercontent.com/2520028/90631666-2148ab80-e1f1-11ea-939d-b68664ad0648.png">
 
```
>> POOL >> SHOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Select Pool:

Tanzeel
[Esc] Cancel

Dumping ledger-state from node, can take a while on larger networks...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Tanzeel
ID : pool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3y
Registered : NO
Metadata
Name : Tanzeel Pool
Ticker : RANA
Homepage : http://businessthor.com/
Description : Tanzeel's ADA staking pool :)
URL : http://businessthor.com/tanzeelmeta.json
Hash URL : 054e837de7e5e0879ae09e8297c70a3a6ea02fd9c6ad64534fd68a81be4391bd
Hash Ledger :
Run arguments : --shelley-kes-key /opt/cardano/cnode/priv/pool/Tanzeel/hot.skey \
--shelley-vrf-key /opt/cardano/cnode/priv/pool/Tanzeel/vrf.skey \
--shelley-operational-certificate /opt/cardano/cnode/priv/pool/Tanzeel/op.cert

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Can someone please help me with getting this issue resolved soon please :( 

**My Wallet that I created and sent the 2000 ADA to :** 

*** transaction id : https://explorer.cardano.org/en/transaction.html?id=ca015fdd0971551dedea6734032a0735f7bf4ca3512a83b6af8b727f40fce06b

<img width="1090" alt="Screen Shot 2020-08-18 at 9 24 55 PM" src="https://user-images.githubusercontent.com/2520028/90631788-58b75800-e1f1-11ea-81ed-e1e22df78067.png">

![Screen Shot 2020-08-19 at 7 56 01 AM](https://user-images.githubusercontent.com/2520028/90631868-75ec2680-e1f1-11ea-88bf-f2151f7a61ff.png)

**New balance inc my Wallet is 1497.624602 ADA** 
```
 >> WALLET >> SHOW
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Select Wallet:

  adaStakeWallet 
  [Esc] Cancel 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Wallet   adaStakeWallet

UTxOs
                           TxHash                                 TxIx        Lovelace
----------------------------------------------------------------------------------------
4561d378d3c34e0109321fc6ea2f95cfe4acaab7b48d89353b04736d8e3b53ce     0        1497624602

Address             : addr1q8sx77tak5xcnf8mk34m9ug5e788eeta59hvgz2zj56swths9d6ylvz93r2nvx2ayyutujttjsctwkz9umtrms2wn65sfm7gd2
Funds               : 1497.624602 ADA
Era                 : shelley
Encoding            : bech32
Enterprise Address  : addr1v8sx77tak5xcnf8mk34m9ug5e788eeta59hvgz2zj56swtsup99z3
Enterprise Funds    : 0.000000 ADA
Rewards             : 0.000000 ADA

Delegated to Tanzeel (pool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3y)

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

press any key to return to home menu
```

**When I run List Pool command I see my pool registered**
![Screen Shot 2020-08-19 at 8 22 42 AM](https://user-images.githubusercontent.com/2520028/90634179-4b03d180-e1f5-11ea-91f4-95e93447d207.png)

**But when I run Pool Show command it shows my pool is not registered**
<img width="890" alt="Screen Shot 2020-08-18 at 9 58 41 PM" src="https://user-images.githubusercontent.com/2520028/90634267-6f5fae00-e1f5-11ea-8edf-b2979b5c0df8.png">

**Comment by DamjanOstrelic** [comment]
I can see it on pooltool.io under fc2966cf162529c09e3f25f558bf14d38b0c367301e7c3f4f3c6d6dd.

Registered with 2% margin, not 1% as shown here.

**Comment by tanzeelrana** [comment]
I modified those parameters. But the problem still exists (cntools.sh > pool > show > Registered > NO)

<img width="918" alt="Screen Shot 2020-08-19 at 5 37 55 PM" src="https://user-images.githubusercontent.com/2520028/90692231-c63fa480-e242-11ea-839e-3390b1f6835c.png">

**Comment by Scitz0** [comment]
What version of cardano-node do you use?

**Comment by tanzeelrana** [comment]
```
cardano-cli version
cardano-cli 1.18.0 - linux-x86_64 - ghc-8.6
git rev 25f882939b7b6e2672f65918019a89595e273ac4

cardano-node version
cardano-node 1.18.0 - linux-x86_64 - ghc-8.6
git rev 25f882939b7b6e2672f65918019a89595e273ac4

```

**Comment by Scitz0** [comment]
Pool >> List only check if pool.cert file exists in pool directory, should only be there on successful registration but not a real test.
Pool >> Show checks ledger state for your pool id to see what's actually registered on-chain and your pool id is not listed here.
The transaction id for your registration is 4561d378d3c34e0109321fc6ea2f95cfe4acaab7b48d89353b04736d8e3b53ce and I can see that this is registered on chain and the 500 ADA deposit is taken. 
Not really sure whats going on. 

What I don't really understand is that you say you modified your parameters, but this is a new registration and not a modification?
Is the goal to run two pools with the same ticker?

**Comment by tanzeelrana** [comment]
`Is the goal to run two pools with the same ticker?`
> NO 

`What I don't really understand is that you say you modified your parameters, but this is a new registration and not a modification?`
> I was able to use the `modify` option in `cntools` script to modify my new registration.

I don't know why I still get `Registered : NO` :(

**Comment by rdlrt** [comment]
@tanzeelrana 
1. Are you sure there is no 1.19.0 installed on your system in one of the paths (we've often seen users have different versions in ~/.cabal/bin and ~/.local/bin)
2. To replicate what cntools is doing at command line to trouble shoot, please run the below:
cd $CNODE_HOME/scripts
```bash
. ./env
. ./cntools.config
. ./cntools.library
TMP_FOLDER=/tmp/cntools
cardano-cli version
timeout -k 5 $TIMEOUT_LEDGER_STATE ${CCLI} shelley query ledger-state ${PROTOCOL_IDENTIFIER} ${NETWORK_IDENTIFIER} --out-file "${TMP_FOLDER}"/ledger-state.json
echo $?
pool_id=$(cat "${POOL_FOLDER}/${pool_name}/${POOL_ID_FILENAME}")
echo "Pool ID is: $pool_id"
ledger_pParams=$(jq -r '.esLState._delegationState._pstate._pParams."'"${pool_id}"'" // empty' "${TMP_FOLDER}"/ledger-state.json)
ledger_fPParams=$(jq -r '.esLState._delegationState._pstate._fPParams."'"${pool_id}"'" // empty' "${TMP_FOLDER}"/ledger-state.json)
echo "pParams: $ledger_pParams "
echo "fPParams: $ledger_fPParams"
```

**Comment by rdlrt** [comment]
Hi @tanzeelrana ,
Looks like your version is 1.19, not 1.18 - as pointed out by @Scitz0 
The pool ID format you're showing starts with `pool` instead of hex, which is only introduced in 1.19.

**Comment by tanzeelrana** [comment]
```
Pool ID : fc2966cf162529c09e3f25f558bf14d38b0c367301e7c3f4f3c6d6dd
```

```
Pool Name: Tanzeel

Pool: Tanzeel
PoolPubKey: pool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3y
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tanzeelrana** [comment]
@Scitz0  after running your script now my pool files are missing :( 

```
 >> POOL >> LIST
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
find: ‘/opt/cardano/cnode/priv/pool’: No such file or directory

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

press any key to return to home menu
```

**Comment by tanzeelrana** [comment]
@rdlrt so if I look at pooltool.io I can see my pool here : https://pooltool.io/pool/fc2966cf162529c09e3f25f558bf14d38b0c367301e7c3f4f3c6d6dd

```
Pool ID : fc2966cf162529c09e3f25f558bf14d38b0c367301e7c3f4f3c6d6dd

Pool Name: Tanzeel

Pool: Tanzeel
PoolPubKey: pool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3y
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tanzeelrana** [comment]
@rdlrt  I can't find the `POOL_ID_FILENAME` 

```
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/priv/pool/Tanzeel# ls -la
total 72
drwxr-xr-x 2 root root 4096 Aug 19 16:04 .
drwxr-xr-x 3 root root 4096 Aug 19 01:27 ..
-rw-r--r-- 1 root root  203 Aug 19 01:40 cold.counter
-rw-r--r-- 1 root root  187 Aug 19 01:27 cold.skey
-rw-r--r-- 1 root root  197 Aug 19 01:27 cold.vkey
-rw-r--r-- 1 root root 1327 Aug 19 01:27 hot.skey
-rw-r--r-- 1 root root  183 Aug 19 01:27 hot.vkey
-rw-r--r-- 1 root root    3 Aug 19 01:40 kes.start
-rw-r--r-- 1 root root  365 Aug 19 01:40 op.cert
-rw-r--r-- 1 root root  580 Aug 19 16:04 pool.cert
-rw-r--r-- 1 root root  231 Aug 19 16:04 pool.config
-rw-r--r-- 1 root root   57 Aug 19 01:27 pool.id
-rw-r--r-- 1 root root  145 Aug 19 01:33 poolmeta-20200819013345.json
-rw-r--r-- 1 root root  145 Aug 19 12:18 poolmeta-20200819121815.json
-rw-r--r-- 1 root root  145 Aug 19 16:02 poolmeta-20200819160248.json
-rw-r--r-- 1 root root  145 Aug 19 16:02 poolmeta.json
-rw-r--r-- 1 root root  230 Aug 19 01:27 vrf.skey
-rw-r--r-- 1 root root  176 Aug 19 01:27 vrf.vkey
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/priv/pool/Tanzeel#
```

**Comment by tanzeelrana** [comment]
@rdlrt this is my output from the script you provided. My pool id should be `fc2966cf162529c09e3f25f558bf14d38b0c367301e7c3f4f3c6d6dd` but its the newer version format somehow. How can I fix it ?

```

root@ubuntu-s-4vcpu-8gb-fra1-01:~# cd $CNODE_HOME/scripts
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# . ./env
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# . ./cntools.config
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# . ./cntools.library
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# TMP_FOLDER=/tmp/cntools
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# cardano-cli version

cardano-cli 1.18.0 - linux-x86_64 - ghc-8.6
git rev 9e06d6f9a293a9656bf6e31b7e5d0a9f498163d1

root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# timeout -k 5 $TIMEOUT_LEDGER_STATE ${CCLI} shelley query ledger-state ${PROTOCOL_IDENTIFIER} ${NETWORK_IDENTIFIER} --out-file "${TMP_FOLDER}"/ledger-state.json
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# echo $?
0

root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# pool_id=$(cat "/opt/cardano/cnode/priv/pool/Tanzeel/pool.id")
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# echo "Pool ID is: $pool_id"
Pool ID is: pool1ls5kdncky55up83lyh6430c56w9scdnnq8nu8a8ncmtd6txcz3y

root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# ledger_pParams=$(jq -r '.esLState._delegationState._pstate._pParams."'"${pool_id}"'" // empty' "${TMP_FOLDER}"/ledger-state.json)
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# ledger_fPParams=$(jq -r '.esLState._delegationState._pstate._fPParams."'"${pool_id}"'" // empty' "${TMP_FOLDER}"/ledger-state.json)
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# echo "pParams: $ledger_pParams "
pParams:  
root@ubuntu-s-4vcpu-8gb-fra1-01:/opt/cardano/cnode/scripts# echo "fPParams: $ledger_fPParams"
fPParams: 

```

**Comment by Scitz0** [comment]
Pool is created with 1.19.0 or latest master branch, else bech32 encoding of pool id instead of hex could not have happened.
If you have reverted after this it won't help as pool.id file now contains the bech32 encoding when CNTools expect hex, at least for now. 
You can fix it by running:
for 1.18.0:
`cardano-cli shelley stake-pool id --verification-key-file /opt/cardano/cnode/priv/pool/Tanzeel/cold.vkey > /opt/cardano/cnode/priv/pool/Tanzeel/pool.id`
or for 1.19.0:
`cardano-cli shelley stake-pool id --verification-key-file /opt/cardano/cnode/priv/pool/Tanzeel/cold.vkey --output-format hex > /opt/cardano/cnode/priv/pool/Tanzeel/pool.id`
Run this to verity that fc2966cf162529c09e3f25f558bf14d38b0c367301e7c3f4f3c6d6dd is written to the file:
`cat /opt/cardano/cnode/priv/pool/Tanzeel/pool.id`

**Comment by tanzeelrana** [comment]
YESSS! this solved the issue 👍  
I think it was because I did the following commands ( specifically `git pull origin master` ) in my setup that I got the latest commits while being on `1.18.0`

```
git fetch --tags --all
git checkout tags/1.18.0
git pull origin master
```

**All is well now**

<img width="796" alt="Screen Shot 2020-08-20 at 11 06 07 AM" src="https://user-images.githubusercontent.com/2520028/90789688-30088e80-e2d5-11ea-8123-39baa8011928.png">
