### ISSUE TITLE
Feature Request -backup with option to not include cold key.

### ISSUE THREAD

**Issue by signallhill** [cardano-community/guild-operators#432]
Please allow an option when doing a backup to do a backup minus the cold keys.

Right now backup does a full backup then asks to delete cold key. Instead do a backup with option to not include cold key. Then give option to delete cold key.

**Comment by Scitz0** [comment]
I'm interested to know more about why this would be needed. Seems like a dangerous thing to omit cold keys and then delete. A recipe for disaster in my book and end-user losing cold keys.

**Comment by signallhill** [comment]
My thinking is that if there is backup option without cold keys then, it can be restored or kept in bp online. The backup with cold keys go offline. This also minimizes user manipulation of the backup. 

if this confuses the enduser, then create 2 zip files at the time of backup - one with cold key and one without . label each as offiline backup and online backup. This way enduser would know to keep cold offline.

**Comment by rdlrt** [comment]
On the contrary - what you're suggesting sounds confusing.
Your backup contains everything, and allows you to delete your keys. Having a backup and deleting things partially (as suggested) is dangerous, insecure and gives false sense of being safe.
Having 2 backups/zips adds to confusion.
Backed up keys contains everything you need to make it offline - and option to delete keys gives users choice whether they want to keep sensitive stuff online / available to cntools
