### ISSUE TITLE
Cardano passive node peers and connections

### ISSUE THREAD

**Issue by nkengcrypto** [cardano-community/guild-operators#438]
During lunch of Cardano passive node with ./cnode.sh from this build: https://cardano-community.github.io/guild-operators/#/build?id=components, I have no peers and epoch/slot remain 0/0 for hours. I have checked to make sure that my port is configured correctly but Still have connection issues. Please help

**Comment by rdlrt** [comment]
Not relevant to cntools, you need to check your node logs for the issue (things like your old db folder, non existent socket folder, etc).

**Comment by nkengcrypto** [comment]
thanks for the response. I think my router might be having issues with outside connection that's why my node is not connecting.
