### ISSUE TITLE
lib64/libtinfo.so.5: no version information available 

### ISSUE THREAD

**Issue by dravenflash** [cardano-community/guild-operators#441]
**Describe the bug**
./prereqs.sh -og
Using yum to prepare packages for "CentOS Linux" system
  Updating system packages...
  Installing missing prerequisite packages, if any..
  Symlink updates not required for ncurse libs, skipping..
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib64/libtinfo.so.5: no version information available (required by /usr/local/lib/ghc-8.6.5/bin/../haskeline-0.7.4.3/libHShaskeline-0.7.4.3-ghc8.6.5.so)
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib64/libtinfo.so.5: no version information available (required by /usr/local/lib/ghc-8.6.5/bin/../ghc-8.6.5/libHSghc-8.6.5-ghc8.6.5.so)
/usr/local/lib/ghc-8.6.5/bin/ghc: /lib64/libtinfo.so.5: no version information available (required by /usr/local/lib/ghc-8.6.5/bin/../terminfo-0.4.1.2/libHSterminfo-0.4.1.2-ghc8.6.5.so)
Creating Folder Structure ..
Environment Variable already set up!
/opt/cardano/cnode/files

**To Reproduce**
Fresh install CentOS 8  run /prereqs.sh
**Expected behavior**

**Version:**
 OS:  CentOS 8
 yum info epel-release
Last metadata expiration check: 0:00:10 ago on Sun 23 Aug 2020 05:31:03 PM EDT.
Installed Packages
Name         : epel-release
Version      : 8
Release      : 8.el8
Architecture : noarch
Size         : 32 k
Source       : epel-release-8-8.el8.src.rpm
Repository   : @System
From repo    : extras
Summary      : Extra Packages for Enterprise Linux repository configuration
URL          : http://download.fedoraproject.org/pub/epel
License      : GPLv2
Description  : This package contains the Extra Packages for Enterprise Linux (EPEL) repository
             : GPG key as well as configuration for yum.

sudo yum install epel-release
Last metadata expiration check: 0:04:26 ago on Sun 23 Aug 2020 05:26:58 PM EDT.
Package epel-release-8-8.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by rdlrt** [comment]
You seem to be running prereqs as root? Your LD_LIBRARY_PATH needs to use /usr/lib64 - default for any standard linux operating system.
Usually running as root could mess things up, due to various things.
