### ISSUE TITLE
Use Cntools offline- 

### ISSUE THREAD

**Issue by mrbrinker** [cardano-community/guild-operators#442]
I would like to suggest a feature, not sure if it is practical. 

As we all agree on cold keys should never be on a server connected to the internet would be really good if we could use cntools to create txs and certificates offline and instead of trying to send it the script would stop before this step and output the file(s)  to a folder where we could cp and upload to our servers.

Thank you

**Comment by Scitz0** [comment]
It would be a nice feature to provide but supporting offline keys is complex for a couple of different reasons. It's worthwhile to look into though for how to best accomplish.

**Comment by rdlrt** [comment]
Merged in alpha branch
