### ISSUE TITLE
Logging cleanup

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#446]
Guild config is set to log using json format and the internal log rotation built into cardano-node. As the internal log rotation is broken currently old log files are never removed. This quickly fills up the hard drive. The cnode.sh script on restart move old log files to an archive folder but never actually does any cleanup. 

I see a couple of options for how to solve this.

1) Replace json logging with stdout and let systemd service handle the logging through syslog. Breaks support for CNTools block collector though so not the best option.
2) Add a cronjob that clean old files from system, something like:
`1 0 * * * /usr/bin/find /opt/cardano/cnode/logs/ -mtime +7 -name "*.json" -print -exec /bin/rm {} \;`
Removes all files older than 7 days ending with .json in logs folder.
3) Do nothing, out of scope for CNTools/Guild to handle logging. Issue open against cardano-node logging hopefully fixed soon.

Any other options to consider for how to handle this?

**Comment by rdlrt** [comment]
Just to add, if IOG accept and solve the [minor bug](https://github.com/input-output-hk/cardano-node/issues/992), this should be easily sorted natively without any additional scripts

**Comment by Scitz0** [comment]
Forgot to add a third option, do nothing. As you mention hopefully this will be solved in code soon and then this is a non-issue. Could also be classified as a required SPO sysadmin skill to know how to handle system logging.
Leaning more towards option 3 now.
