### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ljankok** [cardano-community/guild-operators#448]
It would be great if cntools could provide the option to register a (new) pledge wallet while paying for the fees with another wallet. It would then be possible to have a cold-wallet as the pledge wallet without ever having to put the private key on the hot-node because the payments are being done from a different wallet.

**Comment by cloudstake** [comment]
Along with this great idea, since it is possible to create a pledge wallet through Daedalus, and transfer base.addr, staking.addr, staking.skey, and staking.vkey files, would be great if there were a way to import these as part of registering the pledge wallet (and still pay for fees with a different wallet, as above). Basically, what Ijankok said, plus the ability to process non-cntools generated files.

**Comment by rdlrt** [comment]
@ljankok - you can provide a seperate owner stake key (thus, pledging) already while registering the pool. Your hot wallet can be an operator wallet with minimal amount.

@cloudstake - its generally safer to export and import staging tx than moving keys around, which is what we'd be looking at - to ensure that we dont have unnecessary keys lying on the online node, especially now that this feature is enabled on `cardano-node`.

**Comment by rdlrt** [comment]
Closing as original FR is already present, while the second comment would be similar to #442 .
Feel free to follow up (here or on #442 ) if you think comment above is incorrect

**Comment by ljankok** [comment]
> @ljankok - you can provide a seperate owner stake key (thus, pledging) already while registering the pool. Your hot wallet can be an operator wallet with minimal amount.
> 
> @cloudstake - its generally safer to export and import staging tx than moving keys around, which is what we'd be looking at - to ensure that we dont have unnecessary keys lying on the online node, especially now that this feature is enabled on `cardano-node`.

@rdlrt - Do you mean a multi-owner stake pool where the primary address is used as the fees payment wallet and the secondary address functions as the safe wallet? And then, from this safe wallet, the actual pledge can be done by manually delegating to the stake pool?

**Comment by Scitz0** [comment]
@ljankok - That is correct.

**Comment by ljankok** [comment]
> @ljankok - That is correct.

excellent, thanks!

**Comment by ljankok** [comment]
> Along with this great idea, since it is possible to create a pledge wallet through Daedalus, and transfer base.addr, staking.addr, staking.skey, and staking.vkey files, would be great if there were a way to import these as part of registering the pledge wallet (and still pay for fees with a different wallet, as above). Basically, what Ijankok said, plus the ability to process non-cntools generated files.

I have put together a set of 3 scripts for that:

On the hot-node I use:
step1-hot-build-transaction.sh
step3-hot-submit-signed-transaction.sh

On the air-gapped VM I use:
step2-cold-sign-transaction.sh

**Comment by ljankok** [comment]
> > @cloudstake - its generally safer to export and import staging tx than moving keys around, which is what we'd be looking at - to ensure that we dont have unnecessary keys lying on the online node, especially now that this feature is enabled on `cardano-node`.

@rdlrt 

I have put together a set of 3 scripts for that:

On the hot-node I use:
step1-hot-build-transaction.sh
step3-hot-submit-signed-transaction.sh

On the air-gapped VM I use:
step2-cold-sign-transaction.sh
