### ISSUE TITLE
Deleted cold and payment keys

### ISSUE THREAD

**Issue by docvlad51** [cardano-community/guild-operators#450]
My name is Vladimir and I am running Cardano staking pool. I kindly ask for your advice and help!
I had configured my BP using CNTOOLS (v. 5.3.5) and am running 2 relays on three separate servers (AWS). All three servers are in Private group and have only Private IP addresses. I access each of them through another, Public EC2 that I have in the same VPC Region. I am using Termius chain connection to connect to Private IPs through Public EC2 (with SFTP).
I registered my Cardano staking pool couple of days ago (Aug 21 actually). All was working fine until Aug 22/23. On Aug 22 I made a backup of my wallets and pool keys (and encrypted it), using CNTOOLS Backup option. I chose the option to delete the keys on my core (BP) server.
After I made the first backup file (cntools-20200821175436.tgz  - see below) and opted for Cntools option to delete the cold and payment keys I made another backup, this time without the keys that had been deleted during the first backup (cntools-20200821194604.tgz.gpg). That day I updated CNTOOLS to v. 5.3.6.

Enter key password (length >= 8)
Password: ***********             
Confirm:  ***********             

gpg: directory '/home/kikonyx/.gnupg' created
gpg: keybox '/home/kikonyx/.gnupg/pubring.kbx' created
/opt/cardano/cnode/backup//cntools-20200821175436.tgz successfully encrypted
Backup file /opt/cardano/cnode/backup//cntools-20200821175436.tgz.gpg successfully created

Do you want to delete private keys?

  [n] No 
  [y] Yes 

Deleted: /opt/cardano/cnode/priv/wallet/OWNER/payment.skey
Deleted: /opt/cardano/cnode/priv/wallet/PLEDGE/payment.skey
Deleted: /opt/cardano/cnode/priv/wallet/OWNER/stake.skey
Deleted: /opt/cardano/cnode/priv/wallet/PLEDGE/stake.skey
Deleted: /opt/cardano/cnode/priv/pool/KIKONYX/cold.vkey
Deleted: /opt/cardano/cnode/priv/pool/KIKONYX/cold.skey

I am using Termius chain connection to connect to Private servers IPs (BP and relays) through Public EC2 (with SFTP for file transfer). I tried to transfer the first backup file to my laptop but Termius SFTP didn’t work (could not do it). I tried with the second backup file and it went to my laptop no problem. After I transferred the second backup file (forgetting that the second one does not contain the cold and payment keys), I deleted all the files on my BP server. Hence, I was left with the second backup file only that was made after the keys had been deleted. I restored the file but unfortunately, there were no keys there (listed above in the first backup).

I’d require CNTOOLS expert to help to try to search, find and undelete either the backup file that I accidentally deleted or, the keys that CNTOOLS automatically removed during the backup process. 

My pool is still running but if I don't manage to get any help until the end of this month I'd probably delete the wallets, as I cannot do anything to retire the pool (KIKO) or get my pledge back. I would lose $15,000 in that case. I do want to continue providing staking pool to Cardano community but I don’t want to see my pool minting the blocks and people delegating ADA to it, and me not being able to do anything with it. I’d very much appreciate if you can provide help/support or advice. Thank you very much.

Best regards,

Vladimir (email: vlad.jovanovich@gmail.com; Telegram: @docvlad51)

**Comment by rdlrt** [comment]
Hey Vladimir 
I am sorry but as I advised on telegram, when you deleted the original backup with your keys, you ended up deleting your keys from disk. There isnt much that anyone can do, other than your storage expert to see if you can recover your deleted file contents.

**Comment by docvlad51** [comment]
Thanks Priyank,

 

I thought that guild ops might instruct me on where to look for deleted CNTOOLS’ files after the backup process. I am trying to get someone from AWS to help me out with recovering the files.  Appreciate your help and response.

 

Regards,

 

Vladimir

**Comment by rdlrt** [comment]
They should be in folder you backed up (and then deleted)
