### ISSUE TITLE
Guild LiveView - Future Requests

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#458]
Some gathered input from the community for how to improve Guild LiveView:

- Look into the output on mobile apps, does not seem to handle box-drawing characters properly in all cases. 
- Sanity check of the configuration values.
- Make the color scheme configurable.

**Comment by rdlrt** [comment]
1. Font on mobile apps for UTF-8 characters often have different spacings. One of the ways would be replacing those indicators with standard ascii characters (eg: using # , = , _, - ) for the same
