### ISSUE TITLE
#456

### ISSUE THREAD

**Issue by alwaei** [cardano-community/guild-operators#462]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - OS: [e.g. CentOS 8]
 - Product version: [e.g. CNTools 5.0.1]
 - Cardano Node version: [e.g. output of `cardano-node version`]
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]

**Additional context**

**Comment by alwaei** [comment]
Gunt

**Comment by rdlrt** [comment]
Empty issue
