### ISSUE TITLE
~/git/cardano-graphql/dist directory does not exist after yarn build

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#468]
**Describe the bug**
Instructions say to `cd ~/git/cardano-graphql/dist` but after running `yarn build` directory does not exist and returns the following error:
```
# cd ~/git/cardano-graphql/dist
-bash: cd: /home/cardano/git/cardano-graphql/dist: No such file or directory
```
Using `find ~/git/cardano-db-sync/ -type f -iname "index.js" | grep '/dist/' | wc -l` there are 104 directories that are named dist which contain a file named index.js. There are too many dist/index.js to determine which one to start with node.

**To Reproduce**
1. Follow instructions to build from [Build graphql](https://cardano-community.github.io/guild-operators/#/Build/graphql)
2. See `No such file or directory` error when trying to `cd ~/git/cardano-graphql/dist`

**Expected behavior**
1. The dist directory exists and changing to the directory succeeds.
2. Running node index.js in the final step of instructions succeeds as the correct index.js file is present in ~/git/cardano-graphql/dist.

**Version:**
 - OS: Ubuntu 20.04
 - Product version: CNTools 5.4.0
 - Cardano Node version: 1.19.0
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Comment by TrevorBenson** [comment]
Looking at the instructions to build cardano-graphql from source it appears the directory and index.js in question are probably `~/git/cardano-graphql/packages/server/dist/index.js`? If this is the correct path then whichever method below is preferred by the other contributors I will submit as a PR from my fork.

Symlink it:
`cd ~/git/cardano-graphql ; ln -s ./packages/server/dist ./`

Dull copy of the source:
`cd ~/git/cardano-graphql ; cp -rf ./packages/server/dist ./`

**Comment by rdlrt** [comment]
The graphql documentation is indeed behind. The `dist` folder being in root was output package that's moved since to `packages/server/dist`. We prolly might want to switch to that build folder instead of dist : 
1. To copy node_modules across
2. To use something that is easily upgradable with future versions.

Also, the environment variables required would need to be updated as they've been changed since.

**Comment by Scitz0** [comment]
I made a couple of notes last time I tried to build Hasura and cardano-graphql. 
Not sure if it is better handled in some other way or if there are more changes that are needed but here they are:

### Hasura
- Update to newer ghc (Hasura 1.3.x is compatible with 8.10.1 only)
```
ghcup install 8.10.1
ghcup set 8.10.1
```
- Install missing package (can't remember now but something required krb5 package)
  Depending on OS:
```
sudo yum install -y krb5-devel
sudo apt-get install -y libkrb5-dev
```
- Hasura CLI was required, could not find it in build from Hasura graphql-engine build. I downloaded it separate with (instruction from Hasura install docs):
`curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | INSTALL_PATH=$HOME/bin bash`

Cardano GraphQL
- I used these build commands to install version 2.0.0. 
  Instructions from cardano-graphql wiki: https://github.com/input-output-hk/cardano-graphql/wiki/Building
```
cd ~/git
git clone https://github.com/input-output-hk/cardano-graphql
cd cardano-graphql
git checkout tags/2.0.0
yarn --offline --frozen-lockfile && yarn build
```
- As the last step in the `Set up environment for cardano-graphql` section, I replaced the last three rows.
```
cd ~/git/cardano-graphql/dist
graphql-engine serve &
node index.js
```
with these lines
```
cd ~/git/cardano-graphql
graphql-engine serve &
node ./packages/server/dist/index.js
```

**Comment by rdlrt** [comment]
FYI - this is parked for now, as `cardano-graphql` doco and prerequisites are not being maintained (was removed in #476 ).
There is not a lot being bought to the table via `cardano-graphql` other than pre-defined queries, no reason why a lightweight service like postgREST or postgres.rest cant be used instead. Besides, this was only component using npm in the build tools.

This may be revisited in future

**Comment by oldcryptogeek** [comment]
o.0

**Comment by TrevorBenson** [comment]
@Scitz0  Anything that CNTools does not compile I will build a dedicated container for. Since `cardano-graphql` docs/prereqs are not being maintained I am closing out this ticket to reduce backlog. 

If I misunderstood and you meant the upstream docs & prerequisites are not actively maintained and `cardano-graphql` is intended to remain part of CNTools feel free to reopen this issue.
