### ISSUE TITLE
Error: Package: yarn-1.22.5-1.noarch (yarn) Requires: nodejs

### ISSUE THREAD

**Issue by AdamZWinter** [cardano-community/guild-operators#474]
**Describe the bug**
./prereqs.sh failed
Following the directions here:  https://cardano-community.github.io/guild-operators/#/basics?id=pre-requisites

To Reproduce:
**On fresh EC2 Linux2 instance:**
mkdir "$HOME/tmp";cd "$HOME/tmp"
curl -sS -o prereqs.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh
chmod 755 prereqs.sh
./prereqs.sh

**Expected behavior**
I was previous able to install a working node following the documentation here:  https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/building-the-node-using-nix.html     It didn't require anywhere near so many dependencies.  Is this project so scattered that node.js is required?  Libsodium AND openssl?

**Screenshots**

**Version:**
 - OS: Standard Linux2 EC2 instance spun up fresh just for this

**Comment by Scitz0** [comment]
prereq script install dependencies needed not only for cardano-node and all the different scripts but also to be able to use db-sync / cardano-graphql. The mentioned package causing a problem in your case (yarn/nodejs) is for cardano-graphql. 

A solution to lighten the dependency a bit could be to add a parameter to prereq script for the additional tools not commonly installed by all. It won't remove a huge portion of the deps but could be worth looking into.

**Comment by AdamZWinter** [comment]
For the dependencies I followed the documentation:  https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

And then ran ./prereqs.sh -si to skip the dependencies part and just get the folder structure and cntools
