### ISSUE TITLE
[CNTOOLS] - Update instruction prompt after registering pool

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#477]
As per prereqs.sh from #476 , the updated cnode.sh would allow to simply use $POOL_NAME env variable in cnode.sh to point to right keys. Thus, cntools.sh update instruction post pool registration can now be updated to say something on the lines of "Substitute value for POOL_NAME in `$CNODE_HOME/scripts/cnode.sh` "

**Comment by Scitz0** [comment]
Added in #471

**Comment by Scitz0** [comment]
#534 closes this issue
