### ISSUE TITLE
Integrate sendmytip.sh from pooltool

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#478]
We can do this either in gLiveView.sh (makes it folder structure independent) or in cnode.sh (makes it running as a service and will stay up or go down with the node).

My preference is gLiveView , as it would already have detected all the variables and will be just about adding a curl command - and to see output failure if there is an issue. In either case, we'd want this to be optional and only enabled if peepz modify a switch in the .sh files

**Comment by Scitz0** [comment]
Using gLiveView would require you to have it continually running. I prefer a systemd solution for this. So either integration in cnode.sh or as a separate script. The block collector script could be another alternative, it's what the sendmytip script was originally based on and the only script we already have parsing the json logs. This is the script that requires the least amount of modification to enable the feature.

**Comment by Scitz0** [comment]
After thinking some more about it I think the proper way to handle it is to integrate it into cnode.sh script. Block Collector script requires less work but feels weird to include a future like this in that script. Maybe include both pooltool tip and block collector in cnode.sh script as optional features?
Less work for end-user to have it all integrated into one script.

**Comment by rdlrt** [comment]
sure but then we'd have to be Ultra careful of not missing any child jobs when shutting down node.. can get a bit tedious

**Comment by Scitz0** [comment]
true, maybe best to keep this as a separate script/systemd service. Could rename block collector script to something more general for different log monitoring features. Looking for blocks and pooltool tip sending are two features currently requiring log monitoring but could be more stuff in the future.

**Comment by TrevorBenson** [comment]
Before I migrated my cntools into a containerized setup I had deployed it w/ the deploy-as-systemd.sh script. I then made the following sendmytip.service unit which `Requires` cnode.service and was defined as `After` cnode.service. I then modified the cnode.service to be `Before` sendmytip.service which should ensure the startup and shutdown orders.


```
# systemctl cat sendmytip.service
# /etc/systemd/system/sendmytip.service
[Unit]
Description=Send my tip to api.pooltool.io
After=network.target network-online.target cnode.service
Requires=cnode.service

[Service]
Type=simple
Restart=on-failure
RestartSec=5
User=cardano
WorkingDirectory=/opt/cardano/cnode/scripts
ExecStart=/bin/bash -l -c "exec /opt/cardano/cnode/scripts/shelley-sendmytip.sh"
ExecStop=/bin/bash -l -c "exec kill -2 $(ps -ef | grep [s]endmytip.* | tr -s ' ' | cut -d ' ' -f2)"
KillSignal=SIGINT
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=sendmytip
TimeoutStopSec=5
KillMode=mixed

[Install]
WantedBy=multi-user.target
```

```
# systemctl cat cnode.service
# /etc/systemd/system/cnode.service
[Unit]
Description=Cardano Node
After=network.target network-online.target
Before= sendmytip.service

[Service]
Type=simple
Restart=on-failure
RestartSec=5
User=cardano
LimitNOFILE=1048576
WorkingDirectory=/opt/cardano/cnode/scripts
ExecStart=/bin/bash -l -c "exec /opt/cardano/cnode/scripts/cnode.sh"
ExecStop=/bin/bash -l -c "exec kill -2 $(ps -ef | grep [c]ardano-node.*./opt/cardano/cnode | tr -s ' ' | cut -d ' ' -f2)"
KillSignal=SIGINT
SuccessExitStatus=143
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=cnode
TimeoutStopSec=5
KillMode=mixed

[Install]
WantedBy=multi-user.target

```

The reason for having both network.target and network-online.target in the `After` parameters is that in production environments I have observed services like distributed lock management and various components that can start so quickly after "network.target" that there are either no IP's assigned to the interfaces or traffic is not passing (potentially an issue in LACP and/or STP configurations). So I tend to require network-online.target which requires the network to be up, not just service/interface started.

I'm not using these any longer, however I see an edit occurred after the date I migrated both cnode and sendmytip into their own containers and use systemd to manage stopping, starting and restarting on failure the container. I believe I must have just performed a `:wq` by mistake however I can put both of these through a test to make sure they still work as expected, and described above in this issue.

**Comment by Scitz0** [comment]
Actually, network-online.target is the only one needed in cnode.service and is preferred over network.target which has very little meaning during start-up. Will make sure this change is added in a future update.

Also no need for double reference between cnode.service and sendmytip.service. It's enough to add this in sendmytip.service to have it depend on a running node and make sure it's started after cnode.service. network-online.target is implied here as its a dependency in cnode.service and sendmytip.service wont start until cnode.service has.
```
After=cnode.service
Requires=cnode.service
```

**Comment by TrevorBenson** [comment]
Agreed.

**Comment by rdlrt** [comment]
My preference is still to combine it with one of the existing service(s). Once we find some downtime, will add cnode recording pid to a file and send tip while PID is running, but need to put some thought and checks to trap and send correct kill signal to pid process upon shutdown

**Comment by TrevorBenson** [comment]
Either way is fine by me, just providing prior art as food for thought.

**Comment by Scitz0** [comment]
> My preference is still to combine it with one of the existing service(s). Once we find some downtime, will add cnode recording pid to a file and send tip while PID is running, but need to put some thought and checks to trap and send correct kill signal to pid process upon shutdown , backup option could be using cntools block collector as @Scitz0 mentioned

Agree, my reply above was mostly regarding the service unit implementation, not how to proceed with sendmytip.
Focus now is on the current alpha branch, once that has been merged and proven stable, we can start looking into this. I'm still of the mind that a single general-purpose cnode log monitoring script could be used to solve both block collector and sendmytip.

**Comment by Scitz0** [comment]
Included in CNCLI integration.
