### ISSUE TITLE
[gLiveView] - Versioning and auto updates

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#479]
Wonder if it makes sense to extend version and - optionally, handle auto updates (very simplified version) to `gLiveView` as well

**Comment by Scitz0** [comment]
Something I have thought of adding but never got around to. As you mention a simplified version compared to CNTools could be used. I don't think we need to keep any changelog, GitHub history should be enough for this.

**Comment by rdlrt** [comment]
Agreed, just a version # should be enough...and its single script so we wouldn't bother with handling patch versions
