### ISSUE TITLE
Feature Request: Have gLiveView.sh display if the node is on Mainnet or Testnet

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#483]
**Describe the Feature Request**
Currently I am manually modifying the CNODE_NAME to set `Cardano Node` to `Testnet Node`, as there is a 19 character limit. It would be nice if gLiveView either detected this or was configured to display Testnet (and/or Mainnet) to make it easier to distinguish on a NOC board or display of many nodes/relays.

**Comment by Scitz0** [comment]
I assume you are referring to NODE_NAME in gLiveView and not CNODE_NAME in prereqs script. 
Was meant to be a string that you are free to set to whatever you like. The 19 char limit is to not mess up the overall design but nothing will break if you set a longer name.

With this said we could use the name set with prereqs.sh -t parameter as default in the script.

**Comment by TrevorBenson** [comment]
Yes NODE_NAME, sorry "CNODE" has started to become a force of habit quickly. While functional it still relies on the user to name the path specific to the network. I can take this issue up in my fork and find options to submit for review and potential inclusion.

**Comment by rdlrt** [comment]
The only problem I see with that is, we're not restricted to two testnets.
I suppose using some assumptions, we can build distinction as per below:
- Mainnet
- Testnet (standard what everyone uses)
- Guild (which we spawn time to time - with new NWMagic)
- Custom (which could be peepz starting network temporarily)
