### ISSUE TITLE
[bug] CNTools: WARN: No wallets available that have funds to send!

### ISSUE THREAD

**Issue by des1re10** [cardano-community/guild-operators#484]
**Describe the bug**
I created a wallet and sent ADA to it. Then it had valid balance on it. See screenshot. Then i wanted to withdrawal the funds to another external address by using menu: Funds -> Send and it doesnt show up any valid wallet with any balance. Wallet is also not encrypted. I also dont see any status, that the available wallets are encrypted or not, this would also be very nice to know.

**To Reproduce**
Same behaviour with also a newly created Testwallet, but this had no ADA on it. Not sure if it only shows wallets with ADA on it.

**Expected behavior**
There should be at least one wallet with 1000 ADA on it where i can send ADA from.

**Screenshots**
![Screenshot 2020-09-15 20 19 19](https://user-images.githubusercontent.com/11975743/93248981-e8b8d500-f790-11ea-8ab2-00bc8cbdce23.png)
![Screenshot 2020-09-15 20 19 33](https://user-images.githubusercontent.com/11975743/93248995-ec4c5c00-f790-11ea-8f82-8c8754ded1c9.png)

**Version:**
 - OS: Ubuntu x64
 - Product version: CNTools 5.4.1
 - Cardano Node version: 

cardano-node 1.19.1 - linux-x86_64 - ghc-8.6
git rev 497afd7dedc5d5b9bdcdb0e3cac6a50bd9f7dd54

 - Network you're connecting to: 2017-09-23T21:44:51Z

**Comment by Scitz0** [comment]
You are most likely missing needed keys on disk, ie payment.skey
Did you use backup function and the option to delete private keys?
If so you first need to restore the deleted keys(only payment.skey needs to be restored) from the backup created.

Four files are deleted when using above option:
payment.skey
stake.skey
cold.vkey
cold.skey

**Comment by des1re10** [comment]
Knew it.

Yes i was using the backup and restore function and was using this option for security reasons. And never deleted any file manually. For the Wallet with the funds on it, none of the files, you mentioned, exist, also not in the backup file.

In my other wallet, without funds, only the payment.skey and stake.skey exist.

How in the world can a backup process be successful, when not all files are getting backuped? Please tell me?

I guess my funds are lost now? Or is there maybe a trash bin somewhere?

Who will compensate me for using this beta software?

**Comment by Scitz0** [comment]
I feel for you losing your keys but this functionality has been tested many times and I highly doubt the code is to blame. It packages the entire wallet and pool folders and all the keys therein. 

Have you made several backups and only kept the latest?
If so this will explain the missing keys. The first backup made contains all keys. If deleting private keys is chosen after this, keys are removed from disk and obviously not available in any future backups made unless you first restore the removed keys.

**Comment by rdlrt** [comment]
@des1re10

> How in the world can a backup process be successful, when not all files are getting backuped? Please tell me?

Backup is to save keys present, there is no way to software to define or know how much of your wallets are live/pools are registered, which determines how many files are present.

If you took backup before and only then deleted file using the wizard, it meant you had exactly same files in backup (at the time) as you did on server. Now, what you seem to have done - is take multiple backups (forgetting you deleted keys before), in case of which you may have more than 1 backup file. If so, it's best to spend your time looking where your original backup is which has the keys. The file names will be different

> Or is there maybe a trash bin somewhere?
Only you can determine where you saved/deleted/actioned your old backup. **You can check what you had entered before by issuing the command below (again assuming you havnt cleared your old logs for cntools).**

grep Backup $CNODE_HOME/logs/cntools-history.log

**Comment by des1re10** [comment]
Guys, seriously, there is a clear warning missing here!

Take a look at the backup functionality of Acronis for instance.

Its called full backup and incremental backup. There is a difference.

The usecase you call in your software tool is just backup and restore. Users who use this backup functionality will of course just keep doing backups over time and keeping the latest onces.

The first one should be at least called as master backup with private keys in it or something! Or at least a huge warning NOT to delete the first one, when doing further incomplete incremental backups.

Im software developer myself, and to me this is a clear testcase! Also a very important one!

Imagine is was putting 50k ADA funds in it and was completely relying on your backup functionality. Holy shit.

If you want to scare off, all the pool operators in future, just leave it as it is.

Please urgently fix and improve your backup and restore functionaly in future releases!

I bet i wont be the only one who will fall for this trap.

Some months ago, i had the same issue with Dashlane, they were also that clever not to backup all the data in their backups. And i covered a certain usecase here, which they never considered before. I should never trust any backup functionality of any tool again and do all this manually.

**Comment by Scitz0** [comment]
We will add a warning in a future update if one of these keys are missing when doing the backup.

**Comment by des1re10** [comment]
Okay thanks

**Comment by rdlrt** [comment]
Start by learning about key types. There are clear disclaimers that the scripts DO NOT act as substitute for pool ops to skip learning basics about keys.
