### ISSUE TITLE
[CNTOOLS] Cant register pool. pool.cert file missing, balance mismatch

### ISSUE THREAD

**Issue by des1re10** [cardano-community/guild-operators#485]
**Describe the bug**
I created a new pool and went through the whole register process. In the end runs in an endless loop. Getting error, that pool.cert file is missing (while i didnt touch the linux file structure) and also balance mismatch. I cant register my pool.

**Screenshots**
deleted

**Version:**
 - OS: Ubuntu x64
 - Product version: CNTools 5.4.1
 - Cardano Node version: 

cardano-node 1.19.1 - linux-x86_64 - ghc-8.6
git rev 497afd7dedc5d5b9bdcdb0e3cac6a50bd9f7dd54

**Comment by rdlrt** [comment]
The second screenshot suggests that there is a pool certificate missing, and just above that command output , there is another error, please provide the complete log to check the cause

**Comment by des1re10** [comment]
here is the log file. hope there arent any sensitive information being stored in it. [cntools-history.log](https://github.com/cardano-community/guild-operators/files/5235510/cntools-history.log)

**Comment by rdlrt** [comment]
Sorry - I should have been more specific, I was asking for your console log. The cntools-history.log is only for action logging 🙂

**Comment by des1re10** [comment]
Where is this file stored or should i do the whole register process again?

**Comment by rdlrt** [comment]
You'd have to go through the process to capture the log attempts

**Comment by des1re10** [comment]
![Screenshot 2020-09-17 02 41 07](https://user-images.githubusercontent.com/11975743/93406329-acb86980-f88f-11ea-9cb1-1c46f3074033.png)
![Screenshot 2020-09-17 02 41 14](https://user-images.githubusercontent.com/11975743/93406336-af1ac380-f88f-11ea-856d-62c127cdcff3.png)

**Comment by rdlrt** [comment]
Hmm it seems problem is due to your use of [] in the URL , best to avoid such characters - as even if we escape it from CNTools, we dont know if the wallets or other services will accept these or convert them as per below:
https://embedded-solutions.org/files/%5BEMS%5D_Pool.json
The URL mentioned has to be stored on ledger as-is, keeping it to alphanumeric (and hyphen) would be ideal in that case.

**Comment by des1re10** [comment]
Yeah this was also my idea first. Will try it again without these characters
