### ISSUE TITLE
Postgresl installation instruction 

### ISSUE THREAD

**Issue by AdamZWinter** [cardano-community/guild-operators#488]
These packages in the yum repository don't seem to exist anymore.  Just thought you might want to update that.

sudo yum install -y postgresql-server postgresql-server-devel postgresql-contrib postgresql-devel libpq-devel
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                                                                                    | 3.7 kB  00:00:00
No package postgresql-server-devel available.
No package libpq-devel available.

**Version:**
cenos rhel fedora (linux2 EC2 instance)

**Comment by rdlrt** [comment]
Did you setup epel for your yum?

**Comment by AdamZWinter** [comment]
No.  Forgot about that.  Sorry to bother you.

**Comment by AdamZWinter** [comment]
I started by trying to do:  sudo yum install epel-release
but that doesn't work anymore
So I installed from fedoraproject.org and still came up with nothing when I searched.
running repolist, it would seem the AWS has inserted their own repositories,   maybe they are trying to restrict what can be done?
