### ISSUE TITLE
cnode.sh no longer works with systemd

### ISSUE THREAD

**Issue by cyber-russ** [cardano-community/guild-operators#499]
**Describe the bug**
Upgraded to latest cntools prereqs. Built 1.20.0 node. Attempted to start cnode.service, but doesn't start until you add a line at the start of cnode.sh to specify CNODE_HOME.

**To Reproduce**
1. Install prereqs and build node
2. Run deploy-as-systemd.sh (or not if you've already installed previously given nothing has changed otherwise)
3. sudo systemctl start cnode.service
4. See error in /var/log/syslog that can't find file on line 4 as pointing to /scripts/env (because CNODE_HOME is not defined)

**Expected behavior**
service starts

**Screenshots**

**Version:**
 - OS: 20.04 LTS
 - Product version: Latest as of 26th Sept
 - Cardano Node version: 1.20.0
 - Network you're connecting to: mainnet

**Additional context**

**Comment by rdlrt** [comment]
Fixed via #500

**Comment by cyber-russ** [comment]
Thanks
