### ISSUE TITLE
Correction to Issue Delegation Certificate code for Setup Passive Node

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#50]
This applies to the file: Setup-Passive-Member.md

Sub-heading says "Create singing and verifying keys" should be signing, not singing.

Also, code for Create certificates should be:
cardano-cli issue-delegation-certificate \ 
--config $CNODE_HOME/files/ptn0.yaml \
--since-epoch <?> \
--secret $CNODE_HOME/priv/pbft0p.key \
--delegate-key $CNODE_HOME/priv/pbft0p.vfk \
--certificate $CNODE_HOME/files/pbft0p.json

**Comment by samcgill29** [comment]
This code allowed me to create a certificate, but when I use it to start the passive node I get error: Delegation Certificate Not from Genesis Key

**Comment by oldcryptogeek** [comment]
#52
