### ISSUE TITLE
Add slot leader schedule 

### ISSUE THREAD

**Issue by mrbrinker** [cardano-community/guild-operators#510]
IOG seems to be focused on other things and no development has been made to add this feature so far despite a large number of SPOs supporting the idea.

I believe would be very useful to add the slot leader schedule in Cntools so SPOs could plan maintenance around it even if it gives only the schedule for the next hour or so.

**Comment by DamjanOstrelic** [comment]
I believe the protocol is designed the way that we cannot figure out the slot leader schedule. I remember @ilap mentioning something about the possibility of re-creating this schedule for each epoch using some `secret` parameters.

At the moment, the slot leader schedule is intended to be hidden so there is no easy way to implement it into CNTools as far as I know.

**Comment by Scitz0** [comment]
Though I see the value in a feature like this, CNTools is a script built to utilize the existing functionality in cardano-cli and accompanying tools and package it in a way that is super easy to use. 

Until IOG adds this feature in the code you won't see it in CNTools.

I know the community member Andrew is working on reverse-engineering a way to talk to the node in a language other than Haskell. Though impressive progress has been made he is far from having a feature like this ready if even possible without changes on the Haskell side by IOG.

**Comment by mrbrinker** [comment]
@DamjanOstrelic It is possible, I only opened the FR after have discussed it with people who assured me it can be done outside IOG, not trivial but possible.
@Scitz0 I see where you come from and you have valid points

**Comment by rdlrt** [comment]
(Just adding my view on the topic for future reference, as I believe this was mentioned earlier elsewhere)

I am kinda strongly against the view of calculating or knowing schedule beforehand (tho understand someone will eventually do it):
- Calculating schedule is expensive (10 times more than ITN)
- it requires epoch nonce - which comes from a synched node, cant be independently done just using VRF
- as soon as you have this feature, the craziness with advertisements, shaming others, finding ways to win edge cases (clock hacks, groups/clusters, etc) start getting into view , socially its been shown as a pretty bad outcome

**Comment by rdlrt** [comment]
This was closed due to external dependencies on IOG repo
