### ISSUE TITLE
Topology updater still doesn't allow fetching after days

### ISSUE THREAD

**Issue by castpool** [cardano-community/guild-operators#520]
**Describe the bug**
The topology updater script executed once every hour still responds with "IP is not allowed to fetch this list" after days.
`{ "resultcode": "402", "datetime":"2020-10-09 15:15:00", "clientIp": "myIP", "iptype": 4, "msg": "IP is not allowed to fetch this list" }
`
**To Reproduce**
15 * * * * curl -s -o /path_to/topology.json "https://api.clio.one/htopology/v1/fetch/?max=15"

**Expected behavior**
Should return a list of 15 peers.

**Version:**
 - OS: Ubuntu 20
 - Product version: Using only the latest version of the script
 - Cardano Node version: 1.20 and 1.21.1
 - Network you're connecting to: Shelley mainnet

**Additional context**
I launched the script more than once per hour for the first few days (wrong crontab), then adjusted to once per hour, then deactivated the job for a day then reactivated the hourly job, but to no avail. Is it possible to be blacklisted for days just because of those multi requests per hour for the first couple of days ?

**Comment by rdlrt** [comment]
Are you sure you updated the script to specify your host details to ensure you're pulling and passing info using matching information?
Please provide the stdout response of your submission as well as the host so that @gufmar can check

**Comment by castpool** [comment]
I haven't updated the script to specify my host details, i am only using the one liner curl script, this way : 
`15 * * * * curl -s -o /path/to/topology.json "https://api.clio.one/htopology/v1/fetch/?max=15"`
full stdout response : `{ "resultcode": "402", "datetime":"2020-10-10 23:15:03", "clientIp": "MyRelayIP", "iptype": 4, "msg": "IP is not allowed to fetch this list" }`

Do i need to provide the IP address ? If so, is there a safe way to do it, other than posting it here ?

Thanks

**Comment by rdlrt** [comment]
> { "resultcode": "402", "datetime":"2020-10-10 23:15:03", "clientIp": "MyRelayIP", "iptype": 4, "msg": "IP is not allowed to fetch this list" }

Sorry , I meant result of your push, this is output of the fetch request 😢

**Comment by castpool** [comment]
I solved the issue by opening my server ports. Fantastic
Thanks a lot for your involvment !
