### ISSUE TITLE
Feature Request: Integrate leaderLogs from pooltool.io

### ISSUE THREAD

**Issue by signallhill** [cardano-community/guild-operators#521]
Is it possible to add the leaderLogs from pooltool.io into cntool or scripts.

https://github.com/papacarp/pooltool.io/tree/master/leaderLogs

**Comment by Scitz0** [comment]
Possible, sure. As Andrew cracked the code it's now out in the open so should be possible to integrate but it still requires a bit of custom manual steps, like figuring out epoch nonce. I know Adam host an API to grab this but not sure it's ready to be integrated into CNTools just yet. 

For now, I recommend the existing scripts available from pooltool etc. but adding as an enhancement to look into in the future.

**Comment by Scitz0** [comment]
included in CNCLI integration.
