### ISSUE TITLE
Error registering pool on chain; Balance mismatch

### ISSUE THREAD

**Issue by cloudstake** [cardano-community/guild-operators#530]
Ran through the create pool (works just fine) but during initial register and subsequent modify runs it fails with similar error: 
WARN: Balance mismatch, transaction not included in latest block (400,916.313387 != 400,916.102786)

CNTOOLS 5.4.1

**Describe the bug**
Verbose output of transactions (I broke them into multiple lines for readability):

# Calculate fee, new amount and remaining balance
cardano-cli shelley transaction build-raw --tx-in 200c685ada1433d6f745516490f6bcc1f54c4780225a20fe8129fd0f8cbea2ed#1 \
--tx-in b8d875f7266927e9369297179037ea0d5a8eb5ff0fc4c395b9ca6f90ebce63de#1 \
--tx-in e897a0c0ce7d1a59fc283f7f9dbfbca38bf6be794f8cfdec83873b58ec371a1f#0 \
--tx-in 1a66791910035901c58546ea0c8c456f1e255c833198a7b322e7972c89426ecc#0 \
--tx-in ec0f00242f6f72d7891815f3733ceea7413f655578ce4fc3fa7ff4cdc906f751#1 \
--tx-out addr1qx2hhu3025s0ns5k0ys0hsxdedqqtxcrjzeg2z5y44q5nyae0hdkajsp8vjxc2q7rqm64glr8ks9l4lmuj3e7au44gsqxyxzm8+400916313387 \
--ttl 11051599 \
--certificate-file /opt/cardano/cnode/priv/pool/[hidden]/pool.cert \
--fee 0 \
--out-file /tmp/cntools/tx0.tmp

cardano-cli shelley transaction calculate-min-fee \
--tx-body-file /tmp/cntools/tx0.tmp \
--tx-in-count 5 \
--tx-out-count 1 \
--mainnet --witness-count 3 \
--byron-witness-count 0 \
--protocol-params-file /tmp/cntools/protparams.json

fee is 0.210601 ADA
Balance left to be returned in used UTxO is 400,916.102786 ADA ( 400,916.313387 - 0.210601 )

# Build, Sign & Send transaction
Building transaction
cardano-cli shelley transaction build-raw \
--tx-in 200c685ada1433d6f745516490f6bcc1f54c4780225a20fe8129fd0f8cbea2ed#1 \
--tx-in b8d875f7266927e9369297179037ea0d5a8eb5ff0fc4c395b9ca6f90ebce63de#1 \
--tx-in e897a0c0ce7d1a59fc283f7f9dbfbca38bf6be794f8cfdec83873b58ec371a1f#0 \
--tx-in 1a66791910035901c58546ea0c8c456f1e255c833198a7b322e7972c89426ecc#0 \
--tx-in ec0f00242f6f72d7891815f3733ceea7413f655578ce4fc3fa7ff4cdc906f751#1 \
--tx-out addr1qx2hhu3025s0ns5k0ys0hsxdedqqtxcrjzeg2z5y44q5nyae0hdkajsp8vjxc2q7rqm64glr8ks9l4lmuj3e7au44gsqxyxzm8+400916102786 \
--ttl 11051599 \
--fee 210601 \
--certificate-file /opt/cardano/cnode/priv/pool/[hidden]/pool.cert \
--out-file /tmp/cntools/tx.raw

Signing transaction
cardano-cli shelley transaction sign \
--tx-body-file /tmp/cntools/tx.raw \
--signing-key-file /opt/cardano/cnode/priv/wallet/[hidden]/payment.skey \
--signing-key-file /opt/cardano/cnode/priv/pool/[hidden]/cold.skey \
--signing-key-file /opt/cardano/cnode/priv/wallet/[hidden]/stake.skey \
--mainnet --out-file /tmp/cntools/tx.signed

Sending transaction
cardano-cli shelley transaction submit \
--tx-file /tmp/cntools/tx.signed \
--cardano-mode --mainnet

Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Coin 400916313387) (Coin 401416313387))))]

**To Reproduce**

1. Run Pool modify (after it errored upon initial registration, I now only have modify option)

**Expected behavior**
Pool would get modified as CNTools calculates fees and handles all of the transactions

**Version:**
 - OS: Ubuntu 20.04
 - Product version: [e.g. CNTools 5.4.1]
 - Cardano Node version: 1.21.1 - linux-x86_64 - ghc-8.6 git reve 497afd...
 - Network you're connecting to: mainnet

**Additional context**

**Comment by rdlrt** [comment]
Closing as it's likely as what Ola mentioned + we have newer version, so this already is outdated
