### ISSUE TITLE
Feature Request: Accept environment for variables like POOL_NAME

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#536]
Suggesting handling POOL_NAME the same way CNODE_HOME is handled in cnode.sh.templ:

`[[ -z "$CNODE_HOME" ]] && CNODE_HOME="/opt/cardano/cnode"`

I have my own fork & branch already implementing the following in both cnode.sh.templ & env:

`[[ -z "${POOL_NAME}" ]] && POOL_NAME="TEST"`

I'm seeking input/feedback before submitting a PR. I used this same method in both env and cnode.sh.templ because I am passing environment variables via containers as well, which this will support defining it inside the env or just passing it down into the environment outside of env.

If this is acceptable I will submit a PR to resolve this Feature Request. If not and preference is to have env only declare a new POOL_NAME I can adjust the branch as well as how I am defining the POOL_NAME in deployment scripts.

**Comment by Scitz0** [comment]
Hi,
cnode.sh.templ is deprecated and not used any more, its just cnode.sh now.
Second, env file is not affected by POOL_NAME variable, this is a cnode.sh specific variable. 

I don't see any harm in implementing it this way but I have a couple of ideas for how it should be done so no need to create a PR. I will include a change for this in a coming commit. Might actually remove the POOL_NAME variable all together and just keep POOL_DIR as POOL_NAME is only ever used as part of POOL_DIR.

**Comment by TrevorBenson** [comment]
Sounds good. Any solution you prefer is acceptable to me as long as I can define either POOL_NAME or POOL_DIR in the container environment and is honored inside cnode.sh.

Thanks

**Comment by rdlrt** [comment]
Solved in #540
