### ISSUE TITLE
prereq.sh -n testnet not working

### ISSUE THREAD

**Issue by signallhill** [cardano-community/guild-operators#537]
**Describe the bug**
I was trying to run a node in testnet and used the prereq.sh -n testnet and no error were noted
however I still connect to the mainnet and the files also show mainnet.

**To Reproduce**
1. Go to '~/tmp'
2. Click on 'download and run prereq.sh -n testnet'
3. $CNODE_HOME/files still show mainnet files
4. See error - mainnet running

**Expected behavior**
Testnet files download and cnode running in testnet

**Version:**
 - OS: Ubuntu 20.04 LTE
 - Product version: CNTools 6.0.0
 - Cardano Node version: 1.21.1
 - Network you're connecting to: mainnet

**Comment by Scitz0** [comment]
I see that the help in prereqs.sh -h needs an update.
You need to use -f to force an update, else topology.json, config.json and both genesis files wont be update.
so in your case, use `prereqs.sh -n testnet -f`

**Comment by rdlrt** [comment]
Solved by #539
