### ISSUE TITLE
Feature Request: Integrate or provide similar functionality to topologyBlender from Crypto2099

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#538]
Is it possible to add topologyBlender from Crypto2099 or some other merge of public/private topology. I think I read another thread discussing internalizing this into cntools, which is fine with me. I will describe how I am currently setting this up however as food for thought.

[https://github.com/Crypto2099/topologyBlender](https://github.com/Crypto2099/topologyBlender)

Additional directory/file structures:
```
/opt/cardano/cnode/files/topology.d
/opt/cardano/cnode/files/topology.d/private
/opt/cardano/cnode/files/topology.d/public
/opt/cardano/cnode/scripts/topologyBlender/blend.sh
/opt/cardano/cnode/scripts/topologyBlender/setup.sh
/opt/cardano/cnode/scripts/topologyBlender/blender.conf
```

The layouts are fairly self explanatory but I will still provide explanations. 

- The private topology is stored in `/opt/cardano/cnode/files/topology.d/private`.
- The public topology is stored in `/opt/cardano/cnode/files/topology.d/public`. 
- The public file is updated by either topologyUpdater.sh or get_buddies.sh from pooltool.io. 
 - Running topologyBlender.sh then combines public and private topologies and places them into the default location `/opt/cardano/cnode/files/topology.json`.

I'm not married to any single solution, so if something else is in the works already we can close this ticket.

**Comment by rdlrt** [comment]
In this case, all the private/custom peers you want to add is added to CUSTOM_PEERS variable in topologyUpdater.

Splitting files across to multiple ones makes it a bit complex for average SPO users to understand - while for advanced users, it can easily be married with other solutions using jq + sed to topologyUpdater.sh file for any CUSTOM_PEERS

**Comment by TrevorBenson** [comment]
That works for me. I see all the applicable code inside topologyUpdater.sh. The only suggestion I have is potentially allowing this to be inherited from the environment:

`[[ -z "$CUSTOM_PEERS" ]] && CUSTOM_PEERS="None"`

**Comment by rdlrt** [comment]
Should be sorted in above mentioned PR
