### ISSUE TITLE
Autodetection of node socket and other vars does not work when running mutiple cnode* instances on same host

### ISSUE THREAD

**Issue by ADADE-Pool** [cardano-community/guild-operators#547]
**Describe the bug**
The autodetect of node socket does not work if more than 1 cardano-node is running on the same host. It is because the shell command ps -ef | grep "[c]ardano-node.*.${CNODE_HOME}" returns all processes that have e.g. /opt/cardano/cnode in their name.

**To Reproduce**
Have multiple installations of cnode with this naming:
/opt/cardano/cnode
/opt/cardano/cnode2
/opt/cardano/cnode3
/opt/cardano/cnode4

**Comment by Scitz0** [comment]
Short term solution, call them cnode1, cnode2... 
or wait for #548 to be merged into master.
