### ISSUE TITLE
Guild LiveView - new version 1.7 not work

### ISSUE THREAD

**Issue by SnappsProject** [cardano-community/guild-operators#554]
Hi,
after updating Guild LiveView, the new version (1.7) gives me an error "COULD NOT CONNECT TO A RUNNING INSTANCE, FAILED ATTEMPTS IN A ROW!" instead the old version (1.6 - backup) continues to work.

**Comment by Scitz0** [comment]
Please follow directions at https://cardano-community.github.io/guild-operators/#/upgrade
