### ISSUE TITLE
Enhancement to gLV

### ISSUE THREAD

**Issue by signallhill** [cardano-community/guild-operators#556]
Current peer list has Total/Unique/Unreachable/Skipped

It looks like Unreachable/Skipped are not listed but having this info shown may be helpful if this can be added.

**Comment by Scitz0** [comment]
Not sure what you mean by Unreachable/Skipped are not listed. If you mean the IP:PORT table unreachable are indeed listed. Only skipped, ie multiple connections from the same IP are not listed. 

This is changed in the upcoming 1.8. After this, all connections will be shown and the summary will only show total/unreachable to be less confusing.

**Comment by Scitz0** [comment]
Handled in v1.8
