### ISSUE TITLE
Post CNTools Upgrade the cntools.sh is no longer executable

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#558]
**Describe the bug**
Using the built in cntools update replaces the cntools.sh file with one that is not set executable, requiring a manual chmod +x.

**To Reproduce**
1. Run the cntools update option
2. Once complete pres up arrow to re-run cntools.sh
3. Observe error like: "bash: /opt/cardano/testnet/scripts/cntools.sh: Permission denied"

**Expected behavior**
After the update the file should still be executable so it can be immediately run without user modifying permissions.

**Version:**
 - OS: CentOS 8
 - Product version: CNTools 6.1.0
 - Cardano Node version: N/A
 - Network you're connecting to: N/A

**Comment by rdlrt** [comment]
Was one of the items fixed in CNTools 6.1.0, please execute chmod 750 once and you should be fine for CNTools (for gLiveView, skip/wait for upgrade to 1.9 directly)
