### ISSUE TITLE
prereqs.sh Alternate names does not transform directories with hyphens into underscores.

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#559]
**Describe the bug**
Running prereqs.sh to set an Alternate name like "name-testnet" tries to create a variable of `NAME-TESTNET_HOME=/opt/cardano/name-testnet`. Bourne shell, and I believe all shells I've used (csh, ksh, zsh, etc.), do not allow hyphens in variable names.

**To Reproduce**
1. Follow the guide
2. Run `$ ./prereqs.sh -f -s -t name-testnet`
3. See error

**Expected behavior**
Either:
1. prereqs.sh script should transform hyphens, and potentially any other characters not otherwise permitted in variable names, to underscores. 
2. prereqs.sh help output should provide guidance as to limitations on allowed names

I'd prefer the first behavior, but the second is acceptable as it helps avoid the issue.

**Version:**
 - OS: CentOS 8
 - Product version: CNTools 6.1.0
 - Cardano Node version: N/A
 - Network you're connecting to: N/A

**Comment by rdlrt** [comment]
Will be resolved in #561
