### ISSUE TITLE
Feature Request: Allow disabling key locking via chattr when encyrpting or decrypting pool or wallets.

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#563]
Some secure encrypted USB devices come default as fat32 and will be used by some SPO's to secure keys. For those who do not reformat their device as ext4 or other POSIX filesystems and want to use CNTools offline by mounting the device, chattr will not work. As keys would already be on encrypted hardware only connected during transaction signing an option to not require chattr to lock/unlock would be nice.

**Version:**
 - OS: CentOS 8
 - Product version: CNTools 6.1.0

**Additional context**
I remembered I ran into this during testing before reformatting an Apricorn. Low priority & actually does not impact me since I already reformatted my encrypted devices, but might be helpful to novice operators.

**Comment by Scitz0** [comment]
Should be a fairly easy thing to implement, putting on the list for the next release.

**Comment by Scitz0** [comment]
Option to disable chattr included in CNTools 6.2.0
