### ISSUE TITLE
cold.vkey in backup without private key

### ISSUE THREAD

**Issue by signallhill** [cardano-community/guild-operators#565]
**Describe the bug**
When backing up online backup by answering yes to delete private key, cold.vkey was still in the backup. Not sure if this is by design or a bug. This is in the latest cntool

**To Reproduce**
1. Go to 'cntool.sh'
2. Click on 'pool->backup & restore'
3. Scroll down to 'gave the location answered No to do you want to backup the cold keys'
4. On the Pool folder cold.vkey was still present

**Expected behavior**
cold.vkey should not be in the online backup

**Version:**
 - OS: [Ubuntu 20.04]
 - Product version: [CNTools 6.1.1]
 - Cardano Node version: [1.21.1]
 - Network you're connecting to: [mainnet]

**Comment by rdlrt** [comment]
vkey are public keys, deleting that key does not really mean much. So yeah - working as designed 🙂
