### ISSUE TITLE
Enhancement to gLV

### ISSUE THREAD

**Issue by signallhill** [cardano-community/guild-operators#568]
Is it possible to have gLV show the name of the pool without editing gLV.

cnode.sh has the POOL_DIR. Can gLV read this if Core is running and show the pool name automatically without editing gLV.

**Comment by rdlrt** [comment]
gLV works independently as a script too. Making a choice based on assumption that POOL_DIR exists will force gLV to be limited to users/folks who use guild folder structure.

But you can customise the NODE_NAME field within gLiveView.sh to identify your node uniquely between instances.

Hope this helps 🙂
