### ISSUE TITLE
Locale Issue - Incorrect calculation and formatting in gLiveMode script on Centos OS 8.

### ISSUE THREAD

**Issue by krzo93** [cardano-community/guild-operators#569]
**Describe the bug**
When running gLiveMode script on Centos OS 8, I am getting some printf errors on the display. 

**To Reproduce**
1. Run gLiveMode.sh on Centos OS 8
2. See error

**Expected behavior**
Correct calculation of tips, density etc..

**Screenshots**
![Screenshot_20201028_214858](https://user-images.githubusercontent.com/15124772/97495162-9fe76500-1967-11eb-9e1a-c6aa4a852263.png)

**Version:**
 - OS: CentOS 8
 - Product version: CNTools 6.1.1
 - Cardano Node version: 1.21.2
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Additional context**
This is the lines that are shown in the screenshot above.

./gLiveView.sh: line 746: printf: 17.91296296296296296200: invalid number
746: epoch_items=$(( $(printf %.0f "${epoch_progress}") * granularity / 100 ))

./gLiveView.sh: line 741: printf: 17.91296296296296296200: invalid number
741: epoch_progress_1dec=$(printf "%2.1f" "${epoch_progress}")

./gLiveView.sh: line 513: printf: 4.896071809053199e-2: invalid number
513: density=$(printf "%3.3e" "${density}"| cut -d 'e' -f1)

**Comment by rdlrt** [comment]
I suppose the scripts may not have been tested for other locales, but just to be 100% - could you check and confirm the output of the below:
``` bash
printf "%3.3e\n" "4.896071809053199e-2";echo $LC_ALL

LC_ALL='en_US.UTF-8'; printf "%3.3e" "4.896071809053199e-2"
```

**Comment by krzo93** [comment]
Hi @rdlrt 

First time I've got invalid number again, after the second command it seems to look fine I think.

Command: printf "%3.3e\n" "4.896071809053199e-2";
Output: 4.896e-02

Any idea what this is happening? Just locale related issue?

Thanks

**Comment by rdlrt** [comment]
> Any idea what this is happening? Just locale related issue?

Yeah - as I mentioned , most of the testing would've occurred using `en` locales. In your case, I am guessing your locale recognises numbers as comma (v/s decimal). Thus, causing trouble.

A quick fix for you would be to add the below to your $CNODE_HOME/scripts/env file (under User Variables section):
``` bash
export LC_ALL='C.UTF-8'
```

I would think that should make guild tools use C.UTF8 for locale values instead of your system default, thereby not hitting your issues

**Comment by krzo93** [comment]
Hi @rdlrt 

Yeah, I've changed my system default now to C.UTF-8. 

Thanks
