### ISSUE TITLE
Feature Request: Make easier checking versions via github

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#571]
Wondering if implementing git tags for each Major & Minor version update would be possible. A new tag for each patch version 
 is not part of this request unless that would be preferred method of handling git tags by most contributors. Tags would provide a simple way for building based on new minor versions via CI/CD pipelines without parsing the cntools.library parameters or building for every new repo commit. 

Beyond the obvious benefits this also helps with recent changes by Docker to implement rate limits on container pulls. Tags would allow focusing new builds and container pulls around a new minor release instead of every single commit to the repository.

**Comment by rdlrt** [comment]
Tags are much wider and may apply to entirr repo, not very useful when you have multiple products with different versions with unrelated dependencies
