### ISSUE TITLE
topologyupdater.sh not work with a 3 digit port

### ISSUE THREAD

**Issue by Darkstar91** [cardano-community/guild-operators#575]
My node is running with a 3 digit port (i have set in env CNODE_PORT=888)

i get always this error if i run topologyupdater.sh

{ "resultcode": "501", "datetime":"2020-11-04 00:45:25", "clientIp": "87.78.243.49", "msg": "invalid port" }

if i set a 4 digit port or a 5 digit port in env it works ...only with a 3 digit port not

please fix this bug

**Comment by rdlrt** [comment]
Is your port available publicly?
``` bash
nc -v 87.78.243.49 888
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection timed out.
```

**Comment by gufmar** [comment]
This validation rule was set based on recommendations to only use ports >1024  
The lower, "privileged" ports can only be started as root by default. 
ofc possible by editing pcap for who knows what he does (hopefully as non-root user)

We lowered the validation shields to 88 now.
