### ISSUE TITLE
Location of blocks directory can cause startup issues after database corruption.

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#577]
**Describe the bug**
A database corruption occurred during an OS crash, the node after that point would refuse to start normally and remain at 100-200% CPU (much higher than normal loading). To clear up the issue I removed immutable, ledger lock, protocolMagicId and volatile so they could be regenerated from scratch. I left the db/blocks folder so block history was retained for cntools. This however caused the node to fail to start as expected generating the following error message:

`NoDbMarkerAndNotEmpty "/opt/cardano/testnet/db/protocolMagicId"`

**To Reproduce**
1. Setup a node with CNTools
2. Run cntoolsBlockCollector.sh
3. Stop a running node.
4. Delete files and directories from ${CNODE_HOME}/db, but do not delete blocks directory.
5. Start the node
6. See error: `NoDbMarkerAndNotEmpty "/opt/cardano/testnet/db/protocolMagicId"`

Should be easy to reproduce without using cntoolsBlockCollector.sh and just having a directory/file exist inside db during startup.

**Expected behavior**
The node should start normally without existing database files and retaining block history.

**Version:**
 - OS: CentOS 8
 - Product version: CNTools 6.0.1
 - Cardano Node version:  1.22.1

**Additional context**
Blocks being collected from logs are not really part of the nodes database. To me it makes more sense to have it be a directory below logs: `${CNODE_HOME}/logs/blocks/`.

**Comment by rdlrt** [comment]
Thanks for report, cntools block collector is already almost stale and redundant via #576 , being replaced by cncli . Thus, this will automatically be not be relevant shortly

**Comment by Scitz0** [comment]
Yeah, thanks for this report. I didn't know that a non-empty db folder would make the node not start, a strange behavior. I will have to make some adjustments to #576 for this.
