### ISSUE TITLE
Upgrade from 5.4.1 to  6.1.1 doesn't let CNTools run after following prompt

### ISSUE THREAD

**Issue by bladarunner** [cardano-community/guild-operators#581]
The bug is the lack of progress after following the prompt to press "q"
`~ CNTools - What's New ~

Press any key to show what's new compared to currently installed release, use 'q' to quit viewer
`

**To Reproduce**
1. Go to CNtools and run it
2. Checks for version and then a prompt is displayed to continue or quit with the "what's new" section
3. After pressing "q" to quit
4. Displays "END" and nothing continues
5. Must press control+Z to end the process and get out.
![Screenshot 2020-11-12 223956](https://user-images.githubusercontent.com/69773473/99006505-79662400-253a-11eb-9f4b-c14ff5f81121.jpg)
![Screenshot 2020-11-12 224023](https://user-images.githubusercontent.com/69773473/99006506-79feba80-253a-11eb-9c5f-aa4c71316d4b.jpg)

**Version:**
 - OS: Ubuntu  20.4
 - CNTools 6.1.1
 - Cardano Node version: cardano-node 1.20.0
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Additional context**
Also happens if you type any other character to get out of the script prompt

**Comment by mrbrinker** [comment]
You need to press Q to quit and move forward.

**Comment by bladarunner** [comment]
> 
> 
> You need to press Q to quit and move forward.

Actually, if you look at step 3 above I do mention pressing "q". The expected stdout after the prompt to choose an option (either "q" or any other key) both always lead to an "(END)" stdout instead of the menu list for CNTools.... That is my point.

**Comment by mrbrinker** [comment]
Yes, but for me, when it gets to END I press Q again and it goes to the next menu.

**Comment by bladarunner** [comment]
> 
> 
> Yes, but for me, when it gets to END I press Q again and it goes to the next menu.

Thank you! That worked.
