### ISSUE TITLE
Handle CLI changes for cardano-addresses > v3.0

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#587]

**Comment by rdlrt** [comment]
![image](https://user-images.githubusercontent.com/3169068/104886140-5d10b880-59bd-11eb-9a87-c860f2ab9724.png)

This is kinda road blocker for us to continue (or atleast it'll force us down to actually use cardano-wallet + cardano-address CLI if upgraded. On the other side, cardano-address 2.1 already works with ghc 8.10. I prefer to defer this until MA-ry

**Comment by rdlrt** [comment]
closed via #922
