### ISSUE TITLE
Sample Service/Timer Units: topologyupdater.

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#588]
cnode-topoologyupdater.service
```
[Unit]
Description=CNODE topology updater
After=network-online.target

[Service]
Type=oneshot
User=cardano
RemainAfterExit=true
WorkingDirectory=/opt/cardano/cnode/scripts
ExecStart=/bin/bash -l -c "exec /opt/cardano/cnode/scripts/topologyUpdater.sh"
KillSignal=SIGINT
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=cnode-topologyupdater
KillMode=mixed

[Install]
WantedBy=multi-user.target

```

cnode-topologyupdater.timer
```
[Unit]
Description=Wake up cnode-topologyupdater.service once an hour hour
Requires=cnode-topologyupdater.service

[Timer]
OnUnitActiveSec=1h 30sec
AccuractySec=1us

[Install]
WantedBy=cnode-topologyupdater.service timers.target
```

**Comment by Scitz0** [comment]
This is exactly how I imagined implementing the timer service for topoloyUpdater. 
deploy-as-systemd.sh script handle all the systemd deployments so would be best added here.

We also need to separate the fetch and push in topologyUpdater.sh so that we can integrate the fetch in cnode.sh and also modify the cnode.service file with RuntimeMaxSec to restart the node at a given interval, asking the user when running deploy-as-systemd.sh if it's a relay and how long to wait between restarts. User can easily just rerun the deployment script to change the timer or disable it.

**Comment by TrevorBenson** [comment]
I must have typod while editing the content. I changed it to say "cnode-topologyupdater.service" everywhere instead of my original service unit name so it was more in line with your service unit naming conventions. Sorry about that.

Onto the restart of cnode.service. I find hardcoding a `RuntimeMaxSec` and Restart=always into the cnode.service a little less elegant of a solution than I would hope for. You mention the user can use the script to change or disable the timer. What methods does this follow, does it disable the service make the change and then enable it again? If not, how thoroughly have you tested changing or disabling the RuntimeMaxSec without actually restarting the service unit? Below I discuss some issues I've observed via systemd.

That said I haven't had time to rebuild one of the testnet servers to try out the alpha branch yet. So please take the following as general observations, not an attack on your implementation :+1:.

**Scenario**
Lets just say for example the user has a bug which causes DB corruption on shutdown or startup, or any other reason they come up with, and wants to avoid the restart completely. While the script attempts to make this simple, I'm wondering if it addresses edge cases.

**Potential Issues**
- Changing the `RuntimeMaxSec`, properly, requires the Operator to first stop the cnode.service unit. So once the service unit is started the safe process to change/disable the `RuntimeMaxSec` is cleanly stop the service, edit the unit, daemon-reload and start the service again. 
- Attempting to edit a service unit which has `RuntimeMaxSec`+`Restart=always` while the unit is active can have unexpected results. The timer can be completely ignored for 1 or more intervals or the new interval is the added to the existing interval causing a much longer time before restart, even if the interval was reduced to cause a restart sooner.
- I also found in some cases where editing a live service unit can cause a disconnect between the service unit and the state systemd reports, at least for some period of time if not until a full restart. This exposes itself by the service unit constantly showing a state of deactivating. It appears that this "can" clear itself up over time, however I have not tried to isolate how/when systemd regains sync with the services true state. This did not occur in every test I performed, but often enough to be concerned.

The above issues may be specific to a version of systemd, I am testing on CentOS ATM. However to follow a best practices in disabling/preventing a restart via `RuntimeMaxSec`, without an actual restart, the operator would have to either:

**Safe Steps / Workaround**
1. Stop the service, edit the service unit to remove RuntimeMaxSec, then start the service again.
2. Issue a notify with `EXTEND_TIMEOUT_USEC`, extending the runtime beyond `RuntimeMaxSec`. This would require setting an arbitrarily long extension or to repeat the notification and continually ask to extend the runtime.

This is exactly what a service timer is good for.. The cnode timer unit could provide similar logic achieved by `RuntimeMaxSec`. However in the above scenario the user could simply `systemctl disable cnode.timer` if they do not want the node to restart. They can also `systemctl list-timers` which provides very concise details about the **LAST** restart, timestamp of the **NEXT** restart, and the time **LEFT** until the **NEXT** restart. Also cron could suffice as well, but obviously doesn't provide the extra functionality that systemd timers do. However both methods keep changes to the restart logic out of the core service unit and the potential issues that can expose during ongoing maintenance.

I'd much prefer if the script adjusted a cnode.timer and restarted the timer (or cron job) to achieve a change in restart of the cnode service vs. restarting the actual service and editing the service unit. That said I'm not "dead set against" the above approach, but think it does deserve a discussion and/or additional testing before choosing a method.

**Other Issues**
- Timing of the restarts are not visible via a `systemctl status cnode.service` call. The operator can obtain the last restart time via the status call for the service unit or in the journald logs of the unit and then extrapolate the next restart time. I don't find either method an intuitive way to determine the next restart of a node.

**Comment by Scitz0** [comment]
Thanks for the well thought through and detailed post :) 👍 
I'm not stuck on RuntimeMaxSec, was just one way to handle it. I'm open to giving the timer approach a go as the first option for both topology hourly push as your initial service example show, and to use for cnode.service restart at set interval by the user when running deploy script. 

Had a plan to get a PR added for this during the day but got stuck on #589 instead 😉
But its next on the agenda so at the latest come weekend.

**Comment by TrevorBenson** [comment]
Unless there is benefit to leaving this in an open state, I was going to close it out as the work is underway in Alpha and @Scitz0 has already isolated & resolved many issues with the timer implementation under Ubuntu.

**Comment by Scitz0** [comment]
I think we can close this one, was just waiting for it to get merged but can just as well close now.
