### ISSUE TITLE
Consistency of Socket Path for Multiple Modules

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#61]
The instructions for starting cardano-wallet are as follows:

cardano-wallet-byron serve --node-socket $CNODE_HOME/sockets/pbft_node.socket --testnet $CNODE_HOME/files/genesis.json --database $CNODE_HOME/priv/wallet

the socket is called "pbft_node.socket"

However, the instructions for starting cardano-node as a passive node are as follows:

 CNODE_HOME=/opt/cardano/cnode
cardano-node run \
          --config $CNODE_HOME/files/ptn0.yaml \
          --database-path $CNODE_HOME/db \
          --host-addr $(curl ifconfig.me) \
          --port 9000 \
          --socket-path $CNODE_HOME/sockets/0 \
          --topology $CNODE_HOME/files/topology.json

Here, the socket path is just "0"  Shouldn't these two sockets be the same for communication between the wallet and the node?

**Comment by rdlrt** [comment]
Yes that's an oversight, thanks for reporting. Will update the docs
