### ISSUE TITLE
TopologyUpdater not including custom peers

### ISSUE THREAD

**Issue by fohor** [cardano-community/guild-operators#643]
**Describe the bug**
I added a new relay server and new IP. topologyUpdater.sh has acknowledged my new IP. I also added CUSTOM_PEERS. I updated my toplogy.json, but when I start cnode.sh the topology.json is updated to IP not allowed with IOG peers.

I think topologyUpdater has to do 4 successful ping before it gives peers. That is fine. However, my custom peers are not added to topology.json. Shouldn't IOG + my custom peers be added? 

**To Reproduce**
1. Setup new relay node
2. Systemd topology updater
3. Add custom peers to topology updater
4. start cnode, but topology.json does not have custom peers

**Expected behavior**
Custom peers need to be added even if the IP is not allowed

**Screenshots**
{ "resultcode": "402", "datetime":"time", "clientIp": "0.0.0.0", "iptype": 4, "msg": "IP is not allowed to fetch this list",  "Producers": [ { "addr": "relays-new.cardano-mainnet.iohk.io", "port": 3001, "valency": 2,  "debug":"default fallback result" } ]  } <--missing custom peers

**Version:**
 - OS: Ubuntu 20.04
 - Product version: Latest Master
 - Cardano Node version: 1.24.2
 - Network you're connecting to: mainnet

**Comment by fohor** [comment]
Adding to above: Even if I added my custom peers to topology.json when I restart cnode, it will update it back to above without custom peers.

**Comment by gufmar** [comment]
This sounds like a good and valid suggestion. let me look into it...

**Comment by gufmar** [comment]
the fetch endpoint now also returns custompeers, during the initial subscription wait time. 
thank you for this suggestion
