### ISSUE TITLE
correct handling of MaxConcurrencyDeadline

### ISSUE THREAD

**Issue by gufmar** [cardano-community/guild-operators#644]
**Describe the bug**
It looks like the guild mainnet config template contains an invalid parameter for `MaxConcurrencyDeadline` because it's named `bfcMaxConcurrencyDeadline`

**To Reproduce**
let prereqs.sh download the mainnet config template from 
https://github.com/cardano-community/guild-operators/blob/alpha/files/config-mainnet.json#L14

**Expected behavior**
set it to `MaxConcurrencyDeadline` with default value to 2 and an explanation to increase it to 4 for relays.

**Additional context**
The official mainnet config file currently does not mention this variable at all, and seems to default to 1
https://hydra.iohk.io/build/5098087/download/1/mainnet-config.json

**Comment by rdlrt** [comment]
I wouldn't recommend to increase beyond 2 as default behaviour, it is additional load on relays

**Comment by gufmar** [comment]
I agree 
solved by https://github.com/cardano-community/guild-operators/pull/645
