### ISSUE TITLE
Proxessed TX and mempool Tx at 0

### ISSUE THREAD

**Issue by stakecardano** [cardano-community/guild-operators#652]
On producer node:
Proxessed TX and mempool Tx at 0 after running deploy-as-systemd.sh
selected no on running TopologyUpdater
also no peers in, only out.
node is synced
turned off ufw to test but no difference

Ruining at 1.24.2 with latest cntools installed  using prereqs.sh

**Comment by rdlrt** [comment]
1. Did you register your pool relays for IOG to pick against?
2. Could you verify your CNODE_PORT in env file matches your pool relay information?
3. It is always recommended to know outside of IOG (via pool registration) atleast some other pool to add you to their relays, regardless of whether you are using topology updater

**Comment by stakecardano** [comment]
relays are are using TopologyUpdater "18 relays" plus custom url to: producer ip node and IOG url
standard 6000 in env same for relays
relays proxeseed TX fine. im using chrontab on them instead of systemd

**Comment by stakecardano** [comment]
think i found a propblem, looks like the topologyUpdater dont add custom urls to the the topology.json
