### ISSUE TITLE
CNTOOLS - logMonitor.sh: Different result running in terminal vs systemd service

### ISSUE THREAD

**Issue by samcgill29** [cardano-community/guild-operators#657]
**Describe the bug**
I get different results depending on whether I execute ./logMonitor.sh in my bash terminal or I try to start the systemd service, cnode-logmonitor.service.  Executing the script in the terminal works fine. However, the systemd service fails with the following message:
Dec 20 00:56:18 ip-10-10-2-58 cnode-logmonitor[935333]: Could not get 'ShelleyGenesisFile' from the node configuration file
Dec 20 00:56:18 ip-10-10-2-58 systemd[1]: cnode-logmonitor.service: Main process exited, code=exited, status=1/FAILURE
Dec 20 00:56:18 ip-10-10-2-58 systemd[1]: cnode-logmonitor.service: Failed with result 'exit-code'.
Dec 20 00:56:25 ip-10-10-2-58 systemd[1]: Stopped Cardano Node - Log Monitor.

The lines of code producing this error appear to be in the env file (lines 152-168):
if ! GENESIS_JSON=$(jq -er '.ShelleyGenesisFile' "${CONFIG}" 2>/dev/null); then
  if [[ ${OFFLINE_MODE} = "Y" ]]; then
    if [[ -f "${CNODE_HOME}/files/genesis.json" ]]; then
      GENESIS_JSON="${CNODE_HOME}/files/genesis.json"
    else
      echo "Could not find shelley genesis file in default location or 'ShelleyGenesisFile' from the node configuration file"
      return 1
    fi
  else
    echo "Could not get 'ShelleyGenesisFile' from the node configuration file"
    return 1
  fi
else
  # if relative path is used, assume same parent dir as config
  [[ ! ${GENESIS_JSON} =~ ^/ ]] && GENESIS_JSON="$(dirname "${CONFIG}")/${GENESIS_JSON}"
  [[ ! -f "${GENESIS_JSON}" ]] && echo "Shelley genesis file not found: ${GENESIS_JSON}" && return 1
fi

**To Reproduce**
1. Open terminal
2. Execute ./logMonitor.sh in the directory: /opt/cardano/cnode/scripts
3. monitoring begins normally

Next, stop the script from running and attempt to start the systemd service:
1. cnode.service is running
2. cnode-cncli-sync.service is running
3. sudo systemctl start cnode-logmonitor.service
4. inspect service status: sudo systemctl status cnode-logmonitor.service
5. Service has exited with status 1 and is trying to restart.
6. Stop service: sudo systemctl stop cnode-logmonitor.service

**Expected behavior**
cnode-logmonitor.service should not have any errors.

**Screenshots**
n/a

**Version:**
 - OS: Ubuntu 20.04 LTS
 - Product version: CNTools 6.3.1
 - Cardano Node version: 1.24.2
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Additional context**

**Comment by samcgill29** [comment]
Additional info:

Here are the declarations I have made in my env file:

#CCLI="${HOME}/.cabal/bin/cardano-cli"                  # Override automatic detection of path to cardano-cli executable
#CNCLI="${HOME}/.cargo/bin/cncli"                       # Override automatic detection of path to cncli executable (https
#CNODE_HOME="/opt/cardano/cnode"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
CNODE_PORT=3001                                         # Set node port
CONFIG="${CNODE_HOME}/files/mainnet-config.json"        # Override automatic detection of node config path
SOCKET="${CNODE_HOME}/sockets/node0.socket"             # Override automatic detection of path to socket
#TOPOLOGY="${CNODE_HOME}/files/topology.json"           # Override default topology.json path
#LOG_DIR="${CNODE_HOME}/logs"                           # Folder where your logs will be sent to (must pre-exist)
#DB_DIR="${CNODE_HOME}/db"                              # Folder to store the cardano-node blockchain db
EKG_HOST=127.0.0.1                                      # Set node EKG host
EKG_PORT=12788                                          # Override automatic detection of node EKG port
#EKG_TIMEOUT=3                                          # Maximum time in seconds that you allow EKG request to take before aborting
#CURL_TIMEOUT=10                                        # Maximum time in seconds that you allow curl file download to take before a
#BLOCKLOG_DIR="${CNODE_HOME}/guild-db/blocklog"         # Override default directory used to store block data for cor
#BLOCKLOG_TZ="UTC"                                      # TimeZone to use when displaying blocklog - https://en.wikipedia

#WALLET_FOLDER="${CNODE_HOME}/priv/wallet"              # Root folder for Wallets
#POOL_FOLDER="${CNODE_HOME}/priv/pool"                  # Root folder for Pools

**Comment by rdlrt** [comment]
> if relative path is used, assume same parent dir as config

I would classify that as a very bad config as you're dependent on the config file location instead of specifying the full path to genesis (as in examples of what is used by prereqs).

**Comment by rdlrt** [comment]
Solved after CNODE_HOMe was sppecified in env
