### ISSUE TITLE
gLiveView peer list shows 0 in/out after a node restart

### ISSUE THREAD

**Issue by ADA-Node** [cardano-community/guild-operators#668]
**Describe the bug**
The peer number in/out show 0 after a node is restarted.

**To Reproduce**
1. Started core node as system service.
2. Start gLliveView.
3. Keeping gLive open in another terminal, restart systemctl service.
4. Node looks like it starts correctly and processes transactions, but the Peers: Out/In remain at 0.

**Expected behavior**
The Peer list should show the correct number of peers.

**Screenshots**
none

**Version:**
 - OS: Ubuntu 20.04
 - Product version: gLiveView v1.15
 - Cardano Node version: 1.24.2
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Additional context**
none

**Comment by rdlrt** [comment]
Will be fixed by commit above (gLiveView1.16), to re-check PID upon restart as part of loop
