### ISSUE TITLE
TopologyUpdater includes pre allegra peers

### ISSUE THREAD

**Issue by fohor** [cardano-community/guild-operators#682]
Is it possible for topologyUpdater to do a allegra check and not include pre allegra peers in the topology.json?

Fail2ban works great on peers IN, but peers OUT still includes pre allegra peers.

Apologies if this is already addressed.

**Comment by rdlrt** [comment]
The peers that have not been upgraded will not be in sync , and thus - automatically be disqualified from the list. Thus, while not specifically checking for Allegra, this is already taken care of
