### ISSUE TITLE
Cant see Peer Out, and Peer in Doubles

### ISSUE THREAD

**Issue by tpbsv77** [cardano-community/guild-operators#683]
**Describe the bug**
With node running 1.24.2, when running Guild LiveView v1.15, I show 3 peers in and 3 peers out on my Block producer. I do have 3 relays for that Block Producer.

When I updated to LiveView v1.17, it now shows 6 peers in and 0 peers out. Its still getting txs and all, and producing blocks. 

On my second Pool, which uses the same 3 relays as the other one, it shows 3 peers in and 3 out like it should when running LiveView v1.15

**Screenshots**
![pool-peers](https://user-images.githubusercontent.com/6932127/103488002-6ef83600-4dd7-11eb-99a9-cb6d54951535.png)

**Comment by rdlrt** [comment]
Check and verify the cnode port in your env file

**Comment by rdlrt** [comment]
Closing due to no response
