### ISSUE TITLE
Feature Request: cntools interface to query db-sync

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#696]
**Describe the feature**
Provide a new cntools menu which allows querying a db-sync database. 

**Overview**
The query menu provides a list of query types to perform, epoch wallet or pool. Once a query type is selected the operator then chooses the criteria for the query (which epoch, wallet or pool) the exact query to run and if an additional filter of epoch, wallet or pool would apply. 

- Epoch queries are not specific to any wallet or pool, they query the entire chain for a given epoch, except when an additional filter may be applied of wallet or pool.
- Wallet queries are based on one wallets stake address. When applicable an additional filter (where clause) may be applied of epoch or pool.
- Pool queries based on one pools pool.id/pool.id-bech32 address. When applicable an additional filter (where clause) may be applied of epoch or wallet. 

**To Query Stake Distribution for the Pool**
1. Run CNTools
2. Choose `[i] Investigate Chain`  and observe the investigate (query) menu:
```
>> INVESTIGATE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Current epoch: 240
Investigate Query Menu Options

 ) Epoch            -  Valid Pools, Blocks Created, On-chain supply, Stake distribution
 ) Wallet           -  Transactions, Delegation History, Reward history
 ) Pool             -  Active Pledge, Live Pledge, Stake distribution, Number of blocks

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Select Investigate operation

  [e] Epoch Query
  [w] Wallet Query
  [p] Pool Query
  [Esc] Cancel 
```

4. Choose `[p] Pool Query`  and observe the pool query menu:
```
 >> INVESTIGATE >> POOL
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Current epoch: 240

Active Pledge          - See the Active Pledge within the snapshot for the current/given epoch
Live Pledge             - See the Live Pledge will show the current pledge and the epoch it becomes active
Stake Distribution    - See the Stake Distribution for the current or given epoch
Number of Blocks    - See the Number of Blocks produced for current, all or a given epoch

  [a] Active Pledge
  [l] Live Pledge
  [s] Stake Distribution
  [n] Number of Blocks
  [Esc] Cancel 
```
5. Choose `[s] Stake Distribution` and be presented with new menu to select epoch:
```
Enter epoch to list (enter for current):
```
6. Use the response to query db-sync
7. Render the returned SQL information in cntools tables.

**Additional context**
There is also a list of potential queries in gist [What db-sync queries I would like to see](https://gist.github.com/TrevorBenson/575206f357fab9f2a58c337856c40db3). Comments here or in the gist are welcome to help improve on this idea. Thanks to @rcmorano who already provided a large number of example queries.

A branch will be started to work on this following the issue submission. I do welcome any collaboration as I  would like to keep a clean layout similar to the rest of cntools and appreciate any advice or suggestions about this feature.

I could see a phase 2 of this feature which allows exporting queries to CSV file. For instance to provide details to delegators about rewards.

**Comment by TrevorBenson** [comment]
@Scitz0 Are there any examples of changing the base level menu besides when we are online or offline modes? Figured if somewhere within cntools.sh we have an example showing `println` dynamically building a menu based on `ENABLE_XYZ` parameters i would mimic it. If not I will implement it.

Thx

**Comment by Scitz0** [comment]
We don't have any dynamic menus currently. But would be interesting to tackle and solve :)
I assume the goal is to hide the [i] Investigate Chain choice in main menu if not enabled. Could be useful for blocklog as well.

**Comment by rdlrt** [comment]
I would prefer to use a PostgREST instance to query, and add a page to prepare postgREST instance. Allowing a flag to either use a local instance, or query a remote instance instead. Something we have discussed for long

**Comment by Scitz0** [comment]
> I would prefer to use a PostgREST instance to query, and add a page to prepare postgREST instance. Allowing a flag to either use a local instance, or query a remote instance instead. Something we have discussed for long

Sounds good to me. DBSync and PostgREST are not my area of expertise. But I gladly help with the integration in CNTools. 
Should we move this discussion to the new Discussion section instead?

**Comment by rdlrt** [comment]
agreed

**Comment by DamjanOstrelic** [comment]
Good idea, I have recently set up a postgREST instance for db-sync and doing some web development with it now for a video. I might be able to help with some of the tasks that come up from this.

**Comment by rcmorano** [comment]
Hey, I'll be sharing every query I come across and need on the [referenced gist](https://gist.github.com/rcmorano/c9e062def2ff126569c796e89c2844c7). I'll be adding some new procedures to support [lift-wallet](https://github.com/nothingalike/lift-wallet) like one to "get stake for address at slot N".

By the way, feel free to default to dandelion instance if you feel to; tho I'd encourage anyone to setup its own and start thinking how we could have a [dAPI](https://github.com/api3dao/api3-docs/blob/master/fundamentals/dapi.md) for such services :))
It's currently running on very low resources and might become unstable, but I hope to have some news from Catalyst soon (today?) so I can upgrade the deployment :D!

**Comment by rdlrt** [comment]
This is moved to discussion #699
