### ISSUE TITLE
"Failed to query protocol-parameters from node, not yet fully started?"

### ISSUE THREAD

**Issue by jamiewestell** [cardano-community/guild-operators#702]
When running gLiveview after deploying systemd processes I get the following error:

"Failed to query protocol-parameters from node, not yet fully started?"

cardano-node is running. I have tried a complete reimage and reinstall to no avail. It worked fine on two other machines yesterday.... but I can't get one downloaded today running. Any idea's? My env file is fresh from git.

**Comment by rdlrt** [comment]
Make sure you're on right branch, and that your node is responding. As the error suggests its not able to query protocol parameters, it could mean your node has not yet synched - which you can cross verify by querying manually outside of CLI.

**Comment by kzka90** [comment]
I fixed it now. I was in Master, when should've been in Alpha. I had everything updated to the latest version, but not just the guild-operators.

Thank you.
