### ISSUE TITLE
CPU utilisation has increased

### ISSUE THREAD

**Issue by cyber-russ** [cardano-community/guild-operators#720]
**Describe the bug**
Increased CPU utilisation by approx 10% on block producing nodes that are running cncli after upgrade to the latest version of cntools (as of 15/01/2021). No other configuration changes have been made.
No increased CPU utilisation on relays.

Services running on block nodes (same as before the upgrade)
cnode-cncli-leaderlog.service    cnode-cncli-ptsendtip.service    cnode-cncli-validate.service     cnode.service
cnode-cncli-ptsendslots.service  cnode-cncli-sync.service         cnode-logmonitor.service

Services running on relays (same as before the upgrade)
cnode-tu-fetch.service    cnode-tu-push.service     cnode-tu-push.timer       cnode-tu-restart.service  cnode-tu-restart.timer    cnode.service

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version:**
 - OS: [e.g. CentOS 8]
 - Product version: [e.g. CNTools 5.0.1]
 - Cardano Node version: [e.g. output of `cardano-node version`]
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]

**Additional context**

**Comment by Scitz0** [comment]
Could you try to identify the precise process that is causing the increase in your system?
It's not something I have seen on my systems.
Please also provide versions of sw in issue, like cncli version.
Commands like: `top -c` should show the top cpu consumers.

**Comment by cyber-russ** [comment]
hard to tell, very variable, example top-c below

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                               
   2113 cardano   20   0   20648  12060   7608 S   9.3   0.1   1:18.10 /home/cardano/.cargo/bin/cncli sync --host 127.0.0.1 --network-magic 764824073 --port+

cncli is present in the .cargo directory, -- version gives cncli 0.5.1
