### ISSUE TITLE
syntax error in gLiveView.sh

### ISSUE THREAD

**Issue by raghurammailbox** [cardano-community/guild-operators#733]
**Describe the bug**
gLiveView.sh throws following error
 (standard_in) 1: syntax error./gLiveView.sh: line 983

**To Reproduce**
node is started as systemd. 
./gLiveView.sh is executed the script crashed with following error messages
 (standard_in) 1: syntax error
(standard_in) 1: syntax error
./gLiveView.sh: line 983:

*Screenshot*
the scrip was made to run after the IF FI block around 983 was commented out

![error](https://user-images.githubusercontent.com/5757233/105636002-03603080-5e8c-11eb-9f94-f2f4c3f53d7f.png)

**Version:**
 - OS: Ubuntu 20.04
 - Product version:  installed by 
 - curl -sS -o prereqs.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh

**Comment by rdlrt** [comment]
Wait for the node to sync and reach shelley era and then start gLiveView, future versions already take care of this scenario
