### ISSUE TITLE
gLiveView peers unreachable on centos 8 due to tcptraceroute version

### ISSUE THREAD

**Issue by brainrecursion** [cardano-community/guild-operators#747]
**Describe the bug**
The version of tcptraceroute which gets installed on centos 8 does not work with gLiveView.sh. 
The command has to be run as root due to permissions. Also the output does not include [open] or [closed] which gLiveView relies on.

**To Reproduce**
1. Install on centos 8 without cncli
2. Test gLiveView.sh 
3. All out peers are shown as unreachable.
4. Run tcptraceroute command outside gLiveView to verify

**Expected behavior**

**Version:**
 - OS: CentOS 8
 - Product version: gLiveView 1.19.2
 - Cardano Node version: 1.25.1
 - Network you're connecting to: testnet

**Additional context**

**Comment by rdlrt** [comment]
I use gLiveView on CentOS 8 myself. tcptraceroute does *NOT* need to be run as root. If for some reason you have invalid permissions, it is likely an issue at your OS level - or the process of deploying tcptraceroute on your image.

**Comment by brainrecursion** [comment]
This is running on standard centos 8 image or red hat image on Azure.

**Comment by rdlrt** [comment]
@brainrecursion - We have now added `ss` as option before checking for tcptraceroute - as `ss` should be part of most linux distributions and is already used for fetching peers list
