### ISSUE TITLE
Docker image referencing external files that could change

### ISSUE THREAD

**Issue by chbfiv** [cardano-community/guild-operators#748]
I understand that these files are intended to change to a degree, but because of the use of this pattern the container you build is "dependent" on a moment in time which is really not ideal.

Instead this repo should be setup to "clone" and build from "src" with all the files committed. To get all the files committed as they change it would be easy to setup a cron / monitor that will commit changes in a diff to a git repo. So periodically download the files you want to monitor and check git for changes to these files. If you see changes commit them.

**Comment by rdlrt** [comment]
Could you please be a bit more specific on what you mean by the following:
- "these files are intended to change"
- "dependent" on a moment in time

The scripts already do clone and build from source using cabal , in stages - and only brings in delta at a time. which is why they're split into 3 stages.
(cc: @TrevorBenson @redoracle - seems related to docker design)

**Comment by redoracle** [comment]
Hi chbfiv, many thanks for your comment.

At the moment we do download the cfg every time we build a new image:
https://github.com/cardano-community/guild-operators/blob/alpha/files/docker/node/dockerfile_stage3

So every time  a new node version is out, a new image will be compiled, downloading the configuration at the time of compiling.

In this way we get the latest cfg correlated to the latest node version, every time you (or we) do run a 'docker build'

Does this answer your doubts?

**Comment by chbfiv** [comment]
I would consider this feedback of course and isn't required.

Reproducibility of the creation of the docker image was the purpose of my comment. I can't be sure to reproduce the same docker image that others are building from a given commit because at the time of build those configs could different (not sure not often these change). If you pulled those configs into the repo, then I could say that we are running the same docker image despite the fact we built them independent.

If your says I shouldn't worry about that because "latest" is always correct that is fine. Even just for myself I want Reproducibility so that when I'm debugging issues I can isolate changes and see them change over time (useful with git).

Feel free to close though if this concern isn't applicable here

**Comment by rdlrt** [comment]
So, is the feedback then to add a git commit from guild repo to the docker image build?

With regards other tools, the version of softwares are within each tool. Guild tools by themselves also provide an option to do update-in-place (not so much applicable to image as to containers).

Adding source of all that's compiled to base image potentially makes the storage unnecessarily huge, while cardano-node and cli binaries provide git commit info in versions. Though I understand your point as the tools will be downloaded with latest version at the time of build , I think that was the intent of moving releases. What I could think of potentially (and depends on what @TrevorBenson and @redoracle think) is adding a git commit from guild as well as other repos used to a build-version file, would that be a good middle ground?

**Comment by chbfiv** [comment]
> So, is the feedback then to add a git commit from guild repo to the docker image build?
yeah that is a simple option

**Comment by redoracle** [comment]
Added the following command to get the lates commit version stored in the guild home directory

# Commit Version 
RUN  curl -sL -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/cardano-community/guild-operators/commits | grep -v md | grep -A 2 prereqs.sh | grep sha | head -n 1 | cut -d "\"" -f 4 > ~/guild-latest.txt
