### ISSUE TITLE
7.1.4  prereqs.sh -l error

### ISSUE THREAD

**Issue by jim-jones** [cardano-community/guild-operators#750]
**To Reproduce**
per the Guild Operators doco:

-  curl -sS -o prereqs.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh
- chmod 755 prereqs.sh

now run

- prereqs.sh -l (or prereqs.sh)
and receive the following:

- Using yum to prepare packages for "Amazon Linux" system

  Updating system packages...
  Installing missing prerequisite packages, if any..
Error: Nothing to do
Command line error: no such option: --allowerasing
An error occurred while installing the prerequisite packages, please investigate by using the command below:
sudo yum -y install python3 coreutils pkgconfig libffi-devel gmp-devel openssl-devel ncurses-libs ncurses-compat-libs systemd systemd-devel libsodium-devel zlib-devel make gcc-c++ tmux git jq gnupg libtool autoconf srm iproute bc tcptraceroute dialog sqlite util-linux xz
It would be best if you could submit an issue at https://github.com/cardano-community/guild-operators with the details to tackle in future, as some errors may be due to external/already present dependencies
Exiting...

Version:

OS: Amazon Linux
Product version: CNTools 7.1.4
Cardano Node version: cardano-node 1.24.2 - linux-x86_64 - ghc-8.10
git rev 400d18092ce604352cf36fe5f105b0d7c78be074
Network you're connecting to: 2017-09-23T21:44:51Z

**Comment by rdlrt** [comment]
Hi there,
Could you share your yum version alongwith output of manually executing the mentioned command?
Thanks

**Comment by jim-jones** [comment]
$ yum version
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Installed: 2/x86_64                                                                  493:e72b459ddd4636cada9df2b87d3ef2ac7a43892b
Group-Installed: yum                                                                  12:d4fc72bef03514ec6c53aed1a9506d744e6233d4
version

**Comment by jim-jones** [comment]
need any other info?

**Comment by TrevorBenson** [comment]
@jim-jones The `--allowerasing` flag is actually a `dnf` option. I suspect your Amazon Linux image is based off of RHEL 7 (using yum version 3.4 and rpm 4.11), not RHEL 8 (dnf 4.4 and rpm 4.16), which is where the conflict comes in. Your `yum version` reports 2, where if you run `yum --version` you should see the the yum & rpm packages actual versions.

  I have only been setting up v8 based hosts and containers, even on EC2 instances. So I had not been donating much code back to differentiate v7 yum and v8 dnf, just for package name differences. If Amazon Linux has an image based on 8 this should work without error.  

  I'll start a branch to differentiate v7 (yum) and v8 (yum calling dnf) based distributions.

**Comment by jim-jones** [comment]
im on a new Amazon Linux image based off of RHEL 8.3. after running ./prereqs.sh -l i get this:

We have no automated procedures for this "Red Hat Enterprise Linux" system
please manually install required packages.
Their relative names are:
Debian: curl build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev tmux
CentOS: curl pkgconfig libffi-devel gmp-devel openssl-devel ncurses-libs ncurses-compat-libs systemd-devel zlib-devel tmux

I have manually installed all the required packages and still get this message

running yum --version produces:

4.2.23
  Installed: dnf-0:4.2.23-4.el8.noarch at Sat 31 Oct 2020 05:03:19 AM GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Wed 29 Jul 2020 12:23:18 PM GMT

  Installed: rpm-0:4.14.3-4.el8.x86_64 at Sat 31 Oct 2020 05:02:31 AM GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Fri 26 Jun 2020 03:03:24 PM GMT

**Comment by jim-jones** [comment]
closing this since i wasn't using RHEL 8

**Comment by wuTims** [comment]
Hi, I'm seeing this issue as well from v7 Amazon EC2 image.

yum --version
3.4.3
  Installed: rpm-4.11.3-40.amzn2.0.5.x86_64 at 2021-02-01 01:51
  Built    : Amazon Linux at 2020-09-28 17:17
  Committed: Sai Harsha <ssuryad@amazon.com> at 2020-09-08

  Installed: yum-3.4.3-158.amzn2.0.4.noarch at 2020-06-22 19:50
  Built    : Amazon Linux at 2020-04-30 00:03
  Committed: Trinity Quirk <tquirk@amazon.com> at 2020-04-29

Is there a branch that I should be using that supports v7? Should I remove the --allowerasing option? Or is the solution to upgrade my nodes to v8?
