### ISSUE TITLE
[FR] Manage multi assets via cntools

### ISSUE THREAD

**Issue by mrbrinker** [cardano-community/guild-operators#753]
As we approach Mary HFE later this month would be able to create if we could mint, burn, send etc Cardano native tokens

**Comment by rdlrt** [comment]
TBH - It is also a way to create meaningless spam and increase the size of ledger quite a bit network, but since the node allows it - yes, it will be supported

**Comment by Scitz0** [comment]
Implemented in CNTools 7.2.0 now available in alpha branch and soon to be merged into master.
