### ISSUE TITLE
gLiveView.sh / tcptraceroute using bug

### ISSUE THREAD

**Issue by devilus** [cardano-community/guild-operators#754]
tcptraceroute can't using without root privileges, therefore in gLiveView script this util always return "socket: Operation not permitted" and all peers always marks as unreachable.

**Comment by rdlrt** [comment]
tcptraceroute binary should usually have setuid bit set to root in absence of sudo. This should not be usually required on most OS but sounds like you'd need to in your case (or alternatively set cap_net)

**Comment by rdlrt** [comment]
The linked commit will remove the dependency on tcptraceroute if cncli is not being used completely, will be part of gLiveView 1.19.4 (and higher)
