### ISSUE TITLE
Sign pool registration transaction problem

### ISSUE THREAD

**Issue by devilus** [cardano-community/guild-operators#758]
Hey. I use a latest version of operator scripts on online and offline machines + cardano-hw-cli on offline machine. 

I already registered a wallet address using Ledger Nano S device.
But now when I try to sign offline transaction for pool registration always the error returns.  I tried several times but can't register a pool. Where is my mistake?

```
Do you want to sign Pool Registration with: Owner #1 'Ledger' payment signing key ?
Selected value: [y] Yes

INFO: follow directions on hardware device to witness the transaction
Error: Multiple pool registration certificates found, expected one

ERROR: during hardware wallet signing !!

press any key to return to home menu
```

**Comment by Scitz0** [comment]
You are not allowed to use Ledger wallet as main owner of a pool registration. Has to be a CLI wallet. Add Ledger wallet as a multi-owner to the pool. 

This should have been detected by CNTools. But I assume you didn't use CNTools to extract the keys from Ledger?
CNTools mark vkey file with the string 'Hardware' on import just like the hwsfile. This is used to distinguish it from a CLI wallet. 
payment.vkey description field gets value: `Payment Hardware Verification Key`
stake.vkey description field get value: `Stake Hardware Verification Key`

If you manually imported the keys, please replace description field of the vkeys like above.

**Comment by devilus** [comment]
Yes thanks @Scitz0 I understood. May be my solution helps for another users.

1) Create a separate CLI wallet using cardano-cli and top up this wallet to 505 ADA (pool registration deposit + some fee) onetime.
2) Register both wallets in cardano network.
3) When you register a pool select a CLI wallet with 505 ADA as main, and hardware wallet as additional owner and rewards address. So now your pledge and future rewards will be secure saved on a hardware wallet.
