### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mehmetkose** [cardano-community/guild-operators#765]
When I try to run **cntools.sh**, I'm getting these errors

<img width="876" alt="Screen Shot 2021-02-06 at 10 57 52" src="https://user-images.githubusercontent.com/706678/107112682-6e394080-686a-11eb-924f-1aa822c0a056.png">

Built the cli from the source, followed the docs. Everything is working except these.

OS: Ubuntu 20.04

**Comment by Scitz0** [comment]
This is not something I can replicate. Please re-download scripts to make sure they have not been corrupted.

**Comment by rdlrt** [comment]
Additionally, note that `[[` is a valid bash interpreter, the fact that it was not found suggests that your file didn't run in bash environment. Perhaps double check the bash binary exists where specified in shebang
