### ISSUE TITLE
Failing to modify pool owners

### ISSUE THREAD

**Issue by mrbrinker** [cardano-community/guild-operators#768]
**Describe the bug**
I am trying to add another owner but tx is failing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a 24 words Daedalus wallet, fund and register wallet by delegating to a pool.
2. Using cntools, IMPORT this newly created Daedalus using the mnemonics option, in a separate machine.
3. Create a new cli wallet, delete all the files in the wallet folder.
4. _cp base.addr, reward.addr and stake.vkey_ of the imported Daedalus wallet into the folder 
5. Try to include the imported wallet as one of the owners. It will fail as per screenshots.

**Expected behaviour**
To be able to add a new owner.

**Screenshots**

**Version:**
 - OS: [ Ubuntu 20.04 LTS]
 - Product version: [e.g. CNTools 7.1.4]
 - Cardano Node version: [e.g. output of `cardano-node version 1.25.1
![debug-2](https://user-images.githubusercontent.com/41247403/107172353-17656f80-6a00-11eb-8973-fbf7c6c64836.png)
![debug-1](https://user-images.githubusercontent.com/41247403/107172360-1b918d00-6a00-11eb-9dc9-07b87b5d64f5.png)

`]
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]

**Additional context**

**Comment by rdlrt** [comment]
> cp base.addr, reward.addr and stake.vkey of the imported Daedalus wallet into the folder

You need to sign the transaction in Hybrid mode using the stake private key of second wallet (owner_2) as well, preferably on offline machine. This part seems to be missing in the information provided.

Please double check the offline workflow [here](https://cardano-community.github.io/guild-operators/#/Scripts/cntools?id=offline-workflow) in case it was indeed missing

**Comment by Scitz0** [comment]
A bug related to removing keys has been fixed in alpha branch. Master currently doesn't like if you don't have both stake.vkey and payment.vkey in wallet folder.

**Comment by rdlrt** [comment]
Closing as alpha is now merged to master
