### ISSUE TITLE
Lines potentially off by 1 in promtail.yml

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#769]
@redoracle I haven't tried out the promtail stuff yet, but this line (and ones below it) I suspect are off by 1 space. The rest of the file has the standard 2 space alignment, the labels only have 1.

https://github.com/cardano-community/guild-operators/blob/1b2051daa0baf44529c2fc8e018efb926401b69c/files/docker/node/addons/promtail.yml#L63

**Comment by redoracle** [comment]
as far I can tell it works... did you experienced issues?
