### ISSUE TITLE
[CNTOOLS] ValueNotConservedUTxO (Mary HF)

### ISSUE THREAD

**Issue by papacarp** [cardano-community/guild-operators#776]
**Describe the bug**
When sending ADA from wallet to another in CNTOOLS it will fail if the sending wallet has any tokens

**To Reproduce**

```
# Select source wallet
Selected wallet: MARY (Funds: 903.827019 Ada)

# Amount to Send (in Ada)

Valid entry:  Integer (e.g. 15) or Decimal (e.g. 956.1235) - commas allowed as thousand separator
              The string 'all' to send all available funds in source wallet

Info:         If destination and source wallet is the same and amount set to 'all',
              wallet will be defraged, ie converts multiple UTxO's to one

Amount (Ada): 500

Fee payed by sender? [else amount sent is reduced]
Selected value: [y] Yes

# Select destination type
Selected value: [w] Wallet
Selected wallet: mary2 (Funds: 0.0 Ada)
Selected value: [b] Base (default)
Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (ValueNotConservedUTxO (Value 903827019 (fromList [(PolicyID {policyID = ScriptHash "a8754a2f4b43afee28efb1fda791acb0008c5f3aba4cf641ea5dccea"},fromList [("TESLA",30)])])) (Value 903827019 (fromList [])))))]

press any key to return to home menu
```

**Expected behavior**
I guess we need to decide if we are going to be able to send tokens around with CNTOOLS or just leave CNTOOLS for managing ADA.  If we send tokens around too, then more UI required in CNTOOLS.   If not, then at least we need to allow moving ada around between addresses that may have tokens as well.

**Screenshots**

**Version:**
 CNTools v7.1.6 - Testnet - CONNECTED 

**Additional context**

**Comment by Scitz0** [comment]
CNTools 7.1.6 is not Mary compatible.
Use CNTools 7.2.0 pushed to alpha branch to test this on testnet before pushed to master branch later this month.

-b alpha
