### ISSUE TITLE
Script not working on AWS RHEL 8.3 instance

### ISSUE THREAD

**Issue by jim-jones** [cardano-community/guild-operators#780]
**Describe the bug**
running ./prereqs.sh from $HOME/tmp results in the following output:

-  We have no automated procedures for this "Red Hat Enterprise Linux" system
please manually install required packages.
Their relative names are:
Debian: curl build-essential pkg-config libffi-dev libgmp-dev libssl-dev libtinfo-dev libsystemd-dev zlib1g-dev tmux
CentOS: curl pkgconfig libffi-devel gmp-devel openssl-devel ncurses-libs ncurses-compat-libs systemd-devel zlib-devel tmux

Exiting...

**To Reproduce**
1. launch new RHEL 8 AWS instance
2. sudo yum update
3. mkdir "$HOME/tmp";cd "$HOME/tmp"
4. ./prereqs.sh
5.  See described output above

**Expected behavior**
installation of the pre-requisites for building cardano node and using CNTools

**Version:**
 -   Operating System: Red Hat Enterprise Linux 8.3 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8.3:GA
       Kernel: Linux 4.18.0-240.1.1.el8_3.x86_64
       Architecture: x86-64
 - yum --version 4.2.23
  Installed: dnf-0:4.2.23-4.el8.noarch at Sat 31 Oct 2020 05:03:19 AM GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Wed 29 Jul 2020 12:23:18 PM GMT

  Installed: rpm-0:4.14.3-4.el8.x86_64 at Sat 31 Oct 2020 05:02:31 AM GMT
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Fri 26 Jun 2020 03:03:24 PM GMTProduct version: didn't get that far
 - Cardano Node version: **didn't get that far**
 - Network you're connecting to: **didn't get that far**

**Additional context**
Looking inside the prereqs.sh script when i the grep/cut commands (lines:171-173) used for setting OS_ID, DISTRO, and VERSION_ID variables this is what I get:

- OS_ID="fedora"
- DISTRO="Red Hat Enterprise Linux"
- VERSION=8.3
later in the scripts I see code like this which will not match any of the above values

- elif [[ "${OS_ID}" =~ rhel ]] || [[ "${DISTRO}" =~ Fedora ]]

**Comment by rdlrt** [comment]
Thanks for reporting, Should be fixed now by latest prereqs (as per PR linked above)
