### ISSUE TITLE
Import a Daedalus wallet

### ISSUE THREAD

**Issue by jhormanrus** [cardano-community/guild-operators#791]
I can´t import a Daedalus wallet :(
help

```
 >> WALLET >> IMPORT >> MNEMONIC

ERROR: need 'bech32' (command not found)
try 'sudo apt install bech32'
please install with your packet manager of choice(apt/yum etc..) and relaunch CNTools
ERROR: cardano-address and/or bech32 executables not found in path!
Please run updated prereqs.sh and re-build cardano-node

press any key to return to home menu
```

**Comment by rdlrt** [comment]
As the error message suggests, make sure `bech32` is in your $PATH. You can use instructions [here](https://cardano-community.github.io/guild-operators/#/Build/node-cli) while building your node to ensure bech32 is available as part of your build

**Comment by metinc** [comment]
Somehow I still can't get this to work. I followed the mentioned instructions step by step. I made sure to use the `-o` parameter. But still after executing `$CNODE_HOME/scripts/cabal-build-all.sh -o` all I have in `~/.cabal/bin` is `cardano-cli  cardano-node  cardano-node-chairman`. I expect to find `bech32` there.

**Comment by metinc** [comment]
> > Somehow I still can't get this to work. I followed the mentioned instructions step by step. I made sure to use the `-o` parameter. But still after executing `$CNODE_HOME/scripts/cabal-build-all.sh -o` all I have in `~/.cabal/bin` is `cardano-cli cardano-node cardano-node-chairman`. I expect to find `bech32` there.
> 
> Please execute cabal-build-all.sh with `-o` flag. This will overwrite cabal.project.local file in the cardano-node folder with the latest version from guild repo. This file is the one that set up bech32 and cardano-address to be built along with cardano-node.

Yes, that is exactly what I did. But somehow there is no `bech32` executable being built. However I found an older setup that I did on last Saturday where it was working. That was using an older cabal version. Could there be a connection? In my case everything was building fine on Cabal 3.2.0.0 but many executables are not being build on 3.4.0.0. If someone could confirm this I suggest reopening this issue.

**Comment by Scitz0** [comment]
I will go through all steps on a new fresh system to verify.

**Comment by Scitz0** [comment]
Ok, I can confirm that bech32 and cardano-address are not built with cabal 3.4.0.0.
Re-opening and looking into a solution for this.

**Comment by Scitz0** [comment]
Quick workaround until merged into master:
`ghcup rm cabal 3.4.0.0 &&  ghcup install cabal 3.2.0.0`
