### ISSUE TITLE
Errors when attempting to sign/witness pool modification with hardware device.

### ISSUE THREAD

**Issue by TrevorBenson** [cardano-community/guild-operators#792]
**Describe the bug**
Performing an offline/hybrid transaction signing with Ledger or Trezor device generates an error. Running a `cardano-hw-cli device version` shows the Ledger or Trezor device is connected prior to running cntools in offline mode to witness the transaction:

**Ledger Nano X:**
```
[cardano@adarelaysts01 ~]$ cardano-hw-cli device version
Ledger app version 2.1.0
```

When going to sign a transaction however it errors:
```
Do you want to sign Pool Update with: Owner #2 'Ledger_Nano_Old_Wallet0' stake signing key ?
Selected value: [y] Yes

INFO: follow directions on hardware device to witness the transaction
Error: Ledger device: Invalid data supplied to Ledger

ERROR: during hardware wallet signing !!

press any key to return to home menu
```

**Trezor Model T:**
```
[cardano@adarelaysts01 ~]$ cardano-hw-cli device version
Trezor app version 2.3.6
```

And during signing the transaction.
```
Do you want to sign Pool Update with: Owner #2 'TrezorTest1' stake signing key ?
Selected value: [y] Yes

INFO: follow directions on hardware device to witness the transaction
Error: Invalid address

ERROR: during hardware wallet signing !!

press any key to return to home menu
```
The associated base & payment addr's begin with `addr_test1`, so I do not believe they are incorrect.

**To Reproduce**
1. Modify a pool to include a new Ledger wallet as owner.
2. Copy offline transaction to machine where cardano-hw-cli can identify the ledger.
3. Attempt to sign the transaction

**Expected behavior**
The offline transaction should not provide invalid data to the Ledger or complain that the Trezor has an invalid address.

**Version:**
 - OS: CentOS 8.3
 - Product version: CNTools 7.1.6
 - Cardano Node version: cardano-node 1.25.1
 - Network you're connecting to: 1097911063

**Additional context**
Both wallets tested:

- Have funds
- Have rewards from delegating 
- Are currently registered and earning rewards on the testnet

Will try and look further into this later, but interested if anyone else has tried offline transactions and witnessing from HW wallets w/ v7.1.6?

**Comment by TrevorBenson** [comment]
Got it working by uncommenting some ENV components I would assume are not required for offline transaction signing.

I'm closing this for now. I will isolate which env changes fixed the error and will run some more tests. If this is reproducible in what should otherwise be a valid env for offline transaction signing I'll open a separate ticket.

**Comment by raphipik** [comment]
Hello, I am facing the same issue. May I ask what ENV component you uncommented?
