### ISSUE TITLE
cntools block reporter

### ISSUE THREAD

**Issue by oldcryptogeek** [cardano-community/guild-operators#793]
**Describe the bug**
CNTOOLS returns the current epoch number instead of the chosen epoch when viewing historical block data.

**To Reproduce**
1. In CNTOOLS choose (b)lock
2. Choose (e)poch
3. Enter desired epoch number
4. Correct epoch data is returned, but only the current epoch number is displayed, instead of the selected epoch number, which is slightly confusing to the user.

**Expected behavior**
I would expect the chosen epoch number to be displayed, instead of the current epoch, or perhaps both. :)

**Comment by Scitz0** [comment]
👍 I will add a `Selected epoch` to accompany the current epoch value.

**Comment by Scitz0** [comment]
Fixed in https://github.com/cardano-community/guild-operators/pull/789/commits/bee8be724b9e4d8b494e11690a32547980c249e2
