### ISSUE TITLE
Option error when running ./prereqs.sh

### ISSUE THREAD

**Issue by SproutPool** [cardano-community/guild-operators#795]
Ran ./prereqs.sh after fresh linux install in an AWS instance.

`Command line error: no such option: --allowerasing`

**Screenshot**
![image](https://user-images.githubusercontent.com/79178964/108671695-b0cb6180-7495-11eb-9efa-3cabb34a3ddf.png)

**Comment by rdlrt** [comment]
Please check the comment on previously raised issue [here](https://github.com/cardano-community/guild-operators/issues/750#issuecomment-774568706)
