### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by cpelon** [cardano-community/guild-operators#812]
**Describe the bug**
When I run Backup & Restore >> Backup I get the following error. Cannot open tty-output.

<img width="728" alt="Screen Shot 2021-02-25 at 7 25 50 PM" src="https://user-images.githubusercontent.com/1221883/109237491-a237bf80-779f-11eb-9700-29bf615bf5af.png">

Running Ubuntu 20.04 (LTS) x64 as non root user.

**Comment by rdlrt** [comment]
Hey  , could you provide a bit more detail about whether you used dialog, and if you did what was the path you elected?

**Comment by Scitz0** [comment]
The error message cannot open tty-output seem to indicate that dialog application doesn't run correctly on your system. Please troubleshoot this and/or disable dialog in cntools.config with `ENABLE_DIALOG=false`

**Comment by Scitz0** [comment]
I found this old blog post indicating that it might be related to the usage of --stdout in dialog call.
I will look into a workaround to skip this flag to see if this improves dialog compatibility. 

Reference: http://sgros.blogspot.com/2012/02/error-cannot-open-tty-output.html

**Comment by cpelon** [comment]
Thank you for pointing out the ENABLE_DIALOG=false this resolved my issue. Great tools, support and community guys!

Sent from my iPhone

On Feb 26, 2021, at 4:32 AM, Ola [AHLNET] <notifications@github.com> wrote:

﻿

The error message cannot open tty-output seem to indicate that dialog application doesn't run correctly on your system. Please troubleshoot this and/or disable dialog in cntools.config with ENABLE_DIALOG=false
