### ISSUE TITLE
Issue in output when running gLiveView output

### ISSUE THREAD

**Issue by pbwebdev** [cardano-community/guild-operators#820]
**Description**
gLiveView output is showing some strange output.
│   # :          REMOTE PEER   : RTT (ms)             [1-8] >  │
│   1 :           cubic:cubic  : cubic                         │
│   2 :             7,7:wscale :                               │
│   3 :             612:rto    :                               │
│   4 :             202:20.63.74.134 : rtt                           │

**To Reproduce**
Login to relay
Run gLiveView ./gLiveView.sh
Press P to view Peers

**Expected behavior**
Not expecting to see the strange output.
│   # :          REMOTE PEER   : RTT (ms)             [1-8] >  │
│   1 :           cubic:cubic  : cubic                         │
│   2 :             7,7:wscale :                               │
│   3 :             612:rto    :                               │
│   4 :             202:20.63.74.134 : rtt                           │

**Screenshots**
<img width="448" alt="Screen Shot 2021-03-04 at 7 34 22 pm" src="https://user-images.githubusercontent.com/3688954/109939226-935f8880-7d1c-11eb-8951-813fe3a5163a.png">

**Version:**
 - OS: Ubuntu
 - Product version: CNTools 8.0.0
 - Cardano Node version: 1.25.1
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Additional context**
Dumps from commands with IP address changed.

```
uname -a
ss -tnp | grep [c]ardano-n
```
Linux ip-3-3-3-3 5.4.0-1038-aws  #40-Ubuntu SMP Fri Feb 5 23:50:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

ESTAB   0        0            3.3.3.3:39881          20.63.74.134:6000     users:(("cardano-node",pid=171073,fd=61))                                      
ESTAB   0        53           3.3.3.3:6000         104.237.11.207:38666    users:(("cardano-node",pid=171073,fd=27))                                      
ESTAB   0        0            3.3.3.3:6000           193.93.62.33:64780    users:(("cardano-node",pid=171073,fd=65))                                      
ESTAB   0        53           3.3.3.3:6000         13.228.108.242:38343    users:(("cardano-node",pid=171073,fd=54))                                      
ESTAB   0        0            3.3.3.3:6000           193.93.62.33:65400    users:(("cardano-node",pid=171073,fd=63))                                      
ESTAB   0        0            3.3.3.3:39023         45.76.116.186:3001     users:(("cardano-node",pid=171073,fd=45))                                      
ESTAB   0        0            3.3.3.3:6000          139.218.11.14:37889    users:(("cardano-node",pid=171073,fd=80))                                      
ESTAB   0        0            3.3.3.3:44661         128.199.187.2:6000     users:(("cardano-node",pid=171073,fd=40))                                      
ESTAB   0        0            3.3.3.3:42931         45.76.143.126:6001     users:(("cardano-node",pid=171073,fd=50))                                      
ESTAB   0        0            3.3.3.3:45593         104.219.41.64:6000     users:(("cardano-node",pid=171073,fd=41))                                      
ESTAB   0        0            3.3.3.3:6000          103.6.168.131:38129    users:(("cardano-node",pid=171073,fd=42))                                      
ESTAB   0        0            3.3.3.3:33969        103.125.218.78:3001     users:(("cardano-node",pid=171073,fd=71))                                      
ESTAB   0        0            3.3.3.3:40087         154.16.57.198:50008    users:(("cardano-node",pid=171073,fd=73))                                      
ESTAB   0        0            3.3.3.3:33739       207.154.241.146:3000     users:(("cardano-node",pid=171073,fd=30))                                      
ESTAB   0        0            3.3.3.3:40797        54.241.118.248:6000     users:(("cardano-node",pid=171073,fd=53))                                      
ESTAB   0        0                127.0.0.1:12798             127.0.0.1:57952    users:(("cardano-node",pid=171073,fd=23))                                      
ESTAB   0        0            3.3.3.3:6000           139.59.30.23:33917    users:(("cardano-node",pid=171073,fd=56))                                      
ESTAB   0        0            3.3.3.3:44107         103.21.172.64:5250     users:(("cardano-node",pid=171073,fd=44))                                      
ESTAB   0        53           3.3.3.3:6000         178.128.112.85:39119    users:(("cardano-node",pid=171073,fd=26))                                      
ESTAB   0        12           3.3.3.3:46073         198.251.75.12:6000     users:(("cardano-node",pid=171073,fd=38))                                      
ESTAB   0        0            3.3.3.3:40173          78.47.61.125:6001     users:(("cardano-node",pid=171073,fd=25))                                      
ESTAB   0        0            3.3.3.3:44759        203.29.241.241:6000     users:(("cardano-node",pid=171073,fd=48))                                      
ESTAB   0        0            3.3.3.3:34269         35.177.114.27:3001     users:(("cardano-node",pid=171073,fd=47))                                      
ESTAB   0        0            3.3.3.3:43097          50.45.159.81:5001     users:(("cardano-node",pid=171073,fd=62))                                      
ESTAB   0        53           3.3.3.3:6000         54.254.116.215:45305    users:(("cardano-node",pid=171073,fd=46))                                      
ESTAB   0        0            3.3.3.3:43365         172.31.36.134:6464     users:(("cardano-node",pid=171073,fd=70))                                      
ESTAB   0        0            3.3.3.3:37767       207.244.224.162:6002     users:(("cardano-node",pid=171073,fd=32))                                      
ESTAB   0        53           3.3.3.3:6000         161.97.175.144:35521    users:(("cardano-node",pid=171073,fd=31))                                      
ESTAB   0        0            3.3.3.3:6000           18.195.83.21:43269    users:(("cardano-node",pid=171073,fd=43))                                      
ESTAB   0        0            3.3.3.3:35111        104.131.27.175:3001     users:(("cardano-node",pid=171073,fd=37))                                      
ESTAB   0        0            3.3.3.3:44643        139.64.236.125:3009     users:(("cardano-node",pid=171073,fd=34))                                      
ESTAB   0        0            3.3.3.3:42069         194.36.88.121:2122     users:(("cardano-node",pid=171073,fd=84))                                      
ESTAB   0        0            3.3.3.3:43307         45.79.250.148:3001     users:(("cardano-node",pid=171073,fd=36))                                      
ESTAB   0        0            3.3.3.3:6000          78.128.112.18:62608    users:(("cardano-node",pid=171073,fd=39))                                      
ESTAB   0        0            3.3.3.3:41929         45.79.236.135:6001     users:(("cardano-node",pid=171073,fd=51))                                      
ESTAB   0        0            3.3.3.3:6000          172.93.52.227:37673    users:(("cardano-node",pid=171073,fd=49))                                      
ESTAB   0        0            3.3.3.3:37111         64.227.48.151:3001     users:(("cardano-node",pid=171073,fd=64))                                      
ESTAB   0        0            3.3.3.3:41279        91.205.172.209:3001     users:(("cardano-node",pid=171073,fd=33))                                      
ESTAB   0        0            3.3.3.3:6000          172.31.36.134:33707    users:(("cardano-node",pid=171073,fd=35))

**Comment by Scitz0** [comment]
Please source env in terminal and then run the command used to get out peers, ie these commands:
```
. $CNODE_HOME/scripts/env
ss -tnp state established 2>/dev/null | grep "${CNODE_PID}," | awk -v port=":(${CNODE_PORT}|${EKG_PORT}|${PROM_PORT})" '$3 !~ port {print $4}'
```

**Comment by rdlrt** [comment]
Closing due to no response, can re-open if user comes back with reply

**Comment by danielstefanescu** [comment]
upgraded to v1.19.5 and I have the same issue on the block producer node:
![image](https://user-images.githubusercontent.com/19574258/111894889-43204000-8a17-11eb-901a-ddff195fa77b.png)

**Comment by pbwebdev** [comment]
The previous issue didn't return anything but on a new relay node, I've come across the issue again. Please see requested output.



```
$ ss -ni "dst  143.198.192.124:6000" | tail -1
	 cubic wscale:7,7 rto:316 rtt:115.283/0.385 ato:40 mss:1448 pmtu:1500 rcvmss:1017 advmss:1448 cwnd:10 bytes_sent:65503 bytes_acked:65504 bytes_received:14258230 segs_out:3404 segs_in:11492 data_segs_out:549 data_segs_in:11366 send 1004832bps lastsnd:988 lastrcv:868 lastack:868 pacing_rate 2009648bps delivery_rate 495600bps delivered:550 app_limited busy:33368ms rcv_rtt:115.118 rcv_space:378671 rcv_ssthresh:3144352 minrtt:114.312

$ ss --version
ss utility, iproute2-ss200602
```


Restarted the node and the issue have resolved itself.

**Comment by pbwebdev** [comment]
The IP address that this relay was connecting to was one of my other cloud relays.
CPU and RAM were maxed out.

![Screen Shot 2021-03-23 at 9 48 40 pm](https://user-images.githubusercontent.com/3688954/112141890-a4b3fa80-8c21-11eb-993a-55508f850c9a.png)

I removed the relay from the topology.

**Comment by Scitz0** [comment]
I dont know why the parsing fails but I just added some code in dev branch to at least filter out bad parsing like this.
Most likely rtt field in ss output is missing in some of the responses. 

Will be included together with 1.26.x update when this is pushed to master.

**Comment by joseiadicicco** [comment]
I have the same issue here:
![image](https://user-images.githubusercontent.com/33583361/113711620-8c30ef00-96bb-11eb-890f-e59799166a19.png)

**Comment by joseiadicicco** [comment]
@Scitz0 Could you please open this issue again, since I have the same issue and I would like to solve it? Thank you my friend.

**Comment by Scitz0** [comment]
> @Scitz0 Could you please open this issue again, since I have the same issue and I would like to solve it? Thank you my friend.

It's fixed in alpha branch where we develop for 1.26.x branch. So once this release is officially released we will push a fix to master.

**Comment by joseiadicicco** [comment]
> > @Scitz0 Could you please open this issue again, since I have the same issue and I would like to solve it? Thank you my friend.
> 
> It's fixed in alpha branch where we develop for 1.26.x branch. So once this release is officially released we will push a fix to master.

Okey @Scitz0, then you found where the bug was? Has any implications on my relay functioning? Can cause another issue to my relay or cause some block producing lost like another user sayed? In the meanwhile, there is something I can do to fix it?

Thank you very much!

Jose

**Comment by rdlrt** [comment]
@joseiadicicco - No it does not impact any functionality, it is only a check from network conmand ss, which for some reason gives a garbled value for your machine. But that does not impact your node

**Comment by Mirris** [comment]
Hello Cardano Stake Pool Operators,

even I am fresh new to the community and studying single relay before proceeding forward, I've already had a chance to encounter cubic:cubic, followed by node stuck and later crash.

Increased RAM from 4GBs to 8GBs helped. Uptime of 24+ hours already allocates 4.2G for cardano-node processes and is stable.
Mainly: it runs without issues. Giving it another 24hrs of observations, I believe this might be the way forward. Can't wait to join as active node in decentralised Cardano World :).

Hope my advice helps.

Cheers,
Miro

**Comment by rdlrt** [comment]
@Mirris  - 8gb is really the minimum memory requirement indicated in official docs. However, the state of node running is unrelated to this issue (which is more cosmetic based on output of `ss` command's parsing).

**Comment by Mirris** [comment]
perfect, thank you guys for boosting the code so fast -> I had a chance to see the chart yesterday of cardano being no.1 in commits on github. You have my heart, my investments and I am looking forward to work on a decentralized value exchange eco-system with you. Stay sharp you all & big big respect to developers and community!

**Comment by joseiadicicco** [comment]
Thank you both very much @rdlrt @Scitz0 !!
