### ISSUE TITLE
Imported wallets with zero ADA (CLI)

### ISSUE THREAD

**Issue by raphipik** [cardano-community/guild-operators#828]
**Describe the bug**
I imported a mnemonic (Daedalus) and a hardware wallet (Ledger) to my BP using cntools. The wallets were successfully imported and their receiving addresses match their respecting receiving addresses on Daedalus (the first address on Daedalus). The issue is that on Daedalus the wallets have funds, whereas on CLI the same wallets have zero ADA.

**To Reproduce**
Go to /opt/cardano/cnode/scripts and type ./cntools.sh

Follow the steps to import a wallet (for mnemonic wallet type your 24 words recovery phrase, for ledger wallet install relevant software + use HW to approve importation of wallet to CLI.

**Expected behavior**

I was expecting the funds on CLI to match the ones on Daedalus.

**Screenshots**

![Screenshot from 2021-03-08 16-43-57](https://user-images.githubusercontent.com/76642557/110296671-8d73eb00-802d-11eb-8800-06542deabcc2.png)
As you can see the addresses match.
![Screenshot from 2021-03-08 16-52-10](https://user-images.githubusercontent.com/76642557/110297610-a8932a80-802e-11eb-911b-1aba06cd76e9.png)
But it shows zero ada and behaves as such when I try to register said wallet.

**Version:**
 - OS: [e.g. Ubuntu]
 - Product version: [e.g. CNTools 5.0.1]
 - Cardano Node version: [e.g. output of `cardano-node version`]
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]

**Additional context**

I imported the mnemonic wallet on a Digital Ocean server (Ubuntu) and the hard wallet on my local computer (Ubuntu 20.04). I simply used cntools for both and followed the steps thereafter.

Please let me know if I need to provide more context/information. Thank you so much to the developers of cntools for making the process of creating and managing a stakepool more accessible!

**Comment by rdlrt** [comment]
When you import a wallet, you're told **exactly** why this would be the case. Please read more about [HD wallets here](https://cardano-community.github.io/support-faq/#/wallets?id=heirarchical-deterministic-hd-wallets).
Also re-import your wallet using mnemonics, pause and wait to read an fully understand the Note you see after importing the wallet.

**Comment by raphipik** [comment]
Thank you Priyank for your prompt reply. I apologize for making you repeat something that was already written. I will try to be more diligent.

Thanks again to you and your team for your work.
