### ISSUE TITLE
cncli errors in /var/log/syslog

### ISSUE THREAD

**Issue by cyber-russ** [cardano-community/guild-operators#831]
**Describe the bug**
cnode-cncli-leaderlog[10413]: Error message: invalid type: null, expected u64 at line 1 column 73

**To Reproduce**
1. Run cncli 1.4 (latest) on bpn.

**Expected behavior**
Not get errors

**Screenshots**

**Version:**
 - OS: 20.04LTS
 - Product version: Latest as 09-03-2021
 - Cardano Node version: 1.25.1
 - Network you're connecting to: mainnet

**Additional context**

**Comment by rdlrt** [comment]
Hey,
Sorry we missed to check this issue, do you still have this with the latest releases? Can we ask you to re-open on [cncli repo](https://github.com/AndrewWestberg/cncli) if the issue persists, assuming your sync status seems fine?
