### ISSUE TITLE
Change Prometheus node_exporter to localhost 

### ISSUE THREAD

**Issue by ruttkowa** [cardano-community/guild-operators#838]
**Describe the bug**
Prometheus node_exporter isn't starting when configigured with IP / Binds to IPv6

**To Reproduce**
1. Install through setup_mon.sh without any parameters passed.
2. Node_exporter systemd service fails to start.

**Expected behavior**
Node exporter should start with systemd and not fail.
If started from source / without systemd it did bind to IPv6 by default.

**Version:**
 - OS: RHEL 8.0.0
 - Product version: latest
 - Cardano Node version: 1.25.1

**Additional context**
Node_exporter can be startet with:
ExecStart=/opt/cardano/monitoring/exporters/node_exporter --web.listen-address=":9091"
as a workaround.
Further reading here: 
https://github.com/prometheus-operator/prometheus-operator/issues/3881

--> Proposed solution would be to change 127.0.0.1 to localhost in systemd service file.

**Comment by rdlrt** [comment]
We cannot simply use :9091, as you can see [here](https://github.com/cardano-community/guild-operators/blob/f5dabf7d8e812c53d9cb4ac4e5cb9b0f3220dd55/scripts/cnode-helper-scripts/setup_mon.sh#L293) , there could be genuine cases where CNODE_IP will be remote host and resolve to proper IPv4 address. A more plausible workaround for you could be using an intranet IP address instead.
