### ISSUE TITLE
Add compatibility with cardano-node 1.26.0 for guild tools

### ISSUE THREAD

**Issue by stevetko** [cardano-community/guild-operators#850]
**Describe the bug**
After upgrading a testnet core and relay node to 1.26.0, gLiveView 1.19.4 fails to connect to a running instance.

**To Reproduce**
1. Upgrade cardano node to 1.26.0 (1a25af85)
2. start node, wait for sync
3. start gLiveView 1.19.4

**Comment by rdlrt** [comment]
You're not supposed to use 1.26.0 *AT ALL* yet, unless compatibility is extended. Please do not rush into upgrades

**Comment by stikoian** [comment]
It was on the testnet - I communicated with Ola, and he said I should open an issue.

**Comment by rdlrt** [comment]
Updated title and moved to backlog as node 1.26.0 is bugged (wrt resource consumption) - and is not expected to go live at all to general public. The entire repo will anyways be updated to support 1.26(.x) - a compatible version that will actually be usable

**Comment by rdlrt** [comment]
A nice addition to cardano-cli would be [this](https://github.com/input-output-hk/cardano-node/issues/2509), and will impact (in a positive way) our integrations
