### ISSUE TITLE
I created a rewards wallet and i've accidentally assigned  the new wallet to be my main user pledge wallet.

### ISSUE THREAD

**Issue by VeganPoolOrg** [cardano-community/guild-operators#852]
When  I  modify my pool it only gives me the options to use my  new wallet which i accidentally made my main owner wallet.

I cant see how to select my original wallet as my main wallet with the pledge in it.

Im concerned the next epoch i will have a pool with no pledge assigned to it.

im on newest version on cn tools 

![image](https://user-images.githubusercontent.com/76780318/111773395-06810700-88a6-11eb-96b7-90c8bf6da882.png)

As you can see from the above image I only have the options to choose the previous wallets which happen to be the new wallet not my old previous wallet. A full list of previous wallets is needed to select the older one  otherwise i have no idea how to find it.

**Comment by Scitz0** [comment]
It should list all wallets that have payment.vkey and stake.vkey available in the folder. Please verify that you have all the needed keys available in the wallet folder.

**Comment by VeganPoolOrg** [comment]
![image](https://user-images.githubusercontent.com/76780318/111775349-8d36e380-88a8-11eb-94d2-cc9c5d90724c.png)

**Comment by VeganPoolOrg** [comment]
it shows it when i go to Wallet > List

**Comment by VeganPoolOrg** [comment]
It lists them in wallet list just not available in pool > modify

**Comment by VeganPoolOrg** [comment]
moved the keys required thank you :)
