### ISSUE TITLE
Issue in output when running gLiveView output - 1.19.5 

### ISSUE THREAD

**Issue by danielstefanescu** [cardano-community/guild-operators#854]
upgraded to 1.19.5 and I get strange output
  :          REMOTE PEER   : RTT (ms)               [1-4]  │
│   1 :           cubic:cubic  : cubic                         │
│   2 :             7,7:wscale :                               │
│   3 :             204:rto    :                               │
│   4 :               1:10.0.1.4 : rtt            
![image](https://user-images.githubusercontent.com/19574258/111894916-8b3f6280-8a17-11eb-8d0d-5b0361d08859.png)

**Comment by Scitz0** [comment]
Nothing changed in 1.19.5 compared to 1.19.4 that would affect this. 

Whats the output of:
```
. $CNODE_HOME/scripts/env
echo "use_lsof=${use_lsof}"
ss -tnp state established 2>/dev/null | grep "${CNODE_PID}," | awk -v port=":(${CNODE_PORT}|${EKG_PORT}|${PROM_PORT})" '$3 !~ port {print $4}'
```

**Comment by Scitz0** [comment]
Closing the issue, same as previous one #820. See response in that issue.
