### ISSUE TITLE
Error running cntools.sh

### ISSUE THREAD

**Issue by geantas** [cardano-community/guild-operators#874]
**Issue description**
I am following the docs from [here](https://cardano-community.github.io/guild-operators/). When running `./cntools.sh`, I am getting the following error:
```
\e[31mFailed to query protocol-parameters from node, not yet fully started?\e[0m

ERROR: CNTools failed to load common env file
Please verify set values in 'User Variables' section in env file or log an issue on GitHub
``` 
I am getting a similar issue when trying to run `./gLiveView.sh`:
```
\e[31mFailed to query protocol-parameters from node, not yet fully started?\e[0m
press any key to proceed...
```
If I press any key, I can see the UI and I can see it working there (not sure if it's working correctly, though).

**Steps To Reproduce**
1. Install `cardano node 1.25.1`
2. Follow documentation on https://cardano-community.github.io/guild-operators/ 
3. Come to a step to install the CNTools
4. Execute `./cntools.sh` command
5. See error

**Expected behavior**
Installation of the script went successful.

**Version:**
 - OS: Ubuntu 20.04
 - Product version: [e.g. CNTools 5.0.1] - ***not installed***
 - Cardano Node version: [e.g. output of `cardano-node version`]
```
cardano-node 1.25.1 - linux-x86_64 - ghc-8.10
git rev 9a7331cce5e8bc0ea9c6bfa1c28773f4c5a7000f
```

**Additional context**
I haven't changed anything in the `env` file, so I have default values there:
```
CNODE_PORT=6000
#POOL_NAME="" (commented out)
```

Any help/guidance would be much appreciated!

**Comment by rdlrt** [comment]
Hi There, 
Have you used testnet to get up and going familiarising with usage first? You need to ensure your node is set up , and variables are set in env file first.

Please use telegram workgroup channel for basic usage, following pinned message first, before using any wrapper scripts
