### ISSUE TITLE
-bash: export: `PI-POOL_HOME=/home/ada/pi-pool': not a valid identifier

### ISSUE THREAD

**Issue by wcatz** [cardano-community/guild-operators#884]
**Describe the bug**
The environment I am attempting to create with interactive mode is creating incorrect variable.

**To Reproduce**
1. start prereqs.sh interactively
2. Please enter the project path (default: /opt/cardano): /home/ada
2. Please enter directory name (default: cnode): pi-pool
3. source $HOME/.bashrc

**Expected behavior**
I would like to see a folder 'pi-pool' in $HOME with a working export in .bashrc.
I see it is capitalized for for bash variable but it is not happy with the '-'.
option to create folder name separately or whatever fixes this behavior
ie export PI_POOL_HOME=/home/ada/pi-pool

**Screenshots**
-bash: export: `PI-POOL_HOME=/home/ada/pi-pool': not a valid identifier

**Version:**
 - OS: Ubuntu 20.10 aarch64
 - Product version: latest
 - Cardano Node version: 1.26.1
 - Network you're connecting to: mainnet
**Additional context**
Just a thank you

**Comment by rdlrt** [comment]
Use of non-alpha numeric characters in the name of top level folder is not recommended - not because it is difficult to handle on specific flavour, but can cause trouble on different flavours for different variables.

**Comment by wcatz** [comment]
Thank you, I realize it is more of a feature request.
