### ISSUE TITLE
guild-topology.sh: processing JSON with awk and sed

### ISSUE THREAD

**Issue by terorie** [cardano-community/guild-operators#885]
**Describe the bug**

The script `files/docker/node/addons/guild-topology.sh` uses a complicated awk / tail / sed / grep pipe construction to extract data from JSON.

https://github.com/cardano-community/guild-operators/blob/724aa0dc76eb9b23a4240db720381c15ca361bd7/files/docker/node/addons/guild-topology.sh#L7

**Expected behavior**

It would be more appropriate to use a JSON processing tool like `jq` to process JSON to avoid data parsing errors.

**Comment by redoracle** [comment]
It depends from how you want the data extraction.. there is no wrong way of doing it if it works, as in this case.

**Comment by nyetwurk** [comment]
jq is more appropriate for processing .json data, regardless of the desired output format, which, in this case, also happens to be json.

**Comment by redoracle** [comment]
Ok.. thanks for your feedback.

Il gio 8 apr 2021, 18:14 Nye Liu ***@***.***> ha scritto:
