### ISSUE TITLE
cnode-helper-scripts/env: .hasEKG can be an array or scalar

### ISSUE THREAD

**Issue by nyetwurk** [cardano-community/guild-operators#887]
https://github.com/cardano-community/guild-operators/blob/3f301c94348ba77bad6ff3ce05a7a3a47cdf4a29/scripts/cnode-helper-scripts/env#L187

Support EKG as either:

```bash
jq -r '.hasEKG | if .|type=="array" then .[1] else . end'
```

**Comment by Scitz0** [comment]
Thanks, included in a future update. #888
