### ISSUE TITLE
prereqs.sh fails on yum install on amazon linux 2 for "no such option --allowerasing"

### ISSUE THREAD

**Issue by chitchow** [cardano-community/guild-operators#889]
**Describe the bug**
prereqs.sh fails on yum install on amazon linux 2 for "no such option --allowerasing"

**To Reproduce**

1. Go to an amazon linux 2 instance as a user with sudo
2. run prereqs.sh
3. enter password (if required for user)

**Expected behavior**
regular prerequisite installation

**workaround**
edited the file and removed " --allowerasing" everywhere in the file (2 occurrences)

**Screenshots**
       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
[ec2-user@ip-172----27-43 ~]$ su - lovelace
Password: 
Last login: Sat Apr 10 04:19:01 UTC 2021 on pts/0
[lovelace@ip-172----27-43 ~]$ cd tmp/
[lovelace@ip-172----27-43 tmp]$ ./prereqs.sh
Using yum to prepare packages for "Amazon Linux" system
  Updating system packages...
[sudo] password for lovelace: 
  Installing missing prerequisite packages, if any..
Cannot open: https://dl.fedoraproject.org/pub/epel/epel-release-latest-2.noarch.rpm. Skipping.
Error: Nothing to do
Command line error: no such option: --allowerasing
An error occurred while installing the prerequisite packages, please investigate by using the command below:
sudo yum -y --allowerasing install python3 coreutils pkgconfig libffi-devel gmp-devel openssl-devel ncurses-libs ncurses-compat-libs systemd systemd-devel libsodium-devel zlib-devel make gcc-c++ tmux git jq gnupg libtool autoconf srm iproute bc tcptraceroute dialog sqlite util-linux xz
It would be best if you could submit an issue at https://github.com/cardano-community/guild-operators with the details to tackle in future, as some errors may be due to external/already present dependencies

**Version:**
 - OS: [e.g. Amazon Linux 2]
 - Product version: [e.g. prereqs.sh latest]

**Comment by rdlrt** [comment]
Please check [this](https://dnf.readthedocs.io/en/latest/cli_vs_yum.html#packages-replacement-without-yum-swap) link.
This was raised before (see reply [here](https://github.com/cardano-community/guild-operators/issues/750#issuecomment-774568706) ).
