### ISSUE TITLE
prereqs script: cabal version

### ISSUE THREAD

**Issue by amilamanoj** [cardano-community/guild-operators#890]
**Describe the bug**
prereqs script fails because it can not install the cabal version 3.2.0.0 as specified in the script:
ghcup install cabal 3.2.0.0
Error: Unable to find a download for the requested version/distro.
Error: Also check the logs in "/home/proxima/.ghcup/logs"

**To Reproduce**
1. Follow instructions on https://cardano-community.github.io/guild-operators/#/basics to get the prereqs.sh
2. Execute prereqs script
5. Same error when the command "ghcup install cabal 3.2.0.0" is manually executed.

**Expected behavior**
No errors 

**Screenshots**
N/A

**Version:**
 - OS: Ubuntu Desktop 20.10
 - Product version: https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh
 - GHCup version: v0.1.14
 - Cardano Node version: N/A (prerequisites)
 - Network you're connecting to: N/A (prerequisites)

**Additional context**
Why does the prereqs script try to install cabal 3.2.0.0? 
Documentation here instructs to install 3.4.0.0:
https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

**Comment by rdlrt** [comment]
Hi,

Thanks for raising.
The bump of versions to latest was delayed as other components had yet to catch up with cabal 3.4 (at the same time cardano-node by itself works with 3.2 as well) - thus, 3.2 being the common ground for all components at the time. But now that other components are upgraded, #891 would bump the versions across the board for prereqs.

Having said that, your error message does not seem to relate to having invalid versions:
![image](https://user-images.githubusercontent.com/3169068/114324551-11aa1880-9b6e-11eb-95e1-93cbc4f622d3.png)
