### ISSUE TITLE
gLiveView double latency on BP node only

### ISSUE THREAD

**Issue by reqlez** [cardano-community/guild-operators#892]
**Describe the bug**
On the BP node, when you go to gLiveView and check the connected peers, the OUT peers have exactly DOUBLE the latency. This cannot be seen on any of the relay nodes. Also, doing a regular ping to those hosts, shows normal latency as in the IN section.

**To Reproduce**
Cannot reproduce on relays, only on BP.

**Expected behavior**
Ping rates to be the same, or close, like on relay nodes.

**Screenshots**
https://snipboard.io/KbaeIW.jpg

**Version:**
 - OS: [Ubuntu Server 20.04]
 - Product version: [1.20.3]
 - Cardano Node version: [cardano-node 1.26.1 - linux-x86_64 - ghc-8.10]
 - Network you're connecting to: [MAINNET]

**Additional context**
Tried to update OS, turn off FW, reboot routers.  The second node in that list, the one with 45 ms latency, is connected via LAN over IPSEC, not public IP. First node with 0 latency is on same network. 3rd node is connected via public IP to another datacentre.

**Comment by reqlez** [comment]
I should almost mention i'm running ghc-8.10.4 and Cabal 3.4.0.0

**Comment by Scitz0** [comment]
gLiveView use cncli by default if you have it installed to do a full node handshake and measures the time. 
If you only want a simple ping, please disable cncli ping by starting gLiveView with `-p` flag
