### ISSUE TITLE
Unreachable incoming peers in gLiveView.sh is dangerously misleading

### ISSUE THREAD

**Issue by spklpool** [cardano-community/guild-operators#894]
**Describe the bug**
In the gLiveView peer analysis screen under "In" peers, there is often several peers indicated as Unreachable with a red number under "Total / Unreachable".  This gives the operator the appearance that there is an error in their setup and could lead them to reduce the security of their pool by opening up more ports than they should to attempt to fix the "error".  
![UnreachablePeers](https://user-images.githubusercontent.com/80203161/115110293-9d45ef80-9f48-11eb-9a8f-e001030c6db7.jpg)

While this is acknowledged to be an expected behavior in the info screen, that acknowledgement is too subtle to a point of being potentially dangerous for the operator as stated above.  The word "Unreachable" in that screen should be changed to something that looks less like an error like Undetermined and the color should be changed to Yellow or another color that reduces the appearance of an error.
![UnreachablePeersInfo](https://user-images.githubusercontent.com/80203161/115110309-b5b60a00-9f48-11eb-80e5-25cf54765fe3.jpg)

 - Product version: GLV_VERSION=1.26.1

**Comment by Scitz0** [comment]
You are not the first one to comment on this so I acknowledge that wording might be improved. Your suggestions for `Undetermined` and a color change sounds good to me as all connections listed in gLiveView are established connections to the node and as such ok, just not able to determine the latency. 

Should be an easy fix, putting on TODO list.
