### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by FrancoAra** [cardano-community/guild-operators#897]
I am concerned about security, and would love if you destroy my concerns, but:

I am extremely concerned that many pool operators are basing and standardising their work based on these tools, I see security issues in the sense that:

SPOs are executing scripts directly downloaded from your master branch which is a github repo which most contributions come from 2 persons, that have no clear/transparent governance, nor checks and balances set.

These scripts are having access to SPOs servers AND keys, including the keys for managing the pledges.

The scripts and tools are not easy to verify/analyse, the cost of verifying ALL scripts before executing each time and after accepting automatic updates is too high and makes for introduction of malicious code easy.

It would be relatively easy for a single or coordinated group of contributors to introduce a stealthy commit that steals private keys or does transactions. This would put the whole Cardano network and community at risk, the network depends on the pools, and if most pools depend on the same shared script library, that library becomes a HUGE single point of failure and of incredible risk.

I hope my concerns are completely incorrect, but it is important to consider that for TRUE decentralisation and resilience of the network, the Pools MUST be independent of each other, both technologically and politically, if they get too involved with each other the amalgamation becomes a source of centralisation and single points of failure.

**Comment by psychomb** [comment]
Your concern will get logged and we thank you for it. It is my personal POV that the readme is quite clear about it.
Should people not feel confident about using this repo, they ought to have all the skills necessary to manage a node on their own anyway.

**Comment by rdlrt** [comment]
Also, the security concern is about open source use of tools. The notion is id something is precompiled from organisation like IOG, it will always be safe, while coming from community it will not be. There is a lot at stake for members of community (many ambassadors who have been here since beginning) to introduce rogue changes.
As mentioned above, the documentation is pretty clear about the usage and disclaimers.

**Comment by FrancoAra** [comment]
Thank you for your response. Those are valid arguments, but still I think the project could add some measures, mainly because this facts:

* Maybe IOHK suffers from the same opensource paradigms/concerns, but the difference between them and a community project is that they have checks and balances set, if a rogue attack comes from them they have faces, stake and the potential for governments to investigate them. A community tool has muuuuch less checks and balances, many of us are simply anonymous.
* A community tool should treat itself as a potential attacker, that is what mission critical systems do, I have worked in banks and cryptographic trust and identity providing companies and they care a lot about being transparent to auditors and putting mechanisms to stop a potential internal attack.
* A big part of the network depends on these tools, all the network, systems and for some people entire livelihoods. This should be taken very seriously.

My suggestion would be to increase the level a enforced security for example:

* Do not download automatic updates 
* Downloading the tools should come from immutable stable releases (that maybe one day can be peer reviewd/audited)
* Commands that access keys should check first that the script is being run under a cold environment (for example by trying to fail a ping to the internet) and only doing the operation in a "risky environment" after confirmation of a statement.

Thank you for your time and work :)

**Comment by rdlrt** [comment]
> Do not download automatic updates
Not sure what your understanding is, the scripts dont auto update without user prompts. Besides, gLiveView has NO_INTERNET mode to avoid update checks as well
> Downloading the tools should come from immutable stable releases (that maybe one day can be peer reviewd/audited)
That's a user action, on our ends we do have compulsory reviewal process, and a test process before it's merged to master for users.
> Commands that access keys should check first that the script is being run under a cold environment (for example by trying to fail a ping to the internet) and only doing the operation in a "risky environment" after confirmation of a statement
That's again a user preference, not everyone runs key operations in cold mode. We provide recommendations and disclaimers to use it in offline mode, but we cant enforce our ideology to consumers :)

**Comment by FrancoAra** [comment]
Thank you once more @rdlrt for taking the time to answer to my messages. Maybe this conversation can be referred in the future to anyone else that comes with similar concerns. I wish your project and community the best of luck and thank you for your contributions to the wider community
