### ISSUE TITLE
HW wallet as #2 owner - offline sign error

### ISSUE THREAD

**Issue by iurab** [cardano-community/guild-operators#898]
**Describe the bug**
I always encounter the following error when trying to sign the the transaction which adds a second owner, HW wallet, to the pool
`Error: Failed to parse stakepool registration certificate` 
The wallet is already delegated to the pool - done through CNTools

**To Reproduce**
1. On BP create a transaction, where a second wallet (HW) is assigned to the pool
2. Copy JSON file to air-gapped-pc. I also copied the `pool.cert` file
3. Sign transaction with main wallet `payment` and `stake` files - WORKS
4. Sign transaction with HW wallet `stake` file <-- here I encounter the problem

**Expected behavior**
I wanted to fully sign the transaction

**Screenshots**
![Screenshot from 2021-04-22 23-56-34](https://user-images.githubusercontent.com/17089385/115852639-f920e480-a430-11eb-9a5b-7ba1d3823537.png)

**Version:**
 - OS: Ubuntu 20.04
 - Product version: CNTools 8.1.6
 - Cardano Node version: cardano-cli 1.26.2
 - Network you're connecting to: -
 - cardano-hw-cli version: 1.2.0
 - ledger fw version: 1.2.4-5
 - ledger cardano app version: 2.2.1

**Comment by Scitz0** [comment]
Version of cardano-hw-cli, ledger fw version and ledger app version?

**Comment by iurab** [comment]
> Version of cardano-hw-cli, ledger fw version and ledger app version?

I did an update to the issue with the request details.
Creating the HW wallet, registering it and delegating it to my pool was done through the CNTools

**Comment by Scitz0** [comment]
Currently no good idea. But just so that I understand you correctly:<
1) You had a pool registered since before with one cli owner?
2) You imported, registered, and delegated the hw wallet to your pool?
3) You then tried to update pool to add hw wallet as a second multi-owner to the pool?
No other changes?

I will do some tests later but no idea currently what the problem might be. It would be helpful to get cntools-history.log and the offline tx file. Can be provided to me through TG @olaahlman if you don't want to post that publicly.

**Comment by iurab** [comment]
> Currently no good idea. But just so that I understand you correctly:<
> 
> 1. You had a pool registered since before with one cli owner?
> 2. You imported, registered, and delegated the hw wallet to your pool?
> 3. You then tried to update pool to add hw wallet as a second multi-owner to the pool?
>    No other changes?
> 
> I will do some tests later but no idea currently what the problem might be. It would be helpful to get cntools-history.log and the offline tx file. Can be provided to me through TG @olaahlman if you don't want to post that publicly.

1,2: Yes
3: I'm pretty sure I didn't do any other changes.

Finally I could add my HW wallet as second owner to the pool, with the following steps:
* I generated a new certificate for the pool where I just modified the pool pledge - my cli wallet was set as single owner
   Signing it went OK - as HW wallet was not requested.
* I tried again to add my HW wallet as second owner. Generated the new certificate and the correspondent `json`.
-- I didn't know exactly what content was feed to the `cardano-hw-cli` command in my previous attempt, as the signature from my HW wallet was the third one requested so I did a small change to the `json` file this time:
-- I modified the order in which the signatures are requested and put the HW wallet first

This did the trick for me - but I'm not sure which step resolved it :|

If needed I can come with a feedback when a new signature will be needed - if I'm not mistaken, now also the HW wallet will participate to all new signatures.

**Comment by Scitz0** [comment]
Ok, order shouldn't have anything to do with it. It identifies the type using provided vkey in json and it should be able to detect if it's a hardware wallet or cli as well as if provided skey match. 

Closing for now as issue is resolved. Create a new issue if it reappears.
