### ISSUE TITLE
checkUpdate: command not found

### ISSUE THREAD

**Issue by laplasz** [cardano-community/guild-operators#900]
**Describe the bug**
$ ./topologyUpdater.sh 
./topologyUpdater.sh: line 61: checkUpdate: command not found

**To Reproduce**
call the script
**Expected behavior**
run without error

**Screenshots**

**Version:**
 - OS: ubuntu
 - Product version: latest topologyUpdater script

**Additional context**

**Comment by laplasz** [comment]
just updated the env file, and getting the same result.
then I sourced manually the env and get the following
$ source ./env
dirname: invalid option -- 'b'

OS: ubuntu 18.04

**Comment by Scitz0** [comment]
Your env file must be corrupt. But impossible to tell without looking at it. Can you make it available by uploading it or using some sort of pastebin service?

**Comment by laplasz** [comment]
thanks, I will have a look on it.. but maybe you could introduce versioning in the scripts - so env file could contain a GUILD_VERSION and that could be matched within other scripts  to avoid these situations
I will come back once I found the issue.

**Comment by rdlrt** [comment]
The scripts can all be independent  of each other (one can only run gLV and not CNTools, so version does not necessarily make sense). It is why there is a comparison and prompt to update with the branch. The `invalid option -- 'b'` is not really an issue here.

The issue in your original thread seems to be that you have topologyupdater script updated from alpha branch (perhaps you downloaded it directly from github instead of following the download instruction in the documentation?)

Thus, you're possibly working with alpha branch script against env from master branch. Also, when in doubt - please stick to master branch, unless you're fully aware of proceedings and process for alpha branch (which works with `-b alpha` as argument) 🙂

**Comment by laplasz** [comment]
Hi!

Thanks for the detailed answer - very appreciated.
Correct! - I used the alpha branch..directly from github.
So now I checked out master.. and everything is wokring smoothly!

yes, I agree that this scripts should be work independently but most of them depends on env file..
and btw there is a cntools version - the latest on master is  CNTools 8.1.6
So env file could hold this version info and if topologyUpdater need later version then it could throw an error that env file is out dated.
Also just would like to mention that a tag with 8.1.6 version could be introduced in the repository.

**Comment by rdlrt** [comment]
> Hi!
> 
> Thanks for the detailed answer - very appreciated.
> Correct! - I used the alpha branch..directly from github. (usually the default branch is the master which contains the latest, working version of a tool)
> So now I checked out master.. and everything is wokring smoothly!
> 
> yes, I agree that this scripts should be work independently but most of them depends on env file..
> and btw there is a cntools version - the latest on master is  CNTools 8.1.6
> So env file could hold this version info and if topologyUpdater need later version then it could throw an error that env file is out dated.
> Also just would like to mention that a tag with 8.1.6 version could be introduced in the repository.

Yes, while tools by themselves are versioned, the env file is a lot more dynamic and has to be kept in sync with latest (thus, every commit to env is pretty much a version), and if auto update prompt is allowed, it will be checking and notifying you about the same upon launch of any/every tool

**Comment by laplasz** [comment]
Thanks for the answer.
Btw - is it possible to get the version of the currently executed topologyUpdater? like topologyUpdater -v
topologyUpdater.sh -h - not help either unfortunately

**Comment by Scitz0** [comment]
No, topologyUpdater.sh is not versioned beyond branches and commits on GitHub. It's considered such a small script it makes little sense to version it beyond this.
