### ISSUE TITLE
topologyUpdater - mv: cannot stat '/xxx/spo/mainnet-topology.json.tmp': No such file or directory

### ISSUE THREAD

**Issue by laplasz** [cardano-community/guild-operators#901]
**Describe the bug**
$ ./topologyUpdater.sh 
mv: cannot stat '/xxx/spo/mainnet-topology.json.tmp': No such file or directory

**To Reproduce**
call the script

env file:
CNODE_HOME="/xxx"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
TOPOLOGY="${CNODE_HOME}/spo/mainnet-topology.json

file exists on the given path

**Expected behavior**
scripts executed without error

**Screenshots**

**Version:**
 - OS: ubuntu
 - Product version: latest topologyUpdater

**Additional context**

**Comment by laplasz** [comment]
when /xxx/spo/mainnet-topology.json.tmp is created the error disappeared.

**Comment by Scitz0** [comment]
Almost certainly permission issues in your filesystem. The user running topologyUpdater.sh script needs to be able to write to `/xxx/spo/` directory.

**Comment by rdlrt** [comment]
If you executed the commands from same folder (as your example uses relative path while error suggests a full path) , and  you were using a custom branch that does not exist any longer, the curl command to download (to check difference and prompt you) would fail too - something you might want to double check

**Comment by laplasz** [comment]
just updated the env file, and now works! - thanks for the reply!
