### ISSUE TITLE
topologyUpdater - 501 - "invalid hostname not pointing to client IP" many times

### ISSUE THREAD

**Issue by laplasz** [cardano-community/guild-operators#904]
**Describe the bug**
I have a dynamic IP address so it is managed by DNS resolution. That is why CNODE_HOSTNAME has been changed to the hostname.
Here is the log of topologyUpdater

```
{ "resultcode": "204", "datetime":"2021-04-30 18:15:04", "clientIp": "94.21.184.238", "iptype": 4, "msg": "glad you're staying with us" }
{ "resultcode": "204", "datetime":"2021-04-30 19:15:04", "clientIp": "94.21.184.238", "iptype": 4, "msg": "glad you're staying with us" }
{ "resultcode": "201", "datetime":"2021-04-30 20:15:04", "clientIp": "94.21.214.121", "iptype": 4, "msg": "nice to meet you" }
{ "resultcode": "203", "datetime":"2021-04-30 21:15:06", "clientIp": "94.21.214.121", "iptype": 4, "msg": "welcome to the topology" }
{ "resultcode": "204", "datetime":"2021-04-30 22:15:04", "clientIp": "94.21.214.121", "iptype": 4, "msg": "glad you're staying with us" }
{ "resultcode": "204", "datetime":"2021-04-30 23:15:04", "clientIp": "94.21.214.121", "iptype": 4, "msg": "glad you're staying with us" }
{ "resultcode": "501", "datetime":"2021-05-01 00:15:08", "clientIp": "94.21.214.121", "msg": "invalid hostname not pointing to client IP" }
{ "resultcode": "501", "datetime":"2021-05-01 01:15:08", "clientIp": "94.21.214.121", "msg": "invalid hostname not pointing to client IP" }
{ "resultcode": "204", "datetime":"2021-05-01 02:15:06", "clientIp": "94.21.214.121", "iptype": 4, "msg": "glad you're staying with us" }
{ "resultcode": "501", "datetime":"2021-05-01 03:15:09", "clientIp": "94.21.214.121", "msg": "invalid hostname not pointing to client IP" }
{ "resultcode": "501", "datetime":"2021-05-01 04:15:09", "clientIp": "94.21.214.121", "msg": "invalid hostname not pointing to client IP" }
{ "resultcode": "204", "datetime":"2021-05-01 05:15:04", "clientIp": "94.21.214.121", "iptype": 4, "msg": "glad you're staying with us" }
{ "resultcode": "501", "datetime":"2021-05-01 06:15:14", "clientIp": "94.21.214.121", "msg": "invalid hostname not pointing to client IP" }
{ "resultcode": "204", "datetime":"2021-05-01 07:15:05", "clientIp": "94.21.214.121", "iptype": 4, "msg": "glad you're staying with us" }
{ "resultcode": "204", "datetime":"2021-05-01 08:15:05", "clientIp": "94.21.214.121", "iptype": 4, "msg": "glad you're staying with us" }
```
So as you can see in the 3rd line - the IP has been changed by the ISP - hense the nice to meet you message.
But then even the IP remain the same - randomly got back "invalid hostname not pointing to client IP"
So what can go wrong? How TopologyUpdater detects the IP address for a hostname?

2nd question:
What is the point of CNODE_HOSTNAME? if it is set that means that the generated topology.json will contain the hostname instead of IP for others using the topologyUpdater?

Thanks!

**Expected behavior**
consistent IP address detection

**Version:**
 - OS: [e.g. CentOS 8]
 - Product version: topologyUpdater only - dont know how to determine version for it
 - Cardano Node version: 1.26.2
 - Network you're connecting to: mainnet

**Comment by ghandmann** [comment]
`topologyUpdater.sh` is not producing this message. The script sends a HTTP-Request to the server at `https://api.clio.one/`. The payload of this request contains the value of `CNODE_HOSTNAME`.

The receiving server (`api.clio.one`) then checks, if the ip address the request was coming from (aka remote address) matches the ip address associated with the provided hostname (the `CNODE_HOSTENAME` value).

The error message indicates that those two ip addresses are not the same.

There are a lot of reasons why this could happen.

There could be a "race" between your local machine updating your DNS information after you got a new ip and the moment you run `topologyUpdater.sh`. So you are running the script before the DNS knows about your new ip address, therefore the mismatch occurs.

Another could be, that your DNS provider has rather "big" time to live (TTL) settings. TTL indicates how many seconds an ip address for a hostname may be cached by an intermediate DNS.

You can check the TTL your DNS provider declares by running:
`dig $YourHostname`.

This will display the TTL in a rather "techy" or "cryptic" way. But check this [article](https://ns1.com/blog/decoding-dig-output) for an explanation where to find the TTL in the dig output.

**Comment by rdlrt** [comment]
@laplasz - was there any update/pending query on this issue?
