### ISSUE TITLE
Ledger-State dump hangs

### ISSUE THREAD

**Issue by ADA-Node** [cardano-community/guild-operators#906]
**Describe the bug**
Navigating to the Pool >> Show menu starts the ledger-state dump and the process can be seen via htop monitoring.  It looks like the process completes, but the cntools process continues to run while consuming 100% of a single core.  That process never completes and the cntools menus stays at the "Dumping ledger-state from node, can take a while on larger networks..." message.  The ledger-state json files is not saved to the /tmp/cnode folder either.

**To Reproduce**
1. Go to 'cntools.sh'
2. Click on 'Pools>>Show>>{pool_name}'

**Expected behavior**
Pool >> Show function should show registered pool details

**Screenshots**
N/A

**Version:**
 - OS: Ubuntu Srvr 20.04
 - Product version: v8.2.1
 - Cardano Node version: 1.26.2
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Additional context**
Pool was not created with cntools initially.  I created the pool manually and migrated into the cntools infrastructure.

**Comment by rdlrt** [comment]
That isn't an issue with CNTools, ledger-state dump requires quite some memory and often pools operating at marginal memory run out of it (you can check in `dmesg -T`). The upcoming version of cardano-node will allow partial query, and in parallel there is also an optional PR in works for using postgREST instance.

But given what's available from CLI at the moment, this i(ledger-state eating up memory) isnt an issue that we can affect

**Comment by ADA-Node** [comment]
@rdlrt This ended up not being a memory related issue.  I had removed the pool.cert file from the /priv/pool/folder.  the script seemed to go of into the weeds due to the missing file.
