### ISSUE TITLE
Wrong OS and CPU type selected for aarch64 (arm64 processors) in setup_mon.sh

### ISSUE THREAD

**Issue by whosystem** [cardano-community/guild-operators#907]
**Describe the bug**

**To Reproduce**
./setup_mon.sh
**Expected behavior**
bash -x ./setup_mon.sh 
+ CNODE_IP=127.0.0.1
+ CNODE_PORT=12798
+ GRAFANA_HOST=0.0.0.0
+ GRAFANA_PORT=5000
+ PROJ_PATH=/opt/cardano/monitoring
+ PROM_HOST=127.0.0.1
+ PROM_PORT=9090
+ NEXP_PORT=9091
+ ARCHS=("darwin-amd64" "linux-amd64" "linux-armv6" "linux-arm64" "linux-aarch64")
++ mktemp -d /tmp/cnode_monitoring.XXXXXXXX
+ TMP_DIR=/tmp/cnode_monitoring.FI9rC3DU
+ PROM_VER=2.20.0
+ GRAF_VER=7.1.2
+ NEXP_VER=1.0.1
+ NEXP=node_exporter
+ SKY_DB_URL=https://raw.githubusercontent.com/Oqulent/SkyLight-Pool/master/Haskel_Node_SKY_Relay1_Dash.json
+ IOHK_DB=cardano-application-dashboard-v2.json
+ IOHK_DB_URL=https://raw.githubusercontent.com/input-output-hk/cardano-ops/master/modules/grafana/cardano/cardano-application-dashboard-v2.json
+ export CNODE_IP CNODE_PORT PROJ_PATH TMP_DIR
+ DEBUG=N
+ [[ N == \Y ]]
+ unset DBG
++ command -v curl
+ CURL=/usr/bin/curl
++ command -v wget
+ WGET=/usr/bin/wget
+ DL=/usr/bin/curl
+ '[' -z /usr/bin/curl ']'
+ [[ -f /opt/cardano/cnode/sripts/env ]]
+ getopts :d:i:p: opt
+ shift 0
+ '[' -e /opt/cardano/monitoring ']'
++ get_idx
++ case $OSTYPE in
++ [[ aarch64 == *\x\8\6\_\6\4* ]]
++ [[ aarch64 == *\a\r\m\6\4* ]]
++ [[ aarch64 == *\a\r\m* ]]
++ [[ aarch64 == *\a\a\r\c\h\6\4* ]]
++ IDX=3
++ echo 3
+ IDX=3
+ trap clean_up SIGHUP SIGINT SIGQUIT SIGTRAP SIGABRT SIGTERM
+ PROM_URL=https://github.com/prometheus/prometheus/releases/download/v2.20.0/prometheus-2.20.0.linux-arm64.tar.gz
+ GRAF_URL=https://dl.grafana.com/oss/release/grafana-7.1.2.linux-arm64.tar.gz
+ NEXP_URL=https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-arm64.tar.gz

**Screenshots**

**Version:**
 - OS: [e.g. CentOS 8] 
 - lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
uname -a 
Linux cardano-relay.it4us.top 5.4.0-1034-raspi #37-Ubuntu SMP PREEMPT Mon Apr 12 23:14:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

 - Product version: [e.g. CNTools 5.0.1]
 - latest (may 03 2021)
 cncli -V | cut -d' ' -f2
2.0.3

 - Cardano Node version: [e.g. output of `cardano-node version`]
cardano-node --version
cardano-node 1.26.2 - linux-aarch64 - ghc-8.10
git rev 3531289c9f79eab7ac5d3272ce6e6821504fec4c
 - Network you're connecting to: [output of `jq -r .systemStart $CNODE_HOME/files/genesis.json`]
 jq -r .systemStart $CNODE_HOME/files/genesis.json
2017-09-23T21:44:51Z

**Additional context**
_Solution:_
diff /opt/cardano/cnode/scripts/setup_mon.sh ./setup_mon.sh 
19c19
< ARCHS=("darwin-amd64" "linux-amd64"  "linux-armv6")
---
> ARCHS=("darwin-amd64" "linux-amd64"  "linux-armv6" "linux-arm64" "linux-aarch64")
53a54,55
>             elif [[ $HOSTTYPE == *"arm64"* ]]; then
>                 IDX=3
55a58,59
>             elif [[ $HOSTTYPE == *"aarch64"* ]]; then
>                 IDX=3

**Comment by rdlrt** [comment]
Thanks, should be closed via #944
