### ISSUE TITLE
gLiveView Error

### ISSUE THREAD

**Issue by ClecknerT** [cardano-community/guild-operators#909]
Summary
After launching the cnode, I am receiving an error when trying to use gLiveView. 
Output after running ./gLiveView.sh:
Guild LiveView version check...
Failed to query protocol-parameters from node, not yet fully started?
ERROR: CNTools failed to load common env file
Please verify set values in 'User Variables' section in env file or log an issue on GitHub

sudo systemctl status cnode.service shows the node is active.

System info:
OS:Ubuntu
Version: 20.04
Node version: 1.26.2

**Comment by webdeveloperpr** [comment]
I'm running into the same issue.

**Comment by webdeveloperpr** [comment]
Seems like it's failing on this line: 

https://github.com/cardano-community/guild-operators/blob/51cc10086e8ad26d7ae254f0fa0903d5b703857e/scripts/cnode-helper-scripts/gLiveView.sh#L119

To get `./gLiveView.sh` running

1. open the ./scripts/env file
2. Set `UPDATE_CHECK=N` 
3. run ./scripts/gLiveView.sh

**Comment by webdeveloperpr** [comment]
I believe this is the line and the commit the broke it.
https://github.com/cardano-community/guild-operators/commit/a109e5c3626cbc6ceb666617fb621382aff3e7fd#diff-9f1a45ec3b3d926a83c39e4bb443cb019c237562ed6705f0a6efdc0580984558R125

**Comment by webdeveloperpr** [comment]
Looks like that specific was not tested.

**Comment by webdeveloperpr** [comment]
![Screen Shot 2021-05-08 at 1 05 23 AM](https://user-images.githubusercontent.com/7534346/117527413-e7475180-af99-11eb-9c0d-efd8e458cb09.png)

**Comment by rdlrt** [comment]
@ClecknerT  - Are you following the guide to setup your install? or did you simply download gLiveView.sh from github and trying to get it running?

**Comment by rdlrt** [comment]
@webdeveloperpr  - Deleted off topic (and slightly inaccurate) messages. It sounds like based on your screenshot and findings, you have downloaded a copy of scripts without the accompanying env file (see [download instructions](https://cardano-community.github.io/guild-operators/#/Scripts/gliveview?id=download) ) or used an older copy of env file.

**Comment by kyohmyhi** [comment]
Hi guys, I am consistently getting the same message everytime I try to run ./gLiveView.sh ...I think it has something to do with the env file but I am new to this and don't know exactly where to go...this recently started happening because I have successfully synced with the blockchain before

**Comment by webdeveloperpr** [comment]
@kyohmyhi the problem is that when env get sourced by ` ./gLiveView.sh`  the file throws an error and it doesn't let you start  gLiveView. This happens for cntools too.

**Comment by webdeveloperpr** [comment]
@kyohmyhi  try setting UDATE_CHECK="N" in your env file.

**Comment by webdeveloperpr** [comment]
<img width="1440" alt="Screen Shot 2021-05-08 at 5 55 59 AM" src="https://user-images.githubusercontent.com/7534346/117535246-dd861400-afc2-11eb-974c-42bd5583fc2b.png">

**Comment by kyohmyhi** [comment]
@webdeveloperpr thanks for the update, again, I am new, how do I get to the env file to update to UDATE_CHECK="N"...because when I run scripts/env file, I get -bash: /scripts/env: No such file or directory

**Comment by webdeveloperpr** [comment]
If you followed this guide: it should be under

```shell
${CNODE_HOME}/scripts/env
```

you can open it with nano or vim

```shell
vim ${CNODE_HOME}/scripts/env

# or 

nano ${CNODE_HOME}/scripts/env
```

**Comment by webdeveloperpr** [comment]
@kyohmyhi  I tried both and ran into the same issues.

**Comment by kyohmyhi** [comment]
@webdeveloperpr well i currently cant even open ${CNODE_HOME}/scripts/env...it keeps saying nothing is in the directory so I had to miss something somewhere

**Comment by webdeveloperpr** [comment]
If you followed coincashew I think the file is in 

```
${NODE_HOME}/env
```

**Comment by ClecknerT** [comment]
@webdeveloperpr <https://github.com/webdeveloperpr> Thanks that worked for
me.

**Comment by kyohmyhi** [comment]
@webdeveloperpr i can see the files by running cd ${NODE_HOME} ls -l but I am still at a loss on how to pull up the screen you attached above and change it from yes to no

**Comment by webdeveloperpr** [comment]
@kyohmyhi  In the screenshot I was using vscode editor to ssh into my instance and edit the files. 

In your case you have to either use vim or nano to edit the file. I would suggest using nano first since it's easier.

```shell
nano  ${NODE_HOME}/env
```

**Comment by kyohmyhi** [comment]
well the good news is that I figured out how to change it using nano env...the bad news is now im getting a completely new error message 

ERROR: You specified 12788 as your EKG port, but it looks like the cardano-node (PID: 1568 ) is not listening on this port. Please update the config or kill the conflicting process first.

(I didnt change anything but changed the Y to N as instructed)

**Comment by webdeveloperpr** [comment]
try rebooting the instance 

```sh
sudo reboot
```

**Comment by rumourscape** [comment]
Guys I just installed node via CNTools today and am getting this same issue of protocol parameters not found in both gliveview and CNTools.

**Comment by kyohmyhi** [comment]
it worked @webdeveloperpr thank you so much!

**Comment by rdlrt** [comment]
@rumourscape - protocol-parameters not working is an issue while connecting to your node.
