### ISSUE TITLE
Test relative Paths for all scripts

### ISSUE THREAD

**Issue by rdlrt** [cardano-community/guild-operators#910]
Extend testing for relative paths in vars to:
prereqs
CNTools
gLiveView
cncli

Add testing for ~ and relative paths to resove before using (eg: @disassembler had trouble when using home folder for backup & restore)

**Comment by comozo** [comment]
Hi I'll be happy to help here. Is it possible to have a bit more context ?
Thank you

**Comment by rdlrt** [comment]
Hi @comozo ,
That's great to hear.
The issue is simply to test and handle relative paths (eg: folks using `../` or `./` or `~/` when specifying folder paths in arguments at [prereqs](https://cardano-community.github.io/guild-operators/#/basics?id=pre-requisites) script or in [env](https://cardano-community.github.io/guild-operators/#/Scripts/env) file.

**Comment by comozo** [comment]
Hi @rdlrt Great I'll work on it. Thank you

**Comment by rdlrt** [comment]
The issue description was never added to the ticket, besides - CNODE_HOME is now set based on relative path. Hence, closing..
