### ISSUE TITLE
Restore from mnemonics (using CNTools 8.2.1 and cardano-address 3.4.0) aborts

### ISSUE THREAD

**Issue by rgoerwit** [cardano-community/guild-operators#921]
**Describe the bug**
Restore from mnemonics aborts with Error: Wrong input size of 0, Generated from 1852H/1815H/0H/0/0

**To Reproduce**
1. Install CNTools v8.2.1, cardano-address --version = 3.4.0
2. Attempt to restore a wallet using 24-word mnemonic in offline mode

**Expected behavior**
Keys should get created, wallet built

**Version:**
 - OS: I happen to be using Ubuntu LTS 20.04
 - Product version: v8.2.1
 - cardano-address --version = 3.4.0
 - Cardano Node version: 1.27.0

**Comment by rdlrt** [comment]
You're using wrong cardano-address binary. Guild Doco instructions will install 2.1.0 specifically

**Comment by rgoerwit** [comment]
I understand that it's not always possible, but can the most recent versions be used?  It creates difficulties when developers have current versions of software on their machines for other reasons, to have guild scripts using an older version.

**Comment by rdlrt** [comment]
It can, but we had some obstacles as some features were withdrawn from addresses project that we intend to use for HD Wallets

**Comment by rdlrt** [comment]
@rgoerwit - Hopefully the above PR should help you out keeping compatibility with both versions
