### ISSUE TITLE
Ledger does not work with cntools

### ISSUE THREAD

**Issue by reqlez** [cardano-community/guild-operators#924]
**Describe the bug**
When performing any transactions with the hardware wallet: Command failed: transaction submit  Error: /tmp/cnode/cntools/tx.signed_XXXX: TextEnvelope decode error: DecoderErrorDeserialiseFailure "Shelley Tx" (DeserialiseFailure 367 "Size mismatch when decoding \nRecord RecD.\nExpected 0, but found 2.")

**To Reproduce**
Try any transaction from cntools with Ledger app 2.3.2 and latest cardano-node 1.27.0

**Expected behavior**
Transaction should complete without error?

**Version:**
 - OS: Ubuntu 20.04
 - Product version: CNTools v8.2.1
 - Cardano Node version: cardano-node 1.27.0 - linux-x86_64 - ghc-8.10
 - Network you're connecting to: mainnet
 - Cardano HW CLI Tool version 1.4.0
 - Ledger app version 2.3.2

**Comment by Scitz0** [comment]
So you are able to build offline tx, then sign it with ledger but when submitting to chain it fails?

I don't currently own a Ledger to test on (in the mail). But will check once it arrives.

**Comment by reqlez** [comment]
I haven't tried offline build, this was using online option.

I can do some more tests... I tried updating to latest 8.4.0 version and also tried to rebuild the cnode using the latest cntools build script, same thing.  One thing I find interesting is that the cardano-addresses binary is from several weeks ago, so that means a new version is not being built as part of the process... not sure if it's supposed to?

**Comment by Scitz0** [comment]
cardano-address has nothing to do with it.

only cardano-hw-cli version and the app/fw version on your ledger device in combination with CNTools version. But can't say for sure what is causing your error as you seem to be running the latest version from what you wrote in the first post. Need to test myself once the Ledger device arrives.

**Comment by reqlez** [comment]
Ah okay. Yea I just read that cardano-address is for mnemonic stuff. For sure I know cardano-hw-cli version 1.2.0 had same issue, because I only upgraded later when I saw the issue was there. Maybe this new cardano app version on ledger is what broke it?   I did create this pool via the Ledger method so I know it "used" to work.

**Comment by raphipik** [comment]
I'm facing the exact same issue. Did anyone manage to identify where the problem lies and how to fix it?

**Comment by reqlez** [comment]
Scitz0 said they are waiting for Ledger in the mail to do further tests.  But I'm pretty confident it's something with latest cardano app version.   I'll do some more testing later.

**Comment by Scitz0** [comment]
Might be related to the following issue just raised on Vacuumlabs GH site.
https://github.com/vacuumlabs/cardano-hw-cli/issues/75

**Comment by reqlez** [comment]
Ahh... so it was then the node update not the cardano app update that broke it.  Makes sense. Let's see what they say over there.

**Comment by reqlez** [comment]
https://github.com/vacuumlabs/cardano-hw-cli/pull/78

**Comment by Scitz0** [comment]
cardano-hw-cli 1.5.0 released, please check if issue is resolved.

**Comment by reqlez** [comment]
did a rewards withdrawal from ledger wallet via cntools today and worked like a charm!  with Ledger FW 1.3 that just updated to.

**Comment by reqlez** [comment]
also just sent a transaction to verify pool on pooltool.io, also worked like a charm! I think we are good?  Unless more tests are needed?

**Comment by Scitz0** [comment]
Ok great, I think we can close this issue then
