### ISSUE TITLE
libsodium path missing from environment variables of cnode.service

### ISSUE THREAD

**Issue by mik1893** [cardano-community/guild-operators#933]
**Describe the bug**
After a fresh install of cntools and deploy of system services, cardano-node is not synchronizing the db, throwing the following error:
undefined symbol: crypto_vrf_publickeybytes 
See fix at the end of report

**To Reproduce**
1. Fresh install of cntools, compile cardano-node
2. start cnode
3. status will stop at opening connection with other nodes. after a few minutes, it will crash with the error `undefined symbol: crypto_vrf_publickeybytes`
4. cnode will autorestart (so not easy to spot the error) and go in a loop
5. adding libsodium libs in the service environment variables will fix the issue (see below how to do that if you have the same problem)

**Expected behavior**
cnode service working and cardano-node sync with blockchain

**Version:**
 - OS: Ubuntu 20.04
 - Product version: CNTools v8.4.4
 - Cardano Node version: cardano-node 1.27.0 - linux-x86_64 - ghc-8.10

**Additional context**
You can fix the problem by doing:
`sudo systemctl edit cnode.service`
In the text editor instance that opens up just add the following and save:

[Service]
Environment="LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
Environment="PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"

**Comment by rdlrt** [comment]
This issue should only occur when not following the prereqs as per doco - but regardless, a hardcoded entry is now added to env as per PR, which will make its way to master after going via alpha

**Comment by jaredcassidyluna** [comment]
> Thanks for reporting this one, this issue would _only occur when not following the prereqs as per guild doco_ - but regardless, a hardcoded entry is now added to env as per PR, which will make its way to master after going via alpha.

This is occurring on docker image cardanocommunity/cardano-node

I have tried setting the above environment variable in docker

Should I open a separate issue?

**Comment by rdlrt** [comment]
@jaredcassidyluna - The fix for this is already merged to master, the updated image should already be available now

**Comment by jaredcassidyluna** [comment]
@rdlrt I just double checked and pulled latest onto my local machine and still get the error

image sha256:5ecf08e867a12f6dd5f6385d6459a81be8a5a27f09bb29067c0110ffd158114b

Perhaps I should open a new issue?
