### ISSUE TITLE
Latest docker image still has libsodium error 

### ISSUE THREAD

**Issue by jaredcassidyluna** [cardano-community/guild-operators#938]
**Describe the bug**
The latest https://hub.docker.com/r/cardanocommunity/cardano-node image `Digest:sha256:5ecf08e867a12f6dd5f6385d6459a81be8a5a27f09bb29067c0110ffd158114b`
produces the same error as described in https://github.com/cardano-community/guild-operators/issues/933. 

`cardano-node: symbol lookup error: cardano-node: undefined symbol: crypto_vrf_publickeybytes`

If I run it on an older image `Digest:sha256:d48fa65106c150b1ed82e4c7eca7698d5798b8dce6e1ad44be5cdbfeb1447e4f` the node syncs without issues

I am testing the above on testnet

**To Reproduce**
1. Run the docker node:
```
% docker run -dit \
--name cardano \
--security-opt=no-new-privileges \
-e NETWORK=testnet \
-p 6000:6000 \
cardanocommunity/cardano-node
```

2. Let the node sync till about 1.2GB is used on the volume or about 2 hours depending on your connection
```
$ cd /opt/cardano/cnode/db
$ du -h -d 1
1.9M	./ledger
1.1G	./immutable
45M	./volatile
1.2G	.
```

3. check the docker container logs
```
% docker logs --tail 20 cardano

  _____     _ __   __  ____                    __             
 / ___/_ __(_) /__/ / / __ \___  ___ _______ _/ /____  _______
/ (_ / // / / / _  / / /_/ / _ \/ -_) __/ _ `/ __/ _ \/ __(_-<
\___/\_,_/_/_/\_,_/  \____/ .__/\__/_/  \_,_/\__/\___/_/ /___/
                         /_/ 
                         

NETWORK: testnet  
NODE: d6d52e34fde4 - Port:6000 - 
cardano-node 1.27.0 - linux-x86_64 - ghc-8.10
git rev 8fe46140a52810b6ca456be01d652ca08fe730bf
Listening on http://127.0.0.1:12798
cardano-node: symbol lookup error: cardano-node: undefined symbol: crypto_vrf_publickeybytes
```

**Expected behavior**
cnode service working and cardano-node sync with blockchain

**Version:**
 - OS: `Docker Community Engine 20.10.5`
 - Product version: `latest docker image`
 - Cardano Node version: `1.27.0`
 - Network you're connecting to: `2017-09-23T21:44:51Z`

**Additional context**
In https://github.com/cardano-community/guild-operators/issues/933 the issue was resolved by adding the paths to ENV
This appears to not fix the problem in the docker based nodes.

**Comment by rdlrt** [comment]
See reply [here](https://github.com/cardano-community/guild-operators/issues/937#issuecomment-850061661), you can follow any comments in that issue
