### ISSUE TITLE
cnode.sh issue ipv6 syntax

### ISSUE THREAD

**Issue by Tersken** [cardano-community/guild-operators#941]
**Describe the bug**
When running cnode.sh with mix or ipv6 mode, cardano-node fails and states it cannot parse the ::/0 ip.

**To Reproduce**
1. Set env to have mix or ipv6 mode
2. Run scripts/cnode.sh
3. See error "option –host-ipv6-addr: Failed to parse: ::/0. Use --host-addr to specify IPv4 adddress"

**Expected behavior**
No failed to parse error and the node to start

**Version:**
 - OS: Ubuntu 20.4.2
 - Cardano Node version: cardano-node 1.27.0 - linux-x86_64 - ghc-8.10

**Additional context**
The issue can be solved by removing the port reference. So just plain :: as ipv6 address.
```
[[ ${IP_VERSION} = "6" || ${IP_VERSION} = "mix" ]] && host_addr+=("--host-ipv6-addr" "::")
```

Best regards,
Koen Tersago
http://minasan.io ADA Staking pool in construction

**Comment by rdlrt** [comment]
Thanks, this is included to be fixed by #944
