### ISSUE TITLE
CNTools - Block view breaks node sync calculation

### ISSUE THREAD

**Issue by Straightpool** [cardano-community/guild-operators#943]
**Describe the bug**
Block view breaks node sync calculation upon returning to home

**To Reproduce**
1. Start cntools on an instance which has block data in the guild DB so option "b" is displayed
2. Wait until node sync is in the green zone
3. Hit "b" for blocks
4. Hit "s" for summary or "e" for epoch
5. Confirm / select any epoch until table is displayed
6. Hit "h" to go back to home
7. View node sync be out of wack e.g.  30846673 :(, refresh won't fix this state, only restart of cntools

**Expected behavior**
Viewing block data should not interfere with node sync calculation. 

**Version:**
 - OS: Ubunto 20.4 LTS
 - Product version:  CNTools 8.4.4
 - Cardano Node version: cardano-node 1.27.0 - linux-x86_64 - ghc-8.10
git rev 8fe46140a52810b6ca456be01d652ca08fe730bf
 - Network you're connecting to: 2017-09-23T21:44:51Z

**Additional notes**
Must be some weird side effect, on first look at the code I did not find the issue or I would have fixed it right away. So I keep this issue here as a reminder to look at this.

**Comment by Scitz0** [comment]
The only thing I can think of is that some variable gets overwritten/reused by mistake. I will have a look

**Comment by Scitz0** [comment]
This was an interesting one, still haven't figured out why but the EKG response gets messed up in getNodeMetrics function.
A normal replay would look like this:
`2629074 135 96776 28047176 3.369314282148874e-2 62207 1 363 216 15 526 526 0 1487830 1620928604`
but after entering block view and going back to home menu the call tsv conversion of the EKG response in getNodeMetrics function return this:
`2629074 135     96776   28047176        3.369314282148874e-2    62207   0       0       216     15      526     526     0       1487790 1620928604`
Multiple extra whitespaces added. Not sure how. Need to get some sleep now but will continue to look into it tomorrow.

**Comment by Scitz0** [comment]
Fixed by #944 resetting IFS.
