### ISSUE TITLE
Missing links in the gliveview.md

### ISSUE THREAD

**Issue by IanChok** [cardano-community/guild-operators#949]
Hi, the links are broken for the page [gliveview.md](https://github.com/cardano-community/guild-operators/blob/alpha/docs/Scripts/gliveview.md), for example I can't find the `prereqs.sh` that is mentioned

**Comment by rdlrt** [comment]
The links are correct - but they're relative paths from root for the website, which can be found [here](https://cardano-community.github.io/guild-operators/#/Scripts/gliveview).
