### ISSUE TITLE
sendADA script not retrieving TxHash with most ADA

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#95]
![image](https://user-images.githubusercontent.com/15903629/82116147-c887f380-9767-11ea-9e8c-516447a40a6b.png)

Replacing sort parameters like in image is one way to solve it.

**Comment by rdlrt** [comment]
Thanks @Scitz0 , could you verify the update?

**Comment by Scitz0** [comment]
Unable to confirm as I'm not running the exact same setup as guild-operators.

```Invalid argument `build'```

Running with cardano-node pioneer-2 tag build is not a valid parameter for cardano-cli shelley address. Need to be build-enterprise. But I guess this depends on the version of cardano-node you run.

Also one other thing I noticed in sendADA.sh script. Minor stuff, not sure a new issue is needed.
env is sourced in the script and in env file MAGIC is set. Why not use this instead of its own in sendADA script:
```NWMAGIC=`cat ${GENESIS_JSON} | jq .networkMagic```
Also in env file magic is set as:
```MAGIC=$(cat $GENESIS_JSON | jq -r .protocolConsts|jq -r .protocolMagic)```
This is not correct for the latest version. Magic can be retrieved either by 
```MAGIC=$(cat $GENESIS_JSON | jq -r .protocolMagicId)```
or
```MAGIC=$(cat $GENESIS_JSON | jq -r .networkMagic)```
Not sure what the difference is for the two but for FF genesis they are the same. In guild operators genesis they are different. Either way the code in env to retrieve it is wrong.

**Comment by Scitz0** [comment]
I just noticed that magic is statically set in script as well in one place. 

``` currSlot=`cardano-cli shelley query tip --testnet-magic 42 | awk '{ print $5 }' | grep -Eo '[0-9]{1,}'` ```

**Comment by rdlrt** [comment]
Thanks for the clarification, I see the issue you face.
1. Yes, the guild network was using an older version, wherein the protocolId was not reflected, this should now be corrected.
2, About the second point though, the FnF network has manually overridden the protocolMagic to be same as networkMagic - which is not the default case with shelley genesis. Thus, the two would continue to remain seperate, until merged. But the sendADA script should now pick both NWMAGIC as well as MAGIC from the genesis.
3. The error you mention with build, is probably you're using a specific branch which is in middle of two checkpoints where cardano-cli was referring to addresses differently. Upgrading or downgrading from that branch should make the `build` command work.
Thanks for testing it out!

**Comment by Scitz0** [comment]
Pull request added for a modified sendADA script including updated env file and new balance.sh script.

**Comment by rdlrt** [comment]
Closed via #100
