### ISSUE TITLE
Fix prereqs.sh handling of non-existing branches

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#959]
We currently run:
`curl -s -f -m ${CURL_TIMEOUT} -o config.json.tmp ${URL_RAW}/files/config-mainnet.json 2>/dev/null`
then grep for error with:
`if grep -i '404: Not Found' config.json.tmp >/dev/null ; then`
but curl command is set to fail silently so no tmp file is written and it thinks all is fine.
instead of grep I propose we just check return code from curl directly with if.

Adding as issue to remember to fix it when I get some time to spare.

**Comment by rdlrt** [comment]
Closed via #962
