### ISSUE TITLE
CNTools - improve KES expiration

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#960]
Currently, CNTools rely on kes.start file to calculate the KES expiration time. gLiveView however use node metrics that are more reliable. kes.start could show wrong date if overwritten by an old backup or if KES is rotated on offline machine and this file is not moved to online machine.

I propose that we change CNTools to use node metrics if run in online mode and if metrics are available. And fallback to current method if first fail.

**Comment by rdlrt** [comment]
> I propose that we change CNTools to use node metrics if run in online mode and if metrics are available. And fallback to current method if first fail.

Agreed, just to simplify it a small step further  - instead of checking for a running node, we could simply check using startup switch vars (if started in offline mode)

**Comment by rdlrt** [comment]
Closed via #962
