### ISSUE TITLE
Cntools not showing the ledger logs  on the UI

### ISSUE THREAD

**Issue by djalillounis** [cardano-community/guild-operators#963]
**Describe the bug**
Hello,

starting from the current epoch 273, I am not able to see my block schedule I can see only the mined blocks but not the future one.

I also tried to run>
************:/opt/cardano/cnode/scripts$ cncli leaderlog
error: The following required arguments were not provided:
    --byron-genesis <byron-genesis>
    --pool-id <pool-id>
    --pool-vrf-skey <pool-vrf-skey>
    --shelley-genesis <shelley-genesis>

USAGE:
    cncli leaderlog --byron-genesis <byron-genesis> --db <db> --ledger-set <ledger-set> --ledger-state <ledger-state> --pool-id <pool-id> --pool-vrf-skey <pool-vrf-skey> --shelley-genesis <shelley-genesis> --tz <timezone>

It seems that the cncli is not able to read the env file.

and the ./cncli.sh leaderlog  has no output at all.

Thank you

**To Reproduce**
![image](https://user-images.githubusercontent.com/13331817/122668158-136c0a00-d1b7-11eb-8f78-8e012382eca6.png)

**Expected behavior**
The number 

**Screenshots**

**Version:**
 - OS: [Ubunto 20]
 - Product version: [v8.4.5 ]**
 - Cardano Node version: [e.g. output of `1.27.0`]
 - Network you're connecting to: [Mainnet]

**Additional context**

**Comment by rdlrt** [comment]
> It seems that the cncli is not able to read the env file.

cncli binary is an independent component that will not refer to env file, what you see is correct, as using cncli instead of cncli.sh will need you to supply parameters.

About the rest, do you have enough stake to guarantee a block per epoch?

**Comment by Scitz0** [comment]
> and the ./cncli.sh leaderlog has no output at all.

Please supply force flag when cncli.sh is run manually, eg `./cncli.sh leaderlog force`. This will force a leaderlog calculation and exit after. Just running ./cncli.sh leaderlog will put it in an infinite loop and is designed for systemd/cron deployment. 

You should also check output of `journalctl -f -u cnode-cncli-sync` and `journalctl -f -u cnode-cncli-leaderlog` to see if there are any errors with the deployed services.

**Comment by djalillounis** [comment]
Hello this are the erros I get from >
journalctl -f -u cnode-cncli-leaderlog
Jun 19 23:47:29 XXXXXXX cnode-cncli-leaderlog[660]: Error message: EOF while parsing a value at line 1 column 0
Jun 20 00:40:37 XXXXXXX cnode-cncli-leaderlog[412059]: (standard_in) 1: syntax error
Jun 20 00:40:37 XXXXXXX cnode-cncli-leaderlog[412062]: (standard_in) 1: syntax error
Jun 20 00:40:37 XXXXXXX cnode-cncli-leaderlog[660]: CNCLI DB out of sync :( [0.0000 %] ... checking again in 60s
Jun 20 01:46:48 XXXXXXX cnode-cncli-leaderlog[602988]: (standard_in) 1: syntax error
Jun 20 01:46:48 XXXXXXX cnode-cncli-leaderlog[602991]: (standard_in) 1: syntax error
Jun 20 01:46:48 XXXXXXX cnode-cncli-leaderlog[660]: CNCLI DB out of sync :( [0.0000 %] ... checking again in 60s
Jun 20 11:38:58 XXXXXXX cnode-cncli-leaderlog[2288697]: (standard_in) 1: syntax error
Jun 20 11:38:58 XXXXXXX cnode-cncli-leaderlog[2288700]: (standard_in) 1: syntax error
Jun 20 11:38:58 XXXXXXX cnode-cncli-leaderlog[660]: CNCLI DB out of sync :( [0.0000 %] ... checking again in 60s


The journalctl -f -u cnode-cncli-sync seems Ok
- Logs begin at Sat 2021-04-17 08:17:15 CEST. --
Jun 20 14:54:01 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:54:01.827Z WARN  cardano_ouroboros_network::protocols::chainsync > rollback to slot: 32627333
Jun 20 14:54:01 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:54:01.829Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875851 of 5875851, 100.00% synced
Jun 20 14:55:02 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:55:02.476Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875852 of 5875852, 100.00% synced
Jun 20 14:55:50 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:55:50.624Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875853 of 5875853, 100.00% synced
Jun 20 14:56:11 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:56:11.177Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875854 of 5875854, 100.00% synced
Jun 20 14:56:20 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:56:20.148Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875855 of 5875855, 100.00% synced
Jun 20 14:56:42 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:56:42.277Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875856 of 5875856, 100.00% synced
Jun 20 14:57:05 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:57:05.258Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875857 of 5875857, 100.00% synced
Jun 20 14:58:00 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:58:00.278Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875858 of 5875858, 100.00% synced
Jun 20 14:58:37 XXXXXXX cnode-cncli-sync[5326]:  2021-06-20T12:58:37.493Z INFO  cardano_ouroboros_network::protocols::chainsync > block 5875859 of 5875859, 100.00% synced

**Comment by Scitz0** [comment]
what version of cncli are you running? `cncli -V`
seems like you cncli db has been corrupted.
Run this command and check output:
`sqlite3 "${CNODE_HOME}/guild-db/cncli/cncli.db" "SELECT slot_number FROM chain ORDER BY slot_number DESC LIMIT 1;`
if it fails like log output you posted:
`EOF while parsing a value at line 1 column 0`
then stop services:
`sudo systemctl stop cnode-cncli-sync` (stops all services related to cncli)
then delete db:
`rm -rf ${CNODE_HOME}/guild-db/cncli`
start services:
`sudo systemctl start cnode-cncli-sync`
watch output of sync and wait until its fully synced, then check leaderlog that should automatically kick in once sync is complete (with a few minutes delay).

**Comment by djalillounis** [comment]
I am running the version 2..0.2

The query output is 32627798

I can see that there is a new version cncli , I am not sure if the upgrade will not break things eve more

**Comment by djalillounis** [comment]
I removed tge DB and resyncing now I will let you know if something changed

**Comment by Scitz0** [comment]
the latest version is compatible, I recommend upgrading.

**Comment by Scitz0** [comment]
> The query output is 32627798

Given that you do get a correct output from this command the issue might be elsewhere. It also use slotnum ekg metric from the node to compare against. If it keeps failing after rebuild of cncli db you might want to look into getNodeMetrics from env file by running the following commands:
```
. $CNODE_HOME/scripts/env
getNodeMetrics
echo "slotnum=${slotnum}"
```

**Comment by djalillounis** [comment]
I have this output
slotnum=32635545

**Comment by djalillounis** [comment]
now I dont even see the folder /cncli/ in the path "${CNODE_HOME}/guild-db/cncli/ I see only the blocklog

**Comment by Scitz0** [comment]
then cncli sync isn't working. you have to investigate why this is.

**Comment by djalillounis** [comment]
I need to restart my node to know, but as I dont have ledger logs I cant know when I am scheduled

**Comment by Scitz0** [comment]
cncli services doesn't require you to restart your node. They are independent services that connect to your running node. The dependency tree looks like this:
cnode.service
  - cnode-cncli-sync.service
    - cnode-cncli-leaderlog.service
    - cnode-cncli-validate.service
    
If cnode.service is stopped/restarted, it will trigger a stop/restart of all child services(all cncli services).
If cnode-cncli-sync.service is stopped, it will stop sync and both its child services for leaderlog and validate. But cnode service is unaffected.
