### ISSUE TITLE
docker - Missing fork libs from stage3 docker image

### ISSUE THREAD

**Issue by shibug** [cardano-community/guild-operators#964]
**Describe the bug**
The released docker image when run fails to sync the blockchain around 5% progress with the below error message:

`cardano-node: symbol lookup error: cardano-node: undefined symbol: crypto_vrf_publickeybytes`

**To Reproduce**
1. Run the docker image in relay mode
2. Wait till it crashes with the above error on standard err.

**Expected behavior**
The image should run as a normal container and fully sync up the blockchain as well as function properly like any other cardano node

**Version:**
 - Cardano Node version: 1.27.0
 - Network you're connecting to: Testnet

**Additional context**
Further discussion with @rdlrt captured in Telegram: https://t.me/c/1363966908/1370

**Comment by shibug** [comment]
We need this line in dockerfile_stage3
COPY --from=cardanocommunity/cardano-node:stage2 /usr/local/lib/libsodium.* /usr/local/lib/

I tested this by building it locally. I moved past the point of failure

Let me know if you need me to open a pull request?

**Comment by rdlrt** [comment]
Not exactly, ideally the linked libraries should be built on target VMs.
The decision point is really about whether we want to use that as an option OR add `-l` to `cabal-build-all.sh`

**Comment by redoracle** [comment]
Sorry I forgot to update this issue when the docker images was fixed.
Closing it now.
