### ISSUE TITLE
GHCUP infinitely prompts for path updating

### ISSUE THREAD

**Issue by CaffeinatedCM** [cardano-community/guild-operators#976]
**Describe the bug**
While setting up a new node today, ghcup was infinitely asking about the PATH update. It looks like the options changed

Updating prereqs.sh to use 'P' instead of 'Y' for `next_answer` seems to work, but I'd want to investigate further before saying that's the correct answer.

**To Reproduce**
1. Run prereqs.sh

**Expected behavior**
Script to run succesfully 

**Screenshots**
![image](https://user-images.githubusercontent.com/608002/125347808-6013b280-e329-11eb-97d6-0045fa834eef.png)

**Version:**
 - OS: Amazon Linux 2
 - Product version:  master

**Comment by papacarp** [comment]
Same on Ubuntu 18.04

**Comment by CaffeinatedCM** [comment]
Looks like they changed something again, now running it doesn't loop forever but it also doesn't make the path updates necessary to run the things

**Comment by rdlrt** [comment]
Fix should now be merged to alpha branch
