### ISSUE TITLE
404 Downloading epel in RHEL 8.4.x

### ISSUE THREAD

**Issue by CaffeinatedCM** [cardano-community/guild-operators#978]
**Describe the bug**
`prereqs.sh` attempts to download epel-release-latest from fedoraproject but when determining which version to download it uses 8.4 instead of just 8

**To Reproduce**
1. Run prereqs.sh on a rhel 8 instance

**Expected behavior**
downloads and installs epel-release-latest-8

**Screenshots**

![image](https://user-images.githubusercontent.com/608002/125654573-dac5eb92-e4c2-4759-aadf-d77262c53da6.png)

**Version:**
 - OS:  RHEL 8.4.0
 - Product version:  master

**Comment by rdlrt** [comment]
Thanks for reporting, should be fixed on alpha
