### ISSUE TITLE
Update guide to use prebuilt binaries

### ISSUE THREAD

**Issue by saw235** [cardano-community/guild-operators#992]
In the guide operator guide for the cardano-cli and cardano-node is build with the following commands below
Is there any reason why we need to build the binaries from scratch when they are already provided at
https://github.com/input-output-hk/cardano-node/releases/latest   ?

```
git fetch --tags --all
git pull
# Replace tag against checkout if you do not want to build the latest released version
git checkout $(curl -s https://api.github.com/repos/input-output-hk/cardano-node/releases/latest | jq -r .tag_name)

# Use `-l` argument if you'd like to use system libsodium instead of IOG fork of libsodium while compiling
$CNODE_HOME/scripts/cabal-build-all.sh
```

**Comment by rdlrt** [comment]
Essentially the below:
![image](https://user-images.githubusercontent.com/3169068/126853752-cd7826e2-0513-48be-8243-b6af4c088279.png)

You dont have to use the build instructions as long as you have the binaries available in your `$PATH`
